// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/AddData/nls/strings":{_widgetLabel:"Lisa andmeid",noOptionsConfigured:"\u00dchtki valikut pole konfigureeritud.",tabs:{search:"Otsi",url:"URL",file:"Fail"},search:{featureLayerTitlePattern:"{serviceName} - {layerName}",layerInaccessible:"Kiht on ligip\u00e4\u00e4smatu.",loadError:"Andmete lisamine, ei saa laadida:",searchBox:{search:"Otsi",placeholder:"Otsing..."},bboxOption:{bbox:"Kaardi ulatuses"},scopeOptions:{anonymousContent:"Sisu",myContent:"Minu sisu",myOrganization:"Minu organisatsioon",
curated:"Hallatud",ArcGISOnline:"ArcGIS Online"},sortOptions:{prompt:"Sordi:",relevance:"Asjakohasus",title:"Pealkiri",owner:"Omanik",rating:"Hinnang",views:"Vaatamised",date:"Kuup\u00e4ev",switchOrder:"Vaheta"},typeOptions:{prompt:"T\u00fc\u00fcp",mapService:"Kaarditeenus",featureService:"Objektiteenus",imageService:"Pilditeenus",vectorTileService:"Vektorpildi\u00fcksuste teenus",kml:"KML",wms:"WMS"},resultsPane:{noMatch:"Tulemusi ei leitud."},paging:{first:"\x3c\x3c",firstTip:"Esimene",previous:"\x3c",
previousTip:"Eelmine",next:"\x3e",nextTip:"J\u00e4rgmine",pagePattern:"{page}"},resultCount:{countPattern:"{count} {type}",itemSingular:"\u00dcksus",itemPlural:"Sisu\u00fcksused"},item:{actions:{add:"Lisa",close:"Sule",remove:"Eemalda",details:"Detailid",done:"Valmis",editName:"Muuda nime"},messages:{adding:"Lisamine...",removing:"Eemaldamine...",added:"Lisatud",addFailed:"Lisamine eba\u00f5nnestus",unsupported:"Toetuseta"},typeByOwnerPattern:"t\u00fc\u00fcp {type},\u00a0omanik\u00a0{owner}",dateFormat:"d. MMMM yyyy",
datePattern:"{date}",ratingsCommentsViewsPattern:"{ratings} {ratingsIcon} {comments} {commentsIcon} {views} {viewsIcon}",ratingsCommentsViewsLabels:{ratings:'hinnangud", "kommentaarid": "kommentaarid", "vaatamised": "vaatamised'},types:{"Map Service":"Kaarditeenus","Feature Service":"Objektiteenus","Image Service":"Pilditeenus","Vector Tile Service":"Vektorpildi\u00fcksuste teenus",WMS:"WMS",KML:"KML"}}},addFromUrl:{type:"T\u00fc\u00fcp",url:"URL",types:{ArcGIS:"ArcGIS Server veebiteenus",WMS:"WMS OGC veebiteenus",
WMTS:"WMTS OGC veebiteenus",WFS:"WFS OGC veebiteenus",KML:"KML fail",GeoRSS:"GeoRSS fail",CSV:"CSV fail"},samplesHint:"N\u00e4idis-URL(id)"},addFromFile:{intro:"Saate \u00fchte j\u00e4rgmistest failit\u00fc\u00fcpidest lohistada v\u00f5i nendeni liikuda:",types:{Shapefile:"Shape fail (.zip, ZIP arhiiv, mis sisaldab k\u00f5iki\u00a0Shape faili komponente)",CSV:"CSV v\u00f5i\u00a0TXT failid aadressi v\u00f5i laiuskraadi ja pikkuskraadiga\u00a0(.csv, aadressi v\u00f5i laiuskraadiga, pikkuskraadiga ja koma-, semikoolon- v\u00f5i tabeleraldusega)",
KML:"KML fail (.kml)",GPX:"GPX fail (.gpx, GPS Exchange format)",GeoJSON:"GeoJSON fail (.geo.json v\u00f5i .geojson)"},generalizeOn:"\u00dcldista objekte veebis kuvamiseks",dropOrBrowse:"Lohista v\u00f5i sirvi",browse:"Sirvi",invalidType:"Seda faili t\u00fc\u00fcpi ei toetata.",addingPattern:"{filename}: lisamine...",addFailedPattern:"{filename}: lisamine nurjus",featureCountPattern:"{filename}: {count} objekt(i)",invalidTypePattern:"{filename}: seda t\u00fc\u00fcpi ei toetata",maxFeaturesAllowedPattern:"Lubatud on maksimaalselt {count} objekti",
layerNamePattern:"{filename} \u2013 {name}",generalIssue:"Ilmnes probleem.",kmlProjectionMismatch:"Kaardi ja KML-kihi koordinaats\u00fcsteemid ei kattu ja teisendamine pole klientrakenduses v\u00f5imalik."},layerList:{caption:"Kihid",noLayersAdded:"\u00dchtki kihti pole lisatud.",removeLayer:"Eemalda kiht",back:"Tagasi"},_localized:{}}});