// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/AddData/nls/strings":{_widgetLabel:"Dodajte podatke",noOptionsConfigured:"Nobene mo\u017enosti niso bile konfigurirane.",tabs:{search:"Iskanje",url:"URL",file:"Datoteka"},search:{featureLayerTitlePattern:"{serviceName} \u2013 {layerName}",layerInaccessible:"Sloj je nedostopen.",loadError:"Dodajte podatke, nalaganje ni mogo\u010de:",searchBox:{search:"Iskanje",placeholder:"Iskanje..."},bboxOption:{bbox:"Znotraj karte"},scopeOptions:{anonymousContent:"Vsebina",myContent:"Moja vsebina",
myOrganization:"Moja organizacija",curated:"Kurirano",ArcGISOnline:"ArcGIS Online"},sortOptions:{prompt:"Razvrsti po:",relevance:"Relevantnost",title:"Naslov",owner:"Lastnik",rating:"Ocena",views:"Ogledi",date:"Datum",switchOrder:"Preklopi"},typeOptions:{prompt:"Tip",mapService:"Kartna storitev",featureService:"Geoobjektna storitev",imageService:"Slikovna storitev",vectorTileService:"Vektorska plo\u0161\u010di\u010dna storitev",kml:"KML",wms:"WMS"},resultsPane:{noMatch:"Ni najdenih rezultatov."},
paging:{first:"\x3c\x3c",firstTip:"Prvi",previous:"\x3c",previousTip:"Prej\u0161nje",next:"\x3e",nextTip:"Naprej",pagePattern:"{page}"},resultCount:{countPattern:"{count} {type}",itemSingular:"Element",itemPlural:"Elementi"},item:{actions:{add:"Dodaj",close:"Zapri",remove:"Odstrani",details:"Podrobnosti",done:"Kon\u010dano",editName:"Uredi ime"},messages:{adding:"Dodajanje...",removing:"Odstranjevanje...",added:"Dodano",addFailed:"Dodajanje ni uspelo",unsupported:"Nepodprto"},typeByOwnerPattern:"{type} od {owner}",
dateFormat:"MMMM d llll",datePattern:"{date}",ratingsCommentsViewsPattern:"{ratings} {ratingsIcon} {comments} {commentsIcon} {views} {viewsIcon}",ratingsCommentsViewsLabels:{ratings:"ocene\u00ab, \u00bbkomentarji\u00ab: \u00bbkomentarji\u00ab, \u00bbogledi\u00ab : \u00bbogledi"},types:{"Map Service":"Kartna storitev","Feature Service":"Geoobjektna storitev","Image Service":"Slikovna storitev","Vector Tile Service":"Vektorska plo\u0161\u010di\u010dna storitev",WMS:"WMS",KML:"KML"}}},addFromUrl:{type:"Tip",
url:"URL",types:{ArcGIS:"Spletna stre\u017eni\u0161ka storitev ArcGIS",WMS:"Spletna storitev WMS OGC",WMTS:"Spletna storitev WMTS OGC",WFS:"Spletna storitev WFS OGC",KML:"Datoteka KML",GeoRSS:"datoteka GeoRSS",CSV:"Datoteka CSV"},samplesHint:"Vzorec URL"},addFromFile:{intro:"Odlo\u017eite ali brskate lahko po enem od naslednjih tipov datotek:",types:{Shapefile:"Shapefile (.zip, ZIP arhiv, ki vklju\u010duje vse datoteke oblik)",CSV:"Datoteka CSV (.csv, z naslovom ali geografsko \u0161irino, geografsko dol\u017eino, ki so lo\u010deni z vejico, podpi\u010djem ali zavihkom)",
KML:"Datoteka KML (.kml)",GPX:"Datoteka GPX (.gpx, izmenljiva oblika GPS)",GeoJSON:"Datoteka GeoJSON (.geo.json ali .geojson)"},generalizeOn:"Generaliziraj geoobjekte za spletni prikaz",dropOrBrowse:"Odlo\u017ei ali brskaj",browse:"Prebrskaj",invalidType:"Ta tip datoteke ni podprt.",addingPattern:"{filename}: dodajanje...",addFailedPattern:"{filename}: dodajanje ni uspelo",featureCountPattern:"{filename}: {count} geoobjektov",invalidTypePattern:"{filename}: ta tip ni podprt",maxFeaturesAllowedPattern:"Dovoljenih je maksimalno {count} geoobjektov",
layerNamePattern:"{filename} \u2013 {name}",generalIssue:"Pri\u0161lo je do te\u017eave.",kmlProjectionMismatch:"Koordinatni sistem karte in sloja KML se ne ujemata in konverzije ni mogo\u010de opraviti na odjemalcu."},layerList:{caption:"Sloji",noLayersAdded:"Sloji niso dodani.",removeLayer:"Odstrani sloj",back:"Nazaj"},_localized:{}}});