// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/AddData/nls/strings":{_widgetLabel:"Tilf\u00f8j data",noOptionsConfigured:"Der blev ikke konfigureret nogen indstillinger.",tabs:{search:"S\u00f8g",url:"URL",file:"Fil"},search:{featureLayerTitlePattern:"{serviceName} - {layerName}",layerInaccessible:"Laget er utilg\u00e6ngeligt.",loadError:"AddData, kan ikke indl\u00e6se:",searchBox:{search:"S\u00f8g",placeholder:"S\u00f8g..."},bboxOption:{bbox:"Inden for kortet"},scopeOptions:{anonymousContent:"Indhold",myContent:"Mit indhold",
myOrganization:"Min organisation",curated:"Vedligeholdt",ArcGISOnline:"ArcGIS Online"},sortOptions:{prompt:"Sort\u00e9r efter:",relevance:"Relevans",title:"Titel",owner:"Ejer",rating:"Vurdering",views:"Visninger",date:"Dato",switchOrder:"Skift"},typeOptions:{prompt:"Type",mapService:"Korttjeneste",featureService:"Featuretjeneste",imageService:"Billedtjeneste",vectorTileService:"Vektor-tile-tjeneste",kml:"KML",wms:"WMS"},resultsPane:{noMatch:"Ingen resultater fundet."},paging:{first:"\x3c\x3c",firstTip:"F\u00f8rste",
previous:"\x3c",previousTip:"Forrige",next:"\x3e",nextTip:"N\u00e6ste",pagePattern:"{page}"},resultCount:{countPattern:"{count} {type}",itemSingular:"Element",itemPlural:"Elementer"},item:{actions:{add:"Tilf\u00f8j",close:"Luk",remove:"Fjern",details:"Detaljer",done:"Udf\u00f8rt",editName:"Redig\u00e9r navn"},messages:{adding:"Tilf\u00f8jer...",removing:"Fjerner...",added:"Tilf\u00f8jet",addFailed:"Tilf\u00f8jelse mislykkedes",unsupported:"Ikke underst\u00f8ttet"},typeByOwnerPattern:"{type} efter {owner}",
dateFormat:"MMMM d, \u00e5\u00e5\u00e5\u00e5",datePattern:"{date}",ratingsCommentsViewsPattern:"{ratings} {ratingsIcon} {comments} {commentsIcon} {views} {viewsIcon}",ratingsCommentsViewsLabels:{ratings:'vurderinger", "kommentarer": "kommentarer", "visninger": "visninger'},types:{"Map Service":"Korttjeneste","Feature Service":"Featuretjeneste","Image Service":"Billedtjeneste","Vector Tile Service":"Vektor-tile-tjeneste",WMS:"WMS",KML:"KML"}}},addFromUrl:{type:"Type",url:"URL",types:{ArcGIS:"En ArcGIS Server-webtjeneste",
WMS:"En WMS OGC-webservice",WMTS:"En WMTS OGC-webservice",WFS:"En WFS OGC-webtjeneste",KML:"En KML-fil",GeoRSS:"En GeoRSS-fil",CSV:"En CSV-fil"},samplesHint:"Eksempel-URL(er)"},addFromFile:{intro:"Du kan slippe eller browse til \u00e9n af f\u00f8lgende filtyper:",types:{Shapefile:"En shapefil (.-zip, ZIP-arkiv, der indeholder alle shapefiler)",CSV:"En CSV-fil (.csv, med adresse eller l\u00e6ngde- og breddegrader samt komma-, semikolon- eller tabulatorsepareret)",KML:"En KML-fil (.kml)",GPX:"En GPX-fil (.gpx, GPS Exchange Format)",
GeoJSON:"En GeoJSON-fil (.geo.json eller .geojson)"},generalizeOn:"Generalis\u00e9r objekter til webvisning",dropOrBrowse:"Slip eller gennemse",browse:"Gennemse",invalidType:"Denne filtype underst\u00f8ttes ikke.",addingPattern:"{filename}: tilf\u00f8jer...",addFailedPattern:"{filename}: tilf\u00f8jelse mislykkedes",featureCountPattern:"{filename}: {count} objekt(er)",invalidTypePattern:"{filename}: denne type underst\u00f8ttes ikke",maxFeaturesAllowedPattern:"H\u00f8jst {count} objekter er tilladt",
layerNamePattern:"{filename} - {name}",generalIssue:"Der opstod et problem.",kmlProjectionMismatch:"Den spatiale reference for kortet og KML-laget passer ikke sammen, og konverteringen kan ikke udf\u00f8res for klienten."},layerList:{caption:"Lag",noLayersAdded:"Ingen lag er blevet tilf\u00f8jet.",removeLayer:"Fjern lag",back:"Tilbage"},_localized:{}}});