// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} de ${total} r\u00e9sultats",gotoFirst:"Aller \u00e0 la premi\u00e8re page",gotoNext:"Aller \u00e0 la page suivante",gotoPrev:"Aller \u00e0 la page pr\u00e9c\u00e9dente",gotoLast:"Aller \u00e0 la derni\u00e8re page",gotoPage:"Aller \u00e0 la page",jumpPage:"Aller \u00e0 la page",rowsPerPage:"Number of rows per page",_localized:{}},"esri/dijit/analysis/nls/DataStoreSelect":{relationalDS:"Relationnels",spatialDS:"Spatio-temporels",
agsDataStore:"ArcGIS Data Store",bdfsTemplates:"Mod\u00e8le en sortie de Big Data File Share",_localized:{}},"esri/dijit/analysis/nls/BrowseLayerMixin":{defaultAnaysisLayerTitle:"Choisir une couche d'analyse du Living Atlas",customAnalysisLayerTitle:"Choisir une couche d'analyse",searchPlaceholderText:"Parcourir les couches d\u2019analyse du Living Atlas",searchCustomPlaceholderText:"Parcourir les couches d\u2019analyse",mainActionTitle:"S\u00e9lectionner",customActionName:"S\u00e9lectionner et ajouter \u00e0 la carte",
customeSectionName:"Couches d'analyse Living Atlas",Categories:"Cat\u00e9gories",boundaries:"Limites",places:"Lieux",boundariesAndPlaces:"Fronti\u00e8res et lieux",hexbins:"Groupes hexad\u00e9cimaux",transportation:"Transport",point:"Couches de points",line:"Couches de polylignes",polygon:"Couches de polygones",pointFilterName:"Point",lineFilterName:"Polyligne",polygonFilterName:"Surface",multiPointFilterName:"Points multiples",geometryFilterName:"G\u00e9om\u00e9trie",featureLayerName:"Couche d'entit\u00e9s",
tableLayerName:"Tableau",itemTypeFilterName:"Type d'\u00e9l\u00e9ment",instantFilterName:"Instant",intervalFilterName:"Intervalle",timeFilterName:"Dur\u00e9e",edit:"Mise \u00e0 jour",boundaryLayers:"Couches de contours Esri",customAnalysisGroupName:"Groupes d'analyse de l\u2019organisation",_localized:{}},"widgets/Visibility/nls/strings":{_widgetLabel:"Visibilit\u00e9",observerLocation:"Position d\u2019observation",formatIconTooltip:"Format d'entr\u00e9e",addPointToolTip:"Ajouter un point d\u2019observation",
fieldOfView:"Champ de vision",useMilsText:"Utiliser des valeurs en mils pour les angles",observerHeight:"Hauteur de l\u2019observateur",minObsDistance:"Distance observable minimale",maxObsDistance:"Distance observable maximale",taskURLError:"Le fichier de configuration du widget contient une URL inaccessible. Consulter l\u2019administrateur syst\u00e8me",taskURLInvalid:"La t\u00e2che de g\u00e9otraitement configur\u00e9e avec ce widget n\u2019est pas valide. Consulter l\u2019administrateur syst\u00e8me",
viewshedError:"Une erreur est survenue lors de la cr\u00e9ation de la visibilit\u00e9. V\u00e9rifiez que la position d\u2019observation se trouve dans l\u2019\u00e9tendue de votre surface d\u2019altitude.\x3c/p\x3e",validationError:"\x3cp\x3eDes param\u00e8tres sont manquants ou non valides dans le formulaire de cr\u00e9ation de la visibilit\u00e9. V\u00e9rifiez que\u00a0:\x3c/p\x3e\x3cul\x3e\x3cli\x3eUne position d\u2019observation a \u00e9t\u00e9 d\u00e9finie.\x3c/li\x3e\x3cli\x3eLe champ de visibilit\u00e9 de l\u2019observateur n\u2019est pas \u00e9gal \u00e0\u00a00.\x3c/li\x3e\x3cli\x3eLe champ de hauteur de l\u2019observateur contient une valeur valide.\x3c/li\x3e\x3cli\x3eLes champs des distances observables minimale et maximale contiennent des valeurs valides.\x3c/li\x3e\x3c/ul\x3e",
comfirmInputNotation:"Confirmer la notation entr\u00e9e",notationsMatch:"notations correspondent \u00e0 votre entr\u00e9e. Confirmez celle que vous souhaitez utiliser\u00a0:",createBtn:"Cr\u00e9er",clearBtn:"Effacer",setCoordFormat:"D\u00e9finir une cha\u00eene de format des coordonn\u00e9es",prefixNumbers:"Ajouter le pr\u00e9fixe '+/-' aux nombres positifs et n\u00e9gatifs",parseCoordinatesError:"Impossible d'analyser les coordonn\u00e9es. V\u00e9rifiez votre entr\u00e9e.",cancelBtn:"Annuler",applyBtn:"Appliquer",
invalidMessage:"Entrez une valeur num\u00e9rique.",observerRangeMessage:"Hauteur du point d\u2019observation non valide",minimumRangeMessage:"Plage observable minimale non valide",maximumRangeMessage:"La plage observable maximale doit \u00eatre sup\u00e9rieure \u00e0 la plage observable minimale et ne doit pas d\u00e9passer ${limit} ${units}.",portalURLError:"L\u2019URL de votre organisation ArcGIS Online ou Portal for ArcGIS n\u2019est pas configur\u00e9e. Contactez votre administrateur syst\u00e8me.",
privilegeError:'Votre r\u00f4le d\u2019utilisateur ne peut pas r\u00e9aliser d\u2019analyse. Pour effectuer une analyse, l\u2019administrateur de votre organisation doit vous accorder certains \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3eprivil\u00e8ges\x3c/a\x3e.',noServiceError:"Le service d\u2019analyse d\u2019altitude n\u2019est pas disponible. V\u00e9rifiez les configurations de votre organisation ArcGIS Online ou Portal for ArcGIS.",pointToolTooltip:"Cliquez pour ajouter un point d\u2019observation",
degreesLabel:"degr\u00e9s",milsLabel:"mils",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Degr\u00e9s d\u00e9cimaux - Latitude/Longitude",DDLongLatNotation:"Degr\u00e9s d\u00e9cimaux - Longitude/Latitude",DDMLatLongNotation:"Degr\u00e9s minutes d\u00e9cimales - Latitude/Longitude",DDMLongLatNotation:"Degr\u00e9s minutes d\u00e9cimales - Longitude/Latitude",DMSLatLongNotation:"Degr\u00e9s minutes secondes - Latitude/Longitude",
DMSLongLatNotation:"Degr\u00e9s minutes secondes - Longitude/Latitude",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - Lettre du canal",UTMHemNotation:"UTM - H\u00e9misph\u00e8re (N/S)",_localized:{}}});