// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} z ${total} wynik\u00f3w",gotoFirst:"Przejd\u017a do pierwszej strony",gotoNext:"Przejd\u017a do nast\u0119pnej strony",gotoPrev:"Przejd\u017a do poprzedniej strony",gotoLast:"Przejd\u017a do ostatniej strony",gotoPage:"Przejd\u017a do strony",jumpPage:"Skocz do strony",rowsPerPage:"Number of rows per page",_localized:{}},"esri/dijit/analysis/nls/DataStoreSelect":{relationalDS:"Relacyjne",spatialDS:"Czasowo-przestrzenne",agsDataStore:"ArcGIS Data Store",
bdfsTemplates:"Szablony danych wynikowych udost\u0119pnionych plik\u00f3w du\u017cych zbior\u00f3w danych",_localized:{}},"esri/dijit/analysis/nls/BrowseLayerMixin":{defaultAnaysisLayerTitle:"Wybierz warstw\u0119 analizy Living Atlas",customAnalysisLayerTitle:"Wybierz warstw\u0119 analizy",searchPlaceholderText:"Wyszukaj warstwy analizy atlasu Living Atlas",searchCustomPlaceholderText:"Wyszukaj warstwy analizy",mainActionTitle:"Zaznacz",customActionName:"Wybierz i dodaj do mapy",customeSectionName:"Warstwy analizy atlasu Living Atlas",
Categories:"Kategorie",boundaries:"Granice",places:"Miejsca",boundariesAndPlaces:"Granice i miejsca",hexbins:"Elementy hexbin",transportation:"Transport",point:"Warstwy punktowe",line:"Warstwy poliliniowe",polygon:"Warstwy poligonowe",pointFilterName:"Punkt",lineFilterName:"Polilinia",polygonFilterName:"Poligon",multiPointFilterName:"Wiele punkt\u00f3w",geometryFilterName:"Geometria",featureLayerName:"Warstwa obiektowa",tableLayerName:"Tabela",itemTypeFilterName:"Typ elementu",instantFilterName:"Moment",
intervalFilterName:"Przedzia\u0142",timeFilterName:"Czas",edit:"Edycja",boundaryLayers:"Warstwy granic firmy Esri",customAnalysisGroupName:"Grupa analiz instytucji",_localized:{}},"widgets/Visibility/nls/strings":{_widgetLabel:"Widoczno\u015b\u0107",observerLocation:"Lokalizacja obserwatora",formatIconTooltip:"Formatuj dane wej\u015bciowe",addPointToolTip:"Dodaj lokalizacj\u0119 obserwatora",fieldOfView:"Pole widzenia",useMilsText:"U\u017cyj mils\u00f3w dla k\u0105t\u00f3w",observerHeight:"Wysoko\u015b\u0107 obserwatora",
minObsDistance:"Minimalna widoczna odleg\u0142o\u015b\u0107",maxObsDistance:"Maksymalna widoczna odleg\u0142o\u015b\u0107",taskURLError:"Plik konfiguracji wid\u017cetu zawiera adres URL, kt\u00f3ry jest niedost\u0119pny. Sprawd\u017a u administratora systemu",taskURLInvalid:"Zadanie geoprzetwarzania skonfigurowane przy u\u017cyciu tego wid\u017cetu jest nieprawid\u0142owe. Sprawd\u017a u administratora systemu",viewshedError:"Wyst\u0105pi\u0142 b\u0142\u0105d podczas tworzenia widoczno\u015bci. Upewnij si\u0119, \u017ce lokalizacja obserwatora mie\u015bci si\u0119 w zakresie powierzchni wysoko\u015bciowej.\x3c/p\x3e",
validationError:"\x3cp\x3eW formularzu tworzenia grafiki GRG brakuje niekt\u00f3rych parametr\u00f3w lub s\u0105 one nieprawid\u0142owe. Upewnij si\u0119, \u017ce:\x3c/p\x3e\x3cul\x3e\x3cli\x3eLokalizacja obserwatora zosta\u0142a ustawiona.\x3c/li\x3e\x3cli\x3ePole widzenia obserwatora nie jest r\u00f3wne 0.\x3c/li\x3e\x3cli\x3eWarto\u015b\u0107 wysoko\u015bci obserwatora jest prawid\u0142owa.\x3c/li\x3e\x3cli\x3eWarto\u015bci minimalnej i maksymalnej widocznej odleg\u0142o\u015bci s\u0105 prawid\u0142owe.\x3c/li\x3e\x3c/ul\x3e",
comfirmInputNotation:"Potwierd\u017a notacj\u0119 danych wej\u015bciowych",notationsMatch:"liczba znalezionych notacji zgodnych z danymi wej\u015bciowymi. Wybierz, kt\u00f3rej notacji chcesz u\u017cy\u0107:",createBtn:"Tworzenie",clearBtn:"Wyczy\u015b\u0107",setCoordFormat:"Skonfiguruj ci\u0105g znakowy formatu wsp\u00f3\u0142rz\u0119dnych",prefixNumbers:"Dodaj prefiks '+/-' do liczb dodatnich i ujemnych",parseCoordinatesError:"Nie mo\u017cna przeanalizowa\u0107 wsp\u00f3\u0142rz\u0119dnych. Sprawd\u017a dane wej\u015bciowe.",
cancelBtn:"Anuluj",applyBtn:"Zastosuj",invalidMessage:"Wpisz warto\u015b\u0107 numeryczn\u0105.",observerRangeMessage:"Nieprawid\u0142owa wysoko\u015b\u0107 obserwatora",minimumRangeMessage:"Nieprawid\u0142owy minimalny zakres mo\u017cliwy do obserwacji",maximumRangeMessage:"Maksymalny zakres mo\u017cliwy do obserwacji musi by\u0107 wi\u0119kszy ni\u017c minimalny zakres mo\u017cliwy do obserwacji i nie mo\u017ce przekracza\u0107 ${limit} ${units}.",portalURLError:"Adres URL instytucji w us\u0142udze ArcGIS Online lub witryny Portal for ArcGIS nie jest skonfigurowany. Zwr\u00f3\u0107 si\u0119 do administratora systemu",
privilegeError:'Twoja rola u\u017cytkownika nie umo\u017cliwia wykonania analizy. Aby mo\u017cliwe by\u0142o wykonanie analizy, niezb\u0119dne jest nadanie Tobie przez administratora instytucji odpowiednich \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3euprawnie\u0144\x3c/a\x3e.',noServiceError:"Us\u0142uga analizy wysoko\u015bciowej jest niedost\u0119pna. Sprawd\u017a konfiguracj\u0119 instytucji w us\u0142udze ArcGIS Online lub witryny Portal for ArcGIS.",
pointToolTooltip:"Kliknij, aby doda\u0107 lokalizacj\u0119 obserwatora",degreesLabel:"stopnie",milsLabel:"mile",DD:"DD",DDM:"DDM",DMS:"Stopnie-Minuty-Sekundy (DMS)",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Stopnie dziesi\u0119tne \u2014 szeroko\u015b\u0107/d\u0142ugo\u015b\u0107 geograficzna",DDLongLatNotation:"Stopnie dziesi\u0119tne \u2014 d\u0142ugo\u015b\u0107/szeroko\u015b\u0107 geograficzna",
DDMLatLongNotation:"Stopnie i minuty dziesi\u0119tne \u2014 szeroko\u015b\u0107/d\u0142ugo\u015b\u0107 geograficzna",DDMLongLatNotation:"Stopnie i minuty dziesi\u0119tne \u2014 d\u0142ugo\u015b\u0107/szeroko\u015b\u0107 geograficzna",DMSLatLongNotation:"Stopnie, minuty i sekundy \u2014 szeroko\u015b\u0107/d\u0142ugo\u015b\u0107 geograficzna",DMSLongLatNotation:"Stopnie, minuty i sekundy \u2014 d\u0142ugo\u015b\u0107/szeroko\u015b\u0107 geograficzna",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",
USNGNotation:"USNG",UTMBandNotation:"UTM \u2014 litera pasa",UTMHemNotation:"UTM \u2014 p\u00f3\u0142kula (N/S)",_localized:{}}});