// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} of ${total} resultados",gotoFirst:"Ir para primeira p\u00e1gina",gotoNext:"Ir para pr\u00f3xima p\u00e1gina",gotoPrev:"Ir para p\u00e1gina anterior",gotoLast:"Ir para \u00faltima p\u00e1gina",gotoPage:"Ir para p\u00e1gina",jumpPage:"Pular para p\u00e1gina",rowsPerPage:"Number of rows per page",_localized:{}},"esri/dijit/analysis/nls/DataStoreSelect":{relationalDS:"Relacional",spatialDS:"Espa\u00e7o-Temporal",agsDataStore:"ArcGIS Data Store",
bdfsTemplates:"Modelos de Sa\u00edda para Compartilhar Arquivo de Grandes Dados",_localized:{}},"esri/dijit/analysis/nls/BrowseLayerMixin":{defaultAnaysisLayerTitle:"Escolher Camada de An\u00e1lise do Atlas em Tempo Real",customAnalysisLayerTitle:"Escolher Camada de An\u00e1lise",searchPlaceholderText:"Pesquisar Camadas de An\u00e1lise do Atlas em Tempo Real",searchCustomPlaceholderText:"Pesquisar camadas de an\u00e1lise",mainActionTitle:"Selecionar",customActionName:"Selecionar e adicionar ao mapa",
customeSectionName:"Camada de An\u00e1lise do Atlas em Tempo Real",Categories:"Categorias",boundaries:"Limites",places:"Locais",boundariesAndPlaces:"Limites e Locais",hexbins:"Hexbins",transportation:"Transporte",point:"Camadas de Ponto",line:"Camadas de Polilinha",polygon:"Camadas de Pol\u00edgono",pointFilterName:"Ponto",lineFilterName:"Polilinha",polygonFilterName:"Pol\u00edgono",multiPointFilterName:"M\u00faltiplos Pontos",geometryFilterName:"Geometria",featureLayerName:"Camada de Fei\u00e7\u00e3o",
tableLayerName:"Tabela",itemTypeFilterName:"Tipo do item",instantFilterName:"Instant\u00e2neo",intervalFilterName:"Intervalo",timeFilterName:"Hora",edit:"Editar",boundaryLayers:"Camadas de Limite da Esri",customAnalysisGroupName:"Grupos de An\u00e1lise da Organiza\u00e7\u00e3o",_localized:{}},"widgets/Visibility/nls/strings":{_widgetLabel:"Visibilidade",observerLocation:"Localiza\u00e7\u00e3o do Observador",formatIconTooltip:"Entrada de Formato",addPointToolTip:"Adicionar Localiza\u00e7\u00e3o do Observador",
fieldOfView:"Campo de Visualiza\u00e7\u00e3o",useMilsText:"Utilizar mil\u00e9simo para \u00e2ngulos",observerHeight:"Altura do Observador",minObsDistance:"Dist\u00e2ncia M\u00ednima Observ\u00e1vel",maxObsDistance:"Dist\u00e2ncia M\u00e1xima Observ\u00e1vel",taskURLError:"O arquivo de configura\u00e7\u00e3o do widget cont\u00e9m uma URL que \u00e9 inalcan\u00e7\u00e1vel. Confira com seu administrador do sistema",taskURLInvalid:"A tarefa de geoprocessamento configurada com este widget n\u00e3o \u00e9 v\u00e1lida. Confira com seu administrador do sistema",
viewshedError:"Ocorreu um erro ao criar visibilidade. Garanta que a localiza\u00e7\u00e3o do seu observador caia dentro da extens\u00e3o da sua superf\u00edcie de eleva\u00e7\u00e3o.\x3c/p\x3e",validationError:"\x3cp\x3eO formul\u00e1rio de cria\u00e7\u00e3o de visibilidade tem par\u00e2metros inv\u00e1lidos ou ausentes, garanta que:\x3c/p\x3e\x3cul\x3e\x3cli\x3eUma localiza\u00e7\u00e3o do observador tenha sido definida.\x3c/li\x3e\x3cli\x3eO Campo de Visualiza\u00e7\u00e3o do observador n\u00e3o seja 0.\x3c/li\x3e\x3cli\x3eA altura do observador cont\u00e9m um valor v\u00e1lido.\x3c/li\x3e\x3cli\x3eAs dist\u00e2ncias observ\u00e1veis m\u00ednimas e m\u00e1ximas cont\u00e9m valores v\u00e1lidos.\x3c/li\x3e\x3c/ul\x3e",
comfirmInputNotation:"Confirmar Anota\u00e7\u00e3o de Entrada",notationsMatch:"anota\u00e7\u00f5es que correspondem \u00e0 sua entrada, confirme o que voc\u00ea gostaria de utilizar:",createBtn:"Criar",clearBtn:"Apagar",setCoordFormat:"Definir String de Formato de Coordenadas",prefixNumbers:"Adicionar o prefixo '+/-' para n\u00fameros positivos e negativos",parseCoordinatesError:"N\u00e3o \u00e9 poss\u00edvel analisar coordenadas. Verifique sua entrada.",cancelBtn:"Cancelar",applyBtn:"Aplicar",invalidMessage:"Insira um valor num\u00e9rico.",
observerRangeMessage:"Altura do Observador Inv\u00e1lida",minimumRangeMessage:"Intervalo M\u00ednimo Observ\u00e1vel Inv\u00e1lido",maximumRangeMessage:"O Intervalo M\u00e1ximo Observ\u00e1vel deve ser maior que o Intervalo M\u00ednimo Observ\u00e1vel e n\u00e3o pode ser superior a ${limit} ${units}.",portalURLError:"A URL para sua organiza\u00e7\u00e3o do ArcGIS Online ou Portal for ArcGIS n\u00e3o est\u00e1 configurada. Verifique com seu administrador de sistema.",privilegeError:'Seu papel de usu\u00e1rio n\u00e3o pode executar an\u00e1lise. Para executar an\u00e1lise, o administrador da sua organiza\u00e7\u00e3o precisa conceder a voc\u00ea determinados \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3eprivil\u00e9gios\x3c/a\x3e.',
noServiceError:"Servi\u00e7o de an\u00e1lise de eleva\u00e7\u00e3o n\u00e3o dispon\u00edvel. Verifique as configura\u00e7\u00f5es da sua organiza\u00e7\u00e3o do ArcGIS Online ou Portal for ArcGIS.",pointToolTooltip:"Clique para adicionar localiza\u00e7\u00e3o do observador",degreesLabel:"graus",milsLabel:"mil\u00e9simo",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Graus Decimais - Latitude/Longitude",
DDLongLatNotation:"Graus Decimais - Longitude/Latitude",DDMLatLongNotation:"Graus Minutos Decimais - Latitude/Longitude",DDMLongLatNotation:"Graus Minutos Decimais - Longitude/Latitude",DMSLatLongNotation:"Graus Minutos Segundos - Latitude/Longitude",DMSLongLatNotation:"Graus Minutos Segundos - Longitude/Latitude",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - Letra da Banda",UTMHemNotation:"UTM - Hemisf\u00e9rio (N/S)",_localized:{}}});