// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} di ${total} risultati",gotoFirst:"Vai alla prima pagina",gotoNext:"Vai alla pagina successiva",gotoPrev:"Vai alla pagina precedente",gotoLast:"Vai all'ultima pagina",gotoPage:"Vai a pagina",jumpPage:"Passa a pagina",rowsPerPage:"Number of rows per page",_localized:{}},"esri/dijit/analysis/nls/DataStoreSelect":{relationalDS:"Relazionale",spatialDS:"Spaziotemporale",agsDataStore:"ArcGIS Data Store",bdfsTemplates:"Modelli di output di condivisione del file Big Data",
_localized:{}},"esri/dijit/analysis/nls/BrowseLayerMixin":{defaultAnaysisLayerTitle:"Scegli layer di analisi atlante dinamico",customAnalysisLayerTitle:"Scegliere un layer di analisi",searchPlaceholderText:"Cerca layer di analisi atlante dinamico",searchCustomPlaceholderText:"Cerca layer di analisi",mainActionTitle:"Seleziona",customActionName:"Seleziona e aggiungi alla mappa",customeSectionName:"Layer di analisi del Living Atlas",Categories:"Categorie",boundaries:"Boundary",places:"Luoghi",boundariesAndPlaces:"Confini e luoghi",
hexbins:"File binari esadecimali",transportation:"Trasporti",point:"Layer puntuali",line:"Layer polilineari",polygon:"Layer poligonali",pointFilterName:"Puntuale",lineFilterName:"Polilineare",polygonFilterName:"Poligonale",multiPointFilterName:"Multipunti",geometryFilterName:"Geometria",featureLayerName:"Feature Layer",tableLayerName:"Tabella",itemTypeFilterName:"Tipo di elemento",instantFilterName:"Istante",intervalFilterName:"Intervallo",timeFilterName:"Tempo",edit:"Modifica",boundaryLayers:"Layer di confine di Esri",
customAnalysisGroupName:"Gruppo di analisi dell\u2019organizzazione",_localized:{}},"widgets/Visibility/nls/strings":{_widgetLabel:"Visibilit\u00e0",observerLocation:"Posizione dell\u2019osservatore",formatIconTooltip:"Input formato",addPointToolTip:"Aggiungi posizione osservatore",fieldOfView:"Campo di vista",useMilsText:"Utilizzare miglia per angoli",observerHeight:"Altezza dell\u2019osservatore",minObsDistance:"Distanza minima dell\u2019osservatore",maxObsDistance:"Distanza massima dell\u2019osservatore",
taskURLError:"Il file di configurazione del widget contiene un URL non raggiungibile. Verificare con l'amministratore del sistema.",taskURLInvalid:"L\u2019attivit\u00e0 di geoprocessing configurata con questo widget non \u00e8 valida. Verificare con l'amministratore del sistema.",viewshedError:"Si \u00e8 verificato un errore durante la creazione della visibilit\u00e0. Verificare che la posizione dell\u2019osservatore si trovi all\u2019interno della superficie di elevazione.\x3c/p\x3e",validationError:"\x3cp\x3eIl modulo di creazione della visibilit\u00e0 contiene valori mancanti o non validi. Verificare:\x3c/p\x3e\x3cul\x3e\x3cli\x3eDi aver impostato una posizione dell\u2019osservatore.\x3c/li\x3e\x3cli\x3eChe il Campo di vista dell\u2019osservatore non sia 0.\x3c/li\x3e\x3cli\x3eChe l'altezza dell\u2019osservatore contenga un valore valido.\x3c/li\x3e\x3cli\x3eChe le distanze osservabili minima e massima contengano valori validi.\x3c/li\x3e\x3c/ul\x3e",
comfirmInputNotation:"Confermare l'input annotato.",notationsMatch:"Notazioni corrispondenti all'input. Confermare quale si desidera utilizzare:",createBtn:"Crea",clearBtn:"Cancella",setCoordFormat:"Imposta stringa di formato coordinata",prefixNumbers:"Aggiungere il prefisso '+/-' ai numeri positivi e negativi",parseCoordinatesError:"Impossibile analizzare le coordinate. Controllare l'input.",cancelBtn:"Annulla",applyBtn:"Applica",invalidMessage:"Immettere un valore numerico.",observerRangeMessage:"Altezza osservatore non valida",
minimumRangeMessage:"Intervallo minimo osservabile non valido",maximumRangeMessage:"L\u2019Intervallo massimo osservabile deve essere maggiore dell\u2019Intervallo minimo osservabile e non pu\u00f2 essere maggiore di ${limit} ${units}.",portalURLError:"L'URL dell'organizzazione ArcGIS Online o Portal for ArcGIS non \u00e8 stato configurato. Verificare insieme all'amministratore del sistema",privilegeError:'Il ruolo utente assegnato non consente di eseguire analisi. Per poter eseguire l\'analisi, l\'amministratore dell\'organizzazione deve concedere all\u2019utente determinati \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3eprivilegi\x3c/a\x3e.',
noServiceError:"Servizio di analisi elevazione non disponibile. Verificare le configurazioni dell\u2019organizzazione ArcGIS Online o di Portal for ArcGIS.",pointToolTooltip:"Fare clic per aggiungere la posizione dell\u2019osservatore",degreesLabel:"gradi",milsLabel:"miglia",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Gradi decimali - Latitudine/Longitudine",DDLongLatNotation:"Gradi decimali - Longitudine/Latitudine",
DDMLatLongNotation:"(DDM) Degrees Decimal Minutes - Latitude/Longitude",DDMLongLatNotation:"(DDM) Degrees Decimal Minutes - Longitude/Latitude",DMSLatLongNotation:"(DDS) Degrees Minutes Seconds - Latitude/Longitude",DMSLongLatNotation:"(DDS) Degrees Minutes Seconds - Longitude/Latitude",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - Band Letter",UTMHemNotation:"UTM - Hemisphere (N/S)",_localized:{}}});