// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fet",copy:"Kopier",cut:"Klipp ut","delete":"Slett",indent:"Innrykk",insertHorizontalRule:"Vannrett strek",insertOrderedList:"Nummerert liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Midtstill",justifyFull:"Juster",justifyLeft:"Venstrejuster",justifyRight:"H\u00f8yrejuster",outdent:"Fjern innrykk",paste:"Lim inn",redo:"Gj\u00f8r om",removeFormat:"Fjern format",selectAll:"Velg alle",strikethrough:"Gjennomstreking",subscript:"Senket skrift",
superscript:"Hevet skrift",underline:"Understreking",undo:"Angre",unlink:"Fjern kobling",createLink:"Opprett kobling",toggleDir:"Bytt retning",insertImage:"Sett inn bilde",insertTable:"Sett inn/rediger tabell",toggleTableBorder:"Bytt tabellkant",deleteTable:"Slett tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-kilde",foreColor:"Forgrunnsfarge",hiliteColor:"Bakgrunnsfarge",plainFormatBlock:"Avsnittsstil",formatBlock:"Avsnittsstil",fontSize:"Skriftst\u00f8rrelse",fontName:"Skriftnavn",tabIndent:"Tabulatorinnrykk",
fullScreen:"Sl\u00e5 p\u00e5/av full skjerm",viewSource:"Vis HTML-kilde",print:"Skriv ut",newPage:"Ny side",systemShortcut:'Handlingen "${0}" er bare tilgjengelig i nettleseren ved hjelp av en tastatursnarvei. Bruk ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"St\u00f8rrelse",fontName:"Skrift",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"kursiv",fantasy:"fantasi",noFormat:"Ingen",p:"Avsnitt",
h1:"Overskrift",h2:"Undertittel",h3:"Under-undertittel",pre:"Forh\u00e5ndsformatert",1:"xx-liten",2:"x-liten",3:"liten",4:"middels",5:"stor",6:"x-stor",7:"xx-stor",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Forh\u00e5ndsvis",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8k:",findTooltip:"Skriv inn teksten du vil s\u00f8ke etter",replaceLabel:"Erstatt med:",replaceTooltip:"Skriv inn teksten du vil erstatte med",findReplace:"S\u00f8k og erstatt",matchCase:"Skill mellom store og sm\u00e5 bokstaver",
matchCaseTooltip:"Skill mellom store og sm\u00e5 bokstaver",backwards:"Bakover",backwardsTooltip:"S\u00f8k bakover etter tekst",replaceAllButton:"Erstatt alle",replaceAllButtonTooltip:"Erstatt all tekst",findButton:"S\u00f8k",findButtonTooltip:"S\u00f8k etter teksten",replaceButton:"Erstatt",replaceButtonTooltip:"Erstatt teksten",replaceDialogText:"Erstattet ${0} forekomster.",eofDialogText:"Siste forekomst ${0}",eofDialogTextFind:"funnet",eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Lim inn fra Word",
instructions:"Lim inn innhold fra Word til tekstboksen nedenfor. N\u00e5r du er forn\u00f8yd med innholdet du skal sette inn, trykker du p\u00e5 innlimingsknappen. Hvis du vil avbryte innsettingen av teksten, trykker du p\u00e5 avbruddsknappen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Sett inn anker",title:"Ankeregenskaper",anchor:"Navn:",text:"Beskrivelse:",set:"Definer",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokksitat",_localized:{}},
"widgets/NetworkTrace/setting/nls/strings":{taskUrl:"Oppgave-URL",setTask:"Angi",setTaskPopupTitle:"Angi oppgave",validate:"Angi",inValidGPService:"Angi gyldig geoprosesseringstjeneste.",GPFeatureRecordSetLayerERR:"Angi en geoprosesseringstjeneste med inndata bare av typen \u00abGPFeatureRecordSetLayer\u00bb.",invalidInputParameters:"Antall inndataparametere er enten mindre enn 1 eller flere enn 3. Angi en gyldig geoprosesseringstjeneste.",projectSetting:{title:"Prosjektinnstillinger",note:"Merk: Prosjektinnstillinger er valgfrie, n\u00e5r de f\u00f8rst er konfigurert, kan brukeren lagre prosjektet i \u00f8nskede webkartlag med nettverkets omr\u00e5de for nedetid og inndataparametere. Brukeren kan lagre andre utdataparametere fra gruppen Utdata i kategorien Inndata/utdata.",
projectPolygonLayer:"Prosjektets polygonlag",outputParameterName:"Navn p\u00e5 utdataparameter",projectPointLayer:"Prosjektets punktlag",selectLabel:"Velg",polygonLayerHelp:"\x3cp\x3ePolygonlag med f\u00f8lgende vilk\u00e5r blir vist:\x3cbr/\x3e\x3cli\x3eLaget m\u00e5 ha redigeringsfunksjonene Opprett, Slett og Oppdater\x3c/li\x3e\x3cli\x3eLaget m\u00e5 ha to felt med eksakt navn og datatype:\x3c/li\x3e\x3cul\x3e\x3cli\x3enavn (felt av typen streng)\x3c/li\x3e\x3cli\x3eglobal-ID (felt av typen global ID )\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
outputParameterHelp:"\x3cp\x3ePolygonlag som utdata fra oppgave-URL-en vises\x3cp/\x3e",pointLayerHelp:"\x3cp\x3ePunktlag med f\u00f8lgende vilk\u00e5r blir vist: \x3cbr/\x3e\x3cli\x3eLaget m\u00e5 ha redigeringsfunksjonene Opprett, Slett og Oppdater\x3c/li\x3e\x3cli\x3eLaget m\u00e5 ha to felt med eksakt navn og datatype:\x3c/li\x3e\x3cul\x3e\x3cli\x3einndatatype (felt av typen streng)\x3c/li\x3e\x3cli\x3eprosjekt-ID (felt av typen GUID )\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e"},inputOutputTab:{title:"Inndata/utdata",
inputSettingsLabel:"Innstillinger for inndata",outputSettingsLabel:"Innstillinger for utdata",inputLabel:"Etikett",inputTooltip:"Verkt\u00f8ytips",symbol:"Symbol",typeText:"Type",outputParametersText:"Parametere for utdata",saveToLayerText:"Lagre i lag (valgfritt)",skipText:"Kan hoppes over",visibilityText:"Synlig",exportToCsvText:"Eksporter til CSV",exportToCsvDisplayText:"CSV",settitngstext:"Innstillinger",addFieldTitle:"Legg til felt",enterDisplayText:"Skriv inn visningstekst",setScale:"Angi m\u00e5lestokk",
outputDisplay:"Vis tekst",saveToLayerHelp:"\x3cp\x3eLag med f\u00f8lgende vilk\u00e5r blir vist:\x3cbr/\x3e\x3cli\x3eLaget m\u00e5 ha redigeringsfunksjonene Opprett, Slett og Oppdater\x3c/li\x3e\x3cli\x3eLaget m\u00e5 ha to felt med eksakt navn og datatype:\x3c/li\x3e\x3cul\x3e\x3cli\x3eparameternavn (felt av typen streng)\x3c/li\x3e\x3cli\x3eprosjekt-ID (felt av typen GUID )\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e"},summaryTab:{title:"Sammendrag",summaryFieldsetText:"Oversikt over innstillinger",inputOutput:"Inndata/utdata",
field:"Felter",operator:"Operat\u00f8rer",inputOperatorCountOption:"Antall",outputOperatorCountOption:"Antall",outputOperatorSkipCountOption:"Hopp over antall",fieldOperatorSumOption:"Sum",fieldOperatorMinOption:"Min",fieldOperatorMaxOption:"Maks",fieldOperatorMeanOption:"Gjennomsnitt",expressionAddButtonText:"Legg til",expressionVerifyButtonText:"Bekreft",summaryEditorText:"Tekstsammendrag"},generalSettings:{title:"Generelle innstillinger",displayTextForButtonLegend:"Vis tekst for Kj\u00f8r-knappen",
displayTextforButtonDefaultValue:"Kj\u00f8r",displayTextForButton:"Vis tekst",autoZoomAfterTrace:"Zoomalternativer",zoomText:"Automatisk zoom etter sporing"},validationErrorMessage:{webMapError:"Ingen lag er tilgjengelige i webkartet. Velg et gyldig webkart.",inputTypeFlagGreaterThanError:"Inndata av typen flagg kan ikke v\u00e6re mer enn \u00e9n.",inputTypeFlagLessThanError:"Minst \u00e9n inndata av typen flagg kreves.",inputTypeBarrierErr:"Inndata av typen hindring kan ikke v\u00e6re mer enn \u00e9n.",
inputTypeSkipErr:"Inndata av typen hopp over kan ikke v\u00e6re mer enn \u00e9n.",displayTextForButtonError:"Visningstekst for Kj\u00f8r-knappen m\u00e5 v\u00e6re utfylt.",UnableToLoadGeoprocessError:"Kan ikke laste geoprosesseringstjeneste.",invalidSummaryExpression:"Ugyldig uttrykk.",validSummaryExpression:"Vellykket!",invalidProjectSettings:"Ugyldige prosjektinnstillinger.\x3cbr/\x3e Velg en gyldig verdi i '${projectSetting}'."},hintText:{labelTextHint:"Tips: Opprett visningsetikett til resultatpanelet for utdataparameteren.",
displayTextHint:"Tips: Dette vises i detaljpanelet for denne utdataparameteren.",inputTextHint:"Tips: Bygg uttrykket ovenfor ved \u00e5 velge inndata, utdata og feltnavn.",expressionHint:"Tips: Velg elementer og klikk p\u00e5 Legg til for \u00e5 bygge uttrykk."},_localized:{}}});