// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Consultas",addNew:"Adicionar novo",newQuery:"Nova consulta",queryLayer:"Consultar camada",setSource:"Configurar",setDataSource:"Configurar fonte de dados",name:"Nome",querySource:"Fonte de dados",queryName:"Nome da tarefa",queryDefinition:"Defini\u00e7\u00e3o de filtro",resultsSetting:"Configura\u00e7\u00e3o de resultados",symbolSetting:"Configura\u00e7\u00e3o de s\u00edmbolo",resultSettingTip:"Defina quais e como exibir os resultados de sa\u00edda.",
resultItemTitle:"T\u00edtulo de cada item do resultado",resultItemContent:"Estes atributos do campo aparecer\u00e3o",fieldsSetTip:"Verifique os campos que voc\u00ea deseja exibir. Selecione um campo para atualizar seu nome alternativo, ordem e formato.",addField:"Adicionar campo",visibility:"Visibilidade",alias:"Nome Alternativo",specialType:"Tipo especial",actions:"A\u00e7\u00f5es",none:"Nenhum",link:"Link",image:"Imagem",noField:"Nenhum campo",operationalLayerTip:"Adicionar resultado como camada operacional",
setLayerSymbolTip:"Configure o s\u00edmbolo para resultados da consulta: ",setSelectedSymbolTip:"Configurar s\u00edmbolo da fei\u00e7\u00e3o selecionada.",notUseFilter:"N\u00e3o utilizar filtro",setSourceTip:"Configure a origem da consulta.",setFilterTip:"Configure o filtro corretamente.",ok:"Ok",cancel:"Cancelar",noFilterTip:"Sem express\u00e3o de filtro definida, esta tarefa de consulta listar\u00e1 todas as fei\u00e7\u00f5es na fonte de dados especificada.",relationships:"Relacionamentos",addRelationshipLayer:"Adicionar novo relacionamento",
relatedTo:"Relacionado \u00e0",selectOption:"Selecione..",resultItemSorting:"Classifica\u00e7\u00e3o de item do resultado",field:"Campo",sortingOrder:"Ordenar",configureFieldsTip:"Configure os campos que o resultado da consulta ser\u00e1 classificado.",setSortingFields:"Definir campos de classifica\u00e7\u00e3o",ascending:"Crescente",descending:"Descendente",sortBy:"Classificar por",thenBy:"Ent\u00e3o por",addTask:"Adicionar tarefa",noTasksTip:'Nenhuma consulta configurada. Clique em "${newQuery}" para adicionar uma nova.',
infoText:"Info",filters:"Filtros",results:"Resultados",optionsText:"Op\u00e7\u00f5es",summaryText:"Resumo",attributeFilter:"Filtro de atributos",attributeFilterTip:"Defina express\u00f5es de atributo para utilizar no widget para filtrar a camada de consulta.",defineWhereClause:"Defina uma cl\u00e1usula 'where' para a consulta.",noExpressionDefinedTip:"Nenhuma express\u00e3o definida. Todos os registros ser\u00e3o retornados.",setExpressions:"Definir express\u00f5es",spatialFilter:"Filtros espaciais",
spatialFilterTip:"Escolha quais filtros espaciais estar\u00e3o dispon\u00edveis para usu\u00e1rios finais.",defaultOption:"Padr\u00e3o",useCurrentExtentTip:"Retornar somente fei\u00e7\u00f5es dentro da extens\u00e3o de mapa atual",useDrawGraphicTip:"Somente retorna fei\u00e7\u00f5es que interseccionam com a forma desenhada no mapa",useFeaturesTip:"Retornar somente fei\u00e7\u00f5es que t\u00eam um relacionamento espacial com fei\u00e7\u00f5es em outra camada",noSpatialLimitTip:"Retornar fei\u00e7\u00f5es dentro da extens\u00e3o total do mapa",
drawingTools:"Escolher ferramentas de desenho",bufferSettings:"Habilitar op\u00e7\u00e3o de buffer",defaultDistance:"Dist\u00e2ncia Padr\u00e3o",bufferDistance:"Dist\u00e2ncia do Buffer",defaultUnit:"Unidade Padr\u00e3o",miles:"Milhas",kilometers:"Quil\u00f4metros",feet:"P\u00e9s",meters:"Metros",yards:"Jardas",nauticalMiles:"Milhas n\u00e1uticas",availableSpatialRelationships:"Escolha as regras de relacionamento espacial",setSpatialRelationships:"Configurar relacionamentos espaciais",availability:"Disponibilidade",
relationship:"Relacionamento",label:"R\u00f3tulo",intersect:"interseccionar",contain:"cont\u00e9m",areContainedIn:"est\u00e3o contidos em",cross:"cruz",envelopeIntersect:"intersec\u00e7\u00e3o de envelope",overlap:"sobreposi\u00e7\u00e3o",areOverlapped:"est\u00e3o sobrepostos",touch:"tocar",within:"dentro",areWithin:"est\u00e3o dentro",indexIntersect:"intersec\u00e7\u00e3o de \u00edndice",itemTitle:"T\u00edtulo do item",displayFields:"Campos de visualiza\u00e7\u00e3o",sortingFields:"Classificar itens resultantes",
setDisplayFields:"Definir campos de visualiza\u00e7\u00e3o",symbol:"S\u00edmbolo",setSymbol:"Utilizar s\u00edmbolo personalizado",changeSymbolAtRuntime:"Permite alterar s\u00edmbolos no runtime",serviceSymbolTip:"Utilizar s\u00edmbolos definidos pela camada",exportTip:"Permitir exportar os resultados",keepResultsTip:"Manter resultados no mapa ap\u00f3s o widget ser fechado",queryRelatedRecords:"Consultar registros relacionados",createLayerForTaskTip:"Especifique como a tarefa de consulta cria camadas",
oneLayerForTaskTip:"Substituir a camada cada vez que a consulta for executada",multipleLayerForTaskTip:"Criar uma nova camada cada vez que a consulta for executada",makeDefault:"Tornar padr\u00e3o",icon:"\u00cdcone",newTask:"Nova tarefa",addTaskTip:"Adicione uma ou mais consultas ao widget e configure os par\u00e2metros de cada uma delas.",webMapPopupTip:"Utilizar configura\u00e7\u00e3o de pop-up da camada no mapa da web",customPopupTip:"Configurar conte\u00fado personalizado",showResultsSetActions:"Mostrar a\u00e7\u00f5es para o conjunto de resultados",
zoomTo:"Zoom para",openAttributeTable:"Visualizar na Tabela de Atributos",content:"Conte\u00fado",displaySQLTip:"Exibir express\u00e3o SQL para usu\u00e1rios finais",useLayerDefaultSymbol:"Utilizar s\u00edmbolo padr\u00e3o da camada",setCustomIcon:"Definir \u00edcone personalizado",layerDefaultSymbolTip:"Utilizar s\u00edmbolo padr\u00e3o da camada",uploadImage:"Carregar uma Imagem",attributeCriteira:"Crit\u00e9rios de atributos",specifyFilterAtRuntimeTip:"Os usu\u00e1rios precisar\u00e3o especificar par\u00e2metros para esta express\u00e3o.",
value:"VALOR",hideLayersTip:"Desative as camadas de resultado da consulta quando o widget estiver fechado.",tabLabels:"R\u00f3tulos da tabela",tasks:"Tarefas",queryCriteira:"Crit\u00e9rios de consulta",allowCustomQuery:"Permitir a cria\u00e7\u00e3o de consulta personalizada",showFilterLabelTip:"Mostrar r\u00f3tulos de dados",querySettings:"Configura\u00e7\u00f5es de consulta",expandTip:"Expandir a lista de resultados por padr\u00e3o",customResultNameTip:"Mostrar a op\u00e7\u00e3o para configurar \x3cstrong\x3eNome de camada de resultado\x3c/strong\x3e personalizada",
_localized:{}}});