// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Drafter de Lotes",newTraverseButtonLabel:"Iniciar Nova Transversal",invalidConfigMsg:"Configura\u00e7\u00e3o Inv\u00e1lida",geometryServiceURLNotFoundMSG:"N\u00e3o \u00e9 poss\u00edvel obter URL de Servi\u00e7o de Geometria",editTraverseButtonLabel:"Editar Transversal",mapTooltipForStartNewTraverse:"Selecione um ponto no mapa, ou digite abaixo, para iniciar",mapTooltipForEditNewTraverse:"Selecione um lote para editar",mapTooltipForUpdateStartPoint:"Clique para atualizar ponto inicial",
mapTooltipForScreenDigitization:"Clique para adicionar ponto de lotes",mapTooltipForUpdatingRotaionPoint:"Clique para atualizar o ponto de rota\u00e7\u00e3o",mapTooltipForRotate:"Arraste para rotacionar",mapTooltipForScale:"Arraste para dimensionar",backButtonTooltip:"Voltar",newTraverseTitle:"Nova Transversal",editTraverseTitle:"Editar Transversal",clearingDataConfirmationMessage:"As altera\u00e7\u00f5es ser\u00e3o descartadas, deseja prosseguir?",unableToFetchParcelMessage:"N\u00e3o \u00e9 poss\u00edvel buscar lotes.",
unableToFetchParcelLinesMessage:"N\u00e3o \u00e9 poss\u00edvel buscar linhas de lotes.",planSettings:{planSettingsTitle:"Configura\u00e7\u00f5es",directionOrAngleTypeLabel:"Tipo de \u00c2ngulo ou Dire\u00e7\u00e3o",directionOrAngleUnitsLabel:"Unidades de \u00c2ngulo ou Dire\u00e7\u00e3o",distanceAndLengthUnitsLabel:"Unidades de Comprimento e Dist\u00e2ncia",areaUnitsLabel:"Unidades de \u00c1rea",circularCurveParameters:"Par\u00e2metros da Curva Circulares",northAzimuth:"Azimute Norte",southAzimuth:"Azimute Sul",
quadrantBearing:"Posi\u00e7\u00e3o do Quadrante",radiusAndChordLength:"Raio e Comprimento da Corda",radiusAndArcLength:"Raio e Comprimento do Arco",expandGridTooltipText:"Expandir grade",collapseGridTooltipText:"Recolher grade",zoomToLocationTooltipText:"Zoom na localiza\u00e7\u00e3o",onScreenDigitizationTooltipText:"Digitalizar",updateRotationPointTooltipText:"Atualizar ponto de rota\u00e7\u00e3o"},traverseSettings:{bearingLabel:"Dire\u00e7\u00e3o",lengthLabel:"Comprimento",radiusLabel:"Raio",noMiscloseCalculated:"Fechamento n\u00e3o calculado",
traverseMiscloseBearing:"Dire\u00e7\u00e3o de Fechamento",traverseAccuracy:"Precis\u00e3o",accuracyHigh:"Alto",traverseDistance:"Dist\u00e2ncia de Fechamento",traverseMiscloseRatio:"Taxa de Fechamento",traverseStatedArea:"StatedArea",traverseCalculatedArea:"\u00c1rea Calculada",addButtonTitle:"Adicionar",deleteButtonTitle:"Remover"},parcelTools:{rotationToolLabel:"\u00c2ngulo",scaleToolLabel:"Escala"},newTraverse:{invalidBearingMessage:"Dire\u00e7\u00e3o inv\u00e1lida.",invalidLengthMessage:"Comprimento Inv\u00e1lido.",
invalidRadiusMessage:"Raio Inv\u00e1lido.",negativeLengthMessage:"V\u00e1lido somente para curvas",enterValidValuesMessage:"Insira valores v\u00e1lidos.",enterValidParcelInfoMessage:"Insira algumas informa\u00e7\u00f5es de lotes v\u00e1lidos para salvar.",unableToDrawLineMessage:"N\u00e3o \u00e9 poss\u00edvel desenhar linha.",invalidEndPointMessage:"Ponto Final inv\u00e1lido, n\u00e3o \u00e9 poss\u00edvel desenhar linha."},planInfo:{requiredText:"(exigido)",optionalText:"(opcional)",parcelNamePlaceholderText:"Nome do lote",
parcelDocumentTypeText:"Tipo do documento",planNamePlaceholderText:"Nome do Plano",cancelButtonLabel:"Cancelar",saveButtonLabel:"Salvar",saveNonClosedParcelConfirmationMessage:"O lote inserido n\u00e3o est\u00e1 fechado, ainda deseja prosseguir e salvar somente as linhas de lotes?",unableToCreatePolygonParcel:"N\u00e3o \u00e9 poss\u00edvel criar pol\u00edgono de lotes.",unableToSavePolygonParcel:"N\u00e3o \u00e9 poss\u00edvel salvar pol\u00edgono de lotes.",unableToSaveParcelLines:"N\u00e3o \u00e9 poss\u00edvel salvar linhas de lotes.",
unableToUpdateParcelLines:"N\u00e3o \u00e9 poss\u00edvel atualizar linhas de lotes.",parcelSavedSuccessMessage:"Lotes salvos com sucesso.",parcelDeletedSuccessMessage:"Lote exclu\u00eddo com sucesso.",parcelDeleteErrorMessage:"Erro ao excluir lote.",enterValidParcelNameMessage:"Insira nome de lote v\u00e1lido.",enterValidPlanNameMessage:"Insira nome de plano v\u00e1lido.",enterValidDocumentTypeMessage:"Tipo de documento inv\u00e1lido.",enterValidStatedAreaNameMessage:"Insira \u00e1rea declarada v\u00e1lida."},
xyInput:{explanation:"Na refer\u00eancia espacial da sua camada de lotes"},_localized:{}}});