// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Exibir ou esconder colunas",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Tabela de Atributos",_featureAction_ShowRelatedRecords:"Exibir registos relacionados",_featureAction_ViewInTable:"Visualizar em Tabela de Atributos",ok:"OK",cancel:"Cancelar",unsupportQueryWarning:"A camada tem de suportar opera\u00e7\u00f5es de consulta para ser exibida no widget de Tabela de Atributos. Garanta que a capacidade de consulta est\u00e1 ligada no servi\u00e7o.",
exportMessage:"Exportar dados para ficheiro CSV?",exportFiles:"Exportar para CSV",exportSelected:"Exportar selecionados para CSV",exportAll:"Exportar todos para CSV",options:"Op\u00e7\u00f5es",zoomto:"Efetuar zoom para",highlight:"Destacar gr\u00e1ficos",selectAll:"Selecionar registos em todas as p\u00e1ginas",selectPage:"Selecionar registos na p\u00e1gina atual",clearSelection:"Limpar sele\u00e7\u00e3o",filter:"Filtro",setFilterTip:"Por favor, defina os filtros corretamente.",noFilterTip:"Sem express\u00f5es de filtro definidas, esta tarefa de consulta ir\u00e1 listar todos os elementos na fonte de dados especificada.",
filterByExtent:"Filtrar por extens\u00e3o de mapa",showSelectedRecords:"Exibir registos selecionados",showAllRecords:"Exibir todos os registos",showRelatedRecords:"Exibir registos relacionados",noRelatedRecords:"N\u00e3o foram encontrados registos relacionados",highlightAllRecords:"Real\u00e7ar todos os registos no mapa",attachmentColumn:"Fotografias e ficheiros",refresh:"Atualizar",features:"elementos",records:"registos",selected:"selecionado",transparent:"Modo transparente",indicate:"Localizar sele\u00e7\u00e3o",
columns:"Exibir/Ocultar colunas",selectionSymbol:"S\u00edmbolo de sele\u00e7\u00e3o",closeMessage:"Ocultar tabela (Voltar a expandi-la a partir do fundo)",dataNotAvailable:"Dados n\u00e3o dispon\u00edveis!\x3cbr\x3eClique no bot\u00e3o [Atualizar] para fazer uma tentativa",openTableTip:"Abrir tabela de atributos",closeTableTip:"Esconder a tabela de atributos",sortAsc:"Ordem crescente",sortDes:"Ordem decrescente",statistics:"Estat\u00edsticas",attachments:"Anexos",files:"ficheiros",keepRichTextLabel:"Manter formato de texto rico",
whatsThis:"O que \u00e9 isto?",richTextMessage:{explanatoryText:{line1:"${layerName} cont\u00e9m o(s) seguinte(s) campo(s) de texto rico: ",line2:" que podem incluir estilos de formata\u00e7\u00e3o de texto, como tipos de letra, cores ou tamanhos de textos.",line3:'Quando s\u00e3o exposrtados para CSV, os estilos de formata\u00e7\u00e3o ser\u00e3o preservados na forma de etiquetas HTML. Pode optar por n\u00e3o manter os formatos de texto rico, desmarcando a caixa "Keep rich text format\u201d .'},
example:{label:"Por exemplo:",scenarios:{first:"ser\u00e1 exportado como o seguinte texto por predefni\u00e7\u00e3o:",second:"e o seguinte texto sem formato de texto rico:"}}},noTablesAvailable:"Sem tabelas dispon\u00edveis para exibir.",checkConfigutationToSelectLayers:"Por favor, v\u00e1 \u00e0 p\u00e1gina de defini\u00e7\u00f5es do widget para selecionar camadas.",checkLayerListToSelectLayers:"A Tabela de Atributos encontra-se sincronizada com camadas vis\u00edveis no mapa,  pode utilizar um widget, tal como Layer List para alternar camadas entre ligado/desligado.",
_localized:{}}});