// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dimensione",fontName:"Carattere",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",
monospace:"spaziatura fissa",cursive:"corsivo",fantasy:"fantasy",noFormat:"Nessuna",p:"Paragrafo",h1:"Intestazione",h2:"Sottointestazione",h3:"Sottointestazione secondaria",pre:"Preformattato",1:"piccolissimo",2:"molto piccolo",3:"piccolo",4:"medio",5:"grande",6:"molto grande",7:"grandissimo",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Anteprima",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Trova:",findTooltip:"Immettere il testo da ricercare",replaceLabel:"Sostituisci con:",
replaceTooltip:"Immettere il testo con cui sostituire",findReplace:"Trova e sostituisci",matchCase:"Corrispondenza maiuscolo/minuscolo",matchCaseTooltip:"Corrispondenza maiuscolo/minuscolo",backwards:"Indietro",backwardsTooltip:"Ricercare il testo all'indietro",replaceAllButton:"Sostituisci tutti",replaceAllButtonTooltip:"Sostituisci tutto il testo",findButton:"Trova",findButtonTooltip:"Trova il testo",replaceButton:"Sostituisci",replaceButtonTooltip:"Sostituisci il testo",replaceDialogText:"Sostituite ${0} ricorrenze.",
eofDialogText:"Ultime ${0} ricorrenze",eofDialogTextFind:"trovato",eofDialogTextReplace:"sostituito",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Incolla da Word",instructions:"Incollare i contenuti da Word nella seguente casella di testo. Quando si \u00e8 deciso quali contenuti inserire, fare clic sul pulsante incolla. Per interrompere l'inserimento del testo premere il pulsante annulla.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserisci ancoraggio",
title:"Propriet\u00e0 ancoraggio",anchor:"Nome:",text:"Descrizione:",set:"Imposta",cancel:"Annulla",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Impostazioni grafico",addNewLabel:"Aggiungi nuovo",generalSettingLabel:"Impostazioni generali",searchSourceSettingLabel:"Cerca impostazioni origine",layerChooser:{title:"Selezionare layer da rappresentare",selectPolygonLayerLabel:"Seleziona layer",
selectPolygonLayerHintText:"Suggerimento: se si configurano pi\u00f9 grafici, il tipo di geometria dei layer deve essere identica",selectRelatedTableLayerLabel:"Seleziona tabella correlata a layer",selectRelatedTableLayerHintText:"Suggerimento: vengono visualizzate solo le tabelle con campi numerici",errorInSelectingPolygonLayer:"Selezionare un layer con un layer punto correlato.",errorInSelectingRelatedLayer:"Selezionare una tabella/layer correlato valido nel layer.",polygonLayerNotHavingRelationships:"Il layer selezionato non dispone di tabella/layer correlato."},
ChartSetting:{sectionTitle:"Titolo sezione",sectionTitleHintText:"Suggerimento: visualizzato nel titolo intestazione sezione",chartTitle:"Titolo grafico",chartTitleHintText:"Suggerimento: visualizzato al centro nella parte superiore del grafico",chartDescription:"Descrizione",chartDescriptionHintText:"Suggerimento: visualizzato sotto il grafico",chartType:"Tipo di grafico",barChart:"Grafico a barre",pieChart:"Grafico a torta",polarChart:"Grafico polare",lineChart:"Grafico a linee",dataSeriesField:"Campo serie di dati",
lineDataSeriesField:"Campo valore",labelField:"Campo etichetta",lineLabelSeriesField:"Campo Sequenza",chartColor:"Colore grafico",singleColor:"Colore singolo",colorByTheme:"Colore in base a tema",colorByFieldValue:"Colore in base a valore campo",xAxisTitle:"Titolo asse X",xAxisHintText:"Suggerimento: titolo asse X",yAxisTitle:"Titolo asse Y",yAxisHintText:"Suggerimento: titolo asse Y",fieldColorLabel:"Etichetta",fieldColorColor:"Colore",defaultFieldSelectLabel:"Seleziona",errMsgFieldValuesNotFound:"Impossibile trovare i valori per il campo selezionato",
errMsgSectionTitle:"Immettere i titolo di sezione",errMsgFieldByValue:"Selezionare un colore per valore campo",errMsgDataSeriesField:"Selezionare un campo valore",settingTabTitle:"Impostazione",layoutTabTitle:"Layout",polarChartSelectFieldsHintText:"Suggerimento: selezionare campi per generare grafico polare",visibilityText:"Visibilit\u00e0",fieldNameText:"Nome campo",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Selezionare tre o pi\u00f9 campi per generare grafico polare",polarChartPolygonFillLabel:"Riempi poligono",
polarChartPolygonFillHintText:"Suggerimento: selezionare la casella di controllo per mostrare il riempimento poligono nel grafico polare",viewLayoutLabel:"Layout",setValueFields:"Imposta campi valore",layoutSeriesLabel:"Serie",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"Deserto",themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",
themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Irlanda",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Terreno paludoso",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},
GeneralSetting:{legendGeneralSettingText:"Impostazioni generali",locationSymbolLabel:"Simbolo posizione grafica",locationSymbolHintText:"Suggerimento: utilizzato per visualizzare simbolo per posizione indirizzo e selezione",refreshIntervalLabel:"Intervallo di aggiornamento",refreshIntervalHintText:"Suggerimento: utilizzato per aggiornare i grafici basati su questo intervallo. Specificare un valore compreso tra 1 e 1440 minuti",errMsgRefreshInterval:"Specificare l'intervallo di aggiornamento compreso tra 0 e 1440 minuti",
symbolPickerPreviewText:"Anteprima:",showToolToSelectLabel:"Pulsante Imposta posizione",showToolToSelectHintText:"Suggerimento: fornisce un pulsante per impostare la posizione sulla mappa anzich\u00e9 impostare sempre la posizione quando si fa clic sulla mappa"},searchSourceSetting:{searchSourceSettingTabTitle:"Cerca impostazioni origine",searchSourceSettingTitle:"Cerca impostazioni origine",searchSourceSettingTitleHintText:"Aggiungere e configurare servizi di geocodifica o feature layer come fonti di ricerca. Queste fonti specificate determinano ci\u00f2 che \u00e8 possibile cercare nella casella di ricerca",
addSearchSourceLabel:"Aggiungi fonte di ricerca",featureLayerLabel:"Feature Layer",geocoderLabel:"Geocodificatore",nameTitle:"Nome",generalSettingLabel:"Impostazioni generali",allPlaceholderLabel:"Testo segnaposto per la ricerca in tutti:",allPlaceholderHintText:"Suggerimento: immettere il testo da visualizzare come segnaposto durante la ricerca di tutti i layer e geocodificatore",generalSettingCheckboxLabel:"Mostra il popup per la feature o per la posizione trovata",countryCode:"Codici paesi o regioni",
countryCodeEg:"es. ",countryCodeHint:"Se si lascia vuoto questo campo, la ricerca verr\u00e0 effettuata in tutti i paesi e le regioni",questionMark:"?",searchInCurrentMapExtent:"Esegui la ricerca nell'estensione mappa corrente",zoomScale:"Scala zoom",locatorUrl:"URL del geocodificatore",locatorName:"Nome geocodificatore",locatorExample:"Esempio",locatorWarning:"Questa versione del servizio di geocodifica non \u00e8 supportata. Il widget supporta il servizio di geocodifica 10.0 e versioni successive.",
locatorTips:"I suggerimenti non sono disponibili perch\u00e9 il servizio di geocodifica non supporta tale funzionalit\u00e0.",layerSource:"Origine del layer",setLayerSource:"Imposta layer di origine",setGeocoderURL:"Imposta URL geocodificatore",searchLayerTips:"I suggerimenti non sono disponibili perch\u00e9 il feature service non supporta la funzionalit\u00e0 di paginazione.",placeholder:"Testo del segnaposto",searchFields:"Campi di ricerca",displayField:"Visualizza campo",exactMatch:"Corrispondenza esatta",
maxSuggestions:"Suggerimenti massimi",maxResults:"Risultati massimi",enableLocalSearch:"Abilita ricerca locale",minScale:"Scala Minima",minScaleHint:"Quando la scala della mappa \u00e8 pi\u00f9 grande di questa scala, verr\u00e0 applicata la ricerca locale",radius:"Raggio",radiusHint:"Specifica il raggio di un'area intorno al centro della mappa corrente che viene utilizzato per assegnare la priorit\u00e0 alla classificazione dei candidati di geocodifica in modo che i canditati pi\u00f9 vicini alla posizione vengano restituiti per primi",
meters:"Metri",setSearchFields:"Imposta campi di ricerca",set:"Imposta",fieldName:"Nome",invalidSearchSources:"Impostazioni fonte di ricerca non valide",invalidUrlTip:"URL ${URL} non valido o non accessibile."},_localized:{}}});