// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Tebal",copy:"Salin",cut:"Potong","delete":"Hapus",indent:"Inden",insertHorizontalRule:"Penggaris horisontal",insertOrderedList:"Daftar Bernomor",insertUnorderedList:"Daftar Poin",italic:"Miring",justifyCenter:"Rata Tengah",justifyFull:"Rata Kanan Kiri",justifyLeft:"Rata Kiri",justifyRight:"Rata Kanan",outdent:"Hapus spasi di depan",paste:"Tempel",redo:"Ulangi",removeFormat:"Hapus Format",selectAll:"Pilih Semua",strikethrough:"Coretan",subscript:"Subskrip",
superscript:"Superskrip",underline:"Garis Bawah",undo:"Batalkan",unlink:"Hapus Tautan",createLink:"Buat Tautan",toggleDir:"Ubah Arah",insertImage:"Masukkan Gambar",insertTable:"Masukkan/Edit Tabel",toggleTableBorder:"Ubah Tepi Tabel",deleteTable:"Hapus Tabel",tableProp:"Properti Tabel",htmlToggle:"Sumber HTML",foreColor:"Warna Latar Depan",hiliteColor:"Warna Latar Belakang",plainFormatBlock:"Gaya Paragraf",formatBlock:"Gaya Paragraf",fontSize:"Ukuran Font",fontName:"Nama Font",tabIndent:"Inden Tab",
fullScreen:"Beralih ke Layar Penuh",viewSource:"Lihat Sumber HTML",print:"Cetak",newPage:"Halaman Baru",systemShortcut:'Tindakan "${0}" hanya tersedia pada peramban Anda menggunakan jalan pintas keyboard. Gunakan ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Ukuran",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"None",p:"Paragraf",h1:"Judul",
h2:"Sub Judul",h3:"Sub sub judul",pre:"Praformat",1:"xx-kecil",2:"x-kecil",3:"kecil",4:"medium",5:"besar",6:"x-besar",7:"xx-besar",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pratinjau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Temukan:",findTooltip:"Masukkan teks untuk menemukan",replaceLabel:"Ganti dengan:",replaceTooltip:"Masukkan teks untuk mengganti",findReplace:"Temukan dan Ganti",matchCase:"Cocokkan huruf",matchCaseTooltip:"Cocokkan huruf",backwards:"Mundur",
backwardsTooltip:"Mencari mundur teks",replaceAllButton:"Ganti Semua",replaceAllButtonTooltip:"Ganti semua teks",findButton:"Temukan",findButtonTooltip:"Temukan teks",replaceButton:"Ganti",replaceButtonTooltip:"Ganti teks",replaceDialogText:"Terjadi penggantian ${0}.",eofDialogText:"${0} terakhir kali terjadi",eofDialogTextFind:"Ditemukan",eofDialogTextReplace:"Diganti",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Tempel Dari Word",instructions:"Tempelkan konten dari Word ke dalam kotak teks di bawah.  Setelah Anda merasa yakin dengan konten yang disisipkan, tekan tombol tempel.  Untuk membatalkan penyisipan teks, tekan tombol batal.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Masukkan Jangkar",title:"Properti Jangkar",anchor:"Nama:",text:"Deskripsi:",set:"Atur",cancel:"Batal",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Pengaturan grafik",addNewLabel:"Tambah baru",generalSettingLabel:"Pengaturan umum",searchSourceSettingLabel:"Pengaturan Sumber Pencarian",layerChooser:{title:"Pilih layer untuk grafik",
selectPolygonLayerLabel:"Pilih layer",selectPolygonLayerHintText:"Petunjuk: Jika mengonfigurasi beberapa grafik, layer harus berjenis geometri yang sama",selectRelatedTableLayerLabel:"Pilih tabel yang terkait dengan layer",selectRelatedTableLayerHintText:"Petunjuk: Hanya tabel dengan kolom angka yang ditampilkan",errorInSelectingPolygonLayer:"Pilihlah layer yang memiliki layer titik terkait.",errorInSelectingRelatedLayer:"Pilihlah tabel/layer terkait yang valid untuk layer.",polygonLayerNotHavingRelationships:"Layer terpilih tidak mempunyai tabel/layer terkait apa pun."},
ChartSetting:{sectionTitle:"Judul bagian",sectionTitleHintText:"Petunjuk: Ditampilkan pada judul kepala bagian",chartTitle:"Judul grafik",chartTitleHintText:"Petunjuk: Ditampilkan di tengah atas grafik",chartDescription:"Deskripsi",chartDescriptionHintText:"Petunjuk: Ditampilkan di bawah grafik",chartType:"Jenis grafik",barChart:"Bar chart",pieChart:"Pie chart",polarChart:"Polar chart",lineChart:"Grafik garis",dataSeriesField:"Kolom rangkaian data",lineDataSeriesField:"Kolom nilai",labelField:"Kolom label",
lineLabelSeriesField:"Kolom urutan",chartColor:"Warna grafik",singleColor:"Warna tunggal",colorByTheme:"Warna menurut tema",colorByFieldValue:"Warna menurut nilai kolom",xAxisTitle:"Judul sumbu X",xAxisHintText:"Petunjuk: Judul sumbu X",yAxisTitle:"Judul sumbu Y",yAxisHintText:"Petunjuk: Judul sumbu Y",fieldColorLabel:"Label",fieldColorColor:"Warna",defaultFieldSelectLabel:"Pilih",errMsgFieldValuesNotFound:"Tidak dapat menemukan nilai untuk kolom terpilih",errMsgSectionTitle:"Masukkan judul bagian",
errMsgFieldByValue:"Harap pilih warna menurut nilai kolom",errMsgDataSeriesField:"Harap pilih kolom nilai",settingTabTitle:"Pengaturan",layoutTabTitle:"Layout",polarChartSelectFieldsHintText:"Petunjuk: Pilih kolom untuk menghasilkan polar chart",visibilityText:"Visibilitas",fieldNameText:"Nama Kolom",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Pilihlah tiga atau lebih kolom untuk menghasilkan polar chart",polarChartPolygonFillLabel:"Isi poligon",polarChartPolygonFillHintText:"Petunjuk: Pilih kotak centang untuk memperlihatkan poligon mengisi bagan polar",
viewLayoutLabel:"Tata Letak",setValueFields:"Atur Kolom Nilai",layoutSeriesLabel:"Rangkaian",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"Desert",themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Ireland",themeMiamiNice:"MiamiNice",
themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Wetland",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Pengaturan Umum",locationSymbolLabel:"Simbol lokasi grafik",locationSymbolHintText:"Petunjuk: Digunakan untuk menampilkan simbol untuk alamat dan lokasi klik",
refreshIntervalLabel:"Interval penyegaran",refreshIntervalHintText:"Petunjuk: Digunakan untuk menyegarkan bagan berdasarkan interval ini. Tentukan nilai antara 1 hingga 1440 menit",errMsgRefreshInterval:"Tentukan interval penyegaran antara 0 hingga 1440 menit",symbolPickerPreviewText:"Pratinjau:",showToolToSelectLabel:"Atur tombol lokasi",showToolToSelectHintText:"Petunjuk: Berikan tombol untuk menetapkan lokasi pada peta alih-alih selalu mengatur lokasi ketika peta diklik"},searchSourceSetting:{searchSourceSettingTabTitle:"Pengaturan Sumber Pencarian",
searchSourceSettingTitle:"Pengaturan Sumber Pencarian",searchSourceSettingTitleHintText:"Tambah dan konfigurasikan service geocode atau feature layer sebagai sumber pencarian. Sumber yang ditentukan ini akan menentukan apa saja yang dapat dicari dalam kotak pencarian",addSearchSourceLabel:"Tambah Sumber Pencarian",featureLayerLabel:"Feature layer",geocoderLabel:"Geocoder",nameTitle:"Nama",generalSettingLabel:"Pengaturan Umum",allPlaceholderLabel:"Teks placeholder untuk mencari semua:",allPlaceholderHintText:"Petunjuk: Masukkan teks untuk ditampilkan sebagai placeholder ketika mencari semua layer dan geocoder",
generalSettingCheckboxLabel:"Tampilkan pop-up untuk fitur atau lokasi yang ditemukan",countryCode:"Kode Negara atau Wilayah",countryCodeEg:"mis., ",countryCodeHint:"Membiarkan nilai ini kosong berarti akan mencari semua negara dan wilayah",questionMark:"?",searchInCurrentMapExtent:"Cari hanya dalam jangkauan peta saat ini",zoomScale:"Skala Zoom",locatorUrl:"URL Geocoder",locatorName:"Nama Geocoder",locatorExample:"Contoh",locatorWarning:"Versi service geocode tidak didukung. Widget mendukung service geocode versi 10.0 dan lebih tinggi.",
locatorTips:"Saran tidak tersedia karena service geocode tidak mendukung kemampuan saran.",layerSource:"Sumber Layer",setLayerSource:"Atur Sumber Layer",setGeocoderURL:"Atur URL Geocoder",searchLayerTips:"Saran tidak tersedia karena feature service tidak mendukung kemampuan penomoran halaman.",placeholder:"Teks Placeholder",searchFields:"Kolom Pencarian",displayField:"Kolom Tampilan",exactMatch:"Benar-Benar Cocok",maxSuggestions:"Saran Maksimum",maxResults:"Hasil Maksimum",enableLocalSearch:"Aktifkan pencarian lokal",
minScale:"Skala Min",minScaleHint:"Apabila skala peta lebih besar daripada skala ini, pencarian lokal akan diterapkan",radius:"Radius",radiusHint:"Menentukan radius dari area di sekitar pusat peta saat ini yang digunakan untuk mendorong peringkat calon geocoding sehingga calon yang terdekat dengan lokasi akan dimunculkan terlebih dahulu",meters:"Meter",setSearchFields:"Atur Kolom Pencarian",set:"Atur",fieldName:"Nama",invalidSearchSources:"Pengaturan sumber pencarian tidak valid",invalidUrlTip:"URL ${URL} tidak valid atau tidak dapat diakses."},
_localized:{}}});