// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/PublicNotification/setting/nls/strings":{searchSourceSetting:{title:"S\u00f8ke- og bufferinnstillinger",mainHint:"Du kan aktivere teksts\u00f8k etter adresser og geoobjekter, geometridigitalisering og buffere."},addressSourceSetting:{title:"Adresselag",mainHint:"Du kan angi hvilke adressatetikettlag som er tilgjengelige."},notificationSetting:{title:"Varselalternativer",mainHint:"Du kan angi hvilke typer varsler som er tilgjengelige."},groupingLabels:{addressSources:"Lag som skal brukes til \u00e5 velge adressatlag",
averyStickersDetails:"Avery(r)-etiketter",csvDetails:"Kommadelt verdifil (CSV)",drawingTools:"Tegneverkt\u00f8y for angivelse av omr\u00e5de",featureLayerDetails:"Geoobjektslag",geocoderDetails:"Geokoder",labelFormats:"Tilgjengelige etikettformater",printingOptions:"Alternativer for utskrevne etikettsider",searchSources:"S\u00f8k i kilder",stickerFormatDetails:"Sideparametere for etiketter"},hints:{alignmentAids:"Merker er lagt til i etikettsiden for \u00e5 hjelpe deg med \u00e5 justere siden til skriveren din",
csvNameList:"En kommadelt liste over feltnavn der det skilles mellom sm\u00e5 og store bokstaver",horizontalGap:"Mellomrom mellom to etiketter i en rad",insetToLabel:"Mellomrom mellom siden av etiketten og begynnelsen av teksten",labelFormatDescription:"Hvordan etikettstilen vises i listen med widgetformatalternativer",labelFormatDescriptionHint:"Verkt\u00f8ytips som supplerer beskrivelsen i listen med formatalternativer",labelHeight:"H\u00f8yde for hver etikett p\u00e5 siden",labelWidth:"Bredde for hver etikett p\u00e5 siden",
localSearchRadius:"Angir radiusen for et omr\u00e5de rundt det gjeldende midtpunktet i kartet som brukes til \u00e5 styrke rangeringen til geokodingskandidater, slik at kandidater n\u00e6rmest lokasjonen returneres f\u00f8rst",rasterResolution:"100 piksler per tomme passer omtrent for skjermoppl\u00f8sningen. Jo h\u00f8yere oppl\u00f8sning, jo st\u00f8rre nettleserminne kreves. Nettlesere har forskjellig evne til \u00e5 h\u00e5ndtere store krav til minne.",selectionListOfOptionsToDisplay:"Merkede elementer vises som alternativer i widgeten, endre rekkef\u00f8lge etter behov",
verticalGap:"Mellomrom mellom to etiketter i en kolonne"},propertyLabels:{bufferDefaultDistance:"Standard bufferavstand",bufferUnits:"Bufferenheter som skal angis i widgeten",countryRegionCodes:"Lands- eller regionskoder",description:"Beskrivelse",descriptionHint:"Beskrivelsestips",displayField:"Visningsfelt",drawingToolsFreehandPolygon:"frih\u00e5ndspolygon",drawingToolsLine:"linje",drawingToolsPoint:"punkt",drawingToolsPolygon:"polygon",drawingToolsPolyline:"polylinje",enableLocalSearch:"Aktiver lokalt s\u00f8k",
exactMatch:"N\u00f8yaktig samsvar",fontSizeAlignmentNote:"Skriftst\u00f8rrelse for merknad om utskriftsmarger",gridDarkness:"M\u00f8rkhet for rutenett",gridlineLeftInset:"Innsetting av venstre st\u00f8ttelinje",gridlineMajorTickMarksGap:"Store aksemerker for hver",gridlineMinorTickMarksGap:"Sm\u00e5 aksemerker for hver",gridlineRightInset:"Innsetting av h\u00f8yre st\u00f8ttelinje",labelBorderDarkness:"M\u00f8rkhet for etikettkantlinje",labelBottomEdge:"Nedre kant av etiketter p\u00e5 side",labelFontSize:"Skriftst\u00f8rrelse",
labelHeight:"Etiketth\u00f8yde",labelHorizontalGap:"Vannrett mellomrom",labelInitialInset:"Sett inn i etikettekst",labelLeftEdge:"Venstre kant av etiketter p\u00e5 side",labelMaxLineCount:"Maksimalt antall linjer i etikett",labelPageHeight:"Sideh\u00f8yde",labelPageWidth:"Sidebredde",labelRightEdge:"H\u00f8yre kant av etiketter p\u00e5 side",labelsInAColumn:"Antall etiketter i en kolonne",labelsInARow:"Antall etiketter i en rad",labelTopEdge:"\u00d8vre kant av etiketter p\u00e5 side",labelVerticalGap:"Loddrett mellomrom",
labelWidth:"Etikettbredde",limitSearchToMapExtent:"S\u00f8k kun i gjeldende kartutstrekning",maximumResults:"Maksimum antall resultater",maximumSuggestions:"Maksimum antall forslag",minimumScale:"Minste m\u00e5lestokk",name:"Navn",percentBlack:"% svart",pixels:"piksler",pixelsPerInch:"piksler per tomme",placeholderText:"Plassholdertekst",placeholderTextForAllSources:"Plassholdertekst for s\u00f8k i alle kilder",radius:"Radius",rasterResolution:"Rasteroppl\u00f8sning",searchFields:"S\u00f8kefelter",
showAlignmentAids:"Vis justeringshjelpemidler p\u00e5 side",showGridTickMarks:"Vis aksemerker",showLabelOutlines:"Vis etikettomriss",showPopupForFoundItem:"Vis popuptekst for funnet geoobjekt eller lokasjon",tool:"Verkt\u00f8y",units:"Enheter",url:"URL",urlToGeometryService:"URL til geometritjeneste",useRelatedRecords:"Bruk relaterte poster",useSecondarySearchLayer:"Bruk sekund\u00e6rt utvalgslag",useSelectionDrawTools:"Bruk tegneverkt\u00f8y for utvalg",useVectorFonts:"Bruk vektorskrifter (bare latinske skrifter)",
zoomScale:"Zoomeskala"},buttons:{addAddressSource:"Legg til lag som inneholder adresseetiketter i popupen",addLabelFormat:"Legg til etikettformat",addSearchSource:"Legg til s\u00f8kekilde",set:"Angi"},placeholders:{averyExample:"f.eks. Avery(r)-etikett ${averyPartNumber}",countryRegionCodes:"f.eks. USA,CHN",descriptionCSV:"Kommadelte verdier",descriptionPDF:"PDF-etikett ${heightLabelIn} x ${widthLabelIn} tommer; ${labelsPerPage} per side"},tooltips:{getWebmapFeatureLayer:"Hent geoobjektlaget fra webkartet",
openCountryCodes:"Klikk for \u00e5 f\u00e5 mer informasjon om koder",openFieldSelector:"Klikk for \u00e5 \u00e5pne en feltvelger",setAndValidateURL:"Angi og valider URL-en"},problems:{noAddresseeLayers:"Angi minst ett adressatlag",noBufferUnitsForDrawingTools:"Konfigurer minst \u00e9n bufferenhet for tegneverkt\u00f8yene",noBufferUnitsForSearchSource:'Konfigurer minst \u00e9n bufferenhet for s\u00f8kekilden "${sourceName}"',noGeometryServiceURL:"Konfigurer URL-en til geometritjenesten",noNotificationLabelFormats:"Angi mist ett etikettformat for varsler",
noSearchSourceFields:'Konfigurer ett eller flere felt for s\u00f8kekilden "${sourceName}"',noSearchSourceURL:'Konfigurer URL-en for s\u00f8kekilden "${sourceName}"'},querySourceSetting:{sourceSetting:"S\u00f8kekildeinnstillinger",instruction:"Legg til og konfigurer geokodingstjenester eller geoobjektlag som s\u00f8kekilder. Disse angitte kildene bestemmer hva som er s\u00f8kbart i s\u00f8keboksen.",add:"Legg til s\u00f8kekilde",addGeocoder:"Legg til geokoder",geocoder:"Geokoder",setLayerSource:"Angi lagkilde",
setGeocoderURL:"Angi geokoder-URL",searchableLayer:"Geoobjektslag",name:"Navn",countryCode:"Lands- eller regionskode(r)",countryCodeEg:"f.eks. ",countryCodeHint:"Hvis du lar dette feltet st\u00e5 tomt, s\u00f8kes det i alle land og regioner",generalSetting:"Generelle innstillinger",allPlaceholder:"Plassholdertekst for s\u00f8k i alt: ",showInfoWindowOnSelect:"Vis popuptekst for funnet geoobjekt eller lokasjon",showInfoWindowOnSelect2:"Vis popup n\u00e5r geoobjektet eller lokasjonen blir funnet.",
searchInCurrentMapExtent:"S\u00f8k kun i gjeldende kartutstrekning",zoomScale:"Zoomeskala",locatorUrl:"Geokoder-URL",locatorName:"Geokodernavn",locatorExample:"Eksempel",locatorWarning:"Denne versjonen av geokodingstjenesten st\u00f8ttes ikke. Miniprogrammet st\u00f8tter geokodingstjeneste 10.1 og nyere.",locatorTips:"Forslag er ikke tilgjengelige fordi geokodingstjenesten ikke har st\u00f8tte for forslag.",layerSource:"Lagkilde",searchLayerTips:"Forslag er ikke tilgjengelige, fordi geoobjektstjenesten ikke har st\u00f8tte for paginering.",
placeholder:"Plassholdertekst",searchFields:"S\u00f8kefelter",displayField:"Visningsfelt",exactMatch:"N\u00f8yaktig samsvar",maxSuggestions:"Maksimum antall forslag",maxResults:"Maksimum antall resultater",enableLocalSearch:"Aktiver lokalt s\u00f8k",minScale:"Minste m\u00e5lestokk",minScaleHint:"N\u00e5r kartm\u00e5lestokken er st\u00f8rre enn denne m\u00e5lestokken, brukes lokalt s\u00f8k",radius:"Radius",radiusHint:"Angir radiusen for et omr\u00e5de rundt det gjeldende midtpunktet i kartet som brukes til \u00e5 styrke rangeringen til geokodingskandidater, slik at kandidater n\u00e6rmest lokasjonen returneres f\u00f8rst",
meters:"Meter",setSearchFields:"Angi s\u00f8kefelter",set:"Angi",fieldSearchable:"s\u00f8kbar(t)",fieldName:"Navn",fieldAlias:"Alias",ok:"OK",cancel:"Avbryt",invalidUrlTip:"URL-en ${URL} er ugyldig eller ikke tilgjengelig.",locateResults:"Finn resultater",panTo:"Panorer til",zoomToScale:"Zoom til m\u00e5lestokk",locatorError:"Lokator m\u00e5 st\u00f8tte enkeltlinjes\u00f8k."},_localized:{}}});