// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Vet",copy:"Kopi\u00ebren",cut:"Knippen","delete":"Wissen",indent:"Inspringen",insertHorizontalRule:"Horizontale liniaal",insertOrderedList:"Genummerde lijst",insertUnorderedList:"Lijst met opsommingstekens",italic:"Cursief",justifyCenter:"Centreren",justifyFull:"Uitvullen",justifyLeft:"Links uitlijnen",justifyRight:"Rechts uitlijnen",outdent:"Uitspringen",paste:"Plakken",redo:"Opnieuw",removeFormat:"Opmaak verwijderen",selectAll:"Alles selecteren",strikethrough:"Doorhalen",
subscript:"Subscript",superscript:"Superscript",underline:"Onderstrepen",undo:"Ongedaan maken",unlink:"Link verwijderen",createLink:"Link maken",toggleDir:"Schrijfrichting wijzigen",insertImage:"Afbeelding invoegen",insertTable:"Tabel invoegen/bewerken",toggleTableBorder:"Tabelkader wijzigen",deleteTable:"Tabel wissen",tableProp:"Tabeleigenschap",htmlToggle:"HTML-bron",foreColor:"Voorgrondkleur",hiliteColor:"Achtergrondkleur",plainFormatBlock:"Alineastijl",formatBlock:"Alineastijl",fontSize:"Lettergrootte",
fontName:"Lettertype",tabIndent:"Inspringen",fullScreen:"Volledig scherm in-/uitschakelen",viewSource:"HTML-bron bekijken",print:"Afdrukken",newPage:"Nieuwe pagina",systemShortcut:'De actie "${0}" is alleen beschikbaar in uw browser via een sneltoetscombinatie. Gebruik ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Grootte",fontName:"Lettertype",formatBlock:"Opmaak",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursief",
fantasy:"fantasy",noFormat:"Geen",p:"Alinea",h1:"Kop",h2:"Subkop",h3:"Sub-subkop",pre:"Vooraf opgemaakt",1:"xx-klein",2:"x-klein",3:"klein",4:"gemiddeld",5:"groot",6:"x-groot",7:"xx-groot",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Zoeken:",findTooltip:"Geef de zoektekst op",replaceLabel:"Vervangen door:",replaceTooltip:"Geef de vervangende tekst op",findReplace:"Zoeken en vervangen",matchCase:"Hoofdlettergevoelig",
matchCaseTooltip:"Hoofdlettergevoelig",backwards:"Terug",backwardsTooltip:"Terugwaarts naar tekst zoeken",replaceAllButton:"Alle vervangen",replaceAllButtonTooltip:"Gehele tekst vervangen",findButton:"Zoeken:",findButtonTooltip:"Tekst zoeken",replaceButton:"Vervangen",replaceButtonTooltip:"Tekst vervangen",replaceDialogText:"${0} vervangingen.",eofDialogText:"Laatste positie ${0}",eofDialogTextFind:"gevonden",eofDialogTextReplace:"vervangen",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Plakken vanuit Word",
instructions:"Plak de content vanuit Word in het tekstvak hieronder. Klik als u klaar bent op de knop Plakken. Kies Annuleren als u de invoeging van tekst wilt afbreken.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker invoegen",title:"Ankereigenschappen",anchor:"Naam:",text:"Beschrijving:",set:"Instellen",cancel:"Annuleren",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Grafiekinstellingen",
addNewLabel:"Nieuwe toevoegen",generalSettingLabel:"Algemene instellingen",searchSourceSettingLabel:"Broninstellingen zoeken",layerChooser:{title:"Lagen selecteren voor grafiek",selectPolygonLayerLabel:"Kaartlaag selecteren",selectPolygonLayerHintText:"Tip: Als u meerdere grafieken configureert, dan moeten de lagen van hetzelfde geometrietype zijn",selectRelatedTableLayerLabel:"Selecteer tabel gerelateerd aan laag",selectRelatedTableLayerHintText:"Tip: Alleen tabellen met numerieke velden worden weergegeven",
errorInSelectingPolygonLayer:"Selecteer een laag met een bijbehorende puntlaag.",errorInSelectingRelatedLayer:"Selecteer een geldige gerelateerde tabel/laag op laag.",polygonLayerNotHavingRelationships:"Geselecteerde laag heeft geen gerelateerde tabel/laag."},ChartSetting:{sectionTitle:"Sectietitel",sectionTitleHintText:"Tip: weergegeven in hoofdstuk koptekst",chartTitle:"Grafiektitel",chartTitleHintText:"Tip: weergegeven gecentreerd aan bovenkant grafiek",chartDescription:"Beschrijving",chartDescriptionHintText:"Tip: weergegeven onder grafiek",
chartType:"Grafiektype",barChart:"Staafdiagram",pieChart:"Cirkeldiagram",polarChart:"Polaire grafiek",lineChart:"Lijndiagram",dataSeriesField:"Gegevensreeks veld",lineDataSeriesField:"Waardeveld",labelField:"Labelveld",lineLabelSeriesField:"Volgordeveld",chartColor:"Grafiekkleur",singleColor:"E\u00e9n kleur",colorByTheme:"Kleur per thema",colorByFieldValue:"Kleur per veldwaarde",xAxisTitle:"X-astitel",xAxisHintText:"Tip: X-astitel",yAxisTitle:"Y-astitel",yAxisHintText:"Tip: Y-astitel",fieldColorLabel:"Label",
fieldColorColor:"Kleur",defaultFieldSelectLabel:"Selecteren",errMsgFieldValuesNotFound:"Kan geen waarden vinden voor het geselecteerde veld.",errMsgSectionTitle:"Voer de hoofdstuktitel in.",errMsgFieldByValue:"Selecteer de kleur op veldwaarde",errMsgDataSeriesField:"Selecteer een waardeveld",settingTabTitle:"Instelling",layoutTabTitle:"Lay-out",polarChartSelectFieldsHintText:"Tip: Selecteer velden om polaire grafiek te genereren",visibilityText:"Zichtbaarheid",fieldNameText:"Veldnaam",aliasNameText:"Alias",
errMsgPolarFieldsRequired:"Selecteer drie of meer velden om een polaire grafiek te genereren",polarChartPolygonFillLabel:"Vul polygoon",polarChartPolygonFillHintText:"Tip: Selecteer selectievakje om de polygoonvulling te tonen in een polaire grafiek",viewLayoutLabel:"Lay-out",setValueFields:"Waardevelden instellen",layoutSeriesLabel:"Serie",ThemeSelector:{themeAdobebricks:"Adobebricks",themeAlgae:"Algae",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"Woestijn",
themeDistinctive:"Distinctive",themeDollar:"Dollar",themeGrasshopper:"Grasshopper",themeGrasslands:"Grasslands",themeGreySkies:"GreySkies",themeHarmony:"Harmony",themeIndigoNation:"IndigoNation",themeIreland:"Ierland",themeMiamiNice:"MiamiNice",themeMinty:"Minty",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Waterrijk gebied",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",
themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Algemene instellingen",locationSymbolLabel:"Grafisch locatiesymbool",locationSymbolHintText:"Tip: gebruikt voor de weergave van symbool voor adres en klik op locatie",refreshIntervalLabel:"Interval voor vernieuwen",refreshIntervalHintText:"Tip: gebruikt voor het vernieuwen van grafieken gebaseerd op deze interval. Geef een waarde op tussen 1 en 1440 minuten",
errMsgRefreshInterval:"Geef de interval op voor vernieuwen tussen 0 tot 1440 minuten",symbolPickerPreviewText:"Voorbeeld:",showToolToSelectLabel:"Knop locatie instellen",showToolToSelectHintText:"Opmerking: Biedt een knop om de locatie op de kaart in te stellen in plaats van altijd de locatie in te stellen wanneer op de kaart wordt geklikt"},searchSourceSetting:{searchSourceSettingTabTitle:"Broninstellingen zoeken",searchSourceSettingTitle:"Broninstellingen zoeken",searchSourceSettingTitleHintText:"Geocodeerservices of objectlagen toevoegen en configureren als zoekbronnen. Deze gespecificeerde bronnen bepalen wat doorzoekbaar is in het zoekvak.",
addSearchSourceLabel:"Zoekbron toevoegen",featureLayerLabel:"Objectlaag",geocoderLabel:"Geocoder",nameTitle:"Naam",generalSettingLabel:"Algemene instelling",allPlaceholderLabel:"Plaatshoudertekst om alles te zoeken:",allPlaceholderHintText:"Hint: Voer tekst in die moet worden getoond als plaatshouder tijdens het zoeken door alle lagen en geocoder",generalSettingCheckboxLabel:"Pop-up weergeven voor gevonden object of locatie",countryCode:"Land- of regiocode(s)",countryCodeEg:"bijv. ",countryCodeHint:"Laat deze waarde leeg en alle landen en regio's worden doorzocht",
questionMark:"?",searchInCurrentMapExtent:"Alleen zoeken in huidige kaartextent",zoomScale:"Schaal voor in-/uitzoomen",locatorUrl:"Geocoder-URL",locatorName:"Naam van geocoder",locatorExample:"Voorbeeld",locatorWarning:"Deze versie van geocodeerservice wordt niet ondersteund. De widget ondersteunt geocodeerservice 10.0 en hoger.",locatorTips:"Suggesties zijn niet beschikbaar omdat de geocodeerservice geen suggesties ondersteunt.",layerSource:"Laagbron",setLayerSource:"Laagbron instellen",setGeocoderURL:"Geocoder-URL instellen",
searchLayerTips:"Suggesties zijn niet beschikbaar omdat de feautureservice geen paginering ondersteunt.",placeholder:"Tekst van tijdelijke aanduiding",searchFields:"Zoekvelden",displayField:"Weergaveveld:",exactMatch:"Exacte overeenkomst",maxSuggestions:"Maximale suggesties",maxResults:"Maximale resultaten",enableLocalSearch:"Lokaal zoeken inschakelen",minScale:"Min.schaal",minScaleHint:"Als de kaartschaal groter is dan deze schaal, dan zal lokaal zoeken toegepast worden",radius:"Straal",radiusHint:"Bepaalt de straal van een gebied rond het midden van de huidige kaart, die gebruikt wordt om de rangorde van geocoding-kandidaten te versterken zodat kandidaten die het dichtst in de buurt zijn eerst weergegeven worden",
meters:"Meter",setSearchFields:"Zoekvelden instellen",set:"Instellen",fieldName:"Naam",invalidSearchSources:"Ongeldige instellingen zoekbron",invalidUrlTip:"De URL ${URL} is ongeldig of ontoegankelijk."},_localized:{}}});