// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Upit",executeQueryTip:"Kliknite na jednu od slede\u0107ih stavki zadataka da biste izvr\u0161ili upit.",invalidConfig:"Neva\u017ee\u0107a konfiguracija. Koristite stranicu postavki Upita da biste dobili ispravnu konfiguraciju.",queryParams:"Opcije",parameters:"OPCIJE",queries:"UPITI",apply:"Primeni",queryResults:"Rezultati",clear:"Izbri\u0161i",noResults:"Nije prona\u0111en nijedan geoobjekat.",queryError:"Neuspeo upit!",numberFound:"Broj prona\u0111enih geoobjekata",
mapExtentTip:"Ograni\u010di rezultate na trenutnu oblast mape.",noValue:"Nema vrednosti",and:"i",stringOperatorIs:"je",stringOperatorIsNot:"nije",stringOperatorStartsWith:"po\u010dinje sa",stringOperatorEndsWith:"zavr\u0161ava se sa",stringOperatorContains:"sadr\u017ei",stringOperatorDoesNotContain:"ne sadr\u017ei",stringOperatorIsBlank:"je prazno",stringOperatorIsNotBlank:"nije prazno",dateOperatorIsOn:"je na",dateOperatorIsNotOn:"nije na",dateOperatorIsBefore:"je ispred",dateOperatorIsAfter:"je iza",
dateOperatorDays:"dani",dateOperatorWeeks:"sedmice",dateOperatorMonths:"meseci",dateOperatorInTheLast:"u poslednjih",dateOperatorNotInTheLast:"nije u poslednjih",dateOperatorIsBetween:"je izme\u0111u",dateOperatorIsNotBetween:"nije izme\u0111u",dateOperatorIsBlank:"je prazno",dateOperatorIsNotBlank:"nije prazno",numberOperatorIs:"je",numberOperatorIsNot:"nije",numberOperatorIsAtLeast:"je najmanje",numberOperatorIsLessThan:"je manje od",numberOperatorIsAtMost:"je najvi\u0161e",numberOperatorIsGreaterThan:"je ve\u0107e od",
numberOperatorIsBetween:"je izme\u0111u",numberOperatorIsNotBetween:"nije izme\u0111u",numberOperatorIsBlank:"je prazno",numberOperatorIsNotBlank:"nije prazno",operationalLayerTip:"Dodaj rezultate kao operativni sloj",queryResult:"Rezultat upita",specifyParamsTip:"Navedite parametre za ovaj zadatak",useSpatialFilter:"Koristite prostorni filter da biste ograni\u010dili geoobjekte",useCurrentMapExtent:"Samo geoobjekti koji presecaju trenutnu povr\u0161inu mape",drawGraphicOnMap:"Samo geoobjekti koji presecaju povr\u0161inu koju korisnik odredi",
specifySpatialFilterMsg:"Navedite prostorni filter za ovaj zadatak.",clearResults:"Obri\u0161i rezultate",operationalTip:"Kada je ova opcija potvr\u0111ena, rezultati \u0107e biti zadr\u017eani na mapi dok ne kliknete na dugme \u201e${clearResults}\u201c.",noneQueryTip:"Nema konfigurisanog zadatka upita za ovaj vid\u017eet.",noPermissionsMsg:"Nemate dozvole da pristupite ovom servisu.",attributesFromRelationship:"Atributi iz povezane table",tasks:"Zadaci",applySpatialFilterToLimitResults:"Primenite prostorni filter da biste ograni\u010dili rezultate",
useCurrentExtentTip:"Vrati samo geoobjekte unutar trenutnog obuhvata mape",useDrawGraphicTip:"Vrati samo geoobjekte koji se ukr\u0161taju sa oblikom nacrtanim na mapi",useFeaturesTip:"Vrati samo geoobjekte koji imaju prostornu vezu sa geoobjektima u drugom sloju",noSpatialLimitTip:"Vrati geoobjekte unutar potpunog obuhvata mape",applySearchDistance:"Primeni rastojanje pretrage",spatialRelationship:"Prostorna veza",relatedLayer:"Povezani sloj",bufferDistance:"Rastojanje zone bliskosti",miles:"Milje",
kilometers:"Kilometri",feet:"Stope",meters:"Metri",yards:"Jardi",nauticalMiles:"Nauti\u010dke milje",back:"Nazad",execute:"Izvr\u0161i",zoomTo:"Zumiraj na",openAttributeTable:"Prika\u017ei u tabeli atributa",noResult:"Bez rezultata.",noTask:"Bez zadatka.",removeThisResult:"Ukloni ovaj rezultat",attributeCriteira:"Kriterijumi atributa",spatialFilter:"Prostorni filter",value:"VREDNOST",noAttributeSpatialFilterTip:"Nema definisanih filtera. Svi geoobjekti \u0107e biti vra\u0107eni.",showAllRelatedRecords:"Prika\u017ei sve povezane zapise",
changeSymbol:"Promeni simbol",queryCriteira:"Kriterijum upita",customQuery:"Prilago\u0111eni upit",layer:"Sloj",createCustomQuery:"Kreiraj prilago\u0111eni upit.",rename:"Preimenuj",clearShapeTip:"Obri\u0161ite ovaj oblik nakon primene upita.",displayedFeatures:"Prikazani geoobjekti",loadMore:"U\u010ditaj vi\u0161e",expandAll:"Pro\u0161iri sve",collapseAll:"Skupi sve",_localized:{}}});