// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Screening/nls/strings":{_widgetLabel:"Screening",geometryServicesNotFound:"Geometrie-service niet beschikbaar.",unableToDrawBuffer:"Kan buffer niet tekenen. Probeer het opnieuw.",invalidConfiguration:"Ongeldige configuratie.",clearAOIButtonLabel:"Opnieuw beginnen",noGraphicsShapefile:"De ge\u00fcploade shapefile bevat geen grafische gegevens.",zoomToLocationTooltipText:"Inzoomen op locatie",noGraphicsToZoomMessage:"Geen grafische gegevens gevonden om in te zoomen.",placenameWidget:{placenameLabel:"Zoeken naar een locatie"},
drawToolWidget:{useDrawToolForAOILabel:"Tekenmodus selecteren",toggleSelectability:"Klik om selecteerbaarheid te wisselen",chooseLayerTitle:"Kies selecteerbare lagen",selectAllLayersText:"Alles selecteren",layerSelectionWarningTooltip:"Ten minste \u00e9\u00e9n laag moet geselecteerd worden voor het maken van AOI"},shapefileWidget:{shapefileLabel:"Een gezipte shapefile uploaden",uploadShapefileButtonText:"Uploaden",unableToUploadShapefileMessage:"Kan shapefile niet uploaden."},coordinatesWidget:{selectStartPointFromSearchText:"Een startpunt defini\u00ebren",
addButtonTitle:"Toevoegen",deleteButtonTitle:"Verwijderen",mapTooltipForStartPoint:"Klik op de kaart om een startpunt te defini\u00ebren",mapTooltipForUpdateStartPoint:"Klik op de kaart om het startpunt te updaten",locateText:"Zoom naar",locateByMapClickText:"Initi\u00eble co\u00f6rdinaten selecteren",enterBearingAndDistanceLabel:"Richting en afstand van een startpunt invoeren",bearingTitle:"Richting",distanceTitle:"Afstand",planSettingTooltip:"Instellingen plannen",invalidLatLongMessage:"Voer geldige waarden in."},
bufferDistanceAndUnit:{bufferInputTitle:"Bufferafstand (optioneel)",bufferInputLabel:"Resultaten weergeven binnen"},traverseSettings:{bearingLabel:"Richting",lengthLabel:"Lengte",addButtonTitle:"Toevoegen",deleteButtonTitle:"Verwijderen"},planSettings:{expandGridTooltipText:"Raster uitvouwen",collapseGridTooltipText:"Raster samenvouwen",directionUnitLabelText:"Eenheid routebeschrijving",distanceUnitLabelText:"Eenheden afstand en lengte",planSettingsComingSoonText:"Binnenkort beschikbaar"},newTraverse:{invalidBearingMessage:"Ongeldige richting.",
invalidLengthMessage:"Ongeldige lengte.",negativeLengthMessage:"Negatieve lengte"},reportsTab:{aoiAreaText:"AOI-gebied",downloadButtonTooltip:"Downloaden",printButtonTooltip:"Afdrukken",uploadShapefileForAnalysisText:"Shapefile uploaden om in analyse in te sluiten",uploadShapefileForButtonText:"Bladeren",downloadLabelText:"Opmaak selecteren:",downloadBtnText:"Downloaden",noDetailsAvailableText:"Geen resultaten gevonden",featureCountText:"Aantal",featureAreaText:"Gebied",featureLengthText:"Lengte",
attributeChooserTooltip:"Weer te geven attributen kiezen",csv:"CSV",filegdb:"File geodatabase",shapefile:"Shapefile",noFeaturesFound:"Geen resultaat gevonden voor geselecteerde bestandindeling",selectReportFieldTitle:"Velden selecteren",noFieldsSelected:"Geen velden geselecteerd",intersectingFeatureExceedsMsgOnCompletion:"Voor een of meerdere lagen is het maximale aantal records bereikt.",unableToAnalyzeText:"Kan niet analyseren, maximale aantal records bereikt.",errorInPrintingReport:"Kan het rapport niet afdrukken. Controleer of de rapportinstellingen geldig zijn.",
aoiInformationTitle:"Interessegebied (AOI) informatie",summaryReportTitle:"Samenvatting",notApplicableText:"NVT",downloadReportConfirmTitle:"Download bevestigen",downloadReportConfirmMessage:"Weet u zeker dat u wilt downloaden?",noDataText:"Geen gegevens",createReplicaFailedMessage:"Download mislukt voor volgende la(a)g(en): \x3cbr/\x3e ${layerNames}",extractDataTaskFailedMessage:"Download mislukt.",printLayoutLabelText:"Lay-out",printBtnText:"Afdrukken",printDialogHint:"Opmerking: De naam en commentaren in het rapport kunnen bewerkt worden in de voorbeeldweergave van het rapport.",
unableToDownloadFileGDBText:"File Geodatabase kan niet worden gedownload voor AOI met punt- of lijnlocaties",unableToDownloadShapefileText:"Shapefile kan niet worden gedownload voor AOI met punt- of lijnlocaties",analysisUnitLabelText:"Resultaten weergeven in :",analysisUnitButtonTooltip:"Kies eenheden voor analyse",analysisCloseBtnText:"Sluiten",feetUnit:"Voet / vierkante voet",milesUnit:"Mijl / acre",metersUnit:"Meter / vierkante meter",kilometersUnit:"Kilometer / vierkante kilometer",hectaresUnit:"Kilometers / hectares",
hectaresAbbr:"hectare",layerNotVisibleText:"Kan niet analyseren. Laag is uitgeschakeld of is buiten het zichtbereik van de schaal.",refreshBtnTooltip:"Rapport vernieuwen",featureCSVAreaText:"Intersectiegebied",featureCSVLengthText:"Intersectielengte",errorInFetchingPrintTask:"Fout bij laden van afdruktaakinformatie. Probeer opnieuw.",selectAllLabel:"Alles selecteren",errorInLoadingProjectionModule:"Fout tijdens het laden van de afhankelijkheden van de projectiemodule. Probeer het bestand opnieuw te downloaden."},
_localized:{}}});