// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Consulta",executeQueryTip:"Clique em um dos seguintes itens da tarefa para executar a consulta.",invalidConfig:"Configura\u00e7\u00e3o inv\u00e1lida. Utilize a p\u00e1gina de configura\u00e7\u00e3o da Consulta para obter a configura\u00e7\u00e3o correta.",queryParams:"Op\u00e7\u00f5es",parameters:"OP\u00c7\u00d5ES",queries:"CONSULTAS",apply:"Aplicar",queryResults:"Resultados",clear:"Limpar",noResults:"Nenhuma fei\u00e7\u00e3o encontrada.",queryError:"Falha ao consultar !",
numberFound:"N\u00famero de fei\u00e7\u00f5es encontradas",mapExtentTip:"Limite os resultados na extens\u00e3o de mapa atual.",noValue:"Nenhum valor",and:"e",stringOperatorIs:"\u00e9",stringOperatorIsNot:"n\u00e3o \u00e9",stringOperatorStartsWith:"inicia com",stringOperatorEndsWith:"finaliza com",stringOperatorContains:"cont\u00e9m",stringOperatorDoesNotContain:"n\u00e3o cont\u00e9m",stringOperatorIsBlank:"est\u00e1 em branco",stringOperatorIsNotBlank:"n\u00e3o est\u00e1 em branco",dateOperatorIsOn:"est\u00e1 em",
dateOperatorIsNotOn:"n\u00e3o est\u00e1 em",dateOperatorIsBefore:"est\u00e1 antes",dateOperatorIsAfter:"est\u00e1 ap\u00f3s",dateOperatorDays:"dias",dateOperatorWeeks:"semanas",dateOperatorMonths:"meses",dateOperatorInTheLast:"no \u00faltimo",dateOperatorNotInTheLast:"n\u00e3o no \u00faltimo",dateOperatorIsBetween:"est\u00e1 entre",dateOperatorIsNotBetween:"n\u00e3o est\u00e1 entre",dateOperatorIsBlank:"est\u00e1 em branco",dateOperatorIsNotBlank:"n\u00e3o est\u00e1 em branco",numberOperatorIs:"\u00e9",
numberOperatorIsNot:"n\u00e3o \u00e9",numberOperatorIsAtLeast:"\u00e9 pelo menos",numberOperatorIsLessThan:"\u00e9 menor que",numberOperatorIsAtMost:"\u00e9 na maioria",numberOperatorIsGreaterThan:"\u00e9 maior que",numberOperatorIsBetween:"est\u00e1 entre",numberOperatorIsNotBetween:"n\u00e3o est\u00e1 entre",numberOperatorIsBlank:"est\u00e1 em branco",numberOperatorIsNotBlank:"n\u00e3o est\u00e1 em branco",operationalLayerTip:"Adicionar resultado como camada operacional",queryResult:"Resultado da consulta",
specifyParamsTip:"Especificar par\u00e2metros para esta tarefa",useSpatialFilter:"Utilizar filtro espacial para limitar fei\u00e7\u00f5es",useCurrentMapExtent:"Somente as fei\u00e7\u00f5es que interseccionam a \u00e1rea de mapa atual",drawGraphicOnMap:"Somente as fei\u00e7\u00f5es que interseccionam uma \u00e1rea definida pelo usu\u00e1rio",specifySpatialFilterMsg:"Especifique o filtro espacial para esta tarefa.",clearResults:"Limpar resultados",operationalTip:'Com esta op\u00e7\u00e3o selecionada, os resultados ser\u00e3o mantidos no mapa at\u00e9 o bot\u00e3o "${clearResults}" ser clicado.',
noneQueryTip:"Nenhuma tarefa de consulta configurada para este widget.",noPermissionsMsg:"Voc\u00ea n\u00e3o tem permiss\u00f5es para acessar este servi\u00e7o.",attributesFromRelationship:"Atributos da tabela relacionada",tasks:"Tarefas",applySpatialFilterToLimitResults:"Aplicar um filtro espacial para limitar resultados",useCurrentExtentTip:"Retornar somente fei\u00e7\u00f5es dentro da extens\u00e3o de mapa atual",useDrawGraphicTip:"Somente retorna fei\u00e7\u00f5es que interseccionam com a forma desenhada no mapa",
useFeaturesTip:"Retornar somente fei\u00e7\u00f5es que t\u00eam um relacionamento espacial com fei\u00e7\u00f5es em outra camada",noSpatialLimitTip:"Retornar fei\u00e7\u00f5es dentro da extens\u00e3o total do mapa",applySearchDistance:"Aplicar uma dist\u00e2ncia de pesquisa",spatialRelationship:"Relacionamento espacial",relatedLayer:"Camada Relacionada",bufferDistance:"Dist\u00e2ncia do Buffer",miles:"Milhas",kilometers:"Quil\u00f4metros",feet:"P\u00e9s",meters:"Metros",yards:"Jardas",nauticalMiles:"Milhas n\u00e1uticas",
back:"Voltar",execute:"Executar",zoomTo:"Zoom para",openAttributeTable:"Visualizar na Tabela de Atributos",noResult:"Nenhum resultado.",noTask:"Nenhuma tarefa.",removeThisResult:"Remover este resultado",attributeCriteira:"Crit\u00e9rios de atributos",spatialFilter:"Filtro espacial",value:"VALOR",noAttributeSpatialFilterTip:"Nenhum filtro definido. Todas as fei\u00e7\u00f5es ser\u00e3o retornadas.",showAllRelatedRecords:"Mostrar todos os registros relacionados",changeSymbol:"Alterar s\u00edmbolo",
queryCriteira:"Crit\u00e9rios de consulta",customQuery:"Consulta personalizada",layer:"Camada",createCustomQuery:"Cria consulta personalizada.",rename:"Renomear",clearShapeTip:"Limpar esta forma ap\u00f3s aplicar a consulta.",displayedFeatures:"Fei\u00e7\u00f5es exibidas",loadMore:"Carregar mais",expandAll:"Expandir todos",collapseAll:"Recolher todos",_localized:{}}});