// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Upit",executeQueryTip:"Kliknite na jednu od sljede\u0107ih stavki zadatka kako biste izvr\u0161ili upit.",invalidConfig:"Nevaljana konfiguracija. Ispravite konfiguraciju s pomo\u0107u stranice za postavljanje upita.",queryParams:"Opcije",parameters:"OPCIJE",queries:"UPITI",apply:"Primijeni",queryResults:"Rezultati",clear:"O\u010disti",noResults:"Nema geoobjekta.",queryError:"Neuspje\u0161an upit!",numberFound:"Broj prona\u0111enih geoobjekata",mapExtentTip:"Ograni\u010dite rezultate na trenuta\u010dno podru\u010dje na karti.",
noValue:"Nema vrijednosti",and:"i",stringOperatorIs:"je",stringOperatorIsNot:"nije",stringOperatorStartsWith:"po\u010dinje s",stringOperatorEndsWith:"zavr\u0161ava s",stringOperatorContains:"sadr\u017ei",stringOperatorDoesNotContain:"ne sadr\u017ei",stringOperatorIsBlank:"prazno je",stringOperatorIsNotBlank:"nije prazno",dateOperatorIsOn:"je na",dateOperatorIsNotOn:"nije na",dateOperatorIsBefore:"je prije",dateOperatorIsAfter:"je poslije",dateOperatorDays:"dani",dateOperatorWeeks:"tjedni",dateOperatorMonths:"mjeseci",
dateOperatorInTheLast:"u posljednjem",dateOperatorNotInTheLast:"nije u posljednjem",dateOperatorIsBetween:"jest izme\u0111u",dateOperatorIsNotBetween:"nije izme\u0111u",dateOperatorIsBlank:"prazno je",dateOperatorIsNotBlank:"nije prazno",numberOperatorIs:"je",numberOperatorIsNot:"nije",numberOperatorIsAtLeast:"barem je",numberOperatorIsLessThan:"manje je od",numberOperatorIsAtMost:"najvi\u0161e je",numberOperatorIsGreaterThan:"ve\u0107e je od",numberOperatorIsBetween:"jest izme\u0111u",numberOperatorIsNotBetween:"nije izme\u0111u",
numberOperatorIsBlank:"prazno je",numberOperatorIsNotBlank:"nije prazno",operationalLayerTip:"Dodaj rezultat kao operativni sloj",queryResult:"Rezultat upita",specifyParamsTip:"Odredite parametre za ovaj zadatak",useSpatialFilter:"Upotrijebite prostorni filtar kako biste ograni\u010dili geoobjekte",useCurrentMapExtent:"Samo geoobjekti koji se sijeku na trenuta\u010dnom podru\u010dju na karti",drawGraphicOnMap:"Samo geoobjekti koji se sijeku na podru\u010dju koje je odredio korisnik",specifySpatialFilterMsg:"Odredite prostorni filtar za ovaj zadatak.",
clearResults:"O\u010disti rezultate",operationalTip:"Kad je ova opcija ozna\u010dena, rezultati \u0107e se prikazivati na karti dok se ne klikne gumb \u201e${clearResults}\u201d.",noneQueryTip:"Zadatak upita nije konfiguriran za ovaj widget.",noPermissionsMsg:"Nemate dopu\u0161tenje za pristup ovoj usluzi.",attributesFromRelationship:"Atributi s povezane tablice",tasks:"Zadaci",applySpatialFilterToLimitResults:"Upotrijebite prostorni filtar kako biste ograni\u010dili rezultate",useCurrentExtentTip:"Vrati geoobjekte samo unutar trenuta\u010dnog obuhvata karte",
useDrawGraphicTip:"Vrati samo one geoobjekte koji presijecaju oblik nacrtan na karti",useFeaturesTip:"Vrati samo one geoobjekte koji imaju prostorni odnos s geoobjektima u drugom sloju",noSpatialLimitTip:"Vrati geoobjekte unutar punog obuhvata karte",applySearchDistance:"Primijenite udaljenost za pretra\u017eivanje",spatialRelationship:"Prostorni odnos",relatedLayer:"Povezani sloj",bufferDistance:"Veli\u010dina pojasa",miles:"Milje",kilometers:"Kilometri",feet:"Stope",meters:"Metri",yards:"Jardi",
nauticalMiles:"Nauti\u010dke milje",back:"Natrag",execute:"Izvr\u0161i",zoomTo:"Pove\u0107aj na",openAttributeTable:"Prika\u017ei u atributnoj tablici",noResult:"Nema rezultata.",noTask:"Nema zadatka.",removeThisResult:"Ukloni ovaj rezultat",attributeCriteira:"Atributni kriterij",spatialFilter:"Prostorni filtar",value:"VRIJEDNOST",noAttributeSpatialFilterTip:"Nema definiranih filtara. Vratit \u0107e se svi geoobjekti.",showAllRelatedRecords:"Prika\u017ei sve povezane zapise",changeSymbol:"Promijeni simbol",
queryCriteira:"Kriteriji upita",customQuery:"Prilago\u0111eni upit",layer:"Sloj",createCustomQuery:"Stvorite prilago\u0111eni upit.",rename:"Preimenuj",clearShapeTip:"Izbri\u0161ite ovaj oblik nakon primjene upita.",displayedFeatures:"Prikazane zna\u010dajke",loadMore:"U\u010ditaj vi\u0161e",expandAll:"Pro\u0161iri sve",collapseAll:"Sa\u017emi sve",_localized:{}}});