// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negreta",copy:"Copia",cut:"Retalla","delete":"Suprimeix",indent:"Sagnat",insertHorizontalRule:"Regla horitzontal",insertOrderedList:"Llista numerada",insertUnorderedList:"Llista de vinyetes",italic:"Cursiva",justifyCenter:"Alineaci\u00f3 centrada",justifyFull:"Justifica",justifyLeft:"Alineaci\u00f3 a l'esquerra",justifyRight:"Alineaci\u00f3 a la dreta",outdent:"Sagnat a l'esquerra",paste:"Enganxa",redo:"Ref\u00e9s",removeFormat:"Elimina el format",selectAll:"Selecciona-ho tot",
strikethrough:"Ratllat",subscript:"Sub\u00edndex",superscript:"Super\u00edndex",underline:"Subratllat",undo:"Desf\u00e9s",unlink:"Elimina l'enlla\u00e7",createLink:"Crea un enlla\u00e7",toggleDir:"Inverteix la direcci\u00f3",insertImage:"Insereix imatge",insertTable:"Insereix/edita la taula",toggleTableBorder:"Inverteix els contorns de taula",deleteTable:"Suprimeix la taula",tableProp:"Propietat de taula",htmlToggle:"Font HTML",foreColor:"Color de primer pla",hiliteColor:"Color de fons",plainFormatBlock:"Estil de par\u00e0graf",
formatBlock:"Estil de par\u00e0graf",fontSize:"Mida del tipus de lletra",fontName:"Nom del tipus de lletra",tabIndent:"Sagnat",fullScreen:"Commuta pantalla completa",viewSource:"Visualitza font HTML",print:"Imprimeix",newPage:"P\u00e0gina nova",systemShortcut:"L'acci\u00f3 \"${0}\" \u00e9s l'\u00fanica disponible al navegador utilitzant una drecera del teclat. Utilitzeu ${1}.",ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"now","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["AH"],"field-tue-relative+-1":"last Tuesday","days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G y MMMM d",
"field-fri-relative+-1":"last Friday","field-wed-relative+-1":"last Wednesday","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"G y MMMM d, EEEE","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","field-thu-relative+-1":"last Thursday","dateFormatItem-Md":"MM-dd",
"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["Q1","Q2","Q3","Q4"],"timeFormat-long":"HH:mm:ss z","field-year":"Year","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hour",
"months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"today","field-thu-relative+0":"this Thursday","field-day-relative+1":"tomorrow","field-thu-relative+1":"next Thursday","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"this Sunday","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"next Sunday","quarters-standAlone-abbr":["Q1",
"Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Dayperiod","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"yesterday","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"this Friday",
"field-fri-relative+1":"next Friday","field-day":"Day","days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"field-zone":"Zone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"last year","field-month-relative+-1":"last month","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM",
"days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"Month","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","dateFormat-short":"GGGGG y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second","field-sat-relative+-1":"last Saturday","field-sun-relative+-1":"last Sunday","field-month-relative+0":"this month","field-month-relative+1":"next month","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d, E","field-week":"Week",
"dateFormat-medium":"G y MMM d","field-week-relative+-1":"last week","field-year-relative+0":"this year","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"next year","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"last Monday","dateFormatItem-yyyy":"G y","field-week-relative+0":"this week","field-week-relative+1":"next week",
_localized:{}},"widgets/SituationAwareness/nls/strings":{_widgetLabel:"Coneixement de la situaci\u00f3",locate_incident:"Localitza l'incident",reverse_geocoded_address:"Adre\u00e7a m\u00e9s propera",reverse_geocoded_error:"No disponible",actionLabel:"Defineix la ubicaci\u00f3",drawPoint:"Dibuixa un punt",drawLine:"Dibuixa una l\u00ednia",drawPolygon:"Dibuixar un pol\u00edgon",saveIncident:"Desa",clearIncident:"Comen\u00e7a de nou",noFeaturesFound:"No s'ha trobat cap entitat.",downloadCSV:"Baixa",
sum:"Suma",min:"M\u00ednim",max:"M\u00e0xim",avg:"Mitjana",count:"COUNT",area:"AREA",length:"LENGTH",update_btn:"Fet",delete_btn:"Suprimeix",get_directions:"Obt\u00e9n indicacions",incident:"Incident",incidents:"Incidents",buffer:"\u00c0rea d'influ\u00e8ncia",buffers:"\u00c0rees d'influ\u00e8ncia",_featureAction_ActionLabel:"Defineix la ubicaci\u00f3",_featureAction_AddRemoveActionLabel:"Afegeix o elimina una ubicaci\u00f3",snapshot:"Carpeta SnapShot que ha creat l'ID de l'aplicaci\u00f3:",user_credentials:"L'usuari no t\u00e9 permisos v\u00e0lids.",
notPolySnapShot:"Especifiqueu una dist\u00e0ncia d'\u00e0rea d'influ\u00e8ncia abans de crear una instant\u00e0nia.",notPolyReport:"No hi ha cap resultat v\u00e0lid per afegir a l'informe.",notValidDownload:"No hi ha cap resultat v\u00e0lid per baixar.",of_append:"de",layer_append:"capa",downloadAll:"Baixa-ho tot",createSnapshot:"Crea una instant\u00e0nia",createReport:"Crea un informe",calculated_results:"Informaci\u00f3 resumida",closest:"Entitat m\u00e9s propera",proximity:"Proximitat",summary:"Resum",
groupedSummary:"Recomptes agrupats",_count:"Recompte",approximate:"aproximat",snapshot_name:"Defineix les propietats de la instant\u00e0nia",report_name:"Defineix les propietats de l'informe",invalid_snapshot_name:"Nom d'instant\u00e0nia no v\u00e0lid.",invalid_report_name:"T\u00edtol d'informe no v\u00e0lid.",orientation:"Orientaci\u00f3",pageSize:"Mida de la p\u00e0gina",comments:"Comentaris",choose_group:"Grups",forecast:"Previsi\u00f3",select_group:"Seleccioneu un grup",select_group_instruction:"La instant\u00e0nia es crear\u00e0 i es compartir\u00e0 amb el grup seleccionat",
information_append:" Informaci\u00f3",distance:"DISTANCE",buffer_invalid:"Introdu\u00efu un nombre v\u00e0lid entre ${min} i ${max}",layerNotAvalible:"No s'ha trobat la capa",missingLayer:"Nom: ${name}",missingLayerHint:"Una o diverses capes a les quals es fa refer\u00e8ncia en aquesta configuraci\u00f3 no estan disponibles actualment.",_localized:{}}});