// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/PublicNotification/setting/nls/strings":{searchSourceSetting:{title:"Otsingu ja puhvri seaded",mainHint:"Saate lubada aadresside ja\u00a0objektide tekstip\u00f5hist otsingut, geomeetria digitaliseerimist ja puhverdamist."},addressSourceSetting:{title:"Aadressi kihid",mainHint:"Saate m\u00e4\u00e4rata, millised adressaadi sildi kihid on saadaval."},notificationSetting:{title:"Teavitamise valikud",mainHint:"Saate m\u00e4\u00e4rata, millist t\u00fc\u00fcpi teavitused on saadaval."},
groupingLabels:{addressSources:"Kiht, mida kasutatakse adressaadi kihtide valimisel",averyStickersDetails:"Avery(r) kleepsud",csvDetails:"Komaga eraldatud v\u00e4\u00e4rtuste (CSV) fail",drawingTools:"Joonistust\u00f6\u00f6riistad ala m\u00e4\u00e4ramiseks",featureLayerDetails:"Objektikiht",geocoderDetails:"Geokodeerija",labelFormats:"Saadaolevad kihivormingud",printingOptions:"Prinditud sildi lehtede vlaikud",searchSources:"Otsinguallikad",stickerFormatDetails:"Sildi lehe parameetrid"},hints:{alignmentAids:"Sildi lehele lisatud t\u00e4hised, mis on abiks lehe printeris joondamisel",
csvNameList:"T\u00f5stutundlike v\u00e4ljanimede komaga eraldatud loend",horizontalGap:"Ruum reas oleva kahe\u00a0m\u00e4rgise vahel",insetToLabel:"Ruum\u00a0m\u00e4rgise ja teksti alguse vahel",labelFormatDescription:"Kuidas kujutatakse\u00a0m\u00e4rgise laadi vidina vormingu valikute loendis",labelFormatDescriptionHint:"Kohtspikker t\u00e4iendava kirjelduse jaoks vormingu valikute loendis",labelHeight:"Iga lehel oleva m\u00e4rgise k\u00f5rgus",labelWidth:"Iga lehel oleva\u00a0m\u00e4rgise laius",
localSearchRadius:"M\u00e4\u00e4rab praeguse kaardi keskpunkti \u00fcmber asuva ala raadiuse, mida kasutatakse geokodeerimise kandidaatide j\u00e4rjestuse v\u00f5imendamiseks nii, et asukohale l\u00e4himad kandidaadid tagastatakse esimesena",rasterResolution:"100 pikslit tolli kohta vastab ligikaudu ekraani eraldusv\u00f5imele. Mida suurem on eraldusv\u00f5ime, seda rohkem brauseri m\u00e4lu vajatakse. Brauserite v\u00f5imekus suurte m\u00e4lun\u00f5udlustega sujuvalt toime tulla on erinev.",selectionListOfOptionsToDisplay:"Kontrollitud elemendid kuvatakse vidina valikutena; j\u00e4rjestust saab vastavalt soovile muuta",
verticalGap:"Ruum veeru kahe\u00a0m\u00e4rgise vahel"},propertyLabels:{bufferDefaultDistance:"Puhvri vaikeulatus",bufferUnits:"Vidina puhvri \u00fchikud",countryRegionCodes:"Riigi v\u00f5i piirkonna koodid",description:"Kirjeldus",descriptionHint:"Kirjelduse vihje",displayField:"Kuvamise v\u00e4li",drawingToolsFreehandPolygon:"vabak\u00e4eline pol\u00fcgoon",drawingToolsLine:"joon",drawingToolsPoint:"punkt",drawingToolsPolygon:"pol\u00fcgoon",drawingToolsPolyline:"murdjoon",enableLocalSearch:"Luba kohalik otsing",
exactMatch:"T\u00e4pne vaste",fontSizeAlignmentNote:"Prindiveeriste m\u00e4rkuse fondi suurus",gridDarkness:"Ruudustiku tumedus",gridlineLeftInset:"Ruudujoonte vasak ird",gridlineMajorTickMarksGap:"Suurem kriips m\u00e4rgib igat",gridlineMinorTickMarksGap:"V\u00e4iksem kriips m\u00e4rgib igat",gridlineRightInset:"Ruudujoonte parem ird",labelBorderDarkness:"M\u00e4rgise\u00a0\u00e4\u00e4rise tumedus",labelBottomEdge:"Lehel olevate\u00a0m\u00e4rgiste alumine serv",labelFontSize:"Fondi suurus",labelHeight:"M\u00e4rgise\u00a0k\u00f5rgus",
labelHorizontalGap:"Horisontaalne vahe",labelInitialInset:"M\u00e4rgise\u00a0teksti ird",labelLeftEdge:"Lehel olevate\u00a0m\u00e4rgiste vasak serv",labelMaxLineCount:"M\u00e4rgise\u00a0maksimaalne ridade arv",labelPageHeight:"Lehe k\u00f5rgus",labelPageWidth:"Lehe laius",labelRightEdge:"Lehel olevate\u00a0m\u00e4rgiste parem serv",labelsInAColumn:"M\u00e4rgiste\u00a0arv veerus",labelsInARow:"M\u00e4rgiste\u00a0arv real",labelTopEdge:"Lehel olevate\u00a0m\u00e4rgiste \u00fclemine serv",labelVerticalGap:"Vertikaalne vahe",
labelWidth:"M\u00e4rgise\u00a0laius",limitSearchToMapExtent:"Otsi ainult praegusest kaardiulatusest",maximumResults:"Maksimaalsed tulemused",maximumSuggestions:"Maksimaalsed soovitused",minimumScale:"Minimaalne m\u00f5\u00f5tkava",name:"Nimi",percentBlack:"% must",pixels:"pikslid",pixelsPerInch:"pikslit tolli kohta",placeholderText:"Kohat\u00e4itja tekst",placeholderTextForAllSources:"Kohat\u00e4ite tekst k\u00f5igi allikate otsimiseks",radius:"Raadius",rasterResolution:"Rastri resolutsioon",searchFields:"Otsinguv\u00e4ljad",
showAlignmentAids:"Kuva lehel joondamise abivahendid",showGridTickMarks:"Kuva ruudustiku kriipsm\u00e4rgised",showLabelOutlines:"Kuva\u00a0m\u00e4rgise kontuurid",showPopupForFoundItem:"Kuva leitud objekti v\u00f5i asukoha h\u00fcpikaken",tool:"T\u00f6\u00f6vahendid",units:"\u00dchikud",url:"URL",urlToGeometryService:"Geomeetriateenuse URL",useRelatedRecords:"Kasuta selle seostatud kirjeid",useSecondarySearchLayer:"Kasuta sekundaarset valikukihti",useSelectionDrawTools:"Kasutage selekteerimise joonistusvahendeid",
useVectorFonts:"Kasuta vektorfonte (ainult ladina fondid)",zoomScale:"Suumiskaala"},buttons:{addAddressSource:"Lisa selle h\u00fcpikaknasse aadressisilte sisaldav kiht",addLabelFormat:"Lisa sildi vorming",addSearchSource:"Lisa otsinguallikas",set:"M\u00e4\u00e4ra"},placeholders:{averyExample:"nt Avery(r) silt ${averyPartNumber}",countryRegionCodes:"nt USA,CHN",descriptionCSV:"Komaga eraldatud v\u00e4\u00e4rtused",descriptionPDF:"PDF m\u00e4rgis\u00a0${heightLabelIn} x ${widthLabelIn} tolli; ${labelsPerPage} lehe kohta"},
tooltips:{getWebmapFeatureLayer:"Hangi veebikaardilt objektikiht",openCountryCodes:"Kl\u00f5psake lisateabe saamiseks koodide kohta",openFieldSelector:"Kl\u00f5psake v\u00e4lja valija avamiseks",setAndValidateURL:"M\u00e4\u00e4ra ja valideeri URL"},problems:{noAddresseeLayers:"M\u00e4\u00e4rake v\u00e4hemalt \u00fcks adressaadi kiht",noBufferUnitsForDrawingTools:"Konfigureerige joonistusriistade jaoks v\u00e4hemalt \u00fcks puhvri\u00fchik",noBufferUnitsForSearchSource:"Konfigureerige otsinguallika \u201e${sourceName}\u201c jaoks v\u00e4hemalt \u00fcks puhvri\u00fchik",
noGeometryServiceURL:"Konfigureerige geomeetriateenuse URL",noNotificationLabelFormats:"M\u00e4\u00e4rake v\u00e4hemalt \u00fcks teavitussildi vorming",noSearchSourceFields:"Konfigureerige otsinguallika \u201e${sourceName}\u201c jaoks v\u00e4hemalt \u00fcks otsinguv\u00e4li",noSearchSourceURL:"Konfigureerige otsinguallika \u201e${sourceName}\u201c URL"},querySourceSetting:{sourceSetting:"Otsinguallika seaded",instruction:"Lisa ja konfigureeri geokooditeenused v\u00f5i objektikihid otsinguallikatena. Need etten\u00e4htud allikad m\u00e4\u00e4ravad, mida saab otsingukastis otsida.",
add:"Lisa otsinguallikas",addGeocoder:"Lisa geokodeerija",geocoder:"Geokodeerija",setLayerSource:"M\u00e4\u00e4ra kihi allikas",setGeocoderURL:"M\u00e4\u00e4ra geokodeerija URL",searchableLayer:"Objektikiht",name:"Nimi",countryCode:"Riigi v\u00f5i piirkonna kood(id)",countryCodeEg:"nt ",countryCodeHint:"Kui j\u00e4tate selle v\u00e4lja t\u00fchjaks, teostatakse otsing k\u00f5ikides riikides ja piirkondades",generalSetting:"\u00dcldseaded",allPlaceholder:"Kohat\u00e4ite tekst k\u00f5igi otsimiseks: ",
showInfoWindowOnSelect:"Kuva leitud objekti v\u00f5i asukoha h\u00fcpikaken",showInfoWindowOnSelect2:"Kuva objekti v\u00f5i asukoha leidmisel h\u00fcpikaken.",searchInCurrentMapExtent:"Otsi ainult praegusest kaardiulatusest",zoomScale:"Suumiskaala",locatorUrl:"Geokodeerija URL",locatorName:"Geokodeerija nimi",locatorExample:"N\u00e4ide",locatorWarning:"Seda geokodeerimisteenust ei toetata. Vidin toetab geokodeerimisteenust ArcGIS 10.1 ja sellest uuemate versioonide puhul.",locatorTips:"Soovitused pole saadaval, sest geokodeerimisteenus ei toeta soovituste v\u00f5imalust.",
layerSource:"Kihi allikas",searchLayerTips:"Soovitused pole saadaval, sest objektiteenus ei toeta lehek\u00fcljelise jaotuse v\u00f5imalust.",placeholder:"Kohat\u00e4itja tekst",searchFields:"Otsinguv\u00e4ljad",displayField:"Kuvamise v\u00e4li",exactMatch:"T\u00e4pne vaste",maxSuggestions:"Maksimaalsed soovitused",maxResults:"Maksimaalsed tulemused",enableLocalSearch:"Luba kohalik otsing",minScale:"Min m\u00f5\u00f5tkava",minScaleHint:"Kui kaardi m\u00f5\u00f5kava on sellest m\u00f5\u00f5tkavast suurem, rakendatakse kohalik otsing",
radius:"Raadius",radiusHint:"M\u00e4\u00e4rab praeguse kaardi keskpunkti \u00fcmber asuva ala raadiuse, mida kasutatakse geokodeerimise kandidaatide j\u00e4rjestuse v\u00f5imendamiseks, nii et asukohale l\u00e4himad kandidaadid tagastatakse esimesena",meters:"m",setSearchFields:"M\u00e4\u00e4ra otsinguv\u00e4ljad",set:"M\u00e4\u00e4ra",fieldSearchable:"otsitav",fieldName:"Nimi",fieldAlias:"Alias",ok:"OK",cancel:"Loobu",invalidUrlTip:"URL ${URL} ei sobi v\u00f5i pole k\u00e4ttesaadav.",locateResults:"Otsi tulemused \u00fcles",
panTo:"Liiguta",zoomToScale:"Suumi m\u00f5\u00f5tkavale",locatorError:"Lokaator peab toetama \u00fche joonega asukoha m\u00e4\u00e4ramist."},_localized:{}}});