// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/SituationAwareness/setting/nls/strings":{tabs_section_Label:"Pestanyes",addTab:"Afegeix una pestanya",layerName:"Capa",layerType:"Tipus d'an\u00e0lisi",layerLabel:"Etiqueta",actions:"Accions",closest:"Entitat m\u00e9s propera",proximity:"Proximitat",summary:"Resum",select_lbl:"-- Seleccioneu --",general_setting_Label:"Configuraci\u00f3 general",units_text_lbl:"Unitats de dist\u00e0ncia",maximum_distance_lbl:"Dist\u00e0ncia m\u00e0xima a l'entitat m\u00e9s propera",buffer_text_lbl:"Etiqueta d'\u00e0rea d'influ\u00e8ncia",
buffer_lbl:"Dist\u00e0ncia d'\u00e0rea d'influ\u00e8ncia",buffer_max_lbl:"Dist\u00e0ncia de l'\u00e0rea d'influ\u00e8ncia m\u00e0xima",buffer_min_lbl:"Dist\u00e0ncia de l'\u00e0rea d'influ\u00e8ncia m\u00ednima",buffer_default_lbl:"Dist\u00e0ncia d'\u00e0rea d'influ\u00e8ncia per defecte",not_less_than_max:"La dist\u00e0ncia ha de ser inferior a la dist\u00e0ncia d'\u00e0rea d'influ\u00e8ncia m\u00e0xima",not_between:"La dist\u00e0ncia ha d'estar entre les dist\u00e0ncies d'\u00e0rea d'influ\u00e8ncia m\u00ednima i m\u00e0xima",
not_more_than_min:"La dist\u00e0ncia ha de ser m\u00e9s gran que la dist\u00e0ncia d'\u00e0rea d'influ\u00e8ncia m\u00ednima",not_valid_number:"Ha de ser un nombre v\u00e0lid",invalid_value:"El valor de ${type} no \u00e9s v\u00e0lid",routing_checkBox:"Habilita l'encaminament",weather_removed_message:"Les opcions del temps meteorol\u00f2gic ja no estan disponibles per a aquest widget.",currentlySelectedLayer:"Seleccioneu en capes de mapes",missingTabLabel:"Falta l'etiqueta en una pestanya com a m\u00ednim",
missingLayerInWebMap:"No s'ha trobat cap capa operativa.",selectFields:"Seleccioneu els camps",addField:"Afegeix un camp",sum:"Suma",min:"M\u00ednim",max:"M\u00e0xim",avg:"Mitjana",count:"COUNT",area:"AREA",length:"LENGTH",count_checkBox:"Mostra el recompte d'entitats",area_checkBox:"Mostra la suma de l'\u00e0rea",length_checkBox:"Mostra la suma de la longitud",max_records:"S'ha arribat al l\u00edmit m\u00e0xim",save_label:"Opcions de desament",save_checkbox:"Habilita el desament",report_label:"Opcions d'informe",
report_checkbox:"Habilita l'informe",csv_label:"Opcions de CSV",csv_checkbox:"Exporta tots els camps",display_label:"Opcions de visualitzaci\u00f3",display_checkbox:"Mostra les entitats de resum",snapshot_label:"Opcions d'instant\u00e0nia",snapshot_checkbox:"Habilita la instant\u00e0nia",must_select_template:"Seleccioneu una de les plantilles d'edici\u00f3 a Opcions de desament.",count_label:"Etiqueta de recompte",area_label:"Etiqueta d'\u00e0rea",length_label:"Etiqueta de longitud",invalid_string_width:"El valor \u00e9s massa llarg. ",
layer_type_not_supported:"Tipus de capa no compatible",groupedSummary:"Recomptes agrupats",groupByField:"Agrupa per camp",labelType:"Afegeix l'etiqueta",prefix:"Com a prefix",suffix:"Com a sufix",need_group_field:"Utilitzeu l'acci\u00f3 Edita per definir Agrupa per camp.",fieldTitle:"Camp",typeTitle:"Tipus",actionsTitle:"Accions",save_point_checkbox:"Desa els punts",save_line_checkbox:"Desa les l\u00ednies",save_poly_checkbox:"Desa els pol\u00edgons",no_valid_popup_fields:"No hi ha cap camp v\u00e0lid a la finestra emergent. Utilitzeu l'acci\u00f3 Edita per definir un camp.",
no_valid_fields:"No hi ha cap camp v\u00e0lid. Utilitzeu l'acci\u00f3 Edita per definir les opcions de visualitzaci\u00f3.",incident_label:"Etiqueta de pestanya",locate_incident_label:"Etiqueta de l'\u00e0rea d'inter\u00e8s",incident:"Incident",locate_incident:"Localitza l'incident",buffer_value:"Dist\u00e0ncia d'\u00e0rea d'influ\u00e8ncia",tab_options:"An\u00e0lisi",export_options:"Sortida",instruction_save:"Deseu la ubicaci\u00f3 en un servei d'entitats.",instruction_snapshot:"Creeu un mapa web basat en la ubicaci\u00f3.",
instruction_report:"Creeu un informe impr\u00e8s de la ubicaci\u00f3.",instruction_all_fields:"Exporteu tots els camps amb una baixada de CSV.",data_label:"Configuraci\u00f3 de sortida de dades",layer_error:"La capa falta o no \u00e9s v\u00e0lida.",visibility_checkBox:"Deshabilita l'administraci\u00f3 de la visibilitat de les capes",downloadTab:{reportLegend:"Configuraci\u00f3 d'informe",textColorLabel:"Seleccioneu el color per a la cap\u00e7alera de columna",setButtonLabel:"Defineix",printGPServiceLabel:"URL del servei d'impressi\u00f3",
logoLabel:"Logotip",logoChooserHint:"Feu clic a la icona de la imatge per canviar la imatge",footnoteLabel:"Nota a peu de p\u00e0gina"},roundValue:"Arrodoneix a",roundValueTitle:"Arrodoneix els valors de camp",truncateValue:"Truca a",truncateValueTitle:"Trunca els valors de camp",significantFigures:"xifres significatives",fieldOptions:"Opcions de camp",modifyValues:"Modifica els valors de camp",validatePlaces:"Ha de ser un enter",onlyDouble:"Les opcions de camps addicionals nom\u00e9s s'admeten per a camps num\u00e8rics.",
layerNotAvalible:"No s'ha trobat la capa",missingLayer:"Nom: ${name}",missingLayerHint:"Una o diverses capes a les quals es fa refer\u00e8ncia en aquesta configuraci\u00f3 no estan disponibles actualment.",drawGeodesic:"Dibuixa formes geod\u00e8siques",_localized:{}}});