// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ParcelDrafter/setting/nls/strings":{setBtnLabel:"D\u00e9finir",selectLabel:"S\u00e9lectionner",selectLayerLabel:"S\u00e9lectionner des couches de parcelles",selectLayerHintText:"Astuce\u00a0: utilisez le bouton D\u00e9finir pour s\u00e9lectionner le polygone de parcelle et sa couche de lignes associ\u00e9e",layerSelector:{selectedLayerNotHavingRelatedLayer:"La couche de polygones s\u00e9lectionn\u00e9e n'est pourvue d'aucune couche associ\u00e9e valide."},parcelLineLayer:{selectLayerLabel:"S\u00e9lectionner une couche de lignes associ\u00e9e",
layerSettingTabLabel:"Couches de parcelles",advancedSettingTabLabel:"Param\u00e8tres avanc\u00e9s",selectLayerHintText:"Astuce\u00a0: \u00e0 utiliser pour stocker les valeurs COGO dans la couche de lignes de parcelle",selectFieldLegendLabel:"S\u00e9lectionner des champs pour stocker les valeurs COGO dans la couche de lignes de parcelle",bearingFieldLabel:"Orientation",chordLengthFieldLabel:"Longueur de la corde",distanceFieldLabel:"Distance",sequenceIdFieldLabel:"ID de s\u00e9quence",radiusFieldLabel:"Rayon",
foreignKeyFieldLabel:"Cl\u00e9 \u00e9trang\u00e8re",arcLengthFieldLabel:"Longueur de l\u2019arc",lineTypeFieldLabel:"Type de ligne",parcelPointSymbolLabel:"Symbole de point parcelle",parcelPointSymbolHintText:"Astuce\u00a0: utilis\u00e9 pour afficher le symbole de point correspondant \u00e0 l'origine de la ligne.",startOrRotationSymbolLabel:"Symbole de point de d\u00e9but et de rotation",startOrRotationSymbolHintText:"Astuce : utilis\u00e9 pour afficher le symbole de point de d\u00e9but et de rotation.",
symbolPickerPreviewText:"Aper\u00e7u",selectLineLayerLabel:"S\u00e9lectionner une couche de lignes"},parcelPolygonLayer:{selectPolygonLayerLabel:"S\u00e9lectionner la couche de polygones",selectPolygonLayerHintText:"Astuce\u00a0: utilisez la couche de polygones de parcelle s\u00e9lectionn\u00e9e",selectFieldLegendLabel:"S\u00e9lectionner des champs pour stocker les attributs de polygones de parcelle",parcelNameLabel:"Nom de parcelle",rotationLabel:"Rotation",planNameLabel:"Nom de plan",scalingLabel:"Mise \u00e0 l\u2019\u00e9chelle",
documentTypeLabel:"Type de document",miscloseRatioLabel:"Taux d'\u00e9cart de fermeture",statedAreaLabel:"Zone indiqu\u00e9e",miscloseDistanceLabel:"Distance d'\u00e9cart de fermeture",selectPolygonLayerLabelPopUp:"S\u00e9lectionner une couche de polygones"},lineTypesTable:{lineTypeLabel:"Type de ligne",valueLabel:"Valeur",symbolLabel:"Symbole",connectionLineLabel:"Ligne de connexion",boundaryLineLabel:"Ligne de limite"},closureSetting:{snappingLayerLabel:"Capture de couches",snappingBtnLabel:"D\u00e9finir",
snappingLayerHintText:"Astuce\u00a0: s\u00e9lectionnez les couches pour lesquelles les lignes de parcelle seront captur\u00e9es.",miscloseDistanceLabel:"Distance d'\u00e9cart de fermeture",miscloseDistanceHintText:"Astuce\u00a0: sp\u00e9cifiez la distance d'\u00e9cart de fermeture et ses unit\u00e9s.",miscloseRatioLabel:"Taux d'\u00e9cart de fermeture",miscloseRatioHintText:"Astuce\u00a0: sp\u00e9cifiez un taux d'\u00e9cart de fermeture.",snappingToleranceLabel:"Tol\u00e9rance de capture",pixelLabel:"Pixels",
snappingToleranceHintText:"Astuce\u00a0: sp\u00e9cifiez une tol\u00e9rance de capture.",selectLayerLabel:"S\u00e9lectionner une couche"},errorMsg:{bearingFieldErrMsg:"Champ de rel\u00e8vement non valide",chordLengthErrMsg:"ChordLength non valide",distanceFieldErrMsg:"Distance non valide",sequenceIdFieldErrMsg:"SequenceId non valide",radiusFieldErrMsg:"Rayon non valide",foreignKeyFieldErrMsg:"Cl\u00e9 \u00e9trang\u00e8re non valide",arcLengthFieldErrMsg:"Longueur d'arc non valide",lineTypeFieldErrMsg:"Type de ligne non valide",
parcelNameFieldErrMsg:"Champ Nom de parcelle non valide",planNameFieldErrMsg:"Champ Nom de plan non valide",scaleFieldErrMsg:"Champ Echelle non valide",documentTypeFieldErrMsg:"Champ Type de document non valide",miscloseRatioFieldErrMsg:"Champ Taux d'\u00e9cart de fermeture non valide",statedAreaFieldErrMsg:"Champ Zone indiqu\u00e9e non valide",miscloseDistanceFieldErrMsg:"Champ Distance d'\u00e9cart de fermeture non valide",globalIdFieldErrMsg:'La couche de polygones s\u00e9lectionn\u00e9e ne poss\u00e8de pas de champ "esriFieldTypeGlobalID" valide.',
invalidPolylineLayer:"S\u00e9lectionnez une couche de polylignes de parcelle valide",invalidPolygonLayer:"S\u00e9lectionnez une couche de polygones de parcelle valide",invalidMiscloseDistance:"Entrez une distance d'\u00e9cart de fermeture valide",invalidSnappingTolerance:"Entrez une tol\u00e9rance de capture valide",invalidMiscloseRatio:"Entrez un taux d'\u00e9cart de fermeture valide",selectDistinctLineTypes:"S\u00e9lectionnez une valeur distincte dans chaque type de ligne",invalidConnectionLineType:"Valeur de ligne de connexion non valide",
invalidBoundaryLineType:"Valeur de ligne de limite non valide",selectDistinctPolylineFields:"S\u00e9lectionnez un champ distinct pour chaque valeur COGO.",selectDistinctPolygonFields:"S\u00e9lectionnez un champ distinct pour chaque attribut de polygone de parcelle."},_localized:{}}});