// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Directions/setting/nls/strings":{searchTabTitle:"Ajuste de origen de b\u00fasqueda",routeTabTitle:"Ajuste de ruta",add:"Agregar origen de b\u00fasqueda",addGeocoder:"Agregar geocodificador",geocoder:"Geocodificador",setLayerSource:"Definir origen de capa",setGeocoderURL:"Definir direcci\u00f3n URL de geocodificador",searchableLayer:"Capa de entidades",name:"Nombre",countryCode:"C\u00f3digo(s) de pa\u00eds o regi\u00f3n",countryCodeEg:"p. ej., ",countryCodeHint:"Si se deja este valor en blanco, se buscar\u00e1 en todos los pa\u00edses y regiones",
showInfoWindowOnSelect:"Mostrar ventana emergente de la entidad o la ubicaci\u00f3n encontrada",showInfoWindowOnSelect2:"Mostrar ventana emergente cuando se encuentre la entidad o ubicaci\u00f3n.",searchInCurrentMapExtent:"Buscar solo en la extensi\u00f3n de mapa actual",setSearchFields:"Definir campos de b\u00fasqueda",set:"Establecer",fieldSearchable:"permite b\u00fasqueda",zoomScale:"Escala de zoom",locatorUrl:"Direcci\u00f3n URL del geocodificador",locatorName:"Nombre del geocodificador",locatorExample:"Ejemplo",
locatorWarning:"Esta versi\u00f3n del servicio de geocodificaci\u00f3n no es compatible. Este widget admite el servicio de geocodificaci\u00f3n 10.1 y versiones posteriores.",locatorTips:"No hay sugerencias disponibles porque el servicio de geocodificaci\u00f3n no admite la opci\u00f3n de sugerencias.",layerSource:"Origen de capa",searchLayerTips:"No hay sugerencias disponibles porque el servicio de entidades no admite la opci\u00f3n de paginaci\u00f3n.",placeholderText:"Texto del marcador de posici\u00f3n",
searchFields:"Campos de b\u00fasqueda",displayField:"Mostrar campo",exactMatch:"Coincidencia exacta",maxSuggestions:"M\u00e1ximo de sugerencias",maxResults:"Resultados m\u00e1ximos",enableLocalSearch:"Habilitar b\u00fasqueda local",minScale:"Escala m\u00ednima",minScaleHint:"Si la escala del mapa es mayor que esta escala, se aplicar\u00e1 la b\u00fasqueda local",radius:"Radio",radiusHint:"Permite especificar el radio de un \u00e1rea alrededor del centro del mapa actual que se utilizar\u00e1 para mejorar la clasificaci\u00f3n de los candidatos de geocodificaci\u00f3n a fin de que se devuelvan primero aquellos m\u00e1s cercanos a la ubicaci\u00f3n",
invalidUrlTip:"No se puede acceder a la direcci\u00f3n URL ${URL} o bien no es v\u00e1lida.",routeUrl:"URL de ruta",geocoderOptions:"Opciones de geocodificador",autoComplete:"Autocompletar",maximumSuggestions:"M\u00e1ximo de sugerencias",minCharacters:"Caracteres m\u00ednimos",searchDelay:"Retardo de b\u00fasqueda",placeholder:"Marcador de posici\u00f3n",routeOptions:"Opciones de ruta",directionsLanguage:"Idioma de las indicaciones",directionsLengthUnits:"Unidades de longitud de las indicaciones",
directionsOutputType:"Tipo de salida de las indicaciones",impedanceAttribute:"Atributo de impedancia",kilometers:"Kil\u00f3metros",miles:"Millas",meters:"Metros",feet:"Pies",yards:"Yardas",nauticalMiles:"Millas n\u00e1uticas",parametersTip:"Establece los par\u00e1metros correctamente",complete:"Completar",completeNoEvents:"Completar sin eventos",instructionsOnly:"Solo instrucciones",standard:"Est\u00e1ndar",summaryOnly:"Solo resumen",travelModesUrl:"Direcci\u00f3n URL de modos de viaje",searchPlaceholder:"Buscar direcci\u00f3n o lugar",
trafficLayerUrl:"Direcci\u00f3n URL de capa de tr\u00e1fico",barrierLayerUrl:"Direcci\u00f3n URL de capa de barrera",presetDestinations:"Paradas predefinidas",startPoint:"Punto de inicio",endPoint:"Punto final",destinationHolder:"Direcci\u00f3n o coordenadas",optional:"Opcional.",barrierLayers:"Capas de barrera",pointBarrier:"Barreras de punto",lineBarrier:"Barreras de l\u00ednea",polygonBarrier:"Barreras de pol\u00edgono",noPointBarrier:"Seleccionar barreras de punto",noLineBarrier:"Seleccionar barreras de l\u00ednea",
noPolygonBarrier:"Seleccionar barreras de pol\u00edgono",_localized:{}}});