// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Infographic/setting/dijitsSetting/_dijits/NumberIndicator/MultipleIndicators.html":'\x3cdiv\x3e\r\n    \x3cdiv class\x3d"indicator-add-div top" data-dojo-attach-point\x3d"addIndicator"\x3e\r\n\t\t\x3cdiv data-dojo-attach-point\x3d"topIcon" class\x3d"icon-add-indicator"\x3e\x3c/div\x3e\r\n\t\t\x3cdiv  data-dojo-attach-point\x3d"topBlock" class\x3d"top-mid-block"\x3e\x3c/div\x3e\r\n\t\t\x3cdiv data-dojo-attach-point\x3d"topText" class\x3d"text-add-indicator" title\x3d"${nls.addIndicatorTip}" \x3e${nls.addIndicatorTip}\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"indicatorDiv" data-dojo-attach-point\x3d"indicatorDiv"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dijit/_WidgetBase dojo/Evented dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./MultipleIndicators.html dojo/on dojo/query dojo/mouse dojo/_base/html dojo/_base/lang ./SingleIndicator dijit/form/Select jimu/dijit/CheckBox".split(" "),function(k,l,m,n,p,q,d,r,h,b,c,t){var f=h.enter,g=h.leave,u=window.Sortable;return k([l,m,n,p],{baseClass:"infographic-setting-multiple-indicators",templateString:q,nls:null,constructor:function(){this.inherited(arguments);this.indicators=
[]},postCreate:function(){this.inherited(arguments);this._initEvent();this.setConfig(this.config)},startup:function(){this.inherited(arguments);this.sortableIndicatorNode=u.create(this.indicatorDiv,{handle:".drag-masker",filter:".disable-drag .unvaild",sort:!0,disabled:!1,animation:100,onSort:c.hitch(this,function(){this._onSorted()})});this.setConfig(this.config)},_initEvent:function(){this.own(d(this.topIcon,"click",c.hitch(this,this._onAddIndicatorClicked)));this.own(d(this.topBlock,"click",c.hitch(this,
this._onAddIndicatorClicked)));this.own(d(this.topText,"click",c.hitch(this,this._onAddIndicatorClicked)));this._handleAddIdicatorHoverColor()},_handleAddIdicatorHoverColor:function(){this.own(d(this.topIcon,f,c.hitch(this,function(){b.addClass(this.topIcon,"active");b.addClass(this.topText,"active")})));this.own(d(this.topBlock,f,c.hitch(this,function(){b.addClass(this.topIcon,"active");b.addClass(this.topText,"active")})));this.own(d(this.topText,f,c.hitch(this,function(){b.addClass(this.topIcon,
"active");b.addClass(this.topText,"active")})));this.own(d(this.topIcon,g,c.hitch(this,function(){b.removeClass(this.topIcon,"active");b.removeClass(this.topText,"active")})));this.own(d(this.topBlock,g,c.hitch(this,function(){b.removeClass(this.topIcon,"active");b.removeClass(this.topText,"active")})));this.own(d(this.topText,g,c.hitch(this,function(){b.removeClass(this.topIcon,"active");b.removeClass(this.topText,"active")})))},setConfig:function(a){(this.config=a)&&this._setIndicators()},_getIndicatorIDs:function(){return r(".infographic-setting-single-indicator",
this.indicatorDiv).map(function(a){return b.getAttr(a,"data-id")})},getConfig:function(a){var b=[];this.indicators.forEach(c.hitch(this,function(a){a&&(a=a.getConfig())&&b.push(a)}));return a&&this.indicators.length!==b.length?!1:b},_setIndicators:function(){var a=this.config.indicators;this.clear();a&&a.forEach(c.hitch(this,function(a){this._createIndicator(a)}));this._updateIndicatorBottomLineDisplay()},_reSortIndicatorArray:function(){var a=[];this._getIndicatorIDs().forEach(function(b){this.indicators.some(function(c){return c.uniqueID===
b?(a.push(c),!0):!1})}.bind(this));this.indicators=null;this.indicators=a},_onSorted:function(){this._reSortIndicatorArray();this._updateIndicatorBottomLineDisplay();this._onUpdate()},_onUpdate:function(){this.emit("change")},_updateIndicatorBottomLineDisplay:function(){if(this.indicators&&this.indicators.length){var a=this.indicators.length-1;this.indicators.forEach(c.hitch(this,function(b,c){b&&b.updateBottomLineDisplay(c,a)}))}},_onAddIndicatorClicked:function(a){a.stopPropagation();this._createIndicator()},
_createIndicator:function(a){var b={type:this.type,nls:this.nls,folderUrl:this.folderUrl};a&&(b.config=a);var e=new t(b);e.placeAt(this.indicatorDiv);e.startup();this.own(d(e,"remove",c.hitch(this,function(a){this.indicators=this.indicators.filter(function(b){return b.uniqueID!==a});e.destroy();e=null;this._updateIndicatorBottomLineDisplay()})));this.own(d(e,"change",c.hitch(this,function(){this._onUpdate()})));this.indicators.push(e);this._updateIndicatorBottomLineDisplay()},clear:function(){this.indicators&&
(this.indicators.forEach(c.hitch(this,function(a){a&&(a.destroy(),a=null)})),this.indicators=[])},destroy:function(){this.clear();this.inherited(arguments)}})});