// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/DistanceAndDirection/nls/strings":{_widgetLabel:"Distanza e direzione",tabLineTitle:"Linea",tabCircleTitle:"Cerchio",tabEllipseTitle:"Ellisse",tabRingsTitle:"Anelli",multipleNotationsMessage:" Notazioni corrispondenti all'input. Confermare quale si desidera utilizzare:",invalidCoordinateMessage:"Coordinate non valide",confirmInputNotationMessage:"Confermare l'input annotato.",prefixSuffixMessage:"La coordinata di input \u00e8 stata rilevata come composta da prefisso e suffisso per il valore di latitudine o di longitudine, ma la coordinata restituita \u00e8 contiene solo il prefisso.",
rememberDecisionMessage:"Ricorda l'impostazione e non chiudere pi\u00f9.\x3cbr/\x3e",majorAxisTooltipMessage:"Fare clic sulla lunghezza dell\u2019asse maggiore",minorAxisTooltipMessage:"Spostare il mouse indietro nella posizione iniziale per impostare l'asse minore e terminare l'ellisse del disegno",clickToFinishLineMessage:"Fare clic per completare il disegno della linea",doubleClickEllipseMesage:"Fare doppio clic per completare il disegno degli anelli di intervallo",invalidCoordinateTypeMessage:"Impossibile determinare il tipo di coordinate di input. Controllare l'input.",
noCenterPointSetMessage:"Nessun punto centrale impostato. Controllare l'input.",ellipseMajorAxis:"Asse maggiore",ellipseMinorAxis:"Asse minore",degreesRangeMessage:"Il valore deve essere compreso tra 0 e 360",millsRangeMessage:"Il valore deve essere compreso tra 0 e 6400",lengthLabel:"Lunghezza",angleLabel:"Angolo",startPointLabel:"Punto di partenza",endPointLabel:"Punto finale",centerPointLabel:"Punto centrale",distanceTableErrorMessage:"La tabella delle distanze \u00e8 vuota. Assicurarsi di inserire qualche distanza.",
setCoordFormatStringMessage:"Imposta stringa di formato coordinata",prefixMessage:"Aggiungere il prefisso '+/-' ai numeri positivi e negativi",ddLabel:"DD",ddmLabel:"DDM",dmsLabel:"DMS",garsLabel:"GARS",georefLabel:"GEOREF",mgrsLabel:"MGRS",usngLabel:"USNG",utmLabel:"UTM",utmhLabel:"UTM (H)",DDLatLongNotation:"Gradi decimali - Latitudine/Longitudine",DDLongLatNotation:"Gradi decimali - Longitudine/Latitudine",DDMLatLongNotation:"(DDM) Degrees Decimal Minutes - Latitude/Longitude",DDMLongLatNotation:"(DDM) Degrees Decimal Minutes - Longitude/Latitude",
DMSLatLongNotation:"(DDS) Degrees Minutes Seconds - Latitude/Longitude",DMSLongLatNotation:"(DDS) Degrees Minutes Seconds - Longitude/Latitude",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - Band Letter",UTMHemNotation:"UTM - Hemisphere (N/S)",circleTitle:"Crea cerchio da",radiusLabel:"Raggio",diameterLabel:"Diametro",startPointPlaceHolderLabel:"Immettere le coordinate",formatInputLabel:"Input formato",drawCircleLabel:"Disegna cerchio",drawLineLabel:"Disegna linea",
createCircleInteractivelyLabel:"Crea cerchio in modo interattivo",rangeErrorMessage:"Raggio o diametro non valido",numericInvalidMessage:"Inserire un valore numerico",timeLabel:"Ora",invalidTimeMessage:"Valore dell\u2019ora non valido",hoursLabel:"Ore",minutesLabel:"Minuti",secondsLabel:"Secondi",rateLabel:"Grado",invalidDistanceMessage:"Valore distanza non valida",feetSecondsLabel:"Piedi al secondo",feetHourLabel:"Piedi all\u2019ora",kmSecondLabel:"Chilometri al secondo",kmHourLabel:"Chilometri all'ora",
metersSecondLabel:"Metri al secondo",metersHourLabel:"Metri all\u2019ora",milesSecondLabel:"Miglia al secondo",milesHourLabel:"Miglia all\u2019ora",nauticalMilesSecondLabel:"Miglia nautiche al secondo",nauticalMilesHourLabel:"Miglia nautiche all\u2019ora",clearGraphicsLabel:"Cancella grafici",ellipseTypeLabel:"Tipo di ellisse",ellipseSemiLabel:"Semi",ellipseFullLabel:"Completa",drawEllipseLabel:"Disegna ellisse",createEllipseInteractively:"Crea ellisse in modo interattivo",axisLabel:"Asse",unitLabel:"Unit\u00e0",
majorRadiusLabel:"Maggiore (raggio)",majorDiameterLabel:"Maggiore (diametro)",axisErrorMessage:"Il valore deve essere maggiore di 0",minorRadiusLabel:"Minore (raggio)",minorDiameterLabel:"Minore (diametro)",orientationLabel:"Orientamento",orientationErrorMessage:"Il valore deve essere compreso tra 0 e 360",warningMessage:"Avvertenza: i grafici generati usando lo strumento ellisse non sono geodetici",fromLabel:"Da",distanceBearingLabel:"Distanza e rilevamento",pointsLabel:"Punti",createLineInteractively:"Crea linea in modo interattivo",
lineLengthErrorMessage:"Lunghezza linea non valida",degreesLabel:"Gradi",milsLabel:"Migliaia",lineTypeLabel:"Tipo",interactiveLabel:"Interattivo",fixedLabel:"Fisso",originLabel:"Origine",cumulativeLabel:"Cumulativo",numberOfRingsLabel:"Numero di anelli",ringsErrorMessage:"Numero di anelli non valido",distanceBetweenRingsLabel:"Distanza tra anelli",ringsDecimalErrorMessage:"Inserire un valore numerico con 2 posizioni decimali",distanceUnitsLabel:"Unit\u00e0 Distanza",distancesLabel:"Distanza",numberOfRadialsLabel:"Numero di radiali",
upLabel:"Su",downLabel:"Gi\u00f9",deleteLabel:"Elimina",radialsErrorMessage:"Numero di radiali non valido. Il massimo consentito \u00e8 di 360.",radialsInvalidMessage:"Valore non valido per radiali",addPointLabel:"Aggiungi Punto",valueLabel:"Valore",valueText:"Immetti valore",actionLabel:"Azione",distanceCalculatorLabel:"Calcolatore di distanza",abbrevMetersLabel:"m",abbrevFeetLabel:"piedi",abbrevKmLabel:"km",abbrevMilesLabel:"mi",abbrevYardsLabel:"yd",abbrevNauticalMilesLabel:"mn",abbrevDegreesLabel:"\u00c2\u00b0",
abbrevMilsLabel:"mil",abbrevHoursLabel:"h",abbrevMinutesLabel:"m",abbrevSecondsLabel:"s",abbrevFeetSecondsLabel:"ft/s",abbrevFeetHourLabel:"ft/h",abbrevKmSecondLabel:"km/s",abbrevKmHourLabel:"km/h",abbrevMetersSecondLabel:"m/s",abbrevMetersHourLabel:"m/h",abbrevMilesSecondLabel:"mi/s",abbrevMilesHourLabel:"mi/h",abbrevNauticalMilesSecondLabel:"nm/s",abbrevNauticalMilesHourLabel:"nm/h",_localized:{}}});