// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/DistanceAndDirection/nls/strings":{_widgetLabel:"Et\u00e4isyys ja suunta",tabLineTitle:"Viiva",tabCircleTitle:"Ympyr\u00e4",tabEllipseTitle:"Ellipsi",tabRingsTitle:"Renkaat",multipleNotationsMessage:" l\u00e4ht\u00f6aineistoasi vastaavia esitystapoja. Vahvista k\u00e4ytett\u00e4v\u00e4 esitystapa:",invalidCoordinateMessage:"Virheellinen koordinaatti",confirmInputNotationMessage:"Vahvista l\u00e4ht\u00f6aineiston esitysmuoto",prefixSuffixMessage:"L\u00e4ht\u00f6aineiston koordinaatissa on havaittu olevan pituusasteen tai leveysasteen sek\u00e4 etu- ett\u00e4 j\u00e4lkiliite. Palautettu koordinaatti perustuu etuliitteeseen.",
rememberDecisionMessage:"Muista valintani \u00e4l\u00e4k\u00e4 kysy tietoja uudelleen.\x3cbr/\x3e",majorAxisTooltipMessage:"Napsauta p\u00e4\u00e4akselin pituutta",minorAxisTooltipMessage:"M\u00e4\u00e4rit\u00e4 pikkuakseli ja lopeta ellipsin piirto siirt\u00e4m\u00e4ll\u00e4 hiiri takaisin aloituskohtaan",clickToFinishLineMessage:"Lopeta viivan piirto napsauttamalla",doubleClickEllipseMesage:"Lopeta aluerenkaiden piirto kaksoisnapsauttamalla",invalidCoordinateTypeMessage:"L\u00e4ht\u00f6aineiston koordinaattien tyyppi\u00e4 ei voi m\u00e4\u00e4ritt\u00e4\u00e4. Tarkista l\u00e4ht\u00f6aineistosi.",
noCenterPointSetMessage:"Keskipistett\u00e4 ei ole m\u00e4\u00e4ritetty. Tarkista l\u00e4ht\u00f6aineistosi.",ellipseMajorAxis:"P\u00e4\u00e4akseli",ellipseMinorAxis:"Pikkuakseli",degreesRangeMessage:"Arvon on oltava v\u00e4lill\u00e4 0 ja 360.",millsRangeMessage:"Arvon on oltava v\u00e4lill\u00e4 0 ja 6400.",lengthLabel:"Pituus",angleLabel:"Kulma",startPointLabel:"Aloituspiste",endPointLabel:"Loppupiste",centerPointLabel:"Keskipiste",distanceTableErrorMessage:"Et\u00e4isyystaulukko on tyhj\u00e4. Varmista, ett\u00e4 sy\u00f6t\u00e4t joitakin et\u00e4isyyksi\u00e4.",
setCoordFormatStringMessage:"M\u00e4\u00e4rit\u00e4 koordinaatin muotomerkkijono",prefixMessage:"Lis\u00e4\u00e4 etuliite +/- positiivisiin ja negatiivisiin numeroihin",ddLabel:"da",ddmLabel:"DDM",dmsLabel:"DMS",garsLabel:"GARS",georefLabel:"GEOREF",mgrsLabel:"MGRS",usngLabel:"USNG",utmLabel:"UTM",utmhLabel:"UTM (H)",DDLatLongNotation:"Desimaaliasteet \u2013 leveys-/pituusaste",DDLongLatNotation:"Desimaaliasteet \u2013 pituus-/leveysaste",DDMLatLongNotation:"Asteet, desimaaliminuutit \u2013 leveys-/pituusaste",
DDMLongLatNotation:"Asteet, desimaaliminuutit \u2013 pituus-/leveysaste",DMSLatLongNotation:"Asteet, minuutit, sekunnit \u2013 leveys-/pituusaste",DMSLongLatNotation:"Asteet, minuutit, sekunnit \u2013 pituus-/leveysaste",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM \u2013 kaistan kirjain",UTMHemNotation:"UTM \u2013 pallonpuolisko (P/E)",circleTitle:"Luo ympyr\u00e4 kohteesta",radiusLabel:"S\u00e4de",diameterLabel:"L\u00e4pimitta",startPointPlaceHolderLabel:"Kirjoita koordinaatit",
formatInputLabel:"Muodon l\u00e4ht\u00f6aineisto",drawCircleLabel:"Piirr\u00e4 ympyr\u00e4",drawLineLabel:"Piirr\u00e4 viiva",createCircleInteractivelyLabel:"Luo ympyr\u00e4 vuorovaikutteisesti",rangeErrorMessage:"Virheellinen s\u00e4de tai halkaisija",numericInvalidMessage:"Anna numeroarvo",timeLabel:"kellonaika",invalidTimeMessage:"Virheellinen aika-arvo",hoursLabel:"Tuntia",minutesLabel:"Minuuttia",secondsLabel:"Sekuntia",rateLabel:"Nopeus",invalidDistanceMessage:"Virheellinen et\u00e4isyysarvo",
feetSecondsLabel:"Jalkaa/sekunti",feetHourLabel:"Jalkaa/tunti",kmSecondLabel:"Kilometri\u00e4/sekunti",kmHourLabel:"Kilometri\u00e4/tunti",metersSecondLabel:"Metri\u00e4/sekunti",metersHourLabel:"Metri\u00e4/tunti",milesSecondLabel:"Mailia/sekunti",milesHourLabel:"Mailia/tunti",nauticalMilesSecondLabel:"Merimailia/sekunti",nauticalMilesHourLabel:"Merimailia/tunti",clearGraphicsLabel:"Tyhjenn\u00e4 grafiikka",ellipseTypeLabel:"Ellipsin tyyppi",ellipseSemiLabel:"Puoli-",ellipseFullLabel:"T\u00e4ydellinen",
drawEllipseLabel:"Piirr\u00e4 ellipsi",createEllipseInteractively:"Luo ellipsi vuorovaikutteisesti",axisLabel:"Akseli",unitLabel:"Yksikk\u00f6",majorRadiusLabel:"P\u00e4\u00e4(s\u00e4de)",majorDiameterLabel:"P\u00e4\u00e4akseli (halkaisija)",axisErrorMessage:"Arvon on oltava suurempi kuin 0",minorRadiusLabel:"Ali(s\u00e4de)",minorDiameterLabel:"Pikkuakseli (halkaisija)",orientationLabel:"Suunta",orientationErrorMessage:"Arvon on oltava v\u00e4lill\u00e4 0 ja 360.",warningMessage:"Varoitus: ellipsity\u00f6kalulla luodut grafiikat eiv\u00e4t ole geodeettisi\u00e4",
fromLabel:"Alkaen",distanceBearingLabel:"Et\u00e4isyys ja suuntima",pointsLabel:"Pisteet",createLineInteractively:"Luo viiva vuorovaikutteisesti",lineLengthErrorMessage:"Virheellinen viivan pituus",degreesLabel:"Asteet",milsLabel:"Millimetri\u00e4",lineTypeLabel:"Tyyppi",interactiveLabel:"Vuorovaikutteinen",fixedLabel:"Kiinte\u00e4",originLabel:"Alkupiste",cumulativeLabel:"Kumulatiivinen",numberOfRingsLabel:"Renkaiden m\u00e4\u00e4r\u00e4",ringsErrorMessage:"Virheellinen renkaiden m\u00e4\u00e4r\u00e4",
distanceBetweenRingsLabel:"Renkaiden v\u00e4linen et\u00e4isyys",ringsDecimalErrorMessage:"Anna numeroarvo kahdelle desimaalille",distanceUnitsLabel:"Et\u00e4isyyden yksik\u00f6t",distancesLabel:"Et\u00e4isyydet",numberOfRadialsLabel:"S\u00e4teiden m\u00e4\u00e4r\u00e4",upLabel:"Yl\u00f6s",downLabel:"Alas",deleteLabel:"Poista",radialsErrorMessage:"Virheellinen s\u00e4teiden m\u00e4\u00e4r\u00e4. Suurin sallittu m\u00e4\u00e4r\u00e4 on 360",radialsInvalidMessage:"Virheellinen arvo s\u00e4teille",addPointLabel:"Lis\u00e4\u00e4 piste",
valueLabel:"Arvo",valueText:"Sy\u00f6t\u00e4 arvo",actionLabel:"Toiminto",distanceCalculatorLabel:"Et\u00e4isyyslaskin",abbrevMetersLabel:"m",abbrevFeetLabel:"ft",abbrevKmLabel:"km",abbrevMilesLabel:"mailia",abbrevYardsLabel:"yd",abbrevNauticalMilesLabel:"mpk",abbrevDegreesLabel:"\u00c2\u00b0",abbrevMilsLabel:"ml",abbrevHoursLabel:"k",abbrevMinutesLabel:"m",abbrevSecondsLabel:"s",abbrevFeetSecondsLabel:"ft/s",abbrevFeetHourLabel:"ft/h",abbrevKmSecondLabel:"km/s",abbrevKmHourLabel:"km/h",abbrevMetersSecondLabel:"m/s",
abbrevMetersHourLabel:"m/h",abbrevMilesSecondLabel:"mi/s",abbrevMilesHourLabel:"mi/h",abbrevNauticalMilesSecondLabel:"mpk/s",abbrevNauticalMilesHourLabel:"mpk/h",_localized:{}}});