// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Screening/setting/nls/strings":{units:{feetUnit:"P\u00e9s / P\u00e9s Quadrados",milesUnit:"Milhas / Acres",metersUnit:"Metros / Metros Quadrados",kilometersUnit:"Quil\u00f4metros / Quil\u00f4metros Quadrados",hectaresUnit:"Quil\u00f4metros / Hectares"},analysisTab:{analysisTabLabel:"An\u00e1lise",selectAnalysisLayerLabel:"Selecionar camadas de an\u00e1lise",addLayerLabel:"Adicionar Camadas",noValidLayersForAnalysis:"Nenhuma camada v\u00e1lida localizada no webmap selecionado.",noValidFieldsForAnalysis:"Nenhum campo v\u00e1lido localizado no webmap selecionado. Remova a camada selecionada.",
addLayersHintText:"Sugest\u00e3o: Selecione as camadas e campos para analisar e exibir no relat\u00f3rio",addLayerNameTitle:"Nome da Camada",addFieldsLabel:"Adicionar Campo",addFieldsPopupTitle:"Selecionar Campos",addFieldsNameTitle:"Nomes de Campo",aoiToolsLegendLabel:"Ferramentas AOI",aoiToolsDescriptionLabel:"Habilite as ferramentas para criar \u00e1reas de interesse e especifique seus r\u00f3tulos",placenameLabel:"Nome do local",drawToolsLabel:"Ferramentas de Desenho",uploadShapeFileLabel:"Transferir um Shapefile",
coordinatesLabel:"Coordenadas",coordinatesDrpDwnHintText:"Sugest\u00e3o: Selecione a unidade para exibir as transversais inseridas",coordinatesBearingDrpDwnHintText:"Sugest\u00e3o: Selecione a dire\u00e7\u00e3o para exibir as transversais inseridas",allowShapefilesUploadLabel:"Permitir transfer\u00eancias de shapefiles para an\u00e1lise",allowShapefilesUploadLabelHintText:"Sugest\u00e3o: Exibe 'Transferir shapefile na An\u00e1lise' na Guia Relat\u00f3rio",allowVisibleLayerAnalysisLabel:"N\u00e3o analisar ou relatar resultados para camadas que n\u00e3o s\u00e3o vis\u00edveis",
allowVisibleLayerAnalysisHintText:"Sugest\u00e3o: As camadas que foram desativadas ou n\u00e3o s\u00e3o vis\u00edveis devido ao ajuste das configura\u00e7\u00f5es de visibilidade n\u00e3o ser\u00e3o analisadas ou inclu\u00eddas em resultados impressos ou baixados.",areaUnitsLabel:"Mostrar resultados da an\u00e1lise em",maxFeatureForAnalysisLabel:"M\u00e1ximo de fei\u00e7\u00f5es para an\u00e1lise",maxFeatureForAnalysisHintText:"Sugest\u00e3o: Configure o n\u00famero m\u00e1ximo de fei\u00e7\u00f5es para an\u00e1lise",
searchToleranceLabelText:"Toler\u00e2ncia de Pesquisa",searchToleranceHint:"Sugest\u00e3o: A toler\u00e2ncia de pesquisa \u00e9 somente utilizada ao analisar entradas de pontos e linhas",placenameButtonText:"Nome do local",drawToolsButtonText:"Desenhar",shapefileButtonText:"Shapefile",coordinatesButtonText:"Coordenadas",invalidLayerErrorMsg:"Configure os campos para",drawToolSelectableLayersLabel:"Selecionar ferramenta de desenho de camadas selecion\u00e1veis",drawToolSelectableLayersHint:"Sugest\u00e3o: Selecione camadas que estar\u00e3o dispon\u00edveis para sele\u00e7\u00e3o na lista de camada de ferramenta de desenho"},
downloadTab:{downloadLegend:"Configura\u00e7\u00f5es de Download",reportLegend:"Configura\u00e7\u00f5es do Relat\u00f3rio",downloadTabLabel:"Download",syncEnableOptionLabel:"Camadas de Fei\u00e7\u00f5es",syncEnableOptionHint:"Sugest\u00e3o: Utilizado para baixar informa\u00e7\u00f5es da fei\u00e7\u00e3o para as fei\u00e7\u00f5es que interseccionam a \u00e1rea de interesse nos formatos indicados.",syncEnableOptionNote:"Anota\u00e7\u00e3o: Os servi\u00e7os de fei\u00e7\u00e3o com sincroniza\u00e7\u00e3o habilitada s\u00e3o exigidos para as op\u00e7\u00f5es Arquivo Geodatabase e Shapefile. O formato de Shapefile \u00e9 somente suportado com camadas de fei\u00e7\u00e3o hospedadas do ArcGIS Online.",
extractDataTaskOptionLabel:"Servi\u00e7o de geoprocessamento Extrair Tarefa de Dados",extractDataTaskOptionHint:"Sugest\u00e3o: Utilize um servi\u00e7o de geoprocessamento Extrair Tarefa de Dados publicado para baixar fei\u00e7\u00f5es que interseccionam a \u00e1rea de interesse nos formatos Arquivo Geodatabase ou Shapefile.",cannotDownloadOptionLabel:"Desabilitar o download",syncEnableTableHeaderTitle:{layerNameLabel:"Nome da Camada",csvFileFormatLabel:"CSV",fileGDBFormatLabel:"Arquivo Geodatabase",
ShapefileFormatLabel:"Shapefile",allowDownloadLabel:"Permitir Download"},setButtonLabel:"Configurar",GPTaskLabel:"Especifique a url para o servi\u00e7o de geoprocessamento",printGPServiceLabel:"Imprimir URL do Servi\u00e7o",setGPTaskTitle:"Especifique a URL de Servi\u00e7o de Geoprocessamento exigida",logoLabel:"Logotipo",logoChooserHint:"Sugest\u00e3o: Clique no \u00edcone de imagem para alterar a imagem",footnoteLabel:"Nota de rodap\u00c3\u00a9",columnTitleColorPickerLabel:"Cor para t\u00edtulos de coluna",
reportTitleLabel:"T\u00edtulo do Relat\u00f3rio",errorMessages:{invalidGPTaskURL:"Servi\u00e7o de geoprocessamento inv\u00e1lido. Selecione o servi\u00e7o de geoprocessamento contendo Extrair Tarefa de Dados.",noExtractDataTaskURL:"Selecione qualquer servi\u00e7o de geoprocessamento contendo Extrair Tarefa de Dados.",duplicateCustomOption:"A entrada duplicada para ${duplicateValueSizeName} existe.",invalidLayoutWidth:"Largura inv\u00e1lida inserida para ${customLayoutOptionValue}.",invalidLayoutHeight:"Altura inv\u00e1lida inserida para ${customLayoutOptionValue}.",
invalidLayoutPageUnits:"Unidade de p\u00e1gina inv\u00e1lida selecionada para ${customLayoutOptionValue}.",failtofetchbuddyTaskDimension:"Erro ao procura informa\u00e7\u00f5es da dimens\u00e3o de tarefa do amigo. Tente novamente.",failtofetchbuddyTaskName:"Erro ao procura nome de tarefa do amigo. Tente novamente.",failtofetchChoiceList:"Erro ao buscar a lista de op\u00e7\u00f5es do servi\u00e7o de impress\u00e3o. Tente novamente.",invalidWidth:"Largura Inv\u00e1lida.",invalidHeight:"Altura Inv\u00e1lida."},
addCustomLayoutTitle:"Adicionar Layout Personalizado",customLayoutOptionHint:"Dica: Adicione a op\u00e7\u00e3o de layout personalizado a partir do seu servi\u00e7o de impress\u00e3o \u00e0s op\u00e7\u00f5es de impress\u00e3o.",reportDefaultOptionLabel:"Layout Padr\u00e3o",pageSizeUnits:{millimeters:"Mil\u00edmetros",points:"Pontos"}},generalTab:{generalTabLabel:"Geral",tabLabelsLegend:"R\u00f3tulos do Painel",tabLabelsHint:"Sugest\u00e3o: Especificar R\u00f3tulos",AOITabLabel:"Painel de \u00c1rea de Interesse",
ReportTabLabel:"Painel de Relat\u00f3rio",bufferSettingsLegend:"Configura\u00e7\u00f5es do Buffer",defaultBufferDistanceLabel:"Dist\u00e2ncia de Buffer Padr\u00e3o",defaultBufferUnitsLabel:"Unidades do Buffer",generalBufferSymbologyHint:"Sugest\u00e3o: Configure a simbologia para ser utilizado para exibir buffers ao redor das \u00e1reas de interesse definidas",aoiGraphicsSymbologyLegend:"Simbologia de Gr\u00e1ficos AOI",aoiGraphicsSymbologyHint:"Sugest\u00e3o: Configure a simbologia a ser utilizada ao definir as \u00e1reas de interesse de ponto, linha e pol\u00edgono",
pointSymbologyLabel:"Ponto",previewLabel:"Visualizar",lineSymbologyLabel:"Linha",polygonSymbologyLabel:"Pol\u00edgono",aoiBufferSymbologyLabel:"Simbologia de Buffer",pointSymbolChooserPopupTitle:"S\u00edmbolo de local ou endere\u00e7o",polygonSymbolChooserPopupTitle:"Selecionar s\u00edmbolo para destacar pol\u00edgono",lineSymbolChooserPopupTitle:"Selecione a s\u00edmbolo para destacar a linha",aoiSymbolChooserPopupTitle:"Configurar s\u00edmbolo do buffer",aoiTabText:"AOI",reportTabText:"Relat\u00f3rio",
invalidSymbolValue:"Valor de s\u00edmbolo inv\u00e1lido."},searchSourceSetting:{searchSourceSettingTabTitle:"Configura\u00e7\u00f5es da Fonte de Pesquisa",searchSourceSettingTitle:"Configura\u00e7\u00f5es da Fonte de Pesquisa",searchSourceSettingTitleHintText:"Adicione e configure servi\u00e7os de geoc\u00f3digo ou camadas de fei\u00e7\u00e3o como fontes de pesquisa. Estas fontes especificadas determinam o que \u00e9 pesquis\u00e1vel dentro da caixa de pesquisa.",addSearchSourceLabel:"Adicionar Fonte de Pesquisa",
featureLayerLabel:"Camada de Fei\u00e7\u00e3o",geocoderLabel:"Geocodificador",generalSettingLabel:"Configura\u00e7\u00f5es Gerais",allPlaceholderLabel:"Texto de local reservado para pesquisar todos:",allPlaceholderHintText:"Sugest\u00e3o: Insira o texto a ser mostrado como reservado ao pesquisar todas as camadas e geocodificador",generalSettingCheckboxLabel:"Mostrar pop-up do local ou fei\u00e7\u00e3o localizada",countryCode:"C\u00f3digos de Regi\u00e3o e Pa\u00eds",countryCodeEg:"por exemplo ",countryCodeHint:"Deixar este valor em branco pesquisar\u00e1 todos os pa\u00edses e regi\u00f5es",
questionMark:"?",searchInCurrentMapExtent:"Somente pesquisar na extens\u00e3o de mapa atual",locatorUrl:"URL do Geocodificador",locatorName:"Nome do Geocodificador",locatorExample:"Exemplo",locatorWarning:"Esta vers\u00e3o do servi\u00e7o de geocodifica\u00e7\u00e3o n\u00e3o \u00e9 suportado. O widget suporta servi\u00e7o de geocodifica\u00e7\u00e3o 10.0 e superior.",locatorTips:"As sugest\u00f5es n\u00e3o est\u00e3o dispon\u00edveis, pois o servi\u00e7o de geocodifica\u00e7\u00e3o n\u00e3o suporta o recursos de sugest\u00e3o.",
layerSource:"Origem da Camada",setLayerSource:"Configurar Origem da Camada",setGeocoderURL:"Configurar URL do Geocodificador",searchLayerTips:"As sugest\u00f5es n\u00e3o est\u00e3o dispon\u00edveis, pois o servi\u00e7o da fei\u00e7\u00e3o n\u00e3o suporta o recursos de pagina\u00e7\u00e3o.",placeholder:"Texto do Placeholder",searchFields:"Pesquisar Campos",displayField:"Campo de Visualiza\u00e7\u00e3o",exactMatch:"Combina\u00e7\u00e3o Exata",maxSuggestions:"M\u00e1ximo de Sugest\u00f5es",maxResults:"M\u00e1ximo de Resultados",
enableLocalSearch:"Habilitar pesquisa de local",minScale:"Escala M\u00edn",minScaleHint:"Quando a escala do mapa for maior que esta escala, a pesquisa de local ser\u00e1 aplicada",radius:"Raio",radiusHint:"Especifica o raio de uma \u00e1rea ao redor do centro do mapa atual que \u00e9 utilizado para impulsionar o grau de candidatos de geocodifica\u00e7\u00e3o de forma que os candidatos mais pr\u00f3ximos ao local sejam retornados primeiro",setSearchFields:"Configurar Campos de Pesquisa",set:"Configurar",
invalidUrlTip:"A URL ${URL} \u00e9 inv\u00e1lida ou inacess\u00edvel.",invalidSearchSources:"Configura\u00e7\u00f5es de fonte de pesquisa inv\u00e1lida"},errorMsg:{textboxFieldsEmptyErrorMsg:"Preencha os campos exigidos",bufferDistanceFieldsErrorMsg:"Insira valores v\u00e1lidos",invalidSearchToleranceErrorMsg:"Insira um valor v\u00e1lido para toler\u00e2ncia de pesquisa",atLeastOneCheckboxCheckedErrorMsg:"Configura\u00e7\u00e3o inv\u00e1lida: Pelo menos uma Ferramenta AOI \u00e9 exigida.",noLayerAvailableErrorMsg:"Nenhuma camada dispon\u00edvel",
layerNotSupportedErrorMsg:"N\u00e3o Suportado ",noFieldSelected:"Utilize a a\u00e7\u00e3o de edi\u00e7\u00e3o para selecionar campos para an\u00e1lise.",duplicateFieldsLabels:'Duplicar r\u00f3tulo "${labelText}" adicionado para : "${itemNames}"',noLayerSelected:"Selecione pelo menos uma camada para an\u00e1lise",errorInSelectingLayer:"N\u00e3o \u00e9 poss\u00edvel completar a opera\u00e7\u00e3o de sele\u00e7\u00e3o da camada. Tente novamente.",errorInMaxFeatureCount:"Insira a contagem do m\u00e1ximo de fei\u00e7\u00f5es v\u00e1lidas para an\u00e1lise."},
_localized:{}}});