// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/GriddedReferenceGraphic/nls/strings":{_widgetLabel:"Ruudukkomuotoinen viitegrafiikka",newGRGFromAreaButtonLabel:"M\u00e4\u00e4rit\u00e4 ruudukko alueesta",newGRGFromPointButtonLabel:"M\u00e4\u00e4rit\u00e4 ruudukko pisteest\u00e4",newGRGFromAreaTitle:"M\u00e4\u00e4rit\u00e4 ruudukko alueesta",newGRGFromPointTitle:"M\u00e4\u00e4rit\u00e4 ruudukko pisteest\u00e4",newGRGBySizeButtonLabel:"Ulottuvuuden perusteella",newGRGFromRefSystemButtonLabel:"Viitej\u00e4rjestelm\u00e4n perusteella",
newGRGByTimeLabel:"Ajan ja nopeuden perusteella",newGRGFromNonStandardButtonLabel:"M\u00e4\u00e4rit\u00e4 muu kuin vakiomuotoinen ruudukko",newGRGAreaBySizeTitle:"GRG alueesta ulottuvuuden perusteella",newGRGAreaBySizeDefineAreaLabel:"GRG-alue",addGRGAreaPolygonToolTip:"Piirr\u00e4 GRG-alue aluekohteen avulla",addGRGAreaExtentToolTip:"Piirr\u00e4 GRG-alue kartan n\u00e4kym\u00e4n laajuudelle",rotation:"Ruudukon kierto",numberRowsColumnsLabel:"M\u00e4\u00e4rit\u00e4 rivien ja sarakkeiden m\u00e4\u00e4r\u00e4",
newGRGAreaByRefSystemTitle:"GRG alueesta viitej\u00e4rjestelm\u00e4n perusteella",gridSize:"Ruudukon koko",UTMZoneandBand:"Ruudukon vy\u00f6hyke","100000m":"100 000 metri\u00e4","10000m":"10 000 metri\u00e4","1000m":"1 000 metri\u00e4","100m":"100 metri\u00e4","10m":"10 metri\u00e4",clipGrid:"Leikkaa ruudukko GRG-alueeseen",newGRGAreaFromNonStandardTitle:"Uusi NRG",newGRGPointBySizeTitle:"GRG pisteest\u00e4 ulottuvuuden perusteella",newGRGPointByRefSystemTitle:"GRG pisteest\u00e4 viitej\u00e4rjestelm\u00e4n perusteella",
newGRGPointByTimeTitle:"GRG pisteest\u00e4 ajan ja nopeuden avulla",time:"Kellonaika",rate:"Nopeus",hours:"Tuntia",minutes:"Minuuttia",seconds:"Sekuntia",ftPerSec:"Jalkaa/sekunti",ftPerHour:"Jalkaa/tunti",kmPerSec:"Kilometri\u00e4/sekunti",kmPerHour:"Kilometri\u00e4/tunti",mPerSec:"Metri\u00e4/sekunti",mPerHour:"Metri\u00e4/tunti",miPerSec:"Mailia/sekunti",miPerHour:"Mailia/tunti",nMPerSec:"Merimailia/sekunti",nMPerHour:"Merimailia/tunti",settingsTitle:"Asetukset",labelSettingsLabel:"Tunnustekstien asetukset",
labelSettingsButtonLabel:"M\u00e4\u00e4rit\u00e4 tunnustekstien asetukset",gridSettingsLabel:"Ruudukkoasetukset",gridSettingsButtonLabel:"M\u00e4\u00e4rit\u00e4 ruudukkoasetukset",transparency:"L\u00e4pin\u00e4kyvyys",labelStyle:"Tunnustekstin tyyli",font:"Fontti",textSize:"Tekstin koko",textColor:"Tekstin v\u00e4ri",halo:"Reunus",show:"N\u00e4yt\u00e4",lockSettings:"Sovelluksen omistaja on lukinnut asetukset",gridSettings:{cellShape:"Solun muoto",cellUnits:"Solun yksik\u00f6t",cellOutline:"Solun \u00e4\u00e4riviiva-asetukset",
cellFill:"Solun t\u00e4ytt\u00f6asetukset",gridReferenceSystem:"Viitej\u00e4rjestelm\u00e4",gridDatum:"Datumi: WGS84",labelStartPosition:"Tunnustekstin alkupiste",labelType:"Tunnustekstin tyyppi",labelDirection:"Tunnustekstin suunta",gridOrigin:"Ruudukon alkupiste","default":"Suorakulmio",hexagon:"Kuusikulmio",miles:"Mailia",kilometers:"Kilometri\u00e4",feet:"Jalkaa",meters:"Metri\u00e4",yards:"Jaardia","nautical-miles":"Meripeninkulmaa",lowerLeft:"Alavasen",lowerRight:"Alaoikea",upperLeft:"Yl\u00e4vasen",
upperRight:"Yl\u00e4oikea",center:"Keskit\u00e4",alphaNumeric:"Aakkosnumeerinen",alphaAlpha:"Vain kirjaimia",numeric:"Numeerinen",horizontal:"Vaaka",vertical:"Pysty",MGRS:"MGRS",USNG:"USNG",showLabels:"N\u00e4yt\u00e4 tunnustekstit"},publishTitle:"Julkaise GRG portaaliin",publishGRGBtn:"Julkaise",GRGLayerName:"Julkaistun GRG-karttatason nimi",invalidGRGLayerName:"Karttatason nimi voi sis\u00e4lt\u00e4\u00e4 vain aakkosnumeerisia merkkej\u00e4 ja alaviivoja",missingGRGLayerName:"GRG:n nimi on annettava",
publishWorskpaceError:"VIRHE: virhe ty\u00f6tilan avauksessa",publishingFailedLayerExists:"Julkaisu ep\u00e4onnistui: Sinulla on jo kohdepalvelu nimelt\u00e4 {0}. Valitse toinen nimi.",checkService:"Tarkista palvelu: {0}",createService:"Luo palvelu: {0}",unableToCreate:"Kohteen {0} tuonti ei onnistu",addToDefinition:"Lis\u00e4\u00e4 m\u00e4\u00e4ritykseen: {0}",successfullyPublished:"Web-karttatason julkaisu onnistui{0}Web-karttatason hallinta",userRole:"Palvelun luonti ei onnistu, koska k\u00e4ytt\u00e4j\u00e4ll\u00e4 ei ole k\u00e4ytt\u00f6oikeuksia",
createGRGBtn:"Luo GRG",clearGRGBtn:"Tyhjenn\u00e4",labelFormat:"Tunnustekstin muoto",helpIconTooltip:"Z: ruudukon vy\u00f6hykem\u00e4\u00e4ritys (GZD)\nS: ruudukon 100 000 metrin neli\u00f6n tunnus (GSID)\nX: it\u00e4inen (X-koordinaatti)\nY: pohjoinen (Y-koordinaatti)\n\nEsimerkit:\nZSXY on 15SWC8081751205\nZS X,Y on 15SWC 80817,51205",addPointToolTip:"Lis\u00e4\u00e4 GRG:n alkupiste",cellWidth:"Solun leveys (x)",cellHeight:"Solun korkeus (y)",invalidNumberMessage:"Annettu arvo ei kelpaa",invalidRangeMessage:"Arvon on oltava suurempi kuin 0",
gridAngleInvalidRangeMessage:"Arvon on oltava v\u00e4lill\u00e4 -89,9 ja 89,9.",formatIconTooltip:"Muodon l\u00e4ht\u00f6aineisto",coordInputLabel:"GRG:n alkupiste (DD)",setCoordFormat:"M\u00e4\u00e4rit\u00e4 koordinaatin muotomerkkijono",prefixNumbers:"Lis\u00e4\u00e4 etuliite +/- positiivisiin ja negatiivisiin numeroihin",cancelBtn:"Peruuta",applyBtn:"K\u00e4yt\u00e4",comfirmInputNotation:"Vahvista l\u00e4ht\u00f6aineiston esitysmuoto",notationsMatch:"l\u00e4ht\u00f6aineistoasi vastaavia esitystapoja. Vahvista k\u00e4ytett\u00e4v\u00e4 esitystapa:",
numberOfCellsHorizontal:"Vaakasuuntaisten solujen m\u00e4\u00e4r\u00e4",numberOfCellsVertical:"Pystysuuntaisten solujen m\u00e4\u00e4r\u00e4",gridAngle:"Ruudukon kierto",tooManyCellsErrorMessage:"Yrit\u00e4t luoda ruudukkoa, joka koostuu yli 2 000 solusta. On suositeltavaa pienent\u00e4\u00e4 luotavien solujen m\u00e4\u00e4r\u00e4\u00e4 muuttamalla ruudukon kokoa tai ruudukkoaluetta.",missingParametersMessage:"\x3cp\x3eGRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisi\u00e4. Varmista seuraavat asiat:\x3c/p\x3e\x3cul\x3e\x3cli\x3eGRG-alue on piirretty.\x3c/li\x3e\x3cli\x3eSolun leveys ja korkeus sis\u00e4lt\u00e4v\u00e4t kelvolliset arvot.\x3c/li\x3e\x3c/ul\x3e",
missingOriginParametersMessage:"\x3cp\x3eGRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisi\u00e4. Varmista seuraavat asiat:\x3c/p\x3e\x3cul\x3e\x3cli\x3eGRG:n alkupiste on m\u00e4\u00e4ritetty.\x3c/li\x3e\x3cli\x3eAika-, nopeus- ja kulmasy\u00f6tteet sis\u00e4lt\u00e4v\u00e4t kelvolliset arvot.\x3c/li\x3e\x3c/ul\x3e",invalidWidthHeightParametersMessage:"\x3cp\x3eGRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisi\u00e4. Varmista, ett\u00e4 solun leveys- ja korkeussy\u00f6tteet sis\u00e4lt\u00e4v\u00e4t kelvolliset arvot.\x3c/p\x3e",
invalidHorizontalVerticalParametersMessage:"\x3cp\x3eGRG:n luontilomakkeesta puuttuu parametreja tai ne ovat virheellisi\u00e4. Varmista, ett\u00e4 vaaka- ja pystysy\u00f6tteiden solujen m\u00e4\u00e4r\u00e4t sis\u00e4lt\u00e4v\u00e4t kelvolliset arvot.\x3c\x3e",drawPointToolTip:"Lis\u00e4\u00e4 GRG:n alkupiste napsauttamalla",missingLayerNameMessage:"Kelvollinen karttatason nimi on annettava ennen julkaisua",parseCoordinatesError:"Koordinaattien j\u00e4sennys ei onnistu. Tarkista l\u00e4ht\u00f6aineistosi.",
grgPolarRegionError:"GRG:n laajuus on napa-alueella. Soluja, jotka osuvat napa-alueille, ei luoda.",grgPolarOriginError:"GRG:n alkupiste ei voi olla napa-alueella, kun GRG:t\u00e4 luodaan viitej\u00e4rjestelm\u00e4n perusteella.",deleteBtn:"Poista",DD:"da",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Desimaaliasteet \u2013 leveys-/pituusaste",DDLongLatNotation:"Desimaaliasteet \u2013 pituus-/leveysaste",
DDMLatLongNotation:"Asteet, desimaaliminuutit \u2013 leveys-/pituusaste",DDMLongLatNotation:"Asteet, desimaaliminuutit \u2013 pituus-/leveysaste",DMSLatLongNotation:"Asteet, minuutit, sekunnit \u2013 leveys-/pituusaste",DMSLongLatNotation:"Asteet, minuutit, sekunnit \u2013 pituus-/leveysaste",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM \u2013 kaistan kirjain",UTMHemNotation:"UTM \u2013 pallonpuolisko (P/E)",_localized:{}}});