// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/GriddedReferenceGraphic/nls/strings":{_widgetLabel:"Rutn\u00e4tsreferensgrafik",newGRGFromAreaButtonLabel:"Definiera ett rutn\u00e4t fr\u00e5n ett omr\u00e5de",newGRGFromPointButtonLabel:"Definiera ett rutn\u00e4t fr\u00e5n en punkt",newGRGFromAreaTitle:"Definiera ett rutn\u00e4t fr\u00e5n ett omr\u00e5de",newGRGFromPointTitle:"Definiera ett rutn\u00e4t fr\u00e5n en punkt",newGRGBySizeButtonLabel:"Efter m\u00e5tt",newGRGFromRefSystemButtonLabel:"Efter referenssystem",newGRGByTimeLabel:"Efter tid och hastighet",
newGRGFromNonStandardButtonLabel:"Definiera icke-standardrutn\u00e4t",newGRGAreaBySizeTitle:"GRG fr\u00e5n ett omr\u00e5de efter m\u00e5tt",newGRGAreaBySizeDefineAreaLabel:"GRG-omr\u00e5de",addGRGAreaPolygonToolTip:"Rita GRG-omr\u00e5de med polygon",addGRGAreaExtentToolTip:"Rita GRG-omr\u00e5de med utbredning",rotation:"Rotation f\u00f6r rutn\u00e4t",numberRowsColumnsLabel:"Definiera antal rader och kolumner",newGRGAreaByRefSystemTitle:"GRG fr\u00e5n ett omr\u00e5de efter referenssystem",gridSize:"Rutn\u00e4tsstorlek",
UTMZoneandBand:"Rutn\u00e4tszon","100000m":"100\u00a0000 meter","10000m":"10\u00a0000 meter","1000m":"1\u00a0000 meter","100m":"100 meter","10m":"10 meter",clipGrid:"Klipp ut rutn\u00e4t till GRG-omr\u00e5de",newGRGAreaFromNonStandardTitle:"Nytt NRG",newGRGPointBySizeTitle:"GRG fr\u00e5n en punkt efter m\u00e5tt",newGRGPointByRefSystemTitle:"GRG fr\u00e5n en punkt efter referenssystem",newGRGPointByTimeTitle:"GRG fr\u00e5n en punkt med hj\u00e4lp av tid och hastighet",time:"Tid",rate:"Hastighet",
hours:"Timmar",minutes:"Minuter",seconds:"Sekunder",ftPerSec:"Fot/sekund",ftPerHour:"Fot/timme",kmPerSec:"Kilometer/sekund",kmPerHour:"Kilometer/timme",mPerSec:"Meter/sekund",mPerHour:"Meter/timme",miPerSec:"Engelska mil/sekund",miPerHour:"Engelska mil/timme",nMPerSec:"Nautiska mil/sekund",nMPerHour:"Nautiska mil/timme",settingsTitle:"Inst\u00e4llningar",labelSettingsLabel:"Etikettinst\u00e4llningar",labelSettingsButtonLabel:"Konfigurera etikettinst\u00e4llningar",gridSettingsLabel:"Inst\u00e4llningar f\u00f6r rutn\u00e4t",
gridSettingsButtonLabel:"Konfigurera rutn\u00e4tsinst\u00e4llningar",transparency:"Transparens",labelStyle:"Etikettstil",font:"Teckensnitt",textSize:"Textstorlek",textColor:"Textf\u00e4rg",halo:"Ring",show:"Visa",lockSettings:"Inst\u00e4llningen har l\u00e5sts av applikationens \u00e4gare",gridSettings:{cellShape:"Cellens form",cellUnits:"Cellenheter",cellOutline:"Inst\u00e4llningar f\u00f6r cellens kontur",cellFill:"Inst\u00e4llningar f\u00f6r cellens fyllnadsf\u00e4rg",gridReferenceSystem:"Referenssystem",
gridDatum:"Datum: WGS84",labelStartPosition:"Etikettens ursprung",labelType:"Etikettyp",labelDirection:"Etikettens riktning",gridOrigin:"Rutn\u00e4tets origo","default":"Rektangel",hexagon:"Hexagon",miles:"Mile",kilometers:"Kilometer",feet:"Fot",meters:"Meter",yards:"Yard","nautical-miles":"Nautiska mil",lowerLeft:"Nedre v\u00e4nstra",lowerRight:"Nedre h\u00f6gra",upperLeft:"\u00d6vre v\u00e4nstra",upperRight:"\u00d6vre h\u00f6gra",center:"Centrera",alphaNumeric:"Alfanumerisk",alphaAlpha:"Alfa-alfa",
numeric:"Numerisk",horizontal:"Horisontell",vertical:"Vertikal",MGRS:"MGRS",USNG:"USNG",showLabels:"Visa etiketter"},publishTitle:"Publicera GRG till portalen",publishGRGBtn:"Publicera",GRGLayerName:"Publicerat GRG-lagernamn",invalidGRGLayerName:"Lagrets namn f\u00e5r endast inneh\u00e5lla alfanumeriska tecken och understreck",missingGRGLayerName:"Du m\u00e5ste ange ett namn p\u00e5 GRG",publishWorskpaceError:"FEL: Fel vid \u00f6ppning av arbetskatalogen",publishingFailedLayerExists:"Publiceringen misslyckades: du har redan en geoobjekttj\u00e4nst som heter {0}. V\u00e4lj ett annat namn.",
checkService:"Kontrollera tj\u00e4nsten: {0}",createService:"Skapa tj\u00e4nst: {0}",unableToCreate:"Det gick inte att skapa: {0}",addToDefinition:"L\u00e4gg till i definition: {0}",successfullyPublished:"Webblagret har publicerats{0}Hantera webblagret",userRole:"Det g\u00e5r inte att skapa tj\u00e4nsten eftersom anv\u00e4ndaren inte har beh\u00f6righet",createGRGBtn:"Skapa GRG",clearGRGBtn:"Avmarkera",labelFormat:"Etikettformat",helpIconTooltip:"Z: Tecken f\u00f6r rutn\u00e4tszon (GZD)\nS: 100\u00a0000 meter identifiering av rutn\u00e4tskvadrat (GSID)\nX: \u00d6stlig avvikelse (X-koordinat)\nY: Nordlig avvikelse (Y-koordinat)\n\nExempel:\nZSXY \u00e4r 15SWC8081751205\nZS X,Y \u00e4r 15SWC 80817,51205",
addPointToolTip:"L\u00e4gg till GRG-ursprung",cellWidth:"Cellvidd (x)",cellHeight:"Cellh\u00f6jd (y)",invalidNumberMessage:"Det angivna v\u00e4rdet \u00e4r ogiltigt",invalidRangeMessage:"V\u00e4rdet m\u00e5ste vara st\u00f6rre \u00e4n 0",gridAngleInvalidRangeMessage:"V\u00e4rdet m\u00e5ste vara mellan -89,9 och 89,9",formatIconTooltip:"Formatinmatning",coordInputLabel:"GRG-ursprung (DD)",setCoordFormat:"Ange koordinatstr\u00e4ng",prefixNumbers:'L\u00e4gg till prefixet "+/-" f\u00f6r positiva och negativa tal',
cancelBtn:"Avbryt",applyBtn:"Verkst\u00e4ll",comfirmInputNotation:"Bekr\u00e4fta inmatningsnotation",notationsMatch:"notationer matchar inmatningen. Bekr\u00e4fta vilka du vill anv\u00e4nda:",numberOfCellsHorizontal:"# Horisontella celler",numberOfCellsVertical:"# Vertikala celler",gridAngle:"Rotation f\u00f6r rutn\u00e4t",tooManyCellsErrorMessage:"Du f\u00f6rs\u00f6ker skapa ett rutn\u00e4t som best\u00e5r av fler \u00e4n 2\u00a0000 celler. Vi rekommenderar att du minskar antalet celler som ska skapas genom att \u00e4ndra rutn\u00e4tets storlek eller omr\u00e5de.",
missingParametersMessage:"\x3cp\x3eFormul\u00e4ret f\u00f6r att skapa GRG inneh\u00e5ller saknade eller ogiltiga parametrar. S\u00e4kerst\u00e4ll att:\x3c/p\x3e\x3cul\x3e\x3cli\x3eEtt GRG-omr\u00e5de har ritats.\x3c/li\x3e\x3cli\x3eCellens vidd och h\u00f6jd inneh\u00e5ller giltiga v\u00e4rden.\x3c/li\x3e\x3c/ul\x3e",missingOriginParametersMessage:"\x3cp\x3eFormul\u00e4ret f\u00f6r att skapa GRG inneh\u00e5ller saknade eller ogiltiga parametrar. S\u00e4kerst\u00e4ll att:\x3c/p\x3e\x3cul\x3e\x3cli\x3eEtt GRG-ursprung har angetts.\x3c/li\x3e\x3cli\x3eInmatningarna f\u00f6r tid, hastighet och vinkel inneh\u00e5ller giltiga v\u00e4rden.\x3c/li\x3e\x3c/ul\x3e",
invalidWidthHeightParametersMessage:"\x3cp\x3eFormul\u00e4ret f\u00f6r att skapa GRG inneh\u00e5ller saknade eller ogiltiga parametrar. S\u00e4kerst\u00e4ll att inmatningarna av cellens vidd och h\u00f6jd inneh\u00e5ller giltiga v\u00e4rden.\x3c/p\x3e",invalidHorizontalVerticalParametersMessage:"\x3cp\x3eFormul\u00e4ret f\u00f6r att skapa GRG inneh\u00e5ller saknade eller ogiltiga parametrar. S\u00e4kerst\u00e4ll att inmatningarna f\u00f6r antalet horisontella och vertikala celler inneh\u00e5ller giltiga v\u00e4rden.\x3c/p\x3e",
drawPointToolTip:"Klicka f\u00f6r att l\u00e4gga till en GRG-ursprungspunkt",missingLayerNameMessage:"Du m\u00e5ste ange ett giltigt lagernamn innan du kan publicera",parseCoordinatesError:"Det gick inte att tolka koordinaterna. Kontrollera din inmatning.",grgPolarRegionError:"GRG-utbredningen ligger inom en polarregion. Cellerna som hamnar inom polarregionen skapas inte.",grgPolarOriginError:"GRG-ursprungspunkten kan inte ligga inom en polarregion n\u00e4r en GRG skapas av referenssystemet.",deleteBtn:"Ta bort",
DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Decimalgrader \u2013 Latitud/longitud",DDLongLatNotation:"Decimalgrader \u2013 Longitud/latitud",DDMLatLongNotation:"Grader decimalminuter \u2013 Latitud/longitud",DDMLongLatNotation:"Grader decimalminuter \u2013 Longitud/latitud",DMSLatLongNotation:"Grader minuter sekunder \u2013 Latitud/longitud",DMSLongLatNotation:"Grader minuter sekunder \u2013 Longitud/latitud",
GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM \u2013 Bandbokstav",UTMHemNotation:"UTM \u2013 Halvklot (N/S)",_localized:{}}});