// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/GriddedReferenceGraphic/nls/strings":{_widgetLabel:"Gr\u00e1fico de Refer\u00eancia em Grelha",newGRGFromAreaButtonLabel:"Definir uma Grelha a partir de uma \u00c1rea",newGRGFromPointButtonLabel:"Definir uma Grelha a partir de um Ponto",newGRGFromAreaTitle:"Definir uma Grelha a partir de uma \u00c1rea",newGRGFromPointTitle:"Definir uma Grelha a partir de um Ponto",newGRGBySizeButtonLabel:"Por Dimens\u00e3o",newGRGFromRefSystemButtonLabel:"Por Sistema de Refer\u00eancia",newGRGByTimeLabel:"Por Tempo e Velocidade",
newGRGFromNonStandardButtonLabel:"Definir grelha n\u00e3o-padr\u00e3o",newGRGAreaBySizeTitle:"GRG a partir de uma \u00c1rea por Dimens\u00e3o",newGRGAreaBySizeDefineAreaLabel:"\u00c1rea CRG",addGRGAreaPolygonToolTip:"Desenhar \u00c1rea GRG utilizando pol\u00edgono",addGRGAreaExtentToolTip:"Desenhar \u00c1rea GRG utilizando extens\u00e3o",rotation:"Rota\u00e7\u00e3o da Grelha",numberRowsColumnsLabel:"Definir n\u00famero de linhas e de colunas",newGRGAreaByRefSystemTitle:"GRG a partir de um Sistema de \u00c1rea por Refer\u00eancia",
gridSize:"Tamanho da Grelha",UTMZoneandBand:"Zona da Grelha","100000m":"100000 metros","10000m":"10000 metros","1000m":"1000 metros","100m":"100 metros","10m":"10 metros",clipGrid:"Recortar Grelha para \u00c1rea GRG",newGRGAreaFromNonStandardTitle:"Novo NRG",newGRGPointBySizeTitle:"GRG a partir de Ponto por Dimens\u00e3o",newGRGPointByRefSystemTitle:"GRG a partir de Sistema de Ponto por Refer\u00eancia",newGRGPointByTimeTitle:"GRG a partir de Ponto utilizando Tempo e Velocidade",time:"Tempo",rate:"Velocidade",
hours:"Horas",minutes:"Minutos",seconds:"Segundos",ftPerSec:"P\u00e9s / segundo",ftPerHour:"P\u00e9s / hora",kmPerSec:"Quil\u00f3metros / segundo",kmPerHour:"Quil\u00f3metros / hora",mPerSec:"Metros / segundo",mPerHour:"Metros / hora",miPerSec:"Milhas / segundo",miPerHour:"Milhas / hora",nMPerSec:"Milhas N\u00e1uticas / segundo",nMPerHour:"Milhas N\u00e1uticas / hora",settingsTitle:"Configura\u00e7\u00f5es",labelSettingsLabel:"Defini\u00e7\u00f5es de R\u00f3tulo",labelSettingsButtonLabel:"Configurar Defini\u00e7\u00f5es de R\u00f3tulo",
gridSettingsLabel:"Defini\u00e7\u00f5es de Grelha",gridSettingsButtonLabel:"Configurar Defini\u00e7\u00f5es de Grelha",transparency:"Transpar\u00eancia",labelStyle:"Estilo do R\u00f3tulo",font:"Fonte",textSize:"Tamanho do Texto",textColor:"Cor do Texto",halo:"Halo",show:"Exibir",lockSettings:"As defini\u00e7\u00f5es foram bloqueadas pelo propriet\u00e1rio da aplica\u00e7\u00e3o",gridSettings:{cellShape:"Formato de C\u00e9lulas",cellUnits:"Unidades de C\u00e9lulas",cellOutline:"Defini\u00e7\u00f5es de Contorno de C\u00e9lulas",
cellFill:"Defini\u00e7\u00f5es de Preenchimento de C\u00e9lulas",gridReferenceSystem:"Sistema de Refer\u00eancia",gridDatum:"Datum: WGS84",labelStartPosition:"Origem de R\u00f3tulo",labelType:"Tipo de R\u00f3tulo",labelDirection:"Dire\u00e7\u00e3o de R\u00f3tulo",gridOrigin:"Origem de R\u00f3tulo","default":"Ret\u00e2ngulo",hexagon:"Hex\u00e1gono",miles:"Milhas",kilometers:"Quil\u00f3metros",feet:"P\u00e9s",meters:"Metros",yards:"Jardas","nautical-miles":"Milhas N\u00e1uticas",lowerLeft:"Inferior Esquerda",
lowerRight:"Inferior Direita",upperLeft:"Superior Esquerda",upperRight:"Superior Direita",center:"Centrar",alphaNumeric:"Alfanum\u00e9rico",alphaAlpha:"Alfa-Alfa",numeric:"Num\u00e9rico",horizontal:"Horizontal",vertical:"Vertical",MGRS:"MGRS",USNG:"USNG",showLabels:"Exibir R\u00f3tulos"},publishTitle:"Publicar GRG no Portal",publishGRGBtn:"Publicar",GRGLayerName:"Nome de Camada GRG Publicada",invalidGRGLayerName:"O nome da camada pode apenas conter caracteres alfanum\u00e9ricos e tra\u00e7os inferiores.",
missingGRGLayerName:"Tem de introduzir um nome para o GRG",publishWorskpaceError:"ERRO: Erro ao abrir workspace",publishingFailedLayerExists:"Publica\u00e7\u00e3o Falhou: J\u00e1 possui um servi\u00e7o de elementos denominado {0}. Por favor, escolha outro nome.",checkService:"Verificar Servi\u00e7o: {0}",createService:"Criar Servi\u00e7o: {0}",unableToCreate:"N\u00e3o \u00e9 poss\u00edvel criar: {0}",addToDefinition:"Adicionar a defini\u00e7\u00e3o: {0}",successfullyPublished:"Camada web publicada com sucesso{0}Gerir a camada web",
userRole:"N\u00e3o \u00e9 poss\u00edvel criar o servi\u00e7o porque o utilizador n\u00e3o possui permiss\u00f5es",createGRGBtn:"Criar GRG",clearGRGBtn:"Apagar",labelFormat:"Formato de R\u00f3tulo",helpIconTooltip:"Z: Designador de Zona de Grelha (GZD)\nS: Identifica\u00e7\u00e3o de Quadrado de Grelha de 100,000 metros (GSID)\nX: Avan\u00e7o para Este (Coordenada X)\nY: Avan\u00e7o para Norte (Coordenada Y)\n\nExamples:\nZSXY is 15SWC8081751205\nZS X,Y is 15SWC 80817,51205",addPointToolTip:"Adicionar Origem GRG",
cellWidth:"Largura de C\u00e9lula (x)",cellHeight:"Altura de C\u00e9lula (y)",invalidNumberMessage:"O valor introduzido n\u00e3o \u00e9 v\u00e1lido",invalidRangeMessage:"O valor tem de ser maior do que 0",gridAngleInvalidRangeMessage:"O valor tem de encontrar-se entre -89,9 e 89,9.",formatIconTooltip:"Introdu\u00e7\u00e3o de Formato",coordInputLabel:"Origem GRG (DD)",setCoordFormat:"Definir String de Formata\u00e7\u00e3o de Coordenadas",prefixNumbers:"Adicionar o prefixo \u2018+/-\u2019 a n\u00fameros positivos e negativos",
cancelBtn:"Cancelar",applyBtn:"Aplicar",comfirmInputNotation:"Confirmar Nota\u00e7\u00e3o de Entrada",notationsMatch:"nota\u00e7\u00f5es correspondem \u00e0 sua entrada, por favor, confirme as que pretende utilizar:",numberOfCellsHorizontal:"# C\u00e9lulas Horizontais",numberOfCellsVertical:"# C\u00e9lulas Vericais",gridAngle:"Rota\u00e7\u00e3o da Grelha",tooManyCellsErrorMessage:"Est\u00e1 a tentar criar uma grelha que cont\u00e9m mais do que 2000 c\u00e9lulas. \u00c9 aconselh\u00e1vel reduzir o n\u00famero de c\u00e9lulas a criar, alterando o tamaho da grelha ou a \u00e1rea da grelha.",
missingParametersMessage:"\x3cp\x3eA cria\u00e7\u00e3o do formul\u00e1rio GRG tem par\u00e2metros em falta ou inv\u00e1lidos, Por favor, assegure que:\x3c/p\x3e\x3cul\x3e\x3cli\x3eFoi desenhada uma \u00e1rea GRG.\x3c/li\x3e\x3cli\x3eA largura e altura de c\u00e9lula cont\u00eam valores v\u00e1lidos.\x3c/li\x3e\x3c/ul\x3e",missingOriginParametersMessage:"\x3cp\x3eA cria\u00e7\u00e3o do formul\u00e1rio GRG tem par\u00e2metros em falta ou inv\u00e1lidos, Por favor, assegure que:\x3c/p\x3e\x3cul\x3e\x3cli\x3eFoi definida uma origem GRG.\x3c/li\x3e\x3cli\x3eAs entradas de tempo, velocidade e \u00e2ngulo cont\u00eam valores v\u00e1lidos.\x3c/li\x3e\x3c/ul\x3e",
invalidWidthHeightParametersMessage:"\x3cp\x3eA cria\u00e7\u00e3o do formul\u00e1rio GRG tem par\u00e2metros em falta ou inv\u00e1lidos. Por favor, assegure que as entradas de largura e altura de c\u00e9lula cont\u00eam valores v\u00e1lidos.\x3c/p\x3e",invalidHorizontalVerticalParametersMessage:"\x3cp\x3eA cria\u00e7\u00e3o do formul\u00e1rio GRG tem par\u00e2metros em falta ou inv\u00e1lidos. Por favor, assegure que o n\u00famero de entradas horizontais e verticais de c\u00e9lulas cont\u00eam valores v\u00e1lidos.\x3c/p\x3e",
drawPointToolTip:"Clique para adicionar ponto de origem GRG",missingLayerNameMessage:"Tem de introduzir um nome de camada v\u00e1lido antes de poder publicar",parseCoordinatesError:"N\u00e3o foi poss\u00edvel analisar as coordenadas. Por favor, verifique a entrada.",grgPolarRegionError:"A extens\u00e3o do GRG abrange uma regi\u00e3o polar. As c\u00e9lulas localizadas na regi\u00e3o polar n\u00e3o ser\u00e3o criadas.",grgPolarOriginError:"O ponto de origem GRG n\u00e3o pode encontrar-se numa regi\u00e3o polar ao criar um Sistema GRG por Refer\u00eancia.",
deleteBtn:"Excluir",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Graus Decimais - Latitude/Longitude",DDLongLatNotation:"Graus Decimais  - Longitude/Latitude",DDMLatLongNotation:"Graus Decimais Minutos - Latitude/Longitude",DDMLongLatNotation:"Graus Decimais Minutos - Longitude/Latitude",DMSLatLongNotation:"Graus Minutos Segundos - Latitude/ Longitude",DMSLongLatNotation:"Graus Minutos Segundos - Longitude/Latitude",
GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - Letra de Banda",UTMHemNotation:"UTM - Hemisf\u00e9rio (N/S)",_localized:{}}});