// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Izberite orodja za analizo za uporabo v pripomo\u010dku.",graphicalDisplay:"Grafi\u010dni prikaz",toolSetting:"Nastavite podrobnosti orodja",toolLabel:"Prikazno ime orodja",showHelpTip:"Poka\u017ei povezave za pomo\u010d v pripomo\u010dku",showCurrentMapExtent:"Poka\u017ei mo\u017enost za uporabo trenutnega obsega karte",showCredits:"Prika\u017ei mo\u017enost \x3cb\x3ePoka\u017ei kredite\x3c/b\x3e",saveAsFeatureService:"Shrani rezultat na ra\u010dun uporabnika",
showReadyToUseLayers:"Poka\u017ei sloje, \u017ee pripravljene za uporabo, iz zbirke Living Atlas ArcGIS Online",toolNotAvailable:"To orodje ni na voljo, ker karte ne vsebujejo zahtevanih geoobjektnih slojev.",aggregatePoints:"Agregacija to\u010dk",aggregatePointsUsage:"Agregiraj to\u010dke v poligone",calculateDensity:"Izra\u010dunaj gostoto",calculateDensityUsage:"Ustvarite karto gostote iz to\u010dkovnih ali linijskih geoobjektov za prikaz \u0161irjenja znanih koli\u010din nekaterih pojavov (predstavljenih kot atributi to\u010dk ali linij) na karti.",
connectOriginsToDestinations:"Pove\u017ei izhodi\u0161\u010da s cilji",connectOriginsToDestinationsUsage:"Meri potovalni \u010das ali razdaljo med pari to\u010dk.",createBuffers:"Ustvari obrise",createBuffersUsage:"Ustvarite obrise poligonov iz vhodnih geoobjektov.",createDriveTimeAreas:"Ustvari obmo\u010dja \u010dasa vo\u017enje",createDriveTimeAreasUsage:"Ustvarite poligone \u010dasa vo\u017enje (ali razdalje vo\u017enje) okoli vhodnih to\u010dk za dane vrednosti \u010dasa vo\u017enje.",createViewshed:"Ustvari obmo\u010dja vidnosti",
createViewshedUsage:"Ustvarite obmo\u010dja, ki so vidna glede na navedene lokacije.",createWatersheds:"Ustvari razvodje",createWatershedsUsage:"Ustvarite prispevna obmo\u010dja glede na podane to\u010dke.",deriveNewLocations:"Tvori nove lokacije",deriveNewLocationsUsage:"Tvori nove geoobjekte iz vhodnih slojev, ki ustrezajo navedeni poizvedbi",dissolveBoundaries:"Razgradi meje",dissolveBoundariesUsage:"Razgradi poligone, ki se prekrivajo ali imajo skupno mejo.",enrichLayer:"Obogati sloj",enrichLayerUsage:"Obogatite vhodne geoobjekte z demografskimi, poslovnimi in drugimi dejstvi iz okolice.",
extractData:"Ekstrahiraj podatke",extractDataDesc:"Ekstrahiraj podatke iz enega ali ve\u010d slojev znotraj danega obsega",findCentroids:"Najdi centroide",findCentroidsUsage:"Poi\u0161\u010de reprezentativno sredi\u0161\u010de (centroid) za vsak vhodni mnogoto\u010dkovni, linijski ali poligonski geoobjekt.",findExistingLocations:"Najdi lokacije",findExistingLocationsUsage:"Izberite geoobjekte v vhodnem sloju, ki ustrezajo atributnim in/ali prostorskim poizvedbam.",findHotSpots:"Najdi vro\u010de to\u010dke",
findHotSpotsUsage:"Najdite statisti\u010dno zna\u010dilne gru\u010de vhodnih geoobjektov in visokih/nizkih to\u010dk.",findNearest:"Najdi najbli\u017eje",findNearestUsage:"Za vsak geoobjekt na vhodnem sloju najdite najbli\u017eji geoobjekt na drugem sloju",findPointClusters:"Najdi gru\u010de to\u010dk",findPointClustersUsage:"To orodje zazna obmo\u010dja, kjer so to\u010dke koncentrirane in lo\u010dene po poligonih, ki so prazni ali razpr\u0161eni.",findSimilarLocations:"Najdi podobne lokacije",findSimilarLocationsUsage:"Izmerite podobnost kandidatov za lokacije na eni ali ve\u010d referen\u010dnih lokacijah.",
geocodeLocations:"Geokodiranje lokacij iz tabele",geocodeLocationsUsage:"Priro\u010den na\u010din za geokodiranje velikih tabel in datotek z naslovi v to\u010dke",interpolatePoints:"Interpoliraj to\u010dke",interpolatePointsUsage:"Predvidite vrednosti na novih lokacijah glede na merjene vrednosti zbirk to\u010dk.",mergeLayers:"Zdru\u017ei sloje",mergeLayersUsage:"Zdru\u017eite geoobjekte iz ve\u010d slojev v nov sloj",overlayLayers:"Prekrij sloje",overlayLayersUsage:"Zdru\u017eite ve\u010d slojev v enojen sloj z ohranjenimi informacijami iz izvornih slojev.",
planRoutes:"Na\u010drtuj poti",planRoutesUsage:"Dolo\u010dite, kako u\u010dinkovito razdeliti naloge med mobilno delovno silo.",summarizeCenterAndDispersion:"Povzemi sredi\u0161\u010de in disperzijo",summarizeCenterAndDispersionUsage:"Uporabite to\u010dkovne geoobjekte, da izra\u010dunate sredi\u0161\u010dni geoobjekt, sredi\u0161\u010de povpre\u010dja, sredi\u0161\u010de mediane ali elipso (razporeditev).",summarizeNearby:"Povzemi v bli\u017eini",summarizeNearbyUsage:"Za vsak geoobjekt na vhodnem sloju povzemite podatke znotraj razdalje od geoobjektov na drugem sloju.",
summarizeWithin:"Povzemi znotraj",summarizeWithinUsage:"Za vsak poligon na vhodnem poligonskem sloju povzemite podatke, locirane znotraj poligona, od geoobjektov na drugem sloju.",traceDownstream:"Sledi dolvodno",traceDownstreamUsage:"Izra\u010duna linijo vodnega toka dolvodno od podanih lokacij.",allowToExport:"Dovoli izvoz rezultatov",joinFeatures:"Spoji geoobjekte",joinFeaturesUsage:"Orodje za Spajanje geoobjektov bo pripojilo atribute iz enega sloja ali tabele z drugim glede na prostorske ali atributne relacije. Za pripojene geoobjekte je mogo\u010de izra\u010dunati tudi statistiko.",
includeRouteLayer:"Vklju\u010di usmerjevalne sloje",findOutliers:"Najdi osamelce",findOutliersUsage:"Orodje Najdi osamelce izra\u010duna ali obstajajo statisti\u010dno zna\u010dilni osamelci v prostorskem vzorcu va\u0161ih podatkov.",_localized:{}}});