// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"N\u00e4yt\u00e4 tai piilota sarakkeet",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Ominaisuustaulu",_featureAction_ShowRelatedRecords:"N\u00e4yt\u00e4 liittyv\u00e4t tietueet",_featureAction_ViewInTable:"N\u00e4yt\u00e4 ominaisuustaulukossa",ok:"OK",cancel:"Peruuta",unsupportQueryWarning:"Karttatason on tuettava kyselytoimintoa, jotta karttatason voi n\u00e4ytt\u00e4\u00e4 Ominaisuustietotaulu-pienoisohjelmassa. Varmista, ett\u00e4 palvelun kyselyominaisuus on k\u00e4yt\u00f6ss\u00e4.",
exportMessage:"Vie dataa CSV-tiedostoon?",exportFiles:"Vie CSV-tiedostoon",exportSelected:"Vie valittu kohde CSV-muotoon",exportAll:"Vie kaikki CSV-muotoon",options:"Valinnat",zoomto:"Tarkenna kohteeseen",highlight:"Korosta grafiikkaa",selectAll:"Valitse tietueita kaikilta sivuilta",selectPage:"Valitse tietueita nykyiselt\u00e4 sivulta",clearSelection:"Tyhjenn\u00e4 valinnat",filter:"Suodata",setFilterTip:"M\u00e4\u00e4rit\u00e4 suodattimet oikein.",noFilterTip:"Jos suodatinlausekkeita ei m\u00e4\u00e4ritet\u00e4, kyselyteht\u00e4v\u00e4 luetteloi kaikki m\u00e4\u00e4ritetyn tietol\u00e4hteen kohteet.",
filterByExtent:"Suodata kartan laajuuden mukaan",showSelectedRecords:"N\u00e4yt\u00e4 valitut tietueet",showAllRecords:"N\u00e4yt\u00e4 kaikki tietueet",showRelatedRecords:"N\u00e4yt\u00e4 liittyv\u00e4t tietueet",noRelatedRecords:"Liittyvi\u00e4 tietueita ei l\u00f6ytynyt",highlightAllRecords:"Korosta kaikki kartan tietueet",attachmentColumn:"Valokuvat ja tiedostot",refresh:"P\u00e4ivit\u00e4",features:"kohteet",records:"tietueet",selected:"valitut",transparent:"L\u00e4pin\u00e4kyv\u00e4 tila",indicate:"Paikanna valinta",
columns:"N\u00e4yt\u00e4/piilota sarakkeet",selectionSymbol:"Valintasymboli",closeMessage:"Piilota taulukko (laajenna se uudelleen alareunasta)",dataNotAvailable:"Data ei ole k\u00e4ytett\u00e4viss\u00e4!\x3cbr\x3eYrit\u00e4 uudelleen napsauttamalla [P\u00e4ivit\u00e4]-painiketta.",openTableTip:"Avaa ominaisuustietotaulu",closeTableTip:"Piilota ominaisuustietotaulukko",sortAsc:"Lajittele nousevasti",sortDes:"Lajittele laskevasti",statistics:"Tilastotiedot",attachments:"Liitteet",files:"tiedostot",
keepRichTextLabel:"S\u00e4ilyt\u00e4 RTF-muoto",whatsThis:"Mik\u00e4 t\u00e4m\u00e4 on?",richTextMessage:{explanatoryText:{line1:"${layerName} sis\u00e4lt\u00e4\u00e4 seuraavat RTF-kent\u00e4t: ",line2:" jotka voivat sis\u00e4lt\u00e4\u00e4 tekstinmuotoilutyylej\u00e4, kuten fontteja, v\u00e4rej\u00e4 tai tekstin kokoja.",line3:"Kun tiedosto vied\u00e4\u00e4n CSV-muotoon, muotoilutyylit s\u00e4ilytet\u00e4\u00e4n HTML-tunnisteina. Voit m\u00e4\u00e4ritt\u00e4\u00e4, ettei RTF-muotoja s\u00e4ilytet\u00e4, poistamalla S\u00e4ilyt\u00e4 RTF-muoto -valintaruudun valinnan."},
example:{label:"Esimerkki:",scenarios:{first:"vied\u00e4\u00e4n oletusarvoisesti seuraavana tekstin\u00e4:",second:"ja seuraavana tekstin\u00e4 ilman RTF-muotoa:"}}},noTablesAvailable:"N\u00e4ytett\u00e4vi\u00e4 taulukoita ei ole.",checkConfigutationToSelectLayers:"Valitse karttatasot siirtym\u00e4ll\u00e4 pienoisohjelman asetussivulle.",checkLayerListToSelectLayers:"Ominaisuustietotaulu on synkronoitu kartan n\u00e4kyvien karttatasojen kanssa. Voit vaihtaa karttatasojen n\u00e4kyvyytt\u00e4 pienoisohjelman, kuten karttatasojen luettelon, avulla.",
_localized:{}}});