// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Lihavointi",copy:"Kopioi",cut:"Leikkaa","delete":"Poista",indent:"Sisenn\u00e4",insertHorizontalRule:"Vaakasuuntainen viiva",insertOrderedList:"Numeroitu luettelo",insertUnorderedList:"Numeroimaton luettelo",italic:"Kursivointi",justifyCenter:"Tasaus keskelle",justifyFull:"Tasaus",justifyLeft:"Tasaus vasemmalle",justifyRight:"Tasaus oikealle",outdent:"Ulonna",paste:"Liit\u00e4",redo:"Tee uudelleen",removeFormat:"Poista muotoilu",selectAll:"Valitse kaikki",
strikethrough:"Yliviivaus",subscript:"Alennettu",superscript:"Korotettu",underline:"Alleviivaus",undo:"Kumoa",unlink:"Poista linkki",createLink:"Luo linkki",toggleDir:"Vaihda suuntaa",insertImage:"Lis\u00e4\u00e4 kuva",insertTable:"Lis\u00e4\u00e4 taulukko/muokkaa taulukkoa",toggleTableBorder:"Ota taulukon kehys k\u00e4ytt\u00f6\u00f6n/poista kehys k\u00e4yt\u00f6st\u00e4",deleteTable:"Poista taulukko",tableProp:"Taulukon ominaisuudet",htmlToggle:"HTML-l\u00e4hde",foreColor:"Edustav\u00e4ri",hiliteColor:"Taustav\u00e4ri",
plainFormatBlock:"Kappaletyyli",formatBlock:"Kappaletyyli",fontSize:"Fonttikoko",fontName:"Fontin nimi",tabIndent:"Sarkainsisennys",fullScreen:"Vaihda koko n\u00e4ytt\u00f6",viewSource:"N\u00e4yt\u00e4 HTML-l\u00e4hde",print:"Tulosta",newPage:"Uusi sivu",systemShortcut:'Toiminto "${0}" on k\u00e4ytett\u00e4viss\u00e4 selaimessa vain n\u00e4pp\u00e4imist\u00f6n pikatoiminnolla. K\u00e4yt\u00e4 seuraavaa: ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Koko",
fontName:"Fontti",formatBlock:"Muotoile",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Ei mit\u00e4\u00e4n",p:"Kappale",h1:"Otsikko",h2:"Alatason otsikko",h3:"Alimman tason otsikko",pre:"Esimuotoiltu",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Esikatselu",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Etsi:",findTooltip:"Anna etsitt\u00e4v\u00e4 teksti",
replaceLabel:"Korvaa seuraavalla:",replaceTooltip:"Anna korvaava teksti",findReplace:"Etsi ja korvaa",matchCase:"Sama kirjainkoko",matchCaseTooltip:"Sama kirjainkoko",backwards:"Taaksep\u00e4in",backwardsTooltip:"Etsi teksti\u00e4 taaksep\u00e4in",replaceAllButton:"Korvaa kaikki",replaceAllButtonTooltip:"Korvaa kaikki teksti",findButton:"Etsi",findButtonTooltip:"Etsi teksti",replaceButton:"Korvaa",replaceButtonTooltip:"Korvaa teksti",replaceDialogText:"Korvattu ${0} esiintym\u00e4\u00e4.",eofDialogText:"Viimeinen esiintym\u00e4 ${0}",
eofDialogTextFind:"l\u00f6ytynyt",eofDialogTextReplace:"korvattu",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Liit\u00e4 Word-ohjelmasta",instructions:"Liit\u00e4 sis\u00e4lt\u00f6 Word-tiedostosta alla olevaan tekstikentt\u00e4\u00e4n. Kun lis\u00e4tt\u00e4v\u00e4 sis\u00e4lt\u00f6 on mielest\u00e4si valmis, napsauta Liit\u00e4-painiketta. Voit peruuttaa lis\u00e4yksen napsauttamalla Peruuta-painiketta.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Lis\u00e4\u00e4 ankkuri",
title:"Ankkurin ominaisuudet",anchor:"Nimi:",text:"Kuvaus:",set:"Aseta",cancel:"Peruuta",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/RelatedTableCharts/setting/nls/strings":{chartSettingLabel:"Kaavion asetukset",addNewLabel:"Lis\u00e4\u00e4 uusi",generalSettingLabel:"Yleiset asetukset",searchSourceSettingLabel:"Haun l\u00e4hteen asetukset",layerChooser:{title:"Valitse kaavion lis\u00e4tt\u00e4v\u00e4 karttataso",selectPolygonLayerLabel:"Valitse karttataso",
selectPolygonLayerHintText:"Vihje: jos m\u00e4\u00e4rit\u00e4t useita kaavioita, karttatasojen on oltava samaa geometriatyyppi\u00e4",selectRelatedTableLayerLabel:"Valitse karttatasoon liittyv\u00e4 taulukko",selectRelatedTableLayerHintText:"Vihje: vain numerokentti\u00e4 sis\u00e4lt\u00e4v\u00e4 taulukot n\u00e4ytet\u00e4\u00e4n",errorInSelectingPolygonLayer:"Valitse karttataso, jossa on siihen liittyv\u00e4 pistekarttataso.",errorInSelectingRelatedLayer:"Valitse kelvollinen karttatasoon liittyv\u00e4 taulukko tai karttataso.",
polygonLayerNotHavingRelationships:"Valitussa karttatasossa ei ole yht\u00e4\u00e4n liittyv\u00e4\u00e4 taulukkoa tai karttatasoa."},ChartSetting:{sectionTitle:"Osan otsikko",sectionTitleHintText:"Vihje: n\u00e4ytet\u00e4\u00e4n osan yl\u00e4tunnisteen otsikossa",chartTitle:"Kaavion otsikko",chartTitleHintText:"Vihje: n\u00e4ytet\u00e4\u00e4n keskitettyn\u00e4 kaavion yl\u00e4reunassa",chartDescription:"Kuvaus",chartDescriptionHintText:"Vihje: n\u00e4ytet\u00e4\u00e4n kaavion alapuolella",chartType:"Kaavion tyyppi",
barChart:"Palkkikaavio",pieChart:"Ympyr\u00e4kaavio",polarChart:"Napakaavio",lineChart:"Viivakaavio",dataSeriesField:"Aineistosarjakentt\u00e4",lineDataSeriesField:"Arvokentt\u00e4",labelField:"Tunnustekstikentt\u00e4",lineLabelSeriesField:"J\u00e4rjestyskentt\u00e4",chartColor:"Kaavion v\u00e4ri",singleColor:"Yksitt\u00e4inen v\u00e4ri",colorByTheme:"V\u00e4rit\u00e4 teemoittain",colorByFieldValue:"V\u00e4rit\u00e4 kent\u00e4n arvon mukaan",xAxisTitle:"X-akselin otsikko",xAxisHintText:"Vihje: X-akselin otsikko",
yAxisTitle:"Y-akselin otsikko",yAxisHintText:"Vihje: Y-akselin otsikko",fieldColorLabel:"Tunnusteksti",fieldColorColor:"V\u00e4ri",defaultFieldSelectLabel:"Valitse",errMsgFieldValuesNotFound:"Valitun kent\u00e4n arvoja ei l\u00f6ydy",errMsgSectionTitle:"Anna osan otsikko",errMsgFieldByValue:"Valitse v\u00e4ri kent\u00e4n arvon perusteella",errMsgDataSeriesField:"Valitse arvokentt\u00e4",settingTabTitle:"Asetus",layoutTabTitle:"Asettelu",polarChartSelectFieldsHintText:"Vihje: valitse kent\u00e4t napakaavion luomista varten",
visibilityText:"N\u00e4kyvyys",fieldNameText:"Kent\u00e4n nimi",aliasNameText:"Alias",errMsgPolarFieldsRequired:"Valitse v\u00e4hint\u00e4\u00e4n kolme kentt\u00e4\u00e4 napakaavion luomista varten",polarChartPolygonFillLabel:"T\u00e4ytt\u00f6alue",polarChartPolygonFillHintText:"Vihje: n\u00e4yt\u00e4 aluekohteilla t\u00e4ytetty napakaavio valitsemalla valintaruutu",viewLayoutLabel:"Asettelu",setValueFields:"M\u00e4\u00e4rit\u00e4 arvokent\u00e4t",layoutSeriesLabel:"Sarja",ThemeSelector:{themeAdobebricks:"Adobebricks",
themeAlgae:"Lev\u00e4",themeBahamation:"Bahamation",themeBlueDusk:"BlueDusk",themeCubanShirts:"CubanShirts",themeDesert:"Autiomaa",themeDistinctive:"Erikoislaatuinen",themeDollar:"Dollari",themeGrasshopper:"Hein\u00e4sirkka",themeGrasslands:"Ruohotasanko",themeGreySkies:"GreySkies",themeHarmony:"Harmonia",themeIndigoNation:"IndigoNation",themeIreland:"Ireland",themeMiamiNice:"MiamiNice",themeMinty:"Minttu",themePurpleRain:"PurpleRain",themeRoyalPurples:"RoyalPurples",themeSageToLime:"SageToLime",
themeTufte:"Tufte",themeWatersEdge:"WatersEdge",themeWetlandText:"Kosteikko",themePlotKitblue:"PlotKit.blue",themePlotKitcyan:"PlotKit.cyan",themePlotKitgreen:"PlotKit.green",themePlotKitorange:"PlotKit.orange",themePlotKitpurple:"PlotKit.purple",themePlotKitred:"PlotKit.red"}},GeneralSetting:{legendGeneralSettingText:"Yleiset asetukset",locationSymbolLabel:"Graafinen sijainnin symboli",locationSymbolHintText:"Vihje: k\u00e4ytet\u00e4\u00e4n osoitteen symbolin n\u00e4ytt\u00e4miseen ja sijainnin napsauttamiseen",
refreshIntervalLabel:"P\u00e4ivitysv\u00e4li",refreshIntervalHintText:"Vihje: K\u00e4ytet\u00e4\u00e4n kaavioiden p\u00e4ivitt\u00e4miseen t\u00e4m\u00e4n aikav\u00e4lin perusteella. M\u00e4\u00e4rit\u00e4 arvo v\u00e4lilt\u00e4 1\u20131\u00a0440 minuuttia",errMsgRefreshInterval:"M\u00e4\u00e4rit\u00e4 p\u00e4ivitysv\u00e4liksi 0\u20131\u00a0440 minuuttia",symbolPickerPreviewText:"Esikatselu:",showToolToSelectLabel:"M\u00e4\u00e4rit\u00e4 sijainti -painike",showToolToSelectHintText:"Vinkki: Ota k\u00e4ytt\u00f6\u00f6n painike sijainnin m\u00e4\u00e4ritt\u00e4miseksi kartalla sen sijaan, ett\u00e4 sijainti m\u00e4\u00e4ritet\u00e4\u00e4n aina karttaa napsautettaessa"},
searchSourceSetting:{searchSourceSettingTabTitle:"Hakul\u00e4hteen asetukset",searchSourceSettingTitle:"Hakul\u00e4hteen asetukset",searchSourceSettingTitleHintText:"Lis\u00e4\u00e4 ja m\u00e4\u00e4rit\u00e4 geokoodauspalveluja tai kohdekarttatasoja haun l\u00e4hteiksi. N\u00e4m\u00e4 m\u00e4\u00e4ritetyt l\u00e4hteet m\u00e4\u00e4ritt\u00e4v\u00e4t, mit\u00e4 hakuruudussa voi hakea",addSearchSourceLabel:"Lis\u00e4\u00e4 haun l\u00e4hde",featureLayerLabel:"Kohdekarttataso",geocoderLabel:"Geokooderi",
nameTitle:"Nimi",generalSettingLabel:"Yleinen asetus",allPlaceholderLabel:"Paikkamerkkiteksti haulle kaikkialta:",allPlaceholderHintText:"Vinkki: Anna teksti, joka n\u00e4ytet\u00e4\u00e4n paikkamerkkin\u00e4 kaikista karttatasoista ja geokooderista haettaessa",generalSettingCheckboxLabel:"N\u00e4yt\u00e4 l\u00f6ydetyn kohteen tai sijainnin ponnahdusikkuna",countryCode:"Maa- tai aluekoodit",countryCodeEg:"esim. ",countryCodeHint:"Jos j\u00e4t\u00e4t t\u00e4m\u00e4n arvon tyhj\u00e4ksi, ohjelma etsii kaikista maista ja kaikilta alueilta",
questionMark:"tulisi k\u00e4ytt\u00e4\u00e4?",searchInCurrentMapExtent:"Etsi vain nykyisest\u00e4 karttalaajuudesta",zoomScale:"Tarkennustaso",locatorUrl:"Geokooderin URL-osoite",locatorName:"Geokooderin nimi",locatorExample:"Esimerkki",locatorWarning:"T\u00e4t\u00e4 geokoodauspalvelun versiota ei tueta. Pienoisohjelma tukee geokoodauspalvelua 10.0 ja sit\u00e4 uudempia versioita.",locatorTips:"Ehdotukset eiv\u00e4t ole k\u00e4ytett\u00e4viss\u00e4, koska geokoodauspalvelu ei tue ehdotustoimintoa.",
layerSource:"Karttatason l\u00e4hde",setLayerSource:"M\u00e4\u00e4rit\u00e4 karttatason l\u00e4hde",setGeocoderURL:"M\u00e4\u00e4rit\u00e4 geokooderin URL-osoite",searchLayerTips:"Ehdotukset eiv\u00e4t ole k\u00e4ytett\u00e4viss\u00e4, koska kohdepalvelu ei tue sivutustoimintoa.",placeholder:"Muuttujan teksti",searchFields:"Hakukent\u00e4t",displayField:"N\u00e4ytt\u00f6kentt\u00e4",exactMatch:"Tarkka vastine",maxSuggestions:"Ehdotusten enimm\u00e4ism\u00e4\u00e4r\u00e4",maxResults:"Tulosten enimm\u00e4ism\u00e4\u00e4r\u00e4",
enableLocalSearch:"Ota k\u00e4ytt\u00f6\u00f6n paikallinen haku",minScale:"V\u00e4himm\u00e4ismittakaava",minScaleHint:"Kun kartan mittakaava on suurempi kuin t\u00e4m\u00e4 mittakaava, k\u00e4ytet\u00e4\u00e4n paikallista hakua",radius:"S\u00e4de",radiusHint:"M\u00e4\u00e4ritt\u00e4\u00e4 nykyisen kartan keskikohdan ymp\u00e4rill\u00e4 olevan alueen s\u00e4teen. S\u00e4teen avulla arvioidaan geokoodausehdokkaiden sijoitusta, jotta sijaintia l\u00e4hinn\u00e4 olevat ehdokkaat palautetaan ensin",meters:"Metri\u00e4",
setSearchFields:"M\u00e4\u00e4rit\u00e4 hakukent\u00e4t",set:"Aseta",fieldName:"Nimi",invalidSearchSources:"Virheelliset hakul\u00e4hteen asetukset",invalidUrlTip:"Sy\u00f6tetty URL-osoite ${URL} on virheellinen, tai se ei ole k\u00e4ytett\u00e4viss\u00e4."},_localized:{}}});