// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/string dojo/Deferred esri/lang esri/request dojo/_base/url esri/layers/TileInfo jimu/portalUtils esri/layers/ArcGISTiledMapServiceLayer esri/layers/ArcGISDynamicMapServiceLayer esri/layers/ArcGISImageServiceLayer esri/virtualearth/VETiledLayer esri/layers/OpenStreetMapLayer esri/layers/ImageParameters".split(" "),function(n,p,q,m,k,r,t,u,v,w,x,y,l,z,A){var c={TYPE:{BASE_MAP:"baseMap",ARCGIS_TILED_MAP:"tiledMapService",ARCGIS_DYNAMIC_MAP_SERVICE:"dynamicMapService",
ARCGIS_IMAGE_SERVICE:"imageService",OSM:"openStreetMap",BING_ROAD:"bingMapsRoad",BING_AERIAL:"bingMapsAerial",BING_HYBRID:"bingMapsHybrid"},createBaseLayer:function(a,b,f){var d=new m,g=null,h=a.url,e=a.type;a=a.veLayerInfo;e===c.TYPE.BASE_MAP?d.resolve({layer:"BaseMap"}):e===c.TYPE.ARCGIS_TILED_MAP?c.valid.isArcGISLayersValid(h,b,e).then(function(a){a&&!0===a.res?(g=new w(h),d.resolve({layer:g})):d.resolve({layer:null,err:a.err})},function(a){d.resolve({res:!1,err:a})}):e===c.TYPE.ARCGIS_DYNAMIC_MAP_SERVICE?
c.valid.isArcGISLayersValid(h,b,e).then(function(a){if(a&&!0===a.res){a=a.info;var b={};a&&a.supportedImageFormatTypes&&-1!==a.supportedImageFormatTypes.indexOf("PNG24")&&(b.imageParameters=new A,b.imageParameters.format="png24");g=new x(h,b);d.resolve({layer:g})}else d.resolve({layer:null,err:a.err})},function(a){d.resolve({res:!1,err:a})}):e===c.TYPE.ARCGIS_IMAGE_SERVICE?c.valid.isArcGISLayersValid(h,b,e).then(function(a){a&&!0===a.res?(g=new y(h,{}),d.resolve({layer:g})):d.resolve({layer:null,
err:a.err})},function(a){d.resolve({res:!1,err:a})}):e===c.TYPE.OSM?(g=new z(h,{}),d.resolve({layer:g})):e!==c.TYPE.BING_ROAD&&e!==c.TYPE.BING_AERIAL&&e!==c.TYPE.BING_HYBRID||!a?d.resolve({layer:null}):(b=c.layers.getBingMapKey(f),b&&a.isKeyInPortal||(b="__invalidKey",console.error("OverviewMap Error: BingMapsKey must be provided")),g=new l({bingMapsKey:b,mapStyle:c.layers._getVEStyle(e)}),d.resolve({layer:g}));return d},layers:{_getLayerInfoSR:function(a){return a.spatialReference||a.extent&&a.extent.spatialReference},
_getTileServers:function(a){var b=[],c=new t(a.url);if(a.subDomains&&0<a.subDomains.length&&1<c.authority.split(".").length){var d;p.forEach(a.subDomains,function(a){-1<c.authority.indexOf("${subDomain}")?d=c.scheme+"://"+q.substitute(c.authority,{subDomain:a})+"/":-1<c.authority.indexOf("{subDomain}")&&(d=c.scheme+"://"+c.authority.replace(/\{subDomain\}/gi,a)+"/");b.push(d)},this)}return b&&0<b.length?b:null},_getVEStyle:function(a){switch(a){case c.TYPE.BING_AERIAL:return l.MAP_STYLE_AERIAL;case c.TYPE.BING_HYBRID:return l.MAP_STYLE_AERIAL_WITH_LABELS;
case c.TYPE.BING_ROAD:return l.MAP_STYLE_ROAD;default:return l.MAP_STYLE_AERIAL}},fetchLayerInfo:function(a){var b=new m;r({url:a,handleAs:"json",callbackParamName:"callback",timeout:15E3,content:{f:"json"}}).then(n.hitch(this,function(a){b.resolve(a)}),function(a){b.reject(a)});return b},getBingMapKey:function(a){return(a=window.portalSelf||a&&v.getPortal(a.appConfig.portalUrl))&&a.bingKey?a.bingKey:""}},valid:{baseLayerVerification:function(a,b){var f=new m,d=b.spatialReference;c.createBaseLayer(a,
b).then(function(a){if(a.layer){var b=c.layers._getLayerInfoSR(a.layer);c.valid.sameSpatialReference(d,b)||"BaseMap"===a.layer?f.resolve({res:!0}):f.resolve({res:!1})}else f.resolve({res:!1,err:a.err})},function(a){f.resolve({res:!1,err:a})});return f},ArcGISLayersTypeVerification:function(a,b,f){a=a.toLowerCase();if(0<a.indexOf("/featureserver")||0<a.indexOf("/mapserver"))if(!b||"string"!==typeof b.type||"Feature Layer"!==b.type&&"Table"!==b.type){if(0<a.indexOf("/featureserver"))return!1;if(0<a.indexOf("/mapserver"))return b.tileInfo?
f===c.TYPE.ARCGIS_TILED_MAP||f===c.TYPE.ARCGIS_DYNAMIC_MAP_SERVICE?!0:!1:f===c.TYPE.ARCGIS_DYNAMIC_MAP_SERVICE?!0:!1}else return!1;else if(0<a.indexOf("/imageserver"))return f===c.TYPE.ARCGIS_IMAGE_SERVICE?!0:!1},isArcGISLayersValid:function(a,b,f){var d=new m;c.layers.fetchLayerInfo(a).then(function(g){var h=null,e=null,h=c.layers._getLayerInfoSR(g),e=b&&b.spatialReference;h&&e&&c.valid.sameSpatialReference(e,h)?!0===c.valid.ArcGISLayersTypeVerification(a,g,f)?d.resolve({res:!0,info:g}):d.resolve({res:!1,
err:"layerType"}):h&&e&&!c.valid.sameSpatialReference(e,h)?d.resolve({res:!1,err:"wkid"}):d.resolve({res:!1})},function(a){d.resolve({res:!1,err:a})});return d},tileInfoStr:function(a){try{return new u(JSON.parse(a)),!0}catch(b){return b}},isHaveBingKey:function(){return c.layers.getBingMapKey()?!0:!1},sameSpatialReference:function(a,b){var c=[102113,102100,3857,4326];return a&&b&&k.isDefined(a.wkid)&&k.isDefined(b.wkid)&&-1!==c.indexOf(a.wkid)&&-1!==c.indexOf(b.wkid)||a&&b&&(k.isDefined(a.wkid)&&
k.isDefined(b.wkid)&&a.wkid===b.wkid||k.isDefined(a.latestWkid)&&k.isDefined(b.wkid)&&a.latestWkid===b.wkid||k.isDefined(a.wkid)&&k.isDefined(b.latestWkid)&&a.wkid===b.latestWkid||k.isDefined(a.latestWkid)&&k.isDefined(b.latestWkid)&&a.latestWkid===b.latestWkid)||a&&b&&k.isDefined(a.wkt)&&k.isDefined(b.wkt)&&a.wkt===b.wkt?!0:!1}}};return c});