// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/nls/strings":{_widgetLabel:"Trusselsanalyse",threatAnalysisMainPageTitle:"Baseret p\u00e5 JCAT Counterterrorism Guide",jcatURL:"https://www.dni.gov/nctc/jcat/references.html",inputLocation:"Input-placering",interactive:"Interaktiv",fromCoord:"Fast koordinat",existingFeature:"Fra eksisterende objekter",threatAnalysisCoordInputLabel:"Trusselsplacering",enterCoords:"Angiv koordinater",threatAddPointToolTip:"Tilf\u00f8j trusselsplacering",threatDrawPointToolTip:"Klik for at tilf\u00f8je trusselsplacering",
threatType:"Trusselstype",threatPlaceholder:"Begynd at skrive for at s\u00f8ge efter en trussel",mandatoryLabel:"Obligatorisk evakueringsafstand",safeLabel:"Sikker evakueringsafstand",zoneTypeLabel:"Zonetype",feetLabel:"Fod",metersLabel:"Meter",unitsLabel:"Enheder",threatGraphicLayer:"Trusselsbillede",settingsTitle:"Indstillinger",mandatoryButtonLabel:"Konfigur\u00e9r indstillinger for Obligatorisk evakueringsafstand",safeButtonLabel:"Konfigurer indstillinger for Beskyttelsesrum i stedzone",style:"Type",
lineStyles:{esriSLSDash:"Streg",esriSLSDashDot:"Streg-prik",esriSLSDashDotDot:"Streg-prik-prik",esriSLSDot:"Prik",esriSLSLongDash:"Lang streg",esriSLSLongDashDot:"Lang streg-prik",esriSLSNull:"Nul",esriSLSShortDash:"Kort streg",esriSLSShortDashDot:"Kort streg-prik",esriSLSShortDashDotDot:"Kort streg-prik-prik",esriSLSShortDot:"Kort prik",esriSLSSolid:"Udfyldt"},fillStyles:{esriSFSBackwardDiagonal:"Bagl\u00e6ns",esriSFSCross:"Kryds",esriSFSDiagonalCross:"Diagonalt",esriSFSForwardDiagonal:"Frem",esriSFSHorizontal:"Vandret",
esriSFSNull:"Nul",esriSFSSolid:"Udfyldt",esriSFSVertical:"Lodret"},resultsTitle:"Resultater",publishTABtn:"Public\u00e9r",layerName:"Navn p\u00e5 publiceret lag",invalidLayerName:"Lagnavnet m\u00e5 kun indeholde alfanumeriske tegn og understregninger",missingLayerName:"Du skal indtaste et navn til laget",missingLayerNameMessage:"Du skal indtaste et gyldigt lag-navn, f\u00f8r du kan publicere.",publishingFailedLayerExists:"Publicering mislykkedes: Du har allerede en featuretjeneste med navnet {0}. V\u00e6lg et andet navn.",
checkService:"Kontroller tjeneste: {0}",createService:"Opret tjeneste: {0}",unableToCreate:"Kan ikke oprette: {0}",addToDefinition:"Tilf\u00f8j til definition: {0}",successfullyPublished:"Weblag er oprettet{0}Administr\u00e9r weblaget",userRole:"Kan ikke oprette tjenesten, fordi brugeren ikke har tilladelser",transparencyLabel:"Gennemsigtighed",outline:"Kontur",fill:"Fyld (farve anvendes kun, n\u00e5r typografien er indstillet til massiv)",createBtn:"Opret zoner",clearBtn:"Ryd",invalidNumberMessage:"Den indtastede v\u00e6rdi er ikke gyldig",
invalidRangeMessage:"V\u00e6rdien skal v\u00e6re st\u00f8rre end 0",parseCoordinatesError:"Kan ikke analysere koordinater. Kontroll\u00e9r dit input.",manualCoordinateInputInfo:"Indtast koordinater manuelt, og klik p\u00e5 \x3cb\x3eEnter\x3c/b\x3e for at zoome til positionen",pipeBombLabel:"R\u00f8rbombe",suicideBombLabel:"Selvmordsbombe",briefcaseLabel:"Dokumentmappe",carLabel:"Bil",suvVanLabel:"SUV/VAN",smallDeliveryTruckLabel:"Lille varevogn",containerWaterTruckLabel:"Container-/vandlastbil",semiTrailerLabel:"S\u00e6ttevogn",
selectDrawModeLabel:"V\u00e6lg tegnetilstand",selectFeatureLabel:"V\u00e6lg objekt fra dette lag",_localized:{}}});