// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/nls/strings":{_widgetLabel:"An\u00e1lisis de amenazas",threatAnalysisMainPageTitle:"Basado en la Gu\u00eda de la lucha contra el terrorismo del JCAT",jcatURL:"https://www.dni.gov/nctc/jcat/references.html",inputLocation:"Ubicaci\u00f3n de entrada",interactive:"Interactiva",fromCoord:"Coordenada fija",existingFeature:"De entidades existentes",threatAnalysisCoordInputLabel:"Ubicaci\u00f3n de la amenaza",enterCoords:"Introducir coordenadas",threatAddPointToolTip:"Agregar ubicaci\u00f3n de la amenaza",
threatDrawPointToolTip:"Haga clic para agregar una ubicaci\u00f3n de amenaza",threatType:"Tipo de amenaza",threatPlaceholder:"Comience a escribir para buscar una amenaza",mandatoryLabel:"Distancia de evacuaci\u00f3n obligatoria",safeLabel:"Distancia de evacuaci\u00f3n segura",zoneTypeLabel:"Tipo de zona",feetLabel:"Pies",metersLabel:"Metros",unitsLabel:"Unidades",threatGraphicLayer:"Gr\u00e1fico de amenazas",settingsTitle:"Ajustes",mandatoryButtonLabel:"Configurar los ajustes de Distancia de evacuaci\u00f3n obligatoria",
safeButtonLabel:"Configurar los ajustes de Refugio designado",style:"Estilo",lineStyles:{esriSLSDash:"Guion",esriSLSDashDot:"Guion Punto",esriSLSDashDotDot:"Guion Punto Punto",esriSLSDot:"Punto",esriSLSLongDash:"Guion largo",esriSLSLongDashDot:"Guion largo, Punto",esriSLSNull:"Nulo",esriSLSShortDash:"Guion corto",esriSLSShortDashDot:"Guion corto Punto",esriSLSShortDashDotDot:"Guion corto Punto Punto",esriSLSShortDot:"Corto Punto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Atr\u00e1s",
esriSFSCross:"Cruz",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Hacia delante",esriSFSHorizontal:"Horizontal",esriSFSNull:"Nulo",esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},resultsTitle:"Resultados",publishTABtn:"Publicar",layerName:"Nombre de capa publicado",invalidLayerName:"El nombre de la capa solo debe contener caracteres alfanum\u00e9ricos y guiones bajos",missingLayerName:"Debe introducir un nombre para la capa",missingLayerNameMessage:"Debe introducir un nombre de capa v\u00e1lido antes de publicar",
publishingFailedLayerExists:"Fallo de publicaci\u00f3n: ya tiene un servicio de entidades denominado {0}. Elija otro nombre.",checkService:"Comprobar servicio: {0}",createService:"Crear servicio: {0}",unableToCreate:"Imposible crear: {0}",addToDefinition:"Agregar a definici\u00f3n: {0}",successfullyPublished:"Capa web publicada correctamente{0}Administar la capa web",userRole:"Imposible crear el servicio porque el usuario no tiene permisos",transparencyLabel:"Transparencia",outline:"Lista",fill:"Relleno (el color solo se aplica si el estilo es s\u00f3lido)",
createBtn:"Crear zonas",clearBtn:"Borrar",invalidNumberMessage:"El valor introducido no es v\u00e1lido",invalidRangeMessage:"El valor debe ser mayor que 0",parseCoordinatesError:"Imposible analizar las coordenadas. Compruebe la entrada.",manualCoordinateInputInfo:"Introduzca manualmente las coordenadas y pulse \x3cb\x3eIntro\x3c/b\x3e para acercarse a ellas",pipeBombLabel:"Bomba casera",suicideBombLabel:"Bomba suicida",briefcaseLabel:"Malet\u00edn",carLabel:"Autom\u00f3vil",suvVanLabel:"Todoterreno/furgoneta",
smallDeliveryTruckLabel:"Cami\u00f3n de reparto peque\u00f1o",containerWaterTruckLabel:"Contenedor/cami\u00f3n cisterna",semiTrailerLabel:"Semirremolque",selectDrawModeLabel:"Seleccionar modo de dibujo",selectFeatureLabel:"Seleccionar entidad de esta capa",_localized:{}}});