// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Directions/setting/nls/strings":{searchTabTitle:"Pretra\u017ei postavku izvora",routeTabTitle:"Postavka rute",add:"Dodaj izvor pretrage",addGeocoder:"Dodaj geokoder",geocoder:"Geokoder",setLayerSource:"Postavi izvor sloja",setGeocoderURL:"Postavi URL adresu geokodera",searchableLayer:"Sloj geoobjekata",name:"Naziv",countryCode:"K\u00f4d(ovi) zemlje ili regiona",countryCodeEg:"npr. ",countryCodeHint:"Ako ova vrednost ostane prazna, pretra\u017euju se sve zemlje i regioni",showInfoWindowOnSelect:"Prika\u017ei iska\u010du\u0107i prozor za prona\u0111eni geoobjekat ili lokaciju",
showInfoWindowOnSelect2:"Prika\u017ei iska\u010du\u0107i prozor kada se prona\u0111e geoobjekat ili lokacija.",searchInCurrentMapExtent:"Pretra\u017ei samo u trenutnom obuhvatu mape",setSearchFields:"Postavi polja pretrage",set:"Postavi",fieldSearchable:"pretra\u017eivo",zoomScale:"Skala zumiranja",locatorUrl:"URL adresa geokodera",locatorName:"Ime geokodera",locatorExample:"Primer",locatorWarning:"Ova verzija servisa geokodiranja nije podr\u017eana. Vid\u017eet podr\u017eava servis geokodiranja 10.1 i novije.",
locatorTips:"Predlozi nisu dostupni jer servis geok\u00f4diranja ne podr\u017eava predlo\u017eenu mogu\u0107nost.",layerSource:"Izvor sloja",searchLayerTips:"Predlozi nisu dostupni jer servis geoobjekata ne podr\u017eava mogu\u0107nost paginacije.",placeholderText:"Tekst \u010duvara mesta",searchFields:"Polja za pretragu",displayField:"Prika\u017ei polje",exactMatch:"Potpuno podudaranje",maxSuggestions:"Maksimalno predloga",maxResults:"Maksimalno rezultata",enableLocalSearch:"Omogu\u0107i lokalnu pretragu",
minScale:"Min. razmera",minScaleHint:"Kada je razmera mape ve\u0107a od ove razmere, primenjuje se lokalna pretraga",radius:"Polupre\u010dnik",radiusHint:"Defini\u0161e polupre\u010dnik oblasti oko trenutnog centra mape koja se koristi za pobolj\u0161avanje rangiranja kandidata za geokodiranje kako bi se prvo vra\u0107ali kandidati najbli\u017ei lokaciji",invalidUrlTip:"URL adresa ${URL} nije validna ili nije dostupna.",routeUrl:"URL adresa usmeravanja",geocoderOptions:"Opcije geokodera",autoComplete:"Automatsko popunjavanje",
maximumSuggestions:"Maksimalno predloga",minCharacters:"Minimalno karaktera",searchDelay:"Odlaganje pretrage",placeholder:"\u010cuvar mesta",routeOptions:"Opcije usmeravanja",directionsLanguage:"Jezik uputstava",directionsLengthUnits:"Jedinice du\u017eine u uputstvima za navigaciju",directionsOutputType:"Tip izlaznih rezultata uputstva za navigaciju",impedanceAttribute:"Atributi otpora",kilometers:"Kilometri",miles:"Milje",meters:"Metri",feet:"Stope",yards:"Jardi",nauticalMiles:"Nauti\u010dke milje",
parametersTip:"Pravilno postavite parametre!",complete:"Zavr\u0161i",completeNoEvents:"Zavr\u0161i bez doga\u0111aja",instructionsOnly:"Samo instrukcije",standard:"Standardna verzija",summaryOnly:"Samo rezime",travelModesUrl:"URL adresa re\u017eima putovanja",searchPlaceholder:"Prona\u0111i adresu ili mesto",trafficLayerUrl:"URL adresa sloja saobra\u0107aja",barrierLayerUrl:"URL adresa barijere",presetDestinations:"Unapred pode\u0161ena zaustavljanja",startPoint:"Po\u010detna ta\u010dka",endPoint:"Krajnja ta\u010dka",
destinationHolder:"Adresa ili koordinate",optional:"Opcionalno.",barrierLayers:"Slojevi barijere",pointBarrier:"Ta\u010dkaste barijere",lineBarrier:"Linijske barijere",polygonBarrier:"Poligonalne barijere",noPointBarrier:"Izaberite ta\u010dkaste barijere",noLineBarrier:"Izaberite linijske barijere",noPolygonBarrier:"Izaberite poligonalne barijere",_localized:{}}});