// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Configura\u00e7\u00f5es",titleSettings:"Configura\u00e7\u00f5es de texto",imageSettings:"Configura\u00e7\u00f5es de imagem",backgroundColor:"Cor do plano de fundo",alignment:"Alinhamento",textSize:"Tamanho de texto",textColor:"Cor de texto",dataSource:"Fonte de dados",chartSettings:"Configura\u00e7\u00f5es do gr\u00e1fico",data:"Dados",dataLabels:"R\u00f3tulos de dados",displayMode:"Modo de Visualiza\u00e7\u00e3o",featureOption:"Exibir valores fei\u00e7\u00e3o por fei\u00e7\u00e3o",
categoryOption:"Exibir valores por categoria",countOption:"Exibir contagem de fei\u00e7\u00e3o por categoria",fieldOption:"Exibir valores de atributo como gr\u00e1ficos",categoryField:"Campo de Categoria",labelField:"Campo de r\u00f3tulo",valueFields:"Campos de valores",operation:"Opera\u00e7\u00e3o",sumOption:"Soma",averageOption:"M\u00e9dia",minOption:"M\u00ednimo",maxOption:"M\u00e1ximo",countString:"Contagem",dataFormat:"Formato dos dados",decimalPlaces:"Casas decimais",prefix:"Prefixo",suffix:"Sufixo",
dataType:"Tipo de dados",featureCount:"Contagem de fei\u00e7\u00f5es",fieldStatistics:"Estat\u00edstica de campo",display:"Exibir",chartColor:"Cor do gr\u00e1fico",horizontalAxis:"Eixo horizontal",verticalAxis:"Eixo vertical",legend:"Legenda",position:"Posi\u00e7\u00e3o",top:"Superior",bottom:"Inferior",useDataSourceSelection:"Utilizar sele\u00e7\u00e3o",dataSourceFilterByExtent:"Filtrar por extens\u00e3o",changeTemplate:"Alterar modelo",numberSettings:"Configura\u00e7\u00f5es de n\u00famero",gaugeSettings:"Configura\u00e7\u00f5es do Medidor",
indicators:"Indicadores",ifValue:"Se valor",and:"l",numberOperatorIsLessThan:"\u00e9 menor que",numberOperatorIsGreaterThan:"\u00e9 maior que",numberOperatorIsBetween:"est\u00e1 entre",numberOperatorIsEqual:"\u00e9 igual a",numberOperatorIsNotEqual:"n\u00e3o \u00e9 igual a",then:"Ent\u00e3o",ratio:"Taxa",trueValue:"Valor verdadeiro",changeValueColor:"altera cor de valor para",changeGaugeColor:"altere cor de medidor para",setIndicatorIcon:"configurar \u00edcone de indicador como",icons:"\u00cdcones",
style:"Estilo",placement:"Disposi\u00e7\u00e3o",left:"Esquerda",replace:"Substituir",right:"Direita",color:"Cor",categoryExists:"A categoria existe!",comboxHint:"Digitar ou selecionar um",comboxDisableInputHint:"Selecionar um",comboxDisableSelectHint:"Digite um",comboxDisableInputEmptySelectHint:"Sem mais categorias",sortBy:"Classificar por",labelAxis:"R\u00f3tulo",valueAxis:"Valor",minPeriod:"Per\u00edodo m\u00ednimo",automatic:"Autom\u00e1tico",periodsWithOutRecords:"Per\u00edodos sem registros",
nullValue:"Valor nulo",calculatedAsZero:"Calculado como zero",ignored:"Ignorado",maxCategories:"M\u00e1ximo de categorias",useLayerSymbology:"Utilizar simbologia da camada",hollowsize:"Tamanho do v\u00e1cuo",splitField:"Dividir campo",parsingperiodTip:"Falha ao calcular. Muitos intervalos de tempo devido ao curto per\u00edodo de an\u00e1lise.",manyCategoryTip:"Falha ao exibir gr\u00e1fico. Muitas categorias.",setColor:"Definir cor",setTheColorOf:"Ent\u00e3o configurar cor de",setTheColorAs:"Ent\u00e3o configurar cor como",
ifStr:"Se",as:"como",is:"\u00e9",isNot:"n\u00e3o \u00e9",barCluster:"agrupamento de barra",individualBar:"barra individual",allOthers:"Todos os outros",category:"Categoria",indicatorSum:"SOMA",indicatorAve:"M\u00c9DIA",indicatorMax:"M\u00c1X",indicatorMin:"M\u00cdN",setCorrectyIndicatorTip:"Ajuste os indicadores corretamente.",dataRange:"Faixa de dados",targetValue:"Valor de alvo",currentValue:"Valor atual",gaugeColor:"Cor do medidor",min:"M\u00ednimo",max:"M\u00e1ximo",displayValueIn:"Exibe o valor em",
noData:"Sem dados",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Aviso",noSettingWaring1:"Clique em um elemento para configurar suas propriedades.",noSettingWaring2:"Arraste para dimensionar ou reordenar um elemento.",donNotShowAgain:"N\u00e3o mostrar novamente",changeTemplateWarning:"Isto apagar\u00e1 todas suas configura\u00e7\u00f5es e abre um novo modelo vazio.",requiredFieldWarning:"Este valor \u00e9 exigido:",dataSourceNotSet:"Configure a fonte de dados.",
addIndicatorTip:"Adicionar um indicador",chooseTemplatePopupTitle:"Escolher um modelo",filterExtentTipWithaTag:"Voc\u00ea pode desativar o filtro por \x3ca target\x3d'_blank' href\x3d'http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'\x3eFonte de dados extra\x3c/a\x3e na guia Atributos.",filterExtentTip:"Voc\u00ea pode desativar o filtro por Fonte de dados extra na guia Atributos.",customColorByCategory:"Cor personalizada por categoria",
randomColor:"Cor Aleat\u00f3ria",valueString:"Valor",fieldString:"Campo",includeThresholdValue:"Incluir valor de limite",percentage:"Porcentagem",colorSchema:"Esquema de cores",addCategory:"Adicionar categoria",clickToEdit:"Clique para editar",nullText:"Nulo",others:"Outros",dsErrorTipSuf:"n\u00e3o est\u00e1 dispon\u00edvel.",front:"Frente",back:"Voltar",title:"T\u00edtulo",titleColor:"Cor do t\u00edtulo",labelString:"R\u00f3tulo",labelSize:"Tamanho do r\u00f3tulo",labelColor:"Cor do r\u00f3tulo",
addMarkLine:"Adicionar uma marca de linha",addMarkArea:"Adicionar uma marca de \u00e1rea",labelPosition:"Posi\u00e7\u00e3o do r\u00f3tulo",toString:"para",start:"Iniciar",middle:"Meio",end:"Final",inString:"Dentro",outString:"Fora",lineColor:"Cor da linha",lineWidth:"Largura da linha",dashType:"Tipo de Tra\u00e7o",areaColor:"Cor da \u00e1rea",line:"Linha",area:"\u00c1rea",stringsInTemplate:{name_number:"N\u00famero",name_gauge:"Medidor",name_vertical_gauge:"Medidor Vertical",name_horizontal_gauge:"Medidor Horizontal",
name_pie:"Pizza",name_donut:"C\u00edrculo",name_bar:"Barra",name_stacked_bar:"Barras Empilhadas",name_percentage_stacked_bar:"Porcentagem de Barras Empilhadas",name_column:"Coluna",name_stacked_column:"Coluna empilhada",name_percentage_stacked_column:"Porcentagem de Colunas Empilhadas",name_line:"Linha",name_area:"\u00c1rea",name_stacked_area:"\u00c1rea Empilhada",name_percentage_stacked_area:"Porcentagem de \u00c1reas Empilhadas",titleOfTheInfographic:"T\u00cdTULO DO INFOGR\u00c1FICO",description:"Descri\u00e7\u00e3o: informa\u00e7\u00f5es adicionais sobre este infogr\u00e1fico."},
marks:"Marcadores",displayValue:"Valor de exibi\u00e7\u00e3o",statistic:"Estat\u00edstica",valueType:"Tipo de Valor",valueField:"Campo de valor",fixed:"Fixo",sdsTip:"Escolha os dados estat\u00edsticos configurados na fonte de dados Extra",noSdsTip:"N\u00e3o h\u00e1 dados de estat\u00edstica dispon\u00edveis.",intScaleText:"Exibir somente escala inteira",resetLayout:"Redefinir layout",fbeTip:"Esteja ciente que seu aplicativo est\u00e1 compartilhado publicamente e se torne viral, habilitar esta op\u00e7\u00e3o diminui a velocidade de desempenho do aplicativo dramaticamente. N\u00f3s recomendamos fortemente utilizar outros widgets como, Filtrar e Filtrar Grupo para ampliar nas fei\u00e7\u00f5es ao inv\u00e9s.",
openFbeTip:"Ativar a op\u00e7\u00e3o de qualquer maneira",use1000Separator:"Utilizar separador de milhar",_localized:{}}});