// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Bold",copy:"Copy",cut:"Cut","delete":"Delete",indent:"Indent",insertHorizontalRule:"Horizontal Rule",insertOrderedList:"Numbered List",insertUnorderedList:"Bullet List",italic:"Italic",justifyCenter:"Align Center",justifyFull:"Justify",justifyLeft:"Align Left",justifyRight:"Align Right",outdent:"Outdent",paste:"Paste",redo:"Redo",removeFormat:"Remove Format",selectAll:"Select All",strikethrough:"Strikethrough",subscript:"Subscript",superscript:"Superscript",
underline:"Underline",undo:"Undo",unlink:"Remove Link",createLink:"Create Link",toggleDir:"Toggle Direction",insertImage:"Insert Image",insertTable:"Insert/Edit Table",toggleTableBorder:"Toggle Table Border",deleteTable:"Delete Table",tableProp:"Table Property",htmlToggle:"HTML Source",foreColor:"Foreground Color",hiliteColor:"Background Color",plainFormatBlock:"Paragraph Style",formatBlock:"Paragraph Style",fontSize:"Font Size",fontName:"Font Name",tabIndent:"Tab Indent",fullScreen:"Toggle Full Screen",
viewSource:"View HTML Source",print:"Print",newPage:"New Page",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{ar:1,az:1,bg:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,eu:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,kk:1,ko:1,lt:1,lv:1,mk:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tr:1,uk:1,vi:1,zh:1,"zh-hk":1,"zh-tw":1}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a",
"days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"now","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["AH"],"field-tue-relative+-1":"last Tuesday","days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G y MMMM d","field-fri-relative+-1":"last Friday","field-wed-relative+-1":"last Wednesday","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"G y MMMM d, EEEE","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E",
"field-thu-relative+-1":"last Thursday","dateFormatItem-Md":"MM-dd","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["Q1","Q2","Q3","Q4"],"timeFormat-long":"HH:mm:ss z","field-year":"Year",
"dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hour","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"today","field-thu-relative+0":"this Thursday","field-day-relative+1":"tomorrow","field-thu-relative+1":"next Thursday","dateFormatItem-GyMMMd":"G y MMM d",
"dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dayPeriods-format-abbr-noon":"noon",
"timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"this Sunday","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"next Sunday","quarters-standAlone-abbr":["Q1","Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Dayperiod","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"yesterday","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a",
"dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"this Friday","field-fri-relative+1":"next Friday","field-day":"Day","days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"field-zone":"Zone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"last year","field-month-relative+-1":"last month",
"dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"Month","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})",
"dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","dateFormat-short":"GGGGG y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second","field-sat-relative+-1":"last Saturday","field-sun-relative+-1":"last Sunday","field-month-relative+0":"this month",
"field-month-relative+1":"next month","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d, E","field-week":"Week","dateFormat-medium":"G y MMM d","field-week-relative+-1":"last week","field-year-relative+0":"this year","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"next year","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM",
"field-mon-relative+-1":"last Monday","dateFormatItem-yyyy":"G y","field-week-relative+0":"this week","field-week-relative+1":"next week",_localized:{ar:1,bs:1,cs:1,da:1,de:1,en:1,"en-au":1,"en-gb":1,es:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,pt:1,"pt-pt":1,ro:1,ru:1,sr:1,sv:1,th:1,tr:1,vi:1,zh:1,"zh-hant":1}},"widgets/CostAnalysis/nls/strings":{_widgetLabel:"Cost Analysis",unableToFetchInfoErrMessage:"Unable to fetch geometry service/configured layer details",
invalidCostingGeometryLayer:"Unable to get 'esriFieldTypeGlobalID' in costing geometry layer.",projectLayerNotFound:"Unable to find the configured project layer in map.",costingGeometryLayerNotFound:"Unable to find the configured costing geometry layer in map.",projectMultiplierTableNotFound:"Unable to find the configured project multiplier additional cost table in map.",projectAssetTableNotFound:"Unable to find the configured project asset table in map.",createLoadProject:{createProjectPaneTitle:"Create Project",
loadProjectPaneTitle:"Load Project",projectNamePlaceHolder:"Project Name",projectDescPlaceHolder:"Project Description",selectProject:"Select Project",viewInMapLabel:"View In Map",loadLabel:"Load",createLabel:"Create",deleteProjectConfirmationMsg:"Are you sure you want to delete the project?",noAssetsToViewOnMap:"Selected project don't have any assets to view on map.",projectDeletedMsg:"Project deleted successfully.",errorInCreatingProject:"Error in creating project.",errorProjectNotFound:"Project not found.",
errorInLoadingProject:"Please check if valid project is selected.",errorProjectNotSelected:"Select a project from the dropdown",errorDuplicateProjectName:"Project name already exist."},statisticsSettings:{tabTitle:"Statistics settings",addStatisticsLabel:"Add Statistics",addNewStatisticsText:"Add New Statistics",deleteStatisticsText:"Delete Statistics",moveStatisticsUpText:"Move Statistics Up",moveStatisticsDownText:"Move Statistics Down",layerNameTitle:"Layer",statisticsTypeTitle:"Type",fieldNameTitle:"Field",
statisticsTitle:"Label",actionLabelTitle:"Actions",selectDeselectAllTitle:"Select All"},statisticsType:{countLabel:"Count",averageLabel:"Average",maxLabel:"Maximum",minLabel:"Minimum",summationLabel:"Summation",areaLabel:"Area",lengthLabel:"Length"},costingInfo:{noEditableLayersAvailable:"Layer(s) needs to be checked as editable in layer settings tab"},workBench:{refresh:"Refresh",noAssetAddedMsg:"No assets added",units:"unit(s)",assetDetailsTitle:"Asset Item Details",costEquationTitle:"Cost Equation",
newCostEquationTitle:"New Equation",defaultCostEquationTitle:"Default Equation",geographyTitle:"Geography",scenarioTitle:"Scenario",costingInfoHintText:"\x3cdiv\x3eHint: Use the following keywords\x3c/div\x3e\x3cul\x3e\x3cli\x3e\x3cb\x3e{TOTALCOUNT}\x3c/b\x3e: Uses the total number of same type asset in a geography\x3c/li\x3e \x3cli\x3e\x3cb\x3e{MEASURE}\x3c/b\x3e: Uses the length for line asset and area for polygon asset\x3c/li\x3e\x3cli\x3e\x3cb\x3e{TOTALMEASURE}\x3c/b\x3e: Uses the total length for line asset and total area for polygon asset of same type in a geography\x3c/li\x3e\x3c/ul\x3e You can use functions such as:\x3cul\x3e\x3cli\x3eMath.abs(-100)\x3c/li\x3e\x3cli\x3eMath.floor({TOTALMEASURE})\x3c/li\x3e\x3c/ul\x3ePlease edit cost equation as per your project need.",
zoomToAsset:"Zoom To Asset",deleteAsset:"Delete Asset",closeDialog:"Close dialog",objectIdColTitle:"Object Id",costColTitle:"Cost",errorInvalidCostEquation:"Invalid Cost Equation.",errorInSavingAssetDetails:"Unable to save asset details.",featureModeText:"Feature Mode",sketchToolTitle:"Sketch",selectToolTitle:"Select"},assetDetails:{inGeography:" in ${geography} ",withScenario:" with ${scenario}",totalCostTitle:"Total Cost",additionalCostLabel:"Description",additionalCostValue:"Value",additionalCostNetValue:"Net Value"},
projectOverview:{assetItemsTitle:"Asset Items",assetStatisticsTitle:"Asset Statistics",projectSummaryTitle:"Project Summary",projectName:"Project Name: ${name}",totalCostLabel:"Total Project Cost (*):",grossCostLabel:"Gross Project Cost (*):",roundingLabel:"* Rounding to '${selectedRoundingOption}'",unableToSaveProjectBoundary:"Unable to save project boundary in project layer.",unableToSaveProjectCost:"Unable to save cost(s) in project layer.",roundCostValues:{twoDecimalPoint:"Two Decimal Points",
nearestWholeNumber:"Nearest Whole Number",nearestTen:"Nearest Ten",nearestHundred:"Nearest Hundred",nearestThousand:"Nearest Thousands",nearestTenThousands:"Nearest Ten Thousands"}},projectAttribute:{projectAttributeText:"Project Attribute",projectAttributeTitle:"Edit Project Attributes"},costEscalation:{costEscalationLabel:"Add Additional Cost",valueHeader:"Value",addCostEscalationText:"Add additional cost",deleteCostEscalationText:"Delete selected additional Cost",moveCostEscalationUpText:"Move selected additional cost up",
moveCostEscalationDownText:"Move selected additional cost down",invalidEntry:"One or more entries are invalid.",errorInSavingCostEscalation:"Unable to save additional cost details."},scenarioSelection:{popupTitle:"Select Scenario for the Asset",regionLabel:"Geography",scenarioLabel:"Scenario",noneText:"None",copyFeatureMsg:"Do you want to copy selected features?"},detailStatistics:{detailStatisticsLabel:"Detail Statistics",noDetailStatisticAvailable:"No asset statistics added"},copyFeatures:{title:"Copy Features",
createFeatures:"Create Features",createSingleFeature:"Create 1 Multi-Geometry Feature",noFeaturesSelectedMessage:"No Features Selected",selectFeatureToCopyMessage:"Please select features to copy."},_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}}});