// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negreta",copy:"Copia",cut:"Retalla","delete":"Suprimeix",indent:"Sagnat",insertHorizontalRule:"Regla horitzontal",insertOrderedList:"Llista numerada",insertUnorderedList:"Llista de vinyetes",italic:"Cursiva",justifyCenter:"Alineaci\u00f3 centrada",justifyFull:"Justifica",justifyLeft:"Alineaci\u00f3 a l'esquerra",justifyRight:"Alineaci\u00f3 a la dreta",outdent:"Sagnat a l'esquerra",paste:"Enganxa",redo:"Ref\u00e9s",removeFormat:"Elimina el format",selectAll:"Selecciona-ho tot",
strikethrough:"Ratllat",subscript:"Sub\u00edndex",superscript:"Super\u00edndex",underline:"Subratllat",undo:"Desf\u00e9s",unlink:"Elimina l'enlla\u00e7",createLink:"Crea un enlla\u00e7",toggleDir:"Inverteix la direcci\u00f3",insertImage:"Insereix imatge",insertTable:"Insereix/edita la taula",toggleTableBorder:"Inverteix els contorns de taula",deleteTable:"Suprimeix la taula",tableProp:"Propietat de taula",htmlToggle:"Font HTML",foreColor:"Color de primer pla",hiliteColor:"Color de fons",plainFormatBlock:"Estil de par\u00e0graf",
formatBlock:"Estil de par\u00e0graf",fontSize:"Mida del tipus de lletra",fontName:"Nom del tipus de lletra",tabIndent:"Sagnat",fullScreen:"Commuta pantalla completa",viewSource:"Visualitza font HTML",print:"Imprimeix",newPage:"P\u00e0gina nova",systemShortcut:"L'acci\u00f3 \"${0}\" \u00e9s l'\u00fanica disponible al navegador utilitzant una drecera del teclat. Utilitzeu ${1}.",ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"now","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["AH"],"field-tue-relative+-1":"last Tuesday","days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G y MMMM d",
"field-fri-relative+-1":"last Friday","field-wed-relative+-1":"last Wednesday","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"G y MMMM d, EEEE","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","field-thu-relative+-1":"last Thursday","dateFormatItem-Md":"MM-dd",
"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["Q1","Q2","Q3","Q4"],"timeFormat-long":"HH:mm:ss z","field-year":"Year","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hour",
"months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"today","field-thu-relative+0":"this Thursday","field-day-relative+1":"tomorrow","field-thu-relative+1":"next Thursday","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"this Sunday","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"next Sunday","quarters-standAlone-abbr":["Q1",
"Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Dayperiod","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"yesterday","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"this Friday",
"field-fri-relative+1":"next Friday","field-day":"Day","days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"field-zone":"Zone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"last year","field-month-relative+-1":"last month","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM",
"days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"Month","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","dateFormat-short":"GGGGG y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second","field-sat-relative+-1":"last Saturday","field-sun-relative+-1":"last Sunday","field-month-relative+0":"this month","field-month-relative+1":"next month","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d, E","field-week":"Week",
"dateFormat-medium":"G y MMM d","field-week-relative+-1":"last week","field-year-relative+0":"this year","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"next year","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"last Monday","dateFormatItem-yyyy":"G y","field-week-relative+0":"this week","field-week-relative+1":"next week",
_localized:{}},"widgets/CostAnalysis/nls/strings":{_widgetLabel:"An\u00e0lisi de costos",unableToFetchInfoErrMessage:"No es poden recuperar els detalls del servei de geometria o de la capa configurada",invalidCostingGeometryLayer:'No es pot obtenir "esriFieldTypeGlobalID" a la capa de geometria de valoraci\u00f3 de costos.',projectLayerNotFound:"No es troba la capa de projecte que s'ha configurat al mapa.",costingGeometryLayerNotFound:"No es troba la capa de geometria de valoraci\u00f3 de costos que s'ha configurat al mapa.",
projectMultiplierTableNotFound:"No es troba la taula de costos addicionals del multiplicador del projecte que s'ha configurat al mapa.",projectAssetTableNotFound:"No es troba la taula d'actius del projecte que s'ha configurat al mapa.",createLoadProject:{createProjectPaneTitle:"Crea un projecte",loadProjectPaneTitle:"Carrega el projecte",projectNamePlaceHolder:"Nom del projecte",projectDescPlaceHolder:"Descripci\u00f3 del projecte",selectProject:"Seleccioneu el projecte",viewInMapLabel:"Visualitza-ho al mapa",
loadLabel:"Carrega",createLabel:"Crea",deleteProjectConfirmationMsg:"Segur que voleu suprimir el projecte?",noAssetsToViewOnMap:"El projecte seleccionat no t\u00e9 cap actiu per visualitzar al mapa.",projectDeletedMsg:"El projecte s'ha suprimit correctament.",errorInCreatingProject:"Error en crear el projecte.",errorProjectNotFound:"No s'ha trobat el projecte.",errorInLoadingProject:"Comproveu que el projecte seleccionat sigui v\u00e0lid.",errorProjectNotSelected:"Seleccioneu un projecte de la llista desplegable",
errorDuplicateProjectName:"El nom del projecte ja existeix."},statisticsSettings:{tabTitle:"Configuraci\u00f3 d'estad\u00edstiques",addStatisticsLabel:"Afegeix estad\u00edstiques",addNewStatisticsText:"Afegeix estad\u00edstiques noves",deleteStatisticsText:"Suprimeix estad\u00edstiques",moveStatisticsUpText:"Mou les estad\u00edstiques cap amunt",moveStatisticsDownText:"Mou les estad\u00edstiques cap avall",layerNameTitle:"Capa",statisticsTypeTitle:"Tipus",fieldNameTitle:"Camp",statisticsTitle:"Etiqueta",
actionLabelTitle:"Accions",selectDeselectAllTitle:"Selecciona-ho tot"},statisticsType:{countLabel:"Recompte",averageLabel:"Mitjana",maxLabel:"M\u00e0xim",minLabel:"M\u00ednim",summationLabel:"Suma",areaLabel:"\u00c0rea",lengthLabel:"Longitud"},costingInfo:{noEditableLayersAvailable:"Les capes s'han de marcar com a editables a la pestanya de configuraci\u00f3 de capes"},workBench:{refresh:"Actualitza",noAssetAddedMsg:"No s'ha afegit cap actiu",units:"unitat(s)",assetDetailsTitle:"Detalls dels elements d'actius",
costEquationTitle:"Equaci\u00f3 de costos",newCostEquationTitle:"Equaci\u00f3 nova",defaultCostEquationTitle:"Equaci\u00f3 per defecte",geographyTitle:"Geografia",scenarioTitle:"Escenari",costingInfoHintText:"\x3cdiv\x3eSuggeriment: utilitzeu les paraules clau seg\u00fcents\x3c/div\x3e\x3cul\x3e\x3cli\x3e\x3cb\x3e{TOTALCOUNT}\x3c/b\x3e: utilitza el nombre total de l'actiu del mateix tipus en una geografia\x3c/li\x3e \x3cli\x3e\x3cb\x3e{MEASURE}\x3c/b\x3e: utilitza la longitud de l'actiu de l\u00ednia i l'\u00e0rea de l'actiu de pol\u00edgon\x3c/li\x3e\x3cli\x3e\x3cb\x3e{TOTALMEASURE}\x3c/b\x3e: utilitza la longitud total de l'actiu de l\u00ednia i l'\u00e0rea total de l'actiu de pol\u00edgon del mateix tipus en una geografia\x3c/li\x3e\x3c/ul\x3e Podeu utilitzar funcions com ara:\x3cul\x3e\x3cli\x3eMath.abs(-100)\x3c/li\x3e\x3cli\x3eMath.floor({TOTALMEASURE})\x3c/li\x3e\x3c/ul\x3eEditeu l'equaci\u00f3 de costos segons sigui necessari per al vostre projecte.",
zoomToAsset:"Aplica el zoom a l'actiu",deleteAsset:"Suprimeix l'actiu",closeDialog:"Tanca el di\u00e0leg",objectIdColTitle:"ID d'objecte",costColTitle:"Cost",errorInvalidCostEquation:"Equaci\u00f3 de costos no v\u00e0lida.",errorInSavingAssetDetails:"No es poden desar els detalls dels actius.",featureModeText:"Mode d'entitat",sketchToolTitle:"Esb\u00f3s",selectToolTitle:"Selecciona"},assetDetails:{inGeography:" a ${geography} ",withScenario:" amb ${scenario}",totalCostTitle:"Cost total",additionalCostLabel:"Descripci\u00f3",
additionalCostValue:"Valor",additionalCostNetValue:"Valor net"},projectOverview:{assetItemsTitle:"Elements d'actius",assetStatisticsTitle:"Estad\u00edstiques d'actius",projectSummaryTitle:"Resum del projecte",projectName:"Nom del projecte: ${name}",totalCostLabel:"Cost total del projecte (*):",grossCostLabel:"Cost brut del projecte (*):",roundingLabel:'* Arrodoniment a "${selectedRoundingOption}"',unableToSaveProjectBoundary:"No es pot desar el l\u00edmit del projecte a la capa del projecte.",unableToSaveProjectCost:"No es poden desar els costos a la capa del projecte.",
roundCostValues:{twoDecimalPoint:"Dues comes decimals",nearestWholeNumber:"Nombre enter m\u00e9s proper",nearestTen:"Desena m\u00e9s propera",nearestHundred:"Centenar m\u00e9s proper",nearestThousand:"Miler m\u00e9s proper",nearestTenThousands:"Desena de miler m\u00e9s propera"}},projectAttribute:{projectAttributeText:"Atribut del projecte",projectAttributeTitle:"Edita els atributs del projecte"},costEscalation:{costEscalationLabel:"Afegeix un cost addicional",valueHeader:"Valor",addCostEscalationText:"Afegeix un cost addicional",
deleteCostEscalationText:"Suprimeix el cost addicional seleccionat",moveCostEscalationUpText:"Mou el cost addicional seleccionat cap amunt",moveCostEscalationDownText:"Mou el cost addicional seleccionat cap avall",invalidEntry:"Una o diverses entrades no s\u00f3n v\u00e0lides.",errorInSavingCostEscalation:"No es poden desar els detalls de costos addicionals."},scenarioSelection:{popupTitle:"Seleccioneu un escenari per a l'actiu",regionLabel:"Geografia",scenarioLabel:"Escenari",noneText:"Cap",copyFeatureMsg:"Voleu copiar les entitats seleccionades?"},
detailStatistics:{detailStatisticsLabel:"Estad\u00edstiques dels detalls",noDetailStatisticAvailable:"No s'han afegit estad\u00edstiques d'actius"},copyFeatures:{title:"Copia les entitats",createFeatures:"Crea les entitats",createSingleFeature:"Crea 1 entitat de geometria m\u00faltiple",noFeaturesSelectedMessage:"No s'ha seleccionat cap entitat",selectFeatureToCopyMessage:"Seleccioneu les entitats que voleu copiar."},_localized:{}}});