// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"dom lun mar mer gio ven sab".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"ora","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Giorno della settimana","field-wed-relative+0":"questo mercoled\u00ec","field-wed-relative+1":"mercoled\u00ec prossimo","dateFormatItem-GyMMMEd":"E d MMM y G","dateFormatItem-MMMEd":"E d MMM",eraNarrow:["AH"],"field-tue-relative+-1":"marted\u00ec scorso","days-format-short":"dom lun mar mer gio ven sab".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}",
"dateFormat-long":"dd MMMM y G","field-fri-relative+-1":"venerd\u00ec scorso","field-wed-relative+-1":"mercoled\u00ec scorso","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1}, {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE d MMMM y G","dateFormatItem-yyyyMEd":"E d/M/y GGGGG","field-thu-relative+-1":"gioved\u00ec scorso",
"dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"timeFormat-long":"HH:mm:ss z",
"field-year":"Anno","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Ora","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"questo sabato","field-sat-relative+1":"sabato prossimo","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"oggi","field-thu-relative+0":"questo gioved\u00ec","field-day-relative+1":"domani","field-thu-relative+1":"gioved\u00ec prossimo",
"dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["T1","T2","T3","T4"],"quarters-standAlone-wide":["1\u00ba trimestre","2\u00ba trimestre","3\u00ba trimestre","4\u00ba trimestre"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E d MMM y G","dateFormatItem-M":"L","days-standAlone-wide":"Domenica Luned\u00ec Marted\u00ec Mercoled\u00ec Gioved\u00ec Venerd\u00ec Sabato".split(" "),
"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"questa domenica","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"domenica prossima","quarters-standAlone-abbr":["T1","T2","T3","T4"],eraAbbr:["AH"],"field-minute":"Minuto","field-dayperiod":"AM/PM","days-standAlone-abbr":"dom lun mar mer gio ven sab".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1",
"2","3","4"],"field-day-relative+-1":"ieri","dateTimeFormat-long":"{1} 'alle' {0}","dayPeriods-format-narrow-am":"m.","dateFormatItem-h":"hh a","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E d/M","dateTimeFormat-full":"{1} 'alle' {0}","field-fri-relative+0":"questo venerd\u00ec","field-fri-relative+1":"venerd\u00ec prossimo","field-day":"Giorno","days-format-wide":"domenica luned\u00ec marted\u00ec mercoled\u00ec gioved\u00ec venerd\u00ec sabato".split(" "),"field-zone":"Fuso orario","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),
"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"anno scorso","field-month-relative+-1":"mese scorso","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"hh:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"dom lun mar mer gio ven sab".split(" "),eraNames:["AH"],"days-format-narrow":"DLMMGVS".split(""),"dateFormatItem-yyyyMd":"d/M/y GGGGG","field-month":"Mese","days-standAlone-narrow":"DLMMGVS".split(""),
"dateFormatItem-MMM":"LLL","field-tue-relative+0":"questo marted\u00ec","field-tue-relative+1":"marted\u00ec prossimo","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"questo luned\u00ec","field-mon-relative+1":"luned\u00ec prossimo","dateFormat-short":"dd/MM/yy GGGGG","dateFormatItem-EHms":"E HH:mm:ss",
"dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Secondo","field-sat-relative+-1":"sabato scorso","field-sun-relative+-1":"domenica scorsa","field-month-relative+0":"questo mese","field-month-relative+1":"mese prossimo","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E d","field-week":"Settimana","dateFormat-medium":"dd MMM y G","field-week-relative+-1":"settimana scorsa","field-year-relative+0":"quest\u2019anno","dateFormatItem-yyyyM":"M/y GGGGG",
"field-year-relative+1":"anno prossimo","dayPeriods-format-narrow-pm":"p.","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1}, {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"hh:mm:ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"luned\u00ec scorso","dateFormatItem-yyyy":"y G","field-week-relative+0":"questa settimana","field-week-relative+1":"settimana prossima","field-day-relative+2":"dopodomani","field-day-relative+-2":"l\u2019altro ieri",_localized:{}},
"widgets/CostAnalysis/nls/strings":{_widgetLabel:"Cost Analysis",unableToFetchInfoErrMessage:"Impossibile recuperare i dettagli servizio di geometria/layer configurato",invalidCostingGeometryLayer:"Impossibile ottenere 'esriFieldTypeGlobalID' nel costing geometry layer.",projectLayerNotFound:"Impossibile trovare il layer di progetto configurato nella mappa.",costingGeometryLayerNotFound:"Impossibile trovare nella mappa. il costing geometry layer.",projectMultiplierTableNotFound:"Impossibile trovare configurata nella mappa la tabella project multiplier additional cost",
projectAssetTableNotFound:"Impossibile trovare la tabella di risorse di progetto configurata nella mappa.",createLoadProject:{createProjectPaneTitle:"Crea progetto",loadProjectPaneTitle:"Carica progetto",projectNamePlaceHolder:"Nome progetto",projectDescPlaceHolder:"Descrizione progetto",selectProject:"Seleziona progetto",viewInMapLabel:"Visualizza nella mappa",loadLabel:"Carica",createLabel:"Crea",deleteProjectConfirmationMsg:"Eliminare il progetto?",noAssetsToViewOnMap:"Il progetto selezionato non ha risorse da visualizzare sulla mappa.",
projectDeletedMsg:"Progetto correttamente eliminato.",errorInCreatingProject:"Errore nella creazione del progetto.",errorProjectNotFound:"Progetto non trovato.",errorInLoadingProject:"Spuntare se \u00e8 stato selezionato il progetto valido.",errorProjectNotSelected:"Selezionare un progetto dall\u2019elenco a discesa",errorDuplicateProjectName:"Nome progetto gi\u00e0 esistente."},statisticsSettings:{tabTitle:"Impostazioni statistiche",addStatisticsLabel:"Aggiungi statistiche",addNewStatisticsText:"Aggiungi nuove statistiche",
deleteStatisticsText:"Elimina statistiche",moveStatisticsUpText:"Sposta statistiche in alto",moveStatisticsDownText:"Sposta statistiche in basso",layerNameTitle:"Layer",statisticsTypeTitle:"Tipo",fieldNameTitle:"Campo",statisticsTitle:"Etichetta",actionLabelTitle:"Azioni",selectDeselectAllTitle:"Seleziona tutto"},statisticsType:{countLabel:"Conteggio",averageLabel:"Media",maxLabel:"Massimo",minLabel:"Minimo",summationLabel:"Somma",areaLabel:"Area",lengthLabel:"Lunghezza"},costingInfo:{noEditableLayersAvailable:"I layer devono essere selezionati come editabili nella scheda delle impostazioni del layer"},
workBench:{refresh:"Aggiorna",noAssetAddedMsg:"Nessun elemento aggiunto",units:"unit(s)",assetDetailsTitle:"Dettagli dell'elemento",costEquationTitle:"Equazione di costi",newCostEquationTitle:"Nuova equazione",defaultCostEquationTitle:"Equazione predefinita",geographyTitle:"Geografia",scenarioTitle:"Scenario",costingInfoHintText:"\x3cdiv\x3eSuggerimento: utilizzare le seguenti parole chiave\x3c/div\x3e\x3cul\x3e\x3cli\x3e\x3cb\x3e{TOTALCOUNT}\x3c/b\x3e: utilizza il numero totale di elementi dello stesso tipo in una geografia\x3c/li\x3e \x3cli\x3e\x3cb\x3e{MEASURE}\x3c/b\x3e: utilizza la lunghezza per gli elementi lineri e l\u2019area per llgli elementi poligonali\x3c/li\x3e\x3cli\x3e\x3cb\x3e{TOTALMEASURE}\x3c/b\x3e: utilizza la lunghezza totale per gli elelenti lineari e l\u2019area totale pergli elementi poligonali dello stesso tipo nella geografia\x3c/li\x3e\x3c/ul\x3e \u00c8 possibile utilizzare le funzioni come:\x3cul\x3e\x3cli\x3eMath.abs(-100)\x3c/li\x3e\x3cli\x3eMath.floor({TOTALMEASURE})\x3c/li\x3e\x3c/ul\x3eModificare l'equazione di costi in base alle necessit\u00e0 di progetto.",
zoomToAsset:"Zoom sulla risorsa",deleteAsset:"Elimina risorsa",closeDialog:"Chiudi la finestra di dialogo",objectIdColTitle:"ID oggetto",costColTitle:"Costo",errorInvalidCostEquation:"Equazione costi non valida.",errorInSavingAssetDetails:"Impossibile salvare i dettagli risorsa.",featureModeText:"Modalit\u00e0 feature",sketchToolTitle:"Schizzo",selectToolTitle:"Seleziona"},assetDetails:{inGeography:" in ${geography} ",withScenario:" con ${scenario}",totalCostTitle:"Costo totale",additionalCostLabel:"Descrizione",
additionalCostValue:"Valore",additionalCostNetValue:"Valore netto"},projectOverview:{assetItemsTitle:"Asset Items",assetStatisticsTitle:"Asset Statistics",projectSummaryTitle:"Project Summary",projectName:"Nome del Progetto: ${name}",totalCostLabel:"Total Project Cost (*):",grossCostLabel:"Gross Project Cost (*):",roundingLabel:"* Rounding to '${selectedRoundingOption}'",unableToSaveProjectBoundary:"Impossibile salvare il project boundary in un layer.",unableToSaveProjectCost:"Impossibile salvare i costi in un layer di progetto.",
roundCostValues:{twoDecimalPoint:"Due punti decimali",nearestWholeNumber:"Numero intero pi\u00f9 prossimo",nearestTen:"Decimo pi\u00f9 prossimo",nearestHundred:"Centinaio pi\u00f9 prossimo",nearestThousand:"Migliaio pi\u00f9 prossimo",nearestTenThousands:"Decina di migliaia pi\u00f9 prossime"}},projectAttribute:{projectAttributeText:"Project Attribute",projectAttributeTitle:"Modifica gli attributi progetto"},costEscalation:{costEscalationLabel:"Aggiungi Additional Cost",valueHeader:"Valore",addCostEscalationText:"Aggiungi Additional Cost",
deleteCostEscalationText:"Elimina l'additional Cost selezionato",moveCostEscalationUpText:"Sposta additional Cost selezionato in alto",moveCostEscalationDownText:"Sposta additional Cost selezionato in basso",invalidEntry:"Una o pi\u00f9 voci non sono valide.",errorInSavingCostEscalation:"Impossibile salvare dettagli di costo aggiuntivi."},scenarioSelection:{popupTitle:"Selezionare Scenario per la risorsa",regionLabel:"Geografia",scenarioLabel:"Scenario",noneText:"None",copyFeatureMsg:"Copiare le feature selezionate?"},
detailStatistics:{detailStatisticsLabel:"Statistiche dettagliate",noDetailStatisticAvailable:"Nessun elemento della statistica aggiunto"},copyFeatures:{title:"Copia Feature",createFeatures:"Crea feature",createSingleFeature:"Crea 1 feature multi-geometria",noFeaturesSelectedMessage:"Nessuna feature selezionata",selectFeatureToCopyMessage:"Selezionare le feature da copiare."},_localized:{}}});