// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/keys dojo/dom-construct dojo/query dijit/_WidgetBase dijit/_TemplatedMixin jimu/dijit/ViewStack dojox/gesture/swipe dojox/gesture/tap jimu/utils".split(" "),function(r,e,t,f,h,g,k,n,u,v,w,x,y,q){var m=0;return r([u,v],{baseClass:"jimu-header-more-popup",templateString:'\x3cdiv\x3e\x3cdiv class\x3d"close" tabindex\x3d"0" data-dojo-attach-point\x3d"closeNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"pages" data-dojo-attach-point\x3d"pagesNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"points jimu-corner-bottom"\x3e\x3cdiv class\x3d"points-inner"data-dojo-attach-point\x3d"pointsNode"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
margin:4,postCreate:function(){this.nodes=[];this.pages=[];this.createCloseBtn();this.own(h(this.domNode,"keydown",e.hitch(this,function(a){f.hasClass(a.target,"close-btn")||a.keyCode!==g.ESCAPE||this.closeNode.focus()})))},startup:function(){this.viewStack=new w({views:[],viewType:"dom"},this.pagesNode);this.viewStack.startup();h(this.pagesNode,x.end,e.hitch(this,function(a){m<this.maximumPages-1&&a.dx&&0>a.dx?(m++,this._selectPage(m)):a.dx&&0<a.dx&&0<m&&(m--,this._selectPage(m))}));this.resize();
this.nodes.length&&this.nodes[0].focus()},resize:function(){var a=this._calculateGridParam(),c;null!==a?(f.setStyle(this.domNode,q.getPositionStyle(a.position)),this.nodeWidth=a.cellSize-this.margin,this.oldGridParam&&this.oldGridParam.rows===a.rows&&this.oldGridParam.cols===a.cols||(this.clearPages(),this.createPages(a)),this.nodes.forEach(e.hitch(this,function(c,d){this.setItemNodePosition(c,d,a)})),this.oldGridParam=a,c=n("div.close",this.domNode)[0],f.setStyle(c,{width:.25*this.nodeWidth+"px",
height:.25*this.nodeWidth+"px"})):(this.oldGridParam=null,f.setStyle(this.domNode,q.getPositionStyle({left:0,top:0,width:0,height:0,zIndex:111})),this.nodeWidth=0);!window.appInfo.isRunInMobile&&760<window.innerWidth&&this.numWidget&&8>=this.numWidget.length&&this.hide()},setItemNodePosition:function(a,c,b){var d,l,p=48,e=16;d=0===c%b.cols?0:this.margin/2;l=c%(b.rows*b.cols)<b.cols?0:this.margin/2;c={};"number"===typeof this.nodeWidth&&(c.width=this.nodeWidth+"px",c.height=this.nodeWidth+"px");"number"===
typeof d&&(window.isRTL?c.marginRight=d+"px":c.marginLeft=d+"px");"number"===typeof l&&(c.marginTop=l+"px");if(d=n("img",a)[0])b.iconScaled&&(p*=this.nodeWidth/120),f.setStyle(d,{width:p+"px",height:p+"px"});if(p=n("div.node-label",a)[0])b.showLabel?(b.iconScaled&&(e*=this.nodeWidth/120),f.setStyle(p,{"font-size":e+"px",display:"block"})):f.setStyle(p,{"font-size":e+"px",display:"none"});f.setStyle(a,c)},clearPages:function(){t.forEach(this.pages,function(a){this.viewStack.removeView(a.pageNode)},
this);k.empty(this.pointsNode);this.pages=[];this.nodes=[]},createPages:function(a){var c,b,d,l;this.maximumPages=c=Math.ceil(this.items.length/(a.rows*a.cols));for(b=0;b<c;b++){d=k.create("div",{"class":"page"});this.createPageItems(b,d,a);this.viewStack.addView(d);if(1<c){var f=b===c-1;l=k.create("div",{"class":"point",role:"button",tabindex:0},this.pointsNode);this.own(h(l,"click",e.hitch(this,this._onPageNodeClick,b)));this.own(h(l,"keydown",e.hitch(this,function(a,c,b){b.keyCode===g.ENTER||b.keyCode===
g.SPACE?(this._onPageNodeClick(a),n(".page.view",this.viewStack.domNode)[a].children[0].focus()):c&&!b.shiftKey&&b.keyCode===g.TAB&&b.preventDefault()},b,f)))}this.pages.push({pageNode:d,pointNode:l})}0<this.viewStack.views.length&&this._selectPage(0)},_onPageNodeClick:function(a){this._selectPage(a)},_selectPage:function(a){1<this.pages.length&&(n(".point",this.domNode).removeClass("point-selected jimu-main-background"),f.addClass(this.pages[a].pointNode,"point-selected jimu-main-background"));this.viewStack.switchView(this.pages[a].pageNode)},
createPageItems:function(a,c,b){var d,f,e;d=this.items.length;f=b.rows*b.cols;b=(a+1)*f;e=b-d;b=Math.min(b,d);for(a*=f;a<b;a++)this.createItemNode(a,c);for(a=d;a<d+e;a++)this.createEmptyItemNode(c)},createItemNode:function(a,c){var b;a=this.items[a];b=k.create("div",{"class":"icon-node jimu-float-leading jimu-main-background",title:a.label,"aria-label":a.label,settingId:a.id,"data-widget-name":a.name,role:"button",tabindex:0},c);c=k.create("img",{src:a.icon},b);window.isRTL&&a.mirrorIconForRTL&&f.addClass(c,
"jimu-flipx");k.create("div",{"class":"node-label",title:a.label,innerHTML:q.stripHTML(a.label)},b);b.config=a;this.own(h(b,y,e.hitch(this,function(){this.onNodeClicked(b)})));this.own(h(b,"keydown",e.hitch(this,function(a){if(a.keyCode===g.ENTER||a.keyCode===g.SPACE)this.onNodeClicked(b)})));this.nodes.push(b)},createEmptyItemNode:function(a){a=k.create("div",{"class":"icon-node jimu-float-leading jimu-main-background",tabindex:0},a);this.own(h(a,"focus",e.hitch(this,function(a){q.isInNavMode()&&
(1===this.viewStack.domNode.children.length?a.target.parentNode.children[0].focus():n(".point-selected",this.pointsNode)[0].previousSibling.focus())})));this.nodes.push(a);return a},createCloseBtn:function(){k.create("div",{role:"button","class":"close-inner jimu-main-background"},this.closeNode);this.own(h(this.closeNode,"click",e.hitch(this,function(){this.hide()})));this.own(h(this.closeNode,"keydown",e.hitch(this,function(a){a.keyCode===g.ENTER||a.keyCode===g.SPACE||a.keyCode===g.ESCAPE?this.hide():
a.shiftKey&&a.keyCode===g.TAB&&a.preventDefault()})));return this.closeNode},hide:function(){m=0;f.setStyle(this.domNode,"display","none")},show:function(){f.setStyle(this.domNode,"display","block")},onNodeClicked:function(a){this.hide()},openNodebyId:function(a){for(var c=0,b=this.nodes.length;c<b;c++){var d=this.nodes[c];if(a&&a===f.getAttr(d,"settingId"))return this.onNodeClicked(d),d}},_calculateGridParam:function(){var a,c,b,d,e=!1,g=!0;a=f.getContentBox(jimuConfig.mapId);c=Math.min(a.w,a.h)-
40;if(360<=c)d=120;else{d=Math.floor(c/3);if(10>d)return null;e=!0;80>d&&(g=!1)}c=Math.floor((a.h-40)/d);b=Math.floor((a.w-40)/d);c=4<c?4:c;c=3>c?3:c;b=3>c?3:4<b?4:b;return{rows:c,cols:b,cellSize:d,iconScaled:e,showLabel:g,position:{top:(a.h-d*c)/2,bottom:(a.h-d*c)/2,left:(a.w-d*b)/2,right:(a.w-d*b)/2,width:d*b-this.margin*(b-1)/2,height:d*c-this.margin*(c-1)/2,zIndex:111}}}})});