// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Flurst\u00fcckserstellung",newTraverseButtonLabel:"Neuen Polygonzug beginnen",invalidConfigMsg:"Ung\u00fcltige Konfiguration",geometryServiceURLNotFoundMSG:"URL des Geometrieservice kann nicht abgerufen werden",editTraverseButtonLabel:"Polygonzug bearbeiten",mapTooltipForStartNewTraverse:"W\u00e4hlen Sie einen Punkt auf der Karte oder einen Typ unten aus, um zu beginnen.",mapTooltipForEditNewTraverse:"W\u00e4hlen Sie ein zu bearbeitendes Flurst\u00fcck aus.",
mapTooltipForUpdateStartPoint:"Zum Aktualisieren des Startpunkts klicken",mapTooltipForScreenDigitization:"Zum Hinzuf\u00fcgen von Flurst\u00fcckspunkt klicken",mapTooltipForUpdatingRotaionPoint:"Zum Aktualisieren des Drehpunkts klicken",mapTooltipForRotate:"Zum Drehen ziehen",mapTooltipForScale:"Zum Skalieren ziehen",backButtonTooltip:"Zur\u00fcck",newTraverseTitle:"Neuer Polygonzug",editTraverseTitle:"Polygonzug bearbeiten",clearingDataConfirmationMessage:"Die \u00c4nderungen werden verworfen. M\u00f6chten Sie fortfahren?",
unableToFetchParcelMessage:"Flurst\u00fcck konnte nicht abgerufen werden.",unableToFetchParcelLinesMessage:"Flurst\u00fcckslinien konnten nicht abgerufen werden.",planSettings:{planSettingsTitle:"Einstellungen",directionOrAngleTypeLabel:"Richtungs- oder Winkeltyp",directionOrAngleUnitsLabel:"Richtungs- oder Winkeleinheiten",distanceAndLengthUnitsLabel:"Strecken- und L\u00e4ngeneinheiten",areaUnitsLabel:"Fl\u00e4cheneinheiten",circularCurveParameters:"Parameter der kreisf\u00f6rmigen Kurve",northAzimuth:"Nordazimut",
southAzimuth:"S\u00fcdazimut",quadrantBearing:"Quadrantwinkel",radiusAndChordLength:"Radius und Sehnenl\u00e4nge",radiusAndArcLength:"Radius und Kreisbogenl\u00e4nge",expandGridTooltipText:"Gitternetz erweitern",collapseGridTooltipText:"Gitternetz reduzieren",zoomToLocationTooltipText:"Auf Position zoomen",onScreenDigitizationTooltipText:"Digitalisieren",updateRotationPointTooltipText:"Drehpunkt aktualisieren"},traverseSettings:{bearingLabel:"Peilung",lengthLabel:"L\u00e4nge",radiusLabel:"Radius",
noMiscloseCalculated:"Abschlussfehler nicht berechnet",traverseMiscloseBearing:"Abschlussfehler-Peilung",traverseAccuracy:"Genauigkeit",accuracyHigh:"Hoch",traverseDistance:"Abschlussfehler-Entfernung",traverseMiscloseRatio:"Abschlussfehler-Verh\u00e4ltnis",traverseStatedArea:"Angegebene Fl\u00e4che",traverseCalculatedArea:"Berechnete Fl\u00e4che",addButtonTitle:"Hinzuf\u00fcgen",deleteButtonTitle:"Entfernen"},parcelTools:{rotationToolLabel:"Winkel",scaleToolLabel:"Ma\u00dfstab"},newTraverse:{invalidBearingMessage:"Ung\u00fcltige Peilung.",
invalidLengthMessage:"Ung\u00fcltige L\u00e4nge.",invalidRadiusMessage:"Ung\u00fcltiger Radius.",negativeLengthMessage:"Nur f\u00fcr Kurven g\u00fcltig",enterValidValuesMessage:"Geben Sie g\u00fcltige Werte ein.",enterValidParcelInfoMessage:"Geben Sie zum Speichern g\u00fcltige Informationen zum Flurst\u00fcck ein.",unableToDrawLineMessage:"Linie kann nicht gezogen werden.",invalidEndPointMessage:"Ung\u00fcltiger Endpunkt, Linie kann nicht gezogen werden."},planInfo:{requiredText:"(erforderlich)",
optionalText:"(optional)",parcelNamePlaceholderText:"Flurst\u00fccksname",parcelDocumentTypeText:"Dokumenttyp",planNamePlaceholderText:"Planname",cancelButtonLabel:"Abbrechen",saveButtonLabel:"Speichern",saveNonClosedParcelConfirmationMessage:"Das eingegebene Flurst\u00fcck ist nicht geschlossen. M\u00f6chten Sie den Vorgang trotzdem fortsetzen und nur die Flurst\u00fcckslinien speichern?",unableToCreatePolygonParcel:"Flurst\u00fcckspolygon kann nicht erstellt werden.",unableToSavePolygonParcel:"Flurst\u00fcckspolygon kann nicht gespeichert werden.",
unableToSaveParcelLines:"Flurst\u00fcckslinien k\u00f6nnen nicht gespeichert werden.",unableToUpdateParcelLines:"Flurst\u00fcckslinien k\u00f6nnen nicht aktualisiert werden.",parcelSavedSuccessMessage:"Flurst\u00fcck erfolgreich gespeichert.",parcelDeletedSuccessMessage:"Das Flurst\u00fcck wurde erfolgreich gel\u00f6scht.",parcelDeleteErrorMessage:"Fehler beim L\u00f6schen des Flurst\u00fccks.",enterValidParcelNameMessage:"Geben Sie einen g\u00fcltigen Flurst\u00fccksnamen ein.",enterValidPlanNameMessage:"Geben Sie einen g\u00fcltigen Plannamen ein.",
enterValidDocumentTypeMessage:"Ung\u00fcltiger Dokumenttyp",enterValidStatedAreaNameMessage:"Geben Sie eine g\u00fcltige angegebene Fl\u00e4che ein."},xyInput:{explanation:"Im Raumbezug des Flurst\u00fccks-Layers"},_localized:{}}});