// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/setting/nls/strings":{queries:"Interog\u0103ri",addNew:"Ad\u0103ugare nou",newQuery:"Interogare nou\u0103",queryLayer:"Strat tematic interogare",setSource:"Setare",setDataSource:"Setare surs\u0103 de date",name:"Nume",querySource:"Surs\u0103 de date",queryName:"Nume opera\u0163ie",queryDefinition:"Defini\u0163ie filtru",resultsSetting:"Setare rezultate",symbolSetting:"Setare simbol",resultSettingTip:"Defini\u0163i care sunt \u015fi cum s\u0103 fie afi\u015fate rezultatele.",
resultItemTitle:"Titlul fiec\u0103rui element rezultat",resultItemContent:"Aceste atribute de c\u00e2mpuri vor fi afi\u015fate",fieldsSetTip:"Bifa\u0163i c\u00e2mpurile care dori\u0163i s\u0103 fie afi\u015fate. Selecta\u0163i un c\u00e2mp pentru a-i actualiza pseudonimul, pentru a-l reordona sau pentru a-l formata.",addField:"Ad\u0103ugare c\u00e2mp",visibility:"Vizibilitate",alias:"Pseudonim",specialType:"Tip special",actions:"Ac\u0163iuni",none:"Niciunul",link:"Link",image:"Imagine",noField:"Niciun c\u00e2mp",
operationalLayerTip:"Ad\u0103ugare rezultat drept strat tematic opera\u0163ional",setLayerSymbolTip:"Seta\u0163i simbolul pentru rezultatele interog\u0103rii: ",setSelectedSymbolTip:"Seta\u0163i simbolul pentru obiectul spa\u0163ial selectat.",notUseFilter:"Nu se utilizeaz\u0103 filtrul",setSourceTip:"Seta\u0163i sursa interog\u0103rii.",setFilterTip:"Seta\u0163i corect filtrul.",ok:"OK",cancel:"Anulare",noFilterTip:"F\u0103r\u0103 a avea expresia de filtrare definit\u0103, aceast\u0103 opera\u0163ie de interogare va lista toate obiectele spa\u0163iale din sursa de date specificat\u0103.",
relationships:"Rela\u0163ii",addRelationshipLayer:"Ad\u0103ugare rela\u0163ie nou\u0103",relatedTo:"Referitor la",selectOption:"Selecta\u0163i...",resultItemSorting:"Sortare elemente rezultat",field:"C\u00e2mp",sortingOrder:"Ordine",configureFieldsTip:"Configura\u0163i c\u00e2mpurile dup\u0103 care vor fi sortate rezultatele interog\u0103rii.",setSortingFields:"Setare c\u00e2mpuri de sortare",ascending:"Ascendent",descending:"Descendent",sortBy:"Sortare dup\u0103",thenBy:"Apoi dup\u0103",addTask:"Ad\u0103ugare activitate",
noTasksTip:'Nicio interogare configurat\u0103. Face\u0163i clic pe "${newQuery}" pentru a ad\u0103uga una.',infoText:"Informa\u0163ii",filters:"Filtre",results:"Rezultate",optionsText:"Op\u0163iuni",summaryText:"Rezumat",attributeFilter:"Filtru atribute",attributeFilterTip:"Defini\u0163i expresiile atributelor pentru a fi utilizate \u00een widget cu scopul de a filtra stratul tematic de interog\u0103ri.",defineWhereClause:"Defini\u0163i o clauz\u0103 de loc pentru interogare.",noExpressionDefinedTip:"Nicio expresie definit\u0103. Vor fi returnate toate \u00eenregistr\u0103rile.",
setExpressions:"Setare expresii",spatialFilter:"Filtre spa\u0163iale",spatialFilterTip:"Alege\u0163i filtrele spa\u0163iale care vor fi disponibile pentru utilizatorii finali.",defaultOption:"Implicit",useCurrentExtentTip:"Se returneaz\u0103 numai obiectele spa\u0163iale din extinderea curent\u0103 a h\u0103r\u0163ii",useDrawGraphicTip:"Se returneaz\u0103 numai obiectele spa\u0163iale care se intersecteaz\u0103 cu conturul trasat pe hart\u0103",useFeaturesTip:"Se returneaz\u0103 numai obiectele spa\u0163iale care au o rela\u0163ie spa\u0163ial\u0103 cu obiectele spa\u0163iale din alt strat tematic",
noSpatialLimitTip:"Se returneaz\u0103 obiectele spa\u0163iale din \u00eentreaga extindere a h\u0103r\u0163ii",drawingTools:"Alege\u0163i instrumentele de trasare",bufferSettings:"Activa\u0163i op\u0163iunea de buffer",defaultDistance:"Distan\u0163\u0103 implicit\u0103",bufferDistance:"Distan\u0163\u0103 buffer",defaultUnit:"Unitate implicit\u0103",miles:"Mile",kilometers:"Kilometri",feet:"Ft",meters:"Metri",yards:"Iarzi",nauticalMiles:"Mile marine",availableSpatialRelationships:"Alege\u0163i regulile pentru rela\u0163iile spa\u0163iale",
setSpatialRelationships:"Setare rela\u0163ii spa\u0163iale",availability:"Disponibilitate",relationship:"Rela\u0163ie",label:"Etichet\u0103",intersect:"intersectare",contain:"con\u0163ine",areContainedIn:"sunt con\u0163inute de",cross:"cruce",envelopeIntersect:"intersectare plic",overlap:"suprapunere",areOverlapped:"sunt suprapuse",touch:"atingere",within:"\u00een",areWithin:"sunt la",indexIntersect:"intersectare index",itemTitle:"Titlu element",displayFields:"C\u00e2mpuri de afi\u015fare",sortingFields:"Sortare elemente rezultate",
setDisplayFields:"Setare c\u00e2mpuri de afi\u015fare",symbol:"Simbol",setSymbol:"Utilizare simbol personalizat",changeSymbolAtRuntime:"Permite\u0163i schimbarea simbolurilor la runtime",serviceSymbolTip:"Utiliza\u0163i simbolurile definite de stratul tematic",exportTip:"Permitere exportare rezultate",keepResultsTip:"P\u0103strare rezultate pe hart\u0103 dup\u0103 \u00eenchiderea widgetului",queryRelatedRecords:"\u00cenregistr\u0103ri legate de interog\u0103ri",createLayerForTaskTip:"Specifica\u0163i modul \u00een care interogarea creeaz\u0103 straturi tematice",
oneLayerForTaskTip:"Se suprascrie stratul tematic la fiecare executare a interog\u0103rii",multipleLayerForTaskTip:"Se creeaz\u0103 strat tematic nou la fiecare executare a interog\u0103rii",makeDefault:"Setare ca implicit",icon:"Pictogram\u0103",newTask:"Activitate nou\u0103",addTaskTip:"Ad\u0103uga\u0163i una sau mai multe interog\u0103ri \u00een widget \u015fi configura\u0163i parametri pentru fiecare dintre acestea.",webMapPopupTip:"Utiliza\u0163i configura\u0163ia ferestrei pop-up a stratului tematic de pe harta web",
customPopupTip:"Configurare con\u0163inut personalizat",showResultsSetActions:"Afi\u015fare ac\u0163iuni pentru setul de rezultate",zoomTo:"Transfocare la",openAttributeTable:"Vizualizare \u00een tabelul de atribute",content:"Con\u0163inut",displaySQLTip:"Afi\u015fare expresie SQL pentru utilizatorii finali",useLayerDefaultSymbol:"Utiliza\u0163i simbolul implicit al stratului tematic",setCustomIcon:"Setare pictogram\u0103 personalizat\u0103",layerDefaultSymbolTip:"Utiliza\u0163i simbolul implicit al stratului tematic",
uploadImage:"\u00cenc\u0103rca\u0163i o imagine",attributeCriteira:"Atribui\u0163i criterii",specifyFilterAtRuntimeTip:"Utilizatorii vor trebui s\u0103 specifice parametri pentru aceast\u0103 expresie.",value:"VALOARE",hideLayersTip:"Dezactiva\u0163i straturile tematice cu rezultate la interog\u0103ri atunci c\u00e2nd este \u00eenchis widgetul.",tabLabels:"Etichete fil\u0103",tasks:"Sarcini",queryCriteira:"Criterii interogare",allowCustomQuery:"Permite crearea unei interog\u0103ri particularizate",
showFilterLabelTip:"Afi\u0219are etichete filtre",querySettings:"Set\u0103ri interogare",expandTip:"Extinde\u021bi lista de rezultate \u00een mod implicit",customResultNameTip:"Afi\u0219are op\u021biune pentru configurare \x3cstrong\x3enume strat tematic rezultat\x3c/strong\x3e personalizat",_localized:{}}});