// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/SituationAwareness/setting/nls/strings":{tabs_section_Label:"Vahekaardid",addTab:"Lisa vahekaart",layerName:"Kiht",layerType:"Anal\u00fc\u00fcsi t\u00fc\u00fcp",layerLabel:"M\u00e4rgis",actions:"Toimingud",closest:"L\u00e4him objekt",proximity:"L\u00e4hedus",summary:"Kokkuv\u00f5te",select_lbl:"-- Vali --",general_setting_Label:"\u00dcldseaded",units_text_lbl:"Vahemaa \u00fchikud",maximum_distance_lbl:"L\u00e4hima objekti maksimaalne ulatus",buffer_text_lbl:"Puhvri m\u00e4rgis",buffer_lbl:"Puhvri ulatus",
buffer_max_lbl:"Maksimaalne puhvri ulatus",buffer_min_lbl:"Minimaalne puhvri ulatus",buffer_default_lbl:"Puhvri vaikeulatus",not_less_than_max:"Vahemaa peab olema v\u00e4iksem kui puhvri miinimumulatus",not_between:"Vahemaa peab j\u00e4\u00e4ma puhvri miinimum- ja maksimumulatuse vahele",not_more_than_min:"Vahemaa peab olema suurem kui puhvri maksimumulatus",not_valid_number:"Peab olema sobiv arv",invalid_value:"${type}-v\u00e4\u00e4rtus ei sobi",routing_checkBox:"Luba marsruutimine",weather_removed_message:"Selle vidina jaoks pole ilmavalikud enam saadaval.",
currentlySelectedLayer:"Vali kaardikihtidest",missingTabLabel:"V\u00e4hemalt \u00fchel vahekaardil puudub m\u00e4rgis.",missingLayerInWebMap:"T\u00f6\u00f6kihte ei leitud.",selectFields:"Vali v\u00e4ljad",addField:"Lisa v\u00e4li",sum:"Summa",min:"Miinimum",max:"Maksimum",avg:"Keskmine",count:"KOGUARV",area:"PINDALA",length:"PIKKUS",count_checkBox:"Kuva objektide arv",area_checkBox:"Kuva summaarne pindala",length_checkBox:"Kuva summaarne pikkus",max_records:"Limiit on t\u00e4is",save_label:"Salvestamise valikud",
save_checkbox:"Luba salvestamine",report_label:"Aruande valikud",report_checkbox:"Luba aruanne",csv_label:"CSV valikud",csv_checkbox:"Ekspordi k\u00f5ik v\u00e4ljad",display_label:"Kuvamisvalikud",display_checkbox:"Kuva kokkuv\u00f5tte objektid",snapshot_label:"Hetkt\u00f5mmise valikud",snapshot_checkbox:"Luba hetkt\u00f5mmis",must_select_template:"Valige \u00fcks salvestamise valikute muutmise mall.",count_label:"Arvu m\u00e4rgis",area_label:"Pindala m\u00e4rgis",length_label:"Pikkuse m\u00e4rgis",
invalid_string_width:"V\u00e4\u00e4rtus on liiga pikk. ",layer_type_not_supported:"S\u00e4\u00e4rast t\u00fc\u00fcpi kiht ei ole toetatud",groupedSummary:"R\u00fchmitatud koguarvud",groupByField:"R\u00fchmita veeru alusel",labelType:"Lisa m\u00e4rgis",prefix:"Eesliitena",suffix:"J\u00e4relliitena",need_group_field:"Kasutage\u00a0veeru\u00a0alusel r\u00fchmitamiseks muutmise toimingut.",fieldTitle:"V\u00e4li",typeTitle:"T\u00fc\u00fcp",actionsTitle:"Toimingud",save_point_checkbox:"Salvesta punktid",
save_line_checkbox:"Salvesta jooned",save_poly_checkbox:"Salvesta pol\u00fcgoonid",no_valid_popup_fields:"H\u00fcpikaknas pole sobivaid v\u00e4lju. Kasutage v\u00e4lja m\u00e4\u00e4ratlemiseks muutmistoimingut.",no_valid_fields:"Sobivaid v\u00e4lju pole. Kasutage valikute kuvamiseks muutmistoimingut.",incident_label:"Vahekaardi m\u00e4rgis",locate_incident_label:"Huviala m\u00e4rgise ala",incident:"Juhtum",locate_incident:"Paiguta juhtum",buffer_value:"Puhvri ulatus",tab_options:"Anal\u00fc\u00fcs",
export_options:"V\u00e4ljund",instruction_save:"Salvesta asukoht objektiteenusesse.",instruction_snapshot:"Loo asukoha p\u00f5hjal veebikaart.",instruction_report:"Loo asukoha prinditud aruanne.",instruction_all_fields:"Ekspordi k\u00f5ik v\u00e4ljad koos CSV allalaadimisega.",data_label:"Andmete v\u00e4ljastuss\u00e4tted",layer_error:"Kiht puudub v\u00f5i ei sobi.",visibility_checkBox:"Keela kihi n\u00e4htavuse haldamine",downloadTab:{reportLegend:"Aruande s\u00e4tted",textColorLabel:"Valige tulpade pealkirja v\u00e4rvus",
setButtonLabel:"M\u00e4\u00e4ra",printGPServiceLabel:"Printimise teenuse URL",logoLabel:"Logo",logoChooserHint:"Kl\u00f5psake pildi muutmiseks pildi ikooni",footnoteLabel:"Joonealune m\u00e4rkus"},roundValue:"\u00dcmarda",roundValueTitle:"\u00dcmarda v\u00e4ljav\u00e4\u00e4rtused",truncateValue:"K\u00e4rbi",truncateValueTitle:"K\u00e4rbi v\u00e4ljav\u00e4\u00e4rtused",significantFigures:"Olulised arvud",fieldOptions:"V\u00e4lja valikud",modifyValues:"Muuda v\u00e4lja v\u00e4\u00e4rtusi",validatePlaces:"Peab olema t\u00e4isarv.",
onlyDouble:"V\u00e4lja t\u00e4iendavaid valikuid toetatakse ainult numbriv\u00e4ljadel.",layerNotAvalible:"Kihti ei leitud",missingLayer:"Nimi: ${name}",missingLayerHint:"\u00dcks v\u00f5i mitu selle konfiguratsiooniga seotud kihti pole praegu saadaval.",drawGeodesic:"Joonista geodeetilised kujundid",_localized:{}}});