// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Krepko",copy:"Prekopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Zamik",insertHorizontalRule:"Vodoravno ravnilo",insertOrderedList:"O\u0161tevil\u010den seznam",insertUnorderedList:"Na\u0161tevni seznam",italic:"Le\u017ee\u010de",justifyCenter:"Poravnaj na sredino",justifyFull:"Poravnaj obojestransko",justifyLeft:"Poravnaj levo",justifyRight:"Poravnaj desno",outdent:"Primakni",paste:"Prilepi",redo:"Znova uveljavi",removeFormat:"Odstrani oblikovanje",
selectAll:"Izberi vse",strikethrough:"Pre\u010drtano",subscript:"Podpisano",superscript:"Nadpisano",underline:"Pod\u010drtano",undo:"Razveljavi",unlink:"Odstrani povezavo",createLink:"Ustvari povezavo",toggleDir:"Preklopi smer",insertImage:"Vstavi sliko",insertTable:"Vstavi/uredi tabelo",toggleTableBorder:"Preklopi na obrobo tabele",deleteTable:"Izbri\u0161i tabelo",tableProp:"Lastnost tabele",htmlToggle:"Izvorna koda HTML",foreColor:"Barva ospredja",hiliteColor:"Barva ozadja",plainFormatBlock:"Slog odstavka",
formatBlock:"Slog odstavka",fontSize:"Velikost pisave",fontName:"Ime pisave",tabIndent:"Zamik tabulatorja",fullScreen:"Preklopi na celozaslonski na\u010din",viewSource:"Prika\u017ei izvorno kodo HTML",print:"Natisni",newPage:"Nova stran",systemShortcut:'Dejanje "${0}" lahko v va\u0161em brskalniku uporabite samo z bli\u017enjico na tipkovnici. Uporabite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Velikost",fontName:"Pisava",formatBlock:"Oblika",
serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Brez",p:"Odstavek",h1:"Naslovni slog",h2:"Podnaslovni slog",h3:"Pod-podnaslovni slog",pre:"Vnaprej oblikovan",1:"xx-majhno",2:"x-majhno",3:"majhno",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Predogled ",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Najdi:",findTooltip:"Vnesite besedilo za iskanje",replaceLabel:"Zamenjaj z:",
replaceTooltip:"Vnesite besedilo za zamenjavo",findReplace:"Najdi in zamenjaj",matchCase:"Razlikuj velike in male \u010drke",matchCaseTooltip:"Razlikuj velike in male \u010drke",backwards:"Nazaj",backwardsTooltip:"Vzvratno iskanje besedila",replaceAllButton:"Zamenjaj vse",replaceAllButtonTooltip:"Zamenjaj celotno besedilo",findButton:"Najdi",findButtonTooltip:"Najdi besedilo",replaceButton:"Zamenjaj",replaceButtonTooltip:"Zamenjaj besedilo",replaceDialogText:"Zamenjanih ${0} pojavitev.",eofDialogText:"Zadnja pojavitev ${0}",
eofDialogTextFind:"najdeno",eofDialogTextReplace:"zamenjano",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Prilepi iz programa Word",instructions:"Vsebino iz programa Word prilepite v spodnje besedilno polje. Ko ste zadovoljni z vstavljeno vsebino, pritisnite gumb Vstavi. \u010ce \u017eelite prenehati z vstavljanjem vsebine, pritisnite gumb Prekli\u010di.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Vstavi sidro",title:"Lastnosti sidra",anchor:"Ime:",
text:"Opis:",set:"Nastavi",cancel:"Prekli\u010di",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokovno besedilo",_localized:{}},"widgets/Splash/setting/nls/strings":{instruction:"Pozdravni zaslon se pojavi, preden je mogo\u010de dostopati do aplikacije.",defaultContent:"Tukaj dodajte besedilo, povezave in majhne grafike.",requireConfirm:"Za nadaljevanje je potrebna potrditev.",noRequireConfirm:"Za nadaljevanje ni potrebna potrditev.",optionText:"Mo\u017enost, da uporabnik onemogo\u010di pozdravni zaslov pri zagonu aplikacije",
confirmLabel:"Potrditvena besedila: ",confirmLabelColor:"Barva potrditvenih besedil",defaultConfirmText:"Sogla\u0161am z zgornjimi dolo\u010dili in pogoji",confirmOption:"Pozdravni zaslon poka\u017ei ob zagonu aplikacije",backgroundColor:"Barva ozadja",content:"Vsebina",contentDescription:"Dolo\u010di vsebino pozdravnega zaslona",appearance:"Videz",appearanceDescription:"Nastavite videz pozdravnega zaslona.",size:"Velikost",width:"\u0160irina",height:"Vi\u0161ina",custom:"Po meri",background:"Ozadje",
colorFill:"Barvno polnilo",imageFill:"Polnilo slike",chooseFile:"Izberite datoteko",noFileChosen:"Datoteka ni izbrana",sizeFill:"Polnilo",sizeFit:"Prilagodi",sizeStretch:"Raztegni do polnitve",sizeCenter:"Na sredino",sizeTile:"Plo\u0161\u010dica",buttonColor:"Barva gumba",buttonText:"Besedilo gumba",buttonTextColor:"Barva besedila gumba",contentAlign:"Poravnava vsebine",alignTop:"Zgoraj",alignMiddle:"Na sredino",maskColor:"Barva maske",options:"Mo\u017enosti",optionsDescription:"Nastavite vedenje pozdravnega zaslona.",
_localized:{}}});