// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Aldin",copy:"Copiere",cut:"T\u0103iere","delete":"\u015etergere",indent:"Mic\u015forare indent",insertHorizontalRule:"Linie delimitatoare",insertOrderedList:"List\u0103 numerotat\u0103",insertUnorderedList:"List\u0103 cu marcator",italic:"Cursiv",justifyCenter:"Aliniere centru",justifyFull:"Aliniere st\u00e2nga-dreapta",justifyLeft:"Aliniere st\u00e2nga",justifyRight:"Aliniere dreapta",outdent:"M\u0103rire indent",paste:"Lipire",redo:"Refacere ac\u0163iune",
removeFormat:"\u00cenl\u0103turare format",selectAll:"Selecteaz\u0103 tot",strikethrough:"T\u0103iere text cu o linie",subscript:"Scriere indice inferior",superscript:"Scriere indice superior",underline:"Subliniere",undo:"Anulare ac\u0163iune",unlink:"\u00cenl\u0103turare leg\u0103tur\u0103",createLink:"Creare leg\u0103tur\u0103",toggleDir:"Comutare direc\u0163ie",insertImage:"Inserare imagine",insertTable:"Inserare/Editare tabel\u0103",toggleTableBorder:"Comutare bordur\u0103 tabel\u0103",deleteTable:"\u015etergere tabel\u0103",
tableProp:"Proprietate tabel\u0103",htmlToggle:"Surs\u0103 HTML",foreColor:"Culoare de prim-plan",hiliteColor:"Culoare de fundal",plainFormatBlock:"Stil paragraf",formatBlock:"Stil paragraf",fontSize:"Dimensiune font",fontName:"Nume font",tabIndent:"Indentare Tab",fullScreen:"Comutare ecran complet",viewSource:"Vizualizara surs\u0103 HTML",print:"Tip\u0103rire",newPage:"Pagin\u0103 nou\u0103",systemShortcut:'Ac\u0163iunea "${0}" este disponibil\u0103 \u00een browser doar utiliz\u00e2nd o comand\u0103 rapid\u0103 de la tastatur\u0103. Utiliza\u0163i ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"M\u0103rime",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Nimic",p:"Paragraf",h1:"Titlu",h2:"Subtitlu",h3:"Sub-subtitlu",pre:"Preformatat",1:"xxs (xx-small)",2:"xs (x-small)",3:"s (small)",4:"m (medium)",5:"l (large)",6:"xl (x-large)",7:"xxl (xx-large)",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Previzualizare",
_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"G\u0103sire:",findTooltip:"Introduce\u0163i textul de g\u0103sit",replaceLabel:"\u00cenlocuire cu:",replaceTooltip:"Introduce\u0163i textul cu care s\u0103 \u00eenlocui\u0163i",findReplace:"G\u0103sire \u015fi \u00eenlocuire",matchCase:"Potrivire majuscule",matchCaseTooltip:"Potrivire majuscule",backwards:"\u00cenapoi",backwardsTooltip:"C\u0103utare \u00eenapoi pentru text",replaceAllButton:"\u00cenlocuire tot",replaceAllButtonTooltip:"\u00cenlocui\u0163i tot textul",
findButton:"G\u0103sire",findButtonTooltip:"G\u0103si\u0163i text",replaceButton:"\u00cenlocuire",replaceButtonTooltip:"\u00cenlocui\u0163i text",replaceDialogText:"Au fost \u00eenlocuite ${0} apari\u0163ii.",eofDialogText:"Ultima apari\u0163ie ${0}",eofDialogTextFind:"g\u0103sit",eofDialogTextReplace:"\u00eenlocuit",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Lipire din Word",instructions:"Lipi\u0163i con\u0163inutul din Word \u00een caseta text de mai jos. C\u00e2nd sunte\u0163i satisf\u0103cut cu con\u0163inutul, pentru a insera, ap\u0103sa\u0163i butonul Lipire. Pentru a renun\u0163a la inserarea textului, ap\u0103sa\u0163i butonul Anulare.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserare ancor\u0103",title:"Propriet\u0103\u0163i ancor\u0103",anchor:"Nume:",text:"Descriere:",set:"Setare",cancel:"Anulare",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Bloc citat",_localized:{}},"widgets/Splash/setting/nls/strings":{instruction:"Ecranul de pornire apare \u00eenainte ca aplica\u0163ia s\u0103 poat\u0103 fi accesat\u0103.",defaultContent:"Ad\u0103uga\u0163i text, leg\u0103turi \u015fi alte imagini mici aici.",
requireConfirm:"Pentru a continua, este necesar\u0103 confirmarea",noRequireConfirm:"Nu este necesar\u0103 confirmarea pentru a continua",optionText:"Op\u0163iune pentru utilizator pentru dezactivarea ecranului de pornire la pornirea aplica\u0163iei.",confirmLabel:"Texte de confirmare: ",confirmLabelColor:"Culoare texte de confirmare",defaultConfirmText:"Sunt de acord cu termenii \u015fi condi\u0163iile de mai sus",confirmOption:"Afi\u015fa\u0163i acest ecran de pornire de fiecare dat\u0103 c\u00e2nd este lansat\u0103 aplica\u0163ia",
backgroundColor:"Culoare fundal",content:"Con\u0163inut",contentDescription:"Defini\u0163i con\u0163inutul care este afi\u015fat pe ecranul de pornire.",appearance:"Aspect",appearanceDescription:"Seta\u0163i aspectul ecranului de pornire.",size:"Dimensiune",width:"L\u0103\u0163ime",height:"\u00cen\u0103l\u0163ime",custom:"Personalizat",background:"Fundal",colorFill:"Umplere cu culoare",imageFill:"Umplere cu imagine",chooseFile:"Alegere fi\u015fier",noFileChosen:"Niciun fi\u015fier selectat",sizeFill:"Umplere",
sizeFit:"Potrivire",sizeStretch:"\u00centindere pentru umplere",sizeCenter:"Centru",sizeTile:"Tile",buttonColor:"Culoare buton",buttonText:"Culoare text",buttonTextColor:"Culoare text de buton",contentAlign:"Aliniere con\u0163inut",alignTop:"Sus",alignMiddle:"Mijloc",maskColor:"Culoare masc\u0103",options:"Op\u0163iuni",optionsDescription:"Seta\u0163i comportamentul ecranului de pornire.",_localized:{}}});