// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Pary\u0161kintasis",copy:"Kopijuoti",cut:"Kirpti","delete":"Pa\u0161alinti",indent:"\u012etrauka",insertHorizontalRule:"Horizontali linija",insertOrderedList:"Sunumeruotas s\u0105ra\u0161as",insertUnorderedList:"S\u0105ra\u0161as su \u017eenkleliais",italic:"Pasvirasis",justifyCenter:"Lygiuoti centre",justifyFull:"Abipus\u0117 lygiuot\u0117",justifyLeft:"Lygiuoti kair\u0117je",justifyRight:"Lygiuoti de\u0161in\u0117je",outdent:"Atvirk\u0161tin\u0117 \u012ftrauka",
paste:"\u012eklijuoti",redo:"Gr\u0105\u017einti",removeFormat:"Pa\u0161alinti formatavim\u0105",selectAll:"\u017dym\u0117ti visk\u0105",strikethrough:"Perbrauktasis",subscript:"Apatinis indeksas",superscript:"Vir\u0161utinis indeksas",underline:"Pabrauktasis",undo:"At\u0161aukti",unlink:"Pa\u0161alinti nuorod\u0105",createLink:"Kurti nuorod\u0105",toggleDir:"Perjungti krypt\u012f",insertImage:"\u012eterpti vaizd\u0105",insertTable:"\u012eterpti / redaguoti vaizd\u0105",toggleTableBorder:"Perjungti lentel\u0117s kra\u0161tin\u0119",
deleteTable:"Pa\u0161alinti lentel\u0119",tableProp:"Lentel\u0117s savyb\u0117",htmlToggle:"HTML \u0161altinis",foreColor:"Priekinio plano spalva",hiliteColor:"Fono spalva",plainFormatBlock:"Pastraipos stilius",formatBlock:"Pastraipos stilius",fontSize:"\u0160rifto dydis",fontName:"\u0160rifto pavadinimas",tabIndent:"Tabuliacijos \u012ftrauka",fullScreen:"Perjungti vis\u0105 ekran\u0105",viewSource:"Per\u017ei\u016br\u0117ti HTML \u0161altin\u012f",print:"Spausdinti",newPage:"Naujas puslapis",systemShortcut:'"${0}" veiksm\u0105 galima atlikti nar\u0161ykl\u0117je tik naudojant spart\u0173j\u012f klavi\u0161\u0105. Naudokite ${1}.',
ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dydis",fontName:"\u0160riftas",formatBlock:"Formatuoti",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"N\u0117ra",p:"Pastraipa",h1:"Antra\u0161t\u0117",h2:"Paantra\u0161t\u0117",h3:"Antrin\u0117 paantra\u0161t\u0117",pre:"I\u0161 anksto suformatuota",1:"xx ma\u017eas",2:"x ma\u017eas",3:"ma\u017eas",4:"vidutinis",5:"didelis",6:"x didelis",
7:"xx didelis",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",
findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/NetworkTrace/setting/nls/strings":{taskUrl:"U\u017eduoties URL",setTask:"Taikyti",setTaskPopupTitle:"Nustatyti u\u017eduot\u012f",validate:"Taikyti",inValidGPService:"\u012eveskite leistin\u0105 geoduomen\u0173 apdorojimo paslaug\u0105.",
GPFeatureRecordSetLayerERR:"\u012eveskite geoduomen\u0173 apdorojimo paslaug\u0105 naudodami tik GPFeatureRecordSetLayer tipo \u012fvestis.",invalidInputParameters:"\u012evesties parametr\u0173 skai\u010dius yra ma\u017eesnis nei 1 arba didesnis nei 3. \u012eveskite leistin\u0105 geoduomen\u0173 apdorojimo paslaug\u0105.",projectSetting:{title:"Projekto nustatymai",note:"Pastaba: projekto nustatymai yra pasirinktiniai, juos sukonfig\u016brav\u0119s vartotojas gali i\u0161saugoti projekt\u0105 norimuose internetinio \u017eem\u0117lapio sluoksniuose su tinklo nutr\u016bkimo teritorija ir \u012fvesties parametrais. Vartotojas gali i\u0161saugoti kitus i\u0161vesties parametrus skirtuko \u012evestis / i\u0161vestis grup\u0117je I\u0161vestis.",
projectPolygonLayer:"Projekto poligon\u0173 sluoksnis",outputParameterName:"I\u0161vesties parametro pavadinimas",projectPointLayer:"Projekto ta\u0161k\u0173 sluoksnis",selectLabel:"Pasirinkti",polygonLayerHelp:"\x3cp\x3eBus rodomas (-i) poligon\u0173 sluoksnis (-iai), esant \u0161ioms s\u0105lygoms:\x3cbr/\x3e\x3cli\x3eSluoksnyje turi b\u016bti redagavimo galimyb\u0117s, t. y. Kurti, I\u0161trinti ir Atnaujinti\x3c/li\x3e\x3cli\x3eSluoksnyje turi b\u016bti 2 laukai su tiksliai tokiu pa\u010diu pavadinimu ir duomen\u0173 tipu:\x3c/li\x3e\x3cul\x3e\x3cli\x3ename (tekstinio tipo laukas)\x3c/li\x3e\x3cli\x3eglobalid (GlobalID tipo laukas)\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
outputParameterHelp:"\x3cp\x3eBus rodomas (-i) i\u0161vesties poligon\u0173 sluoksnis (-iai) i\u0161 u\u017eduoties URL\x3cp/\x3e",pointLayerHelp:"\x3cp\x3eBus rodomas (-i) ta\u0161k\u0173 sluoksnis (-iai), esant \u0161ioms s\u0105lygoms:\x3cbr/\x3e\x3cli\x3eSluoksnyje turi b\u016bti redagavimo galimyb\u0117s, t. y. Kurti, I\u0161trinti ir Atnaujinti\x3c/li\x3e\x3cli\x3eSluoksnyje turi b\u016bti 2 laukai su tiksliai tokiu pa\u010diu pavadinimu ir duomen\u0173 tipu:\x3c/li\x3e\x3cul\x3e\x3cli\x3einputtype (tekstinio tipo laukas)\x3c/li\x3e\x3cli\x3eprojectid (GUID tipo laukas)\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e"},
inputOutputTab:{title:"\u012evestis / i\u0161vestis",inputSettingsLabel:"\u012evesties nustatymai",outputSettingsLabel:"I\u0161vesties nustatymai",inputLabel:"Klas\u0117",inputTooltip:"\u012erankio u\u017euomina",symbol:"Simbolis",typeText:"Tipas",outputParametersText:"I\u0161vesties parametrai",saveToLayerText:"\u012era\u0161yti \u012f sluoksn\u012f (pasirinktinai)",skipText:"Galima praleisti",visibilityText:"Matoma",exportToCsvText:"Eksportuoti \u012f CSV",exportToCsvDisplayText:"CSV",settitngstext:"Parametrai",
addFieldTitle:"Prid\u0117ti lauk\u0105",enterDisplayText:"\u012eveskite rodoma tekst\u0105",setScale:"Nustatyti mastel\u012f",outputDisplay:"Rodyti tekst\u0105",saveToLayerHelp:"\x3cp\x3eBus rodomas sluoksnis, esant \u0161ioms s\u0105lygoms:\x3cbr/\x3e\x3cli\x3eSluoksnyje turi b\u016bti redagavimo galimyb\u0117s, t. y. Kurti, I\u0161trinti ir Atnaujinti\x3c/li\x3e\x3cli\x3eSluoksnyje turi b\u016bti du laukai su pavadinimu ir duomen\u0173 tipu:\x3c/li\x3e\x3cul\x3e\x3cli\x3eparametername (tekstinio tipo laukas)\x3c/li\x3e\x3cli\x3eprojectid (GUID tipo laukas)\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e"},
summaryTab:{title:"Santrauka",summaryFieldsetText:"Santraukos nustatymai",inputOutput:"\u012evestys / i\u0161vestys",field:"Laukai",operator:"Operatoriai",inputOperatorCountOption:"Skai\u010dius",outputOperatorCountOption:"Skai\u010dius",outputOperatorSkipCountOption:"SkipCount",fieldOperatorSumOption:"Suma",fieldOperatorMinOption:"Min.",fieldOperatorMaxOption:"Maks.",fieldOperatorMeanOption:"Vidurkis",expressionAddButtonText:"Prid\u0117ti",expressionVerifyButtonText:"Tikrinti",summaryEditorText:"Santraukos tekstas"},
generalSettings:{title:"Bendrieji parametrai",displayTextForButtonLegend:"Rodyti mygtuko Vykdyti tekst\u0105",displayTextforButtonDefaultValue:"Vykdyti",displayTextForButton:"Rodyti tekst\u0105",autoZoomAfterTrace:"Mastelio keitimo parinktys",zoomText:"Automatinis mastelio keitimas po trasavimo"},validationErrorMessage:{webMapError:"Internetiniame \u017eem\u0117lapyje sluoksni\u0173 n\u0117ra. Pasirinkite galiojant\u012f internetin\u012f \u017eem\u0117lap\u012f.",inputTypeFlagGreaterThanError:"V\u0117liav\u0117l\u0117s tipo \u012fvestis negali b\u016bti didesn\u0117 nei vienas.",
inputTypeFlagLessThanError:"B\u016btina bent viena v\u0117liav\u0117l\u0117s tipo \u012fvestis.",inputTypeBarrierErr:"Kli\u016bties tipo \u012fvestis negali b\u016bti didesn\u0117 nei vienas.",inputTypeSkipErr:"Praleidimo tipo \u012fvestis negali b\u016bti didesn\u0117 nei vienas.",displayTextForButtonError:"Negali neb\u016bti mygtuko Vykdyti rodymo teksto.",UnableToLoadGeoprocessError:"Nepavyksta \u012fkelti geoduomen\u0173 apdorojimo paslaugos.",invalidSummaryExpression:"Netinkama i\u0161rai\u0161ka.",
validSummaryExpression:"Pavyko!",invalidProjectSettings:"Netinkami projekto nustatymai.\x3cbr/\x3eDalyje ${projectSetting} pasirinkite tinkam\u0105 reik\u0161m\u0119."},hintText:{labelTextHint:"Patarimas: pateikite i\u0161vesties parametro rezultat\u0173 skil\u010diai rodom\u0105 u\u017era\u0161\u0105.",displayTextHint:"Patarimas: tai bus rodoma \u0161io i\u0161vesties parametro i\u0161samios informacijos skiltyje.",inputTextHint:"Patarimas: auk\u0161\u010diau sukurkite i\u0161rai\u0161k\u0105, pasirinkdami \u012fvesties, i\u0161vesties ir lauk\u0173 pavadinimus.",
expressionHint:"Patarimas: pasirinkite elementus ir spustel\u0117kite \u012etraukti, kad sukurtum\u0117te i\u0161rai\u0161k\u0105."},_localized:{}}});