// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/SmartEditor/setting/layerAndFieldsApplyOn.html":'\x3cdiv data-dojo-attach-point \x3d "layerAndFieldsMainDiv"\x3e\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/on jimu/BaseWidgetSetting dijit/_TemplatedMixin jimu/dijit/CheckBox jimu/utils dojo/dom-attr dojo/dom-class dojo/query dojo/string dojo/text!./layerAndFieldsApplyOn.html".split(" "),function(u,k,h,l,q,v,w,t,x,m,r,n,y,z){return u([v,w],{baseClass:"jimu-widget-smartEditor-setting-layersAndFieldsApplyOn",templateString:z,checkBoxNodes:null,layerCheckBoxNodes:null,defalutFieldInfos:[{actionName:"Intersection",enabled:!1,
fields:[]},{actionName:"Address",enabled:!1},{actionName:"Coordinates",enabled:!1,coordinatesSystem:"MapSpatialReference",field:"x"},{actionName:"Preset",enabled:!1}],nlsActionName:{Intersection:"Intersection1",Address:"Address1",Coordinates:"Coordinates1",Preset:"Preset1"},postCreate:function(){this.inherited(arguments);this.nlsActionName={Intersection:this.nls.actionPage.copyAction.intersection,Address:this.nls.actionPage.copyAction.address,Coordinates:this.nls.actionPage.copyAction.coordinates,
Preset:this.nls.actionPage.copyAction.preset};this.layerCheckBoxNodes={};this.checkBoxNodes={};this._prevAppliedOnLayers=[];this.appliedOn&&(this._prevAppliedOnLayers=k.clone(Object.keys(this.appliedOn)));this._addLayerAndFields()},_mergeFieldValuesForPreset:function(c){var b={},a=[],a=this._getAllLayersFieldValues(a,this._configInfos,c);for(c=0;c<a.length;c++){var d=a[c],e;for(e in d)if(b.hasOwnProperty(e))for(var f=0;f<d[e].length;f++){var g=d[e][f];if(g.actionName===this.actionName&&g.enabled&&
(!this.prevName||!g.hasOwnProperty("attributeActionGroupName")||g.hasOwnProperty("attributeActionGroupName")&&g.attributeActionGroupName!==this.prevName))for(var p=0;p<b[e].length;p++)b[e][p].actionName===this.actionName&&(b[e][p]=g)}else b[e]=d[e]}return b},_addLayerAndFields:function(){var c,b=[],a;c=this.layerDetails;for(var d in c)if(0<Object.keys(c[d]).length){a=l.create("div",{"class":"esriCTLayerMainDiv"},this.layerAndFieldsMainDiv);this._createLayerName(a,d);a="Preset"===this.actionName?this._mergeFieldValuesForPreset(d):
this._getLayersFieldValues(d);this.appliedOn&&this.appliedOn.hasOwnProperty(d)&&0<this.appliedOn[d].length&&b.push(d);for(var e in c[d])if(c[d][e].editable){var f=!1,g=l.create("div",{"class":"esriCTFieldsDiv  esriCTHidden"},this.layerAndFieldsMainDiv);m.set(g,"layerid",d);a&&a.hasOwnProperty(e)&&h.some(a[e],function(a){if(a.actionName===this.actionName&&a.enabled&&(!a.hasOwnProperty("attributeActionGroupName")||a.hasOwnProperty("attributeActionGroupName")&&a.attributeActionGroupName!==this.prevName))return f=
!0},this);this._createFieldName(c[d][e],d,g,f)}}0<b.length&&setTimeout(k.hitch(this,function(){this._applyPrevSettings();h.forEach(b,k.hitch(this,function(a){var b=n('[rootnodelayerid\x3d"'+a+'"]');b&&0<b.length&&r.contains(b[0],"esriCTToggleLayerExpanded")&&(n('[rootnodelayerid\x3d"'+a+'"]').toggleClass("esriCTToggleLayerExpanded"),n('[layerid\x3d"'+a+'"]').toggleClass("esriCTHidden"))}))}),100)},_createLayerName:function(c,b){var a,d,e;this.layerCheckBoxNodes[b]=[];this.checkBoxNodes[b]=[];this.layerInfos.getLayerOrTableInfoById(b)&&
(a=this.layerInfos.getLayerOrTableInfoById(b).layerObject.name,d=l.create("div",{"class":"esriCTToggleLayerIcon esriCTToggleLayerCollapsed esriCTToggleLayerExpanded"},c),m.set(d,"rootnodelayerid",b),this.own(q(d,"click",k.hitch(this,function(a){r.toggle(a.currentTarget,"esriCTToggleLayerExpanded");e=m.get(a.currentTarget,"rootnodelayerid");n('[layerid\x3d"'+e+'"]').toggleClass("esriCTHidden")}))),c=l.create("div",{"class":"esriCTLayercheckBox"},c),l.create("div",{innerHTML:a},c),a=new t({label:a,
checked:!1}),this.layerCheckBoxNodes[b].push(a),m.set(a.domNode,"LayerCheckBoxId",b),q(a.domNode,"click",k.hitch(this,this._parentNodeStateChanged)))},_getLayersFieldValues:function(c){var b;h.some(this._configInfos,function(a){if(a.featureLayer&&a.featureLayer.id===c)return a.fieldValues?b=a.fieldValues:a.fieldValues={},!0},this);return b},_getAllLayersFieldValues:function(c,b,a){h.forEach(b,function(b){b.featureLayer&&b.featureLayer.id===a&&(b.fieldValues?c||(c=[]):b.fieldValues={},c.push(b.fieldValues));
b.relationshipInfos&&(c=this._getAllLayersFieldValues(c,b.relationshipInfos,a))},this);return c},_createFieldName:function(c,b,a,d){c=x.getDefaultPortalFieldInfo(c);var e=y.substitute(this.nls.attributeActionsPage.alreadyAppliedActionMsg,{action:this.nlsActionName[this.actionName]}),e=l.create("div",{"class":"esriCTExistingExpressionDiv esriCTVisibilityHidden",title:e},a);d&&r.remove(e,"esriCTVisibilityHidden");a=l.create("div",{"class":"esriCTFieldsCheckBox"},a);a=new t({label:c.label,value:c.fieldName,
checked:!1},a);this.checkBoxNodes[b].push(a);m.set(a.domNode,"fieldsCheckBoxId",b);q(a.domNode,"click",k.hitch(this,this._childNodeStateChanged))},_parentNodeStateChanged:function(c){var b,a;b=m.get(c.currentTarget,"LayerCheckBoxId");c=this.layerCheckBoxNodes[b];b=this.checkBoxNodes[b];a=c[0].getValue();h.forEach(b,k.hitch(this,function(b){a?b.setValue(!0):b.setValue(!1)}))},_childNodeStateChanged:function(c){var b,a;b=m.get(c.currentTarget,"fieldsCheckBoxId");c=this.layerCheckBoxNodes[b];b=this.checkBoxNodes[b];
a=!0;h.some(b,k.hitch(this,function(b){if(!b.getValue())return a=!1,!0}));c[0].setValue(a)},getCheckedFields:function(c){var b={},a;for(a in this.checkBoxNodes){b[a]=[];for(var d in this.checkBoxNodes[a])this.checkBoxNodes[a][d].checked&&b[a].push(this.checkBoxNodes[a][d].get("value"))}this._applySettingsInLayer(c,b);return b},_removeSettingsFromOtherGroups:function(c,b,a){var d;if(this.existingGroups)for(var e in this.existingGroups)if(e!==c&&e!==this.prevName&&(d=this.existingGroups[e].appliedOn)&&
d.hasOwnProperty(b)&&-1<d[b].indexOf(a)){var f=d[b].indexOf(a);d[b].splice(f,1)}},_removePrevSettingsFromLayerFields:function(c){var b=[];if((b=this._getAllLayersFieldValues(b,this._configInfos,c))&&0<b.length)for(var a=0;a<b.length;a++)if(c=b[a])for(var d in c)for(var e=c[d],f=0;f<e.length;f++)e[f].actionName===this.actionName&&e[f].hasOwnProperty("attributeActionGroupName")&&e[f].attributeActionGroupName===this.prevName&&(e[f].enabled=!1,delete e[f].attributeActionGroupName,"Intersection"===this.actionName?
(e[f].fields=[],e[f].ignoreLayerRanking=!1):"Address"===this.actionName?delete e[f].field:"Coordinates"===this.actionName&&(e[f].coordinatesSystem="MapSpatialReference",e[f].field="x"))},_applysettingsToField:function(c,b,a){var d,e=[];if((e=this._getAllLayersFieldValues(e,this._configInfos,c))&&0<e.length){for(var f=0;f<e.length;f++)if(d=e[f],this.appliedOn&&this.appliedOn.hasOwnProperty(c)){var g=this.appliedOn[c];g&&0<g.length&&h.forEach(g,function(a){if(-1===b.indexOf(a)&&d.hasOwnProperty(a)){a=
d[a];for(var c=0;c<a.length;c++)a[c].actionName===this.actionName&&(a[c].enabled=!1,delete a[c].attributeActionGroupName,"Intersection"===this.actionName?(a[c].fields=[],a[c].ignoreLayerRanking=!1):"Address"===this.actionName?delete a[c].field:"Coordinates"===this.actionName&&(a[c].coordinatesSystem="MapSpatialReference",a[c].field="x"))}},this)}h.forEach(b,function(b){for(var f=0;f<e.length;f++){var g;d=e[f];d.hasOwnProperty(b)||(d[b]=k.clone(this.defalutFieldInfos));g=d[b];for(var h=0;h<g.length;h++)g[h].actionName===
this.actionName&&(a.attributeInfo&&(g[h]=k.mixin(g[h],a.attributeInfo)),g[h].enabled=!0,g[h].attributeActionGroupName=a.name,"Preset"===this.actionName&&this._configuredPresetInfos&&(this._configuredPresetInfos[b]=a.presetValue),this._removeSettingsFromOtherGroups(a.name,c,b))}},this)}},_applySettingsInLayer:function(c,b){for(var a in b){var d;this._prevAppliedOnLayers&&-1<this._prevAppliedOnLayers.indexOf(a)&&(d=this._prevAppliedOnLayers.indexOf(a),this._prevAppliedOnLayers.splice(d,1));this._applysettingsToField(a,
b[a],c)}this.deleteGroup()},deleteGroup:function(){this._prevAppliedOnLayers&&h.forEach(this._prevAppliedOnLayers,function(c){this._removePrevSettingsFromLayerFields(c)},this)},_applyPrevSettings:function(){if(this.appliedOn)for(var c in this.appliedOn)if(this.appliedOn.hasOwnProperty(c)){var b=this.appliedOn[c];if(b&&0<b.length){var a=this.layerCheckBoxNodes[c],d=!0;h.forEach(this.checkBoxNodes[c],k.hitch(this,function(a){-1<b.indexOf(a.value)?a.setValue(!0):a.getValue()||(d=!1)}));d&&a&&a[0]&&a[0].setValue(d)}}}})});