// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Rasvane",copy:"Kopeeri",cut:"L\u00f5ika","delete":"Kustuta",indent:"Paremtaane",insertHorizontalRule:"Horisontaaljoon",insertOrderedList:"Nummerdatud loend",insertUnorderedList:"T\u00e4pploend",italic:"Kursiiv",justifyCenter:"Keskjoondus",justifyFull:"R\u00f6\u00f6pjoondus",justifyLeft:"Vasakjoondus",justifyRight:"Paremjoondus",outdent:"Vasaktaane",paste:"Kleebi",redo:"Tee uuesti",removeFormat:"Eemalda vorming",selectAll:"Vali k\u00f5ik",strikethrough:"L\u00e4bikriipsutus",
subscript:"Allindeks",superscript:"\u00dclaindeks",underline:"Allajoonitud",undo:"T\u00fchista",unlink:"Eemalda link",createLink:"Loo link",toggleDir:"Vaheta suund",insertImage:"Sisesta pilt",insertTable:"Lisa/muuda tabelit",toggleTableBorder:"L\u00fclita tabeli\u00e4\u00e4ris sisse/v\u00e4lja",deleteTable:"Kustuta tabel",tableProp:"Tabeli atribuut",htmlToggle:"HTML-l\u00e4htetekst",foreColor:"Esiv\u00e4rv",hiliteColor:"Taustav\u00e4rv",plainFormatBlock:"L\u00f5igu laad",formatBlock:"L\u00f5igu laad",
fontSize:"Fondi suurus",fontName:"Fondi nimi",tabIndent:"Tabeldustaane",fullScreen:"L\u00fclita t\u00e4isekraan sisse/v\u00e4lja",viewSource:"Kuva HTML-l\u00e4htetekst",print:"Prindi",newPage:"Uus leht",systemShortcut:"Seda toimingut ${0} saab Teie brauseris teha ainult kiirklahvi abil. Kasutage klahvikombinatsiooni ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"now","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["AH"],"field-tue-relative+-1":"last Tuesday","days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G y MMMM d",
"field-fri-relative+-1":"last Friday","field-wed-relative+-1":"last Wednesday","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"G y MMMM d, EEEE","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","field-thu-relative+-1":"last Thursday","dateFormatItem-Md":"MM-dd",
"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["Q1","Q2","Q3","Q4"],"timeFormat-long":"HH:mm:ss z","field-year":"Year","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hour",
"months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"today","field-thu-relative+0":"this Thursday","field-day-relative+1":"tomorrow","field-thu-relative+1":"next Thursday","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"this Sunday","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"next Sunday","quarters-standAlone-abbr":["Q1",
"Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Dayperiod","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"yesterday","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"this Friday",
"field-fri-relative+1":"next Friday","field-day":"Day","days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"field-zone":"Zone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"last year","field-month-relative+-1":"last month","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM",
"days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"Month","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","dateFormat-short":"GGGGG y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second","field-sat-relative+-1":"last Saturday","field-sun-relative+-1":"last Sunday","field-month-relative+0":"this month","field-month-relative+1":"next month","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d, E","field-week":"Week",
"dateFormat-medium":"G y MMM d","field-week-relative+-1":"last week","field-year-relative+0":"this year","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"next year","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"last Monday","dateFormatItem-yyyy":"G y","field-week-relative+0":"this week","field-week-relative+1":"next week",
_localized:{}},"widgets/NetworkTrace/nls/strings":{_widgetLabel:"V\u00f5rguj\u00e4litus",configError:"Vidin ei ole \u00f5igesti konfigureeritud.",clearButtonValue:"T\u00fchista",GPExecutionFailed:"J\u00e4litust ei saa l\u00f5petada. Palun proovige uuesti",backButtonValue:"Tagasi",exportToCSVSuccess:"Eksportimine CSV-formaati oli edukas.",lblInputLocTab:"Sisendi asukohad",lblBlockLocTab:"Blokeeri asukohad",lblInputLocation:"Sisendobjekt",lblBlockLocation:"Blokeeri objekt",lblInputLocHeader:"Sisendi asukohad (0)",
lblBlockLocHeader:"Blokeeri asukohad (0)",inputTabTitle:"Sisend",outputTabTitle:"V\u00e4ljund",exportSelectAllCheckBoxLabel:"Vali k\u00f5ik",lblSkipLocHeader:"J\u00e4ta asukohad vahele (0)",lblSkipLocation:"Asukoht",lblSkipLocTab:"J\u00e4ta asukohad vahele",skipAllLocationButtonLabel:"J\u00e4ta k\u00f5ik asukohad vahele",allLocationSkippedMessage:"K\u00f5ik asukohad j\u00e4eti vahele",locationAlreadySkippedMessage:"Asukoht on juba vahele j\u00e4etud",locationSkippedMessage:"Asukoht j\u00e4eti vahele",
removeAllSkipLocationLabel:"Eemalda k\u00f5ik",newProjectOptionText:"Uus projekt",saveButtonLabel:"Salvesta",exportToCSVText:"Ekspordi CSV-formaati",editProjectAttributesToolTip:"Redigeeri projekti atribuute",projectNameLabel:"Projekti nimi",saveProjectPopupTitle:"Salvesta",saveAsLabel:"Salvesta nimega",saveChangesMsg:"Kas soovite salvestada oma muudatused nimega \x3cb\x3e${loadProjectDropdownlabel}\x3c/b\x3e v\u00f5i uue projektina?",creatingNewProjectErrorMessage:"Viga uue projekti loomisel. Palun proovige uuesti",
projectNameFetchingErr:"Viga olemasolevate projektinimede toomisel. Palun proovige uuesti",projectAttributeLoadingErr:"Viga projekti atribuutide laadimisel. Palun proovige uuesti",attributeUpdatedMsg:"Atribuudid uuendati edukalt.",projectAttributeUpdatingErr:"Viga projekti atribuutide uuendamisel.",loadingProjectDetailsErrorMessage:"Viga lipikute, t\u00f5kete ja vahelej\u00e4etud asukohtade toomisel. Palun proovige uuesti",savingProjectDetailsErr:"Viga projekti \u00fcksikasjade salvestamisel. Palun proovige projekti uuesti salvestada.",
updatingOutagePolygonErr:"Viga katkestatud hulknurga uuendamisel. Palun proovige projekti uuesti salvestada.",deletingExistingPolygonErr:"Viga olemasoleva katkestatud hulknurga kustutamisel. Palun proovige projekti uuesti salvestada.",loadingProjectFeaturesErr:"Viga projekti objektide laadimisel. Palun proovige projekti uuesti laadida.",addingProjectFeaturesErr:"Viga projekti objektide lisamisel. Palun proovige projekti uuesti salvestada.",deletingExistingProjectFeaturesErr:"Viga projekti olemasolevate omaduste kustutamisel. Palun proovige projekti uuesti salvestada.",
projectNotFoundErr:"Projekti ei leitud",projectLayersNotFound:"Projekti konfigureeritud seadekihid ei ole kaardil saadaval. Vidinat ei saa laadida \u201evisandi re\u017eiimis\u201c.",fetchingOutagePolygonMessage:"Viga katkestatud hulknurga toomisel. Palun proovige projekti uuesti laadida.",projectNameExistsMessage:"Projekti nimi on juba olemas. Sisestage projekti unikaalne nimi.",fetchingProjectNamesErrorMessage:"Viga olemasolevate projektinimede toomisel. Palun proovige projekti uuesti salvestada.",
enterProjectNameMessage:"Sisestage projekti nimi.",projectLengthErrorMessage:"Projekti nimi ei tohi olla pikem kui",gpServiceNotAccessible:"Teie kontol pole juurdep\u00e4\u00e4su selle j\u00e4lituse l\u00e4biviimiseks vajalikule teenusele.",loadingClonedLayerErrorMessage:"Viga kloonitud objektikihi laadimisel. Palun proovige uuesti",addingFeatureInClonedLayerError:"Viga graafika lisamisel kloonitud objektikihile. Palun proovige uuesti",selectingFeatureInClonedLayerError:"Viga graafika valimisel kloonitud objektikihis. Palun proovige uuesti",
filteredProjectError:"Viga filtreeritud projekti \u00fcksikasjade toomise kontrollimisel. Palun proovige uuesti",filteredProjectMessage:"Projekti valitud atribuudid ei ole saadaval filtrite t\u00f5ttu, mida rakendatakse veebikaardilt v\u00f5i m\u00f5nelt muult vidinalt. Kustutage filter (filtrid) ja proovige uuesti.",filteredProjectLoadMessage:"Teie projekt ei ole enam saadaval. Palun valige aktiivne projekt.",defaultValueForRunButton:"K\u00e4ivita",_localized:{}}});