// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/columnHider":{popupTriggerLabel:"Show or hide columns",popupLabel:"Wy\u015bwietl lub ukryj kolumny",_localized:{}},"widgets/AttributeTable/nls/strings":{_widgetLabel:"Tabela atrybut\u00f3w",_featureAction_ShowRelatedRecords:"Poka\u017c powi\u0105zane rekordy",_featureAction_ViewInTable:"Wy\u015bwietl w tabeli atrybut\u00f3w",ok:"OK",cancel:"Anuluj",unsupportQueryWarning:"Warstwa musi obs\u0142ugiwa\u0107 zapytania w celu wy\u015bwietlenia w wid\u017cecie tabeli atrybut\u00f3w. Upewnij si\u0119, \u017ce funkcja zapytania w us\u0142udze jest w\u0142\u0105czona.",
exportMessage:"Wyeksportowa\u0107 dane do pliku CSV?",exportFiles:"Eksportuj do pliku CSV",exportSelected:"Eksportuj wybrane do pliku CSV",exportAll:"Eksportuj wszystko do pliku CSV",options:"Opcje",zoomto:"Powi\u0119ksz do",highlight:"Wyr\u00f3\u017cnij grafik\u0119",selectAll:"Zaznacz rekordy na wszystkich stronach",selectPage:"Zaznacz rekordy na bie\u017c\u0105cej stronie",clearSelection:"Clear selection",filter:"Filtruj",setFilterTip:"Skonfiguruj poprawnie filtry.",noFilterTip:"Je\u015bli wyra\u017cenia filtr\u00f3w nie zostan\u0105 zdefiniowane, zadanie zapytania zwr\u00f3ci wszystkie obiekty w podanym \u017ar\u00f3dle danych.",
filterByExtent:"Filtrowanie wed\u0142ug zasi\u0119gu mapy",showSelectedRecords:"Poka\u017c wybrane rekordy",showAllRecords:"Poka\u017c wszystkie rekordy",showRelatedRecords:"Poka\u017c powi\u0105zane rekordy",noRelatedRecords:"Nie znaleziono powi\u0105zanych rekord\u00f3w",highlightAllRecords:"Wyr\u00f3\u017cnij wszystkie rekordy na mapie",attachmentColumn:"Zdj\u0119cia i pliki",refresh:"Od\u015bwie\u017c",features:"obiekty",records:"rekordy",selected:"wybrane",transparent:"Tryb przezroczysty",indicate:"Zlokalizuj wybrane",
columns:"Poka\u017c/ukryj kolumny",selectionSymbol:"Symbol selekcji",closeMessage:"Ukryj tabel\u0119 (rozwi\u0144 j\u0105 ponownie od do\u0142u)",dataNotAvailable:"Dane s\u0105 niedost\u0119pne!\x3cbr\x3eKliknij przycisk [Od\u015bwie\u017c], aby ponowi\u0107 pr\u00f3b\u0119.",openTableTip:"Otw\u00f3rz tabel\u0119 atrybut\u00f3w",closeTableTip:"Ukryj tabel\u0119 atrybut\u00f3w",sortAsc:"Sortuj rosn\u0105co",sortDes:"Sortuj malej\u0105co",statistics:"Statystyka",attachments:"Za\u0142\u0105czniki",files:"plikami",
keepRichTextLabel:"Zachowaj format RTF",whatsThis:"Co to jest?",richTextMessage:{explanatoryText:{line1:"Warstwa ${layerName} zawiera nast\u0119puj\u0105ce pola w formacie RTF: ",line2:" , kt\u00f3re mog\u0105 zawiera\u0107 style formatowania tekstu, jak np. czcionki, kolory i rozmiary tekstu.",line3:'Po wyeksportowaniu do pliku CSV style formatowania zostan\u0105 zachowane w postaci znacznik\u00f3w HTML. Mo\u017cna zdecydowa\u0107, \u017ce format RTF nie zostanie zachowany, usuwaj\u0105c zaznaczenie pola "Zachowaj format RTF".'},
example:{label:"Przyk\u0142ad:",scenarios:{first:"zostanie wyeksportowany domy\u015blnie jako poni\u017cszy tekst:",second:"i poni\u017cszy tekst bez formatu RTF:"}}},noTablesAvailable:"Brak tabel dost\u0119pnych do wy\u015bwietlenia.",checkConfigutationToSelectLayers:"Przejd\u017a na stron\u0119 ustawie\u0144 wid\u017cetu, aby wybra\u0107 warstwy.",checkLayerListToSelectLayers:"Tabela atrybut\u00f3w jest synchronizowana z warstwami widocznymi na mapie, warstwy mo\u017cna w\u0142\u0105cza\u0107 i wy\u0142\u0105cza\u0107 przy u\u017cyciu wid\u017cetu, takiego jak Lista warstw.",
_localized:{}}});