// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/on dojo/string dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/_base/array dojo/dom-construct esri/graphic jimu/dijit/Message dijit/_WidgetBase ./presetUtils dojo/query esri/tasks/RelationshipQuery dojo/dom-geometry dojo/dom-class".split(" "),function(t,u,p,v,k,q,g,n,l,w,r,x,y,f,z,A,m){return t([x,u],{newRelatedFeature:{},_validRelations:[],isSaveEnable:!1,postCreate:function(){this._validRelations=[]},startup:function(){this._createTable()},_createTable:function(){var b;
b=l.create("div",{"class":"relatedTablesContainer"},this.domNode);n.forEach(this.relationshipInfo,g.hitch(this,function(c){c.featureLayer&&c.hasOwnProperty("relationshipId")&&this._createRelatedTableItem(c,b)}));0<f(".relatedTableTitleContainer",this.domNode).length?this.emit("addRelatedItemContent",!0):this.emit("addRelatedItemContent",!1)},_getKeyField:function(b){var c,a;c=b;b=b.toLowerCase();for(a in this.parentFeature.attributes)if(b===a.toLowerCase()){c=a;break}return c},_createRelatedTableItem:function(b,
c){var a,d,e,h={};d=this.layerInfosObj.getLayerOrTableInfoById(b.featureLayer.id);a=l.create("div",{"class":"relatedTableTitleContainer"},c);k.set(a,"layerId",d.id);k.set(a,"relationshipId",b.relationshipId);k.set(a,"parentFeatureOID",this.parentFeature.attributes[this.parentFeature._layer.objectIdField]);p(a,"click",g.hitch(this,function(a){a=k.get(a.currentTarget,"relatedRecordCount");(null===a||a&&0!==parseInt(a,10))&&this.emit("titleClicked",d.id,b.relationshipId,!1,this.parentFeatureIndexInAI,
this.parentFeature.attributes[this.parentFeature._layer.objectIdField],this.newRelatedFeature[b.relationshipId].foreignKeyField)}));l.create("div",{"class":"relatedTableTitle esriCTEllipsis",innerHTML:d.title,title:d.title},a);l.create("div",{"class":"esriCTLoadingIcon hidden"},a);l.create("div",{"class":"esriCTRelatedTableRecordsCount"},a);h=this._checkRelationShip(d,b.relationshipId);h.isValidRelation?(this._createNewGraphics(b.relationshipId,d.id,h.primaryKeyField,h.foreignKeyField),this._validRelations.push(b)):
l.destroy(a);this._canAddFeatures(b,d)&&"Table"===d.layerObject.type&&(c=l.create("div",{"class":"relatedTableIcons itemTitleCreateNew",title:this.nls.addNewFeature},a),k.set(c,"tableId",d.id),p(c,"click",g.hitch(this,function(c){c.stopPropagation();e=this.newRelatedFeature[b.relationshipId];this.isSaveEnable?r({message:this.nls.pendingFeatureSaveMsg}):(this.parentFeature.attributes.hasOwnProperty(e.primaryKeyField)||(e.primaryKeyField=this._getKeyField(e.primaryKeyField)),void 0===this.parentFeature.attributes[e.primaryKeyField]||
null===this.parentFeature.attributes[e.primaryKeyField]?(c=y.getFieldInfoByFieldName(this.parentFieldInfos,e.primaryKeyField).label||e.primaryKeyField,c=v.substitute(this.nls.invalidRelationShipMsg,{parentKeyField:c}),r({message:c})):(this.newRelatedFeature[b.relationshipId].attributes[this.newRelatedFeature[b.relationshipId].foreignKeyField]=this.parentFeature.attributes[this.newRelatedFeature[b.relationshipId].primaryKeyField],this.emit("addRelatedRecord",this.newRelatedFeature[b.relationshipId],
a,d.id,this.parentFeatureIndexInAI,this.newRelatedFeature[b.relationshipId].foreignKeyField)))})));h.isValidRelation&&this.getRelatedRecordsCount(b.relationshipId,d.id)},_canAddFeatures:function(b,c){c=c.layerObject.getEditCapabilities();return!b.allowUpdateOnly&&b._editFlag&&c.canCreate?!0:!1},_checkRelationShip:function(b,c){var a,d,e,h=!0;a=this._getRelationShipById(this.parentFeature._layer,c);b=this._getRelationShipById(b.layerObject,c);a&&a.keyField&&b&&b.keyField?(d=a.keyField,e=b.keyField):
h=!1;return{isValidRelation:h,foreignKeyField:e,primaryKeyField:d}},_createNewGraphics:function(b,c,a,d){var e;e={};c=this.layerInfosObj.getLayerOrTableInfoById(c);0<c.layerObject.templates.length?e=c.layerObject.templates[0].prototype.attributes:0<c.layerObject.types.length&&(e=c.layerObject.types[0].templates[0].prototype.attributes);e=new w(null,null,g.clone(e));e.attributes.hasOwnProperty(d)&&(e.attributes[d]=this.parentFeature.attributes[a]);this.newRelatedFeature[b]=e;this.newRelatedFeature[b].primaryKeyField=
a;this.newRelatedFeature[b].foreignKeyField=d;this.newRelatedFeature[b].featureLayer=c;return!0},_getRelationShipById:function(b,c){var a;n.some(b.relationships,g.hitch(this,function(b){if(b.id===c)return a=b,!0}));return a},updateFeatureInstance:function(b){this.parentFeature&&(this.parentFeature.attributes=g.clone(b))},displayRelatedRecordCount:function(b,c){var a,d,e;c=f("[relationshipid \x3d "+c+"]",this.domNode);e=f(".relatedTableIcons.itemTitleCreateNew",this.domNode);d=f(".esriCTLoadingIcon",
c[0])[0];m.add(d,"hidden");a=f(".esriCTRelatedTableRecordsCount",c[0])[0];m.remove(a,"hidden");d=f(".relatedTableTitle",c[0])[0];k.set(a,"innerHTML","("+b+")");k.set(c[0],"relatedRecordCount",b);a=A.position(a).w;if("auto"===a||void 0===a||""===a||0===a)a=8+7*b.toString().length;a=0<e.length?a+35:a+10;q.set(d,"width","calc(100% - "+a+"px)");0===b?m.add(c[0],"esriCTRelatedTableTitleDefaultCursor"):m.remove(c[0],"esriCTRelatedTableTitleDefaultCursor")},updateRelatedRecordsCount:function(){n.forEach(this._validRelations,
g.hitch(this,function(b){this.getRelatedRecordsCount(b.relationshipId,b.featureLayer.id)}))},_showLoadingIndicator:function(b){var c,a,d;a=f("[relationshipid \x3d "+b+"]",this.domNode);b=f(".relatedTableIcons.itemTitleCreateNew",this.domNode);d=f(".esriCTLoadingIcon",a[0])[0];c=f(".esriCTRelatedTableRecordsCount",a[0])[0];a=f(".relatedTableTitle",a[0])[0];m.remove(d,"hidden");m.add(c,"hidden");c=20;c=0<b.length?c+35:c+10;q.set(a,"width","calc(100% - "+c+"px)")},getRelatedRecordsCount:function(b,c){var a,
d,e;d=this.parentFeature._layer;e=this.parentFeature.attributes[this.parentFeature._layer.objectIdField];a=new z;c=this.layerInfosObj.getLayerOrTableInfoById(c).layerObject.objectIdField;a.returnGeometry=!1;a.outSpatialReference=this.mapSpatialReference;a.relationshipId=b;a.objectIds=[e];a.outFields=[c];this._showLoadingIndicator(b);d.queryRelatedFeatures(a,g.hitch(this,function(a){(a=a[e]&&a[e].features)?this.displayRelatedRecordCount(a.length,b):this.displayRelatedRecordCount(0,b)}),g.hitch(this,
function(){this.displayRelatedRecordCount(0,b)}))}})});