// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/Deferred jimu/utils jimu/portalUrlUtils jimu/LayerInfos/LayerInfos esri/request esri/kernel esri/symbols/PictureMarkerSymbol esri/symbols/jsonUtils".split(" "),function(f,h,m,k,n,p,q,r,t,u){return{getDefaultPopupInfo:function(a,b,c){var e={title:"",fieldInfos:[],description:null,showAttachments:!1,mediaInfos:[]};c=!!c;if(a.displayField){var d=this._getRealFieldName(a.displayField,a);e.title="{"+d+"}"}else if(d=k.getObjectIdField(a))e.title="{"+d+
"}";e.showAttachments=!!a.hasAttachments;d=a=a.fields;b||(d=h.filter(a,f.hitch(this,function(a){return"esriFieldTypeGeometry"!==a.type})));b=h.map(d,f.hitch(this,function(a){a=k.getDefaultPortalFieldInfo(a);a.visible=c;return a}));e.fieldInfos=b;return e},_getRealFieldName:function(a,b){a=a.toUpperCase();if(b.fields&&0<b.fields.length)for(var c=0;c<b.fields.length;c++)if(b.fields[c].name.toUpperCase()===a)return b.fields[c].name;return""},getPortalFieldInfosWithoutShape:function(a,b){return h.filter(b,
f.hitch(this,function(b){return(b=k.getFieldInfoByFieldName(a.fields,b.fieldName))?"esriFieldTypeGeometry"!==b.type:!0}))},getPopupInfoByAttributes:function(a,b){var c=this.getDefaultPopupInfo(a,!1),e=[],d={},l;for(l in b){e.push(l);var g=k.getFieldInfoByFieldName(a.fields,l).type;if("esriFieldTypeSingle"===g||"esriFieldTypeDouble"===g)g=b[l],null!==g&&void 0!==g&&(g=parseFloat(g),isNaN(g)||(g=g.toString().split("."),2===g.length&&(d[l]=g[1].length)))}c.fieldInfos=h.filter(c.fieldInfos,f.hitch(this,
function(a){var b=a.fieldName;d.hasOwnProperty(b)&&(a.format.places=d[b]);return e.indexOf(b)}));return c},upgradePopupToPopupInfo:function(a,b){var c=this.getDefaultPopupInfo(a,!1,!1);c.title=b.title||"";c.title=c.title.replace("${","{");if(b.fields){var e={};h.forEach(b.fields,f.hitch(this,function(a){e[a.name]=a}));h.forEach(c.fieldInfos,f.hitch(this,function(a){var b=a.fieldName,d=e[b];d&&(a.label=d.alias||a.label,a.visible=!0,"image"===d.specialType&&(b="{"+b+"}",c.mediaInfos.push({title:"",
type:"image",caption:a.label,value:{sourceURL:b,linkURL:b}})))}))}return c},isImageServiceLayer:function(a){return a.url&&-1<a.url.indexOf("/ImageServer")},isTable:function(a){return"Table"===a.type},getConfigWithValidDataSource:function(a){a=f.clone(a);var b=p.getInstanceSync();a.queries=h.filter(a.queries,f.hitch(this,function(a){return(a=a.webMapLayerId)?b.getLayerInfoById(a)?!0:!!b.getTableInfoById(a):!0}));return a},removePopupInfoUnsupportFields:function(a,b){var c=h.map(a.fields,f.hitch(this,
function(a){return a.name}));b.fieldInfos&&0<b.fieldInfos.length&&(b.fieldInfos=h.filter(b.fieldInfos,f.hitch(this,function(a){return 0<=c.indexOf(a.fieldName)})))},overridePopupTemplateMethodGetAttachments:function(a,b,c){a.getAttachments=function(a){var d=new m;try{var e=a.attributes[c],g=b+"/"+e+"/attachments";a={url:g,content:{f:"json"},callbackParamName:"callback"};var f="",k=r.id.findCredential(b);k&&k.token&&(f="?token\x3d"+k.token);q(a).then(function(a){a=a.attachmentInfos;h.forEach(a,function(a){a.url=
g+"/"+a.id+f;a.objectId=e});d.resolve(a)},function(a){d.reject(a)})}catch(v){console.error(v)}return d}},isServiceSupportsOrderBy:function(a){var b=!1;a.advancedQueryCapabilities&&a.advancedQueryCapabilities.supportsOrderBy&&(b=!0);return b},isServiceSupportsPagination:function(a){var b=!1;a.advancedQueryCapabilities&&a.advancedQueryCapabilities.supportsPagination&&(b=!0);return b},isSupportObjectIds:function(a){var b=0,c=k.getObjectIdField(a);a.currentVersion&&(b=parseFloat(a.currentVersion));return!!c&&
(10<=b||a.hasOwnProperty("typeIdField"))},getQueryType:function(a){var b=-1;return b=this.isServiceSupportsOrderBy(a)&&this.isServiceSupportsPagination(a)?1:this.isSupportObjectIds(a)?2:3},getWebMapPopupInfoByUrl:function(a,b){var c=null;b=b.replace(/\/*$/g,"");var e=n.removeProtocol(b);h.some(a.operationalLayers,f.hitch(this,function(a){if(a&&a.url){var b=n.removeProtocol(a.url.replace(/\/*$/g,""));if(a.popupInfo){if(b===e)return c=a.popupInfo,!0}else if(a.layers&&0<a.layers.length)return h.some(a.layers,
f.hitch(this,function(d){return b+"/"+d.id===e?(c=a.popupInfo,!0):!1}))}return!1}));return c},getPopupInfoForRelatedLayer:function(a,b,c){(a=this.getWebMapPopupInfoByUrl(a,b))||(a=this.getDefaultPopupInfo(c,!1,!0));!a.title&&(c=k.getObjectIdField(c))&&(a.title="{"+c+"}");return a},dynamicUpdateConfigIcon:function(a,b){b=window.location.protocol+"//"+window.location.hostname+b;a.icon&&"object"===typeof a.icon?a.icon=u.fromJson(a.icon):"string"===typeof a.icon&&(b=new t({yoffset:16,type:"picturemarkersymbol",
url:a.icon?a.icon:b,width:24,height:24,size:16,xoffset:0}),a.icon=b)},tryGetLayerObject:function(a){var b=new m;if(!a)return b.resolve(),b;a=this._tryGetLayerInfo(a);if(!a)return console.error("Invalid data source"),b.resolve(),b;a.getLayerObject().then(function(a){b.resolve(a)}.bind(this),function(a){b.reject(a)});return b},_tryGetLayerInfo:function(a){var b=p.getInstanceSync(),c=b.getLayerInfoById(a);c||(c=b.getTableInfoById(a));return c}}});