// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Directions/setting/nls/strings":{searchTabTitle:"Param\u00e8tre de source de recherche",routeTabTitle:"Param\u00e8tre d\u2019itin\u00e9raire",add:"Ajouter une source de recherche",addGeocoder:"Ajouter un g\u00e9ocodeur",geocoder:"G\u00e9ocodeur",setLayerSource:"D\u00e9finir une source de couche",setGeocoderURL:"D\u00e9finir l'URL du g\u00e9ocodeur",searchableLayer:"Couche d'entit\u00e9s",name:"Nom",countryCode:"Codes de pays ou de r\u00e9gions",countryCodeEg:"par ex. ",countryCodeHint:"Si cette valeur n'est pas renseign\u00e9e, la recherche s'effectue dans tous les pays et toutes les r\u00e9gions",
showInfoWindowOnSelect:"Afficher la fen\u00eatre contextuelle de l'entit\u00e9 ou de l'emplacement trouv\u00e9",showInfoWindowOnSelect2:"Afficher la fen\u00eatre contextuelle lorsque l\u2019entit\u00e9 ou l\u2019emplacement est trouv\u00e9.",searchInCurrentMapExtent:"Rechercher uniquement dans l'\u00e9tendue de la carte actuelle",setSearchFields:"D\u00e9finir les champs de recherche",set:"D\u00e9finir",fieldSearchable:"Peut faire l'objet d\u2019une recherche",zoomScale:"Echelle de zoom",locatorUrl:"URL du g\u00e9ocodeur",
locatorName:"Nom du g\u00e9ocodeur",locatorExample:"Exemple",locatorWarning:"Cette version du service de g\u00e9ocodage n'est pas prise en charge. Le widget prend en charge le service de g\u00e9ocodage 10.1 et version sup\u00e9rieure.",locatorTips:"Les suggestions ne sont pas disponibles, car le service de g\u00e9ocodage ne prend pas en charge la fonction de suggestion.",layerSource:"Source de la couche",searchLayerTips:"Les suggestions ne sont pas disponibles, car le service d'entit\u00e9s ne prend pas en charge la fonction de pagination.",
placeholderText:"Texte de l'espace r\u00e9serv\u00e9",searchFields:"Champs de recherche",displayField:"Champ d\u2019affichage",exactMatch:"Correspondance parfaite",maxSuggestions:"Nombre maximal de suggestions",maxResults:"Nombre maximal de r\u00e9sultats",enableLocalSearch:"Activer la recherche locale",minScale:"Echelle min.",minScaleHint:"Lorsque l'\u00e9chelle de la carte est sup\u00e9rieure \u00e0 cette \u00e9chelle, la recherche locale est appliqu\u00e9e",radius:"Rayon",radiusHint:"Indique le rayon d'une surface autour du centre de la carte qui permet d'optimiser le classement des candidats de g\u00e9ocodage, afin que les plus proches de l'emplacement soient renvoy\u00e9s en premier",
invalidUrlTip:"L\u2019URL ${URL} est incorrecte ou inaccessible.",routeUrl:"URL de l\u2019itin\u00e9raire",geocoderOptions:"Options du g\u00e9ocodeur",autoComplete:"Terminer automatiquement",maximumSuggestions:"Nombre maximal de suggestions",minCharacters:"Nombre minimum de caract\u00e8res",searchDelay:"D\u00e9lai de recherche",placeholder:"Espace r\u00e9serv\u00e9",routeOptions:"Options de l\u2019itin\u00e9raire",directionsLanguage:"Langue de la feuille de route",directionsLengthUnits:"Unit\u00e9s de distance de la feuille de route",
directionsOutputType:"Type de sortie de la feuille de route",impedanceAttribute:"Attribut d\u2019imp\u00e9dance",kilometers:"Kilom\u00e8tres",miles:"Miles",meters:"M\u00e8tres",feet:"Pieds",yards:"Yards",nauticalMiles:"Milles marins",parametersTip:"D\u00e9finissez les param\u00e8tres correctement.",complete:"Complet",completeNoEvents:"Complet sans \u00e9v\u00e9nements",instructionsOnly:"Instructions uniquement",standard:"Standard",summaryOnly:"R\u00e9sum\u00e9 uniquement",travelModesUrl:"URL des modes de d\u00e9placement",
searchPlaceholder:"Rechercher une adresse ou un lieu",trafficLayerUrl:"URL de la couche de trafic",barrierLayerUrl:"URL de la couche d\u2019interruption",presetDestinations:"Arr\u00eats pr\u00e9d\u00e9finis",startPoint:"Point de d\u00e9part",endPoint:"Point d'arriv\u00e9e",destinationHolder:"Adresse ou coordonn\u00e9es",optional:"Facultatif.",barrierLayers:"Couches d\u2019interruptions",pointBarrier:"Interruptions ponctuelles",lineBarrier:"Interruptions lin\u00e9aires",polygonBarrier:"Interruptions surfaciques",
noPointBarrier:"S\u00e9lectionner des interruptions ponctuelles",noLineBarrier:"S\u00e9lectionner des interruptions lin\u00e9aires",noPolygonBarrier:"S\u00e9lectionner des interruptions surfaciques",_localized:{}}});