// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/EmergencyResponseGuide/nls/strings":{_widgetLabel:"Emergency Response Guide",ergMainPageTitle:"Based on the Emergency Response Guidebook 2016",coordInputLabelStart:"Spill Location (DD)",coordInputLabel:"Spill Location",addPointToolTip:"Add Spill Location",drawPointToolTip:"Click to add spill location",material:"Material",materialPlaceholder:"Start typing to search for a material",table3Message:"The material you have selected requires additional information if you are dealing with a large spill.\n\nPlease ensure you have the correct values selected for wind speed and transport container.",
table2Message:"The material you have selected may produces a large amount of Toxic Inhalation Hazard gases when spilled in water.\n\nYou may want to consider using the following material(s):\n\n",spillSize:"Spill Size",small:"Small",large:"Large",fireLabel:"Show Fire Isolation Zone",weatherLabel:"Current Weather at Spill Location",weatherIntialText:"\x3cbr /\x3eUpdated once a spill location has been idenitified",temperature:"Temperature",wind:"Wind",c:"C",f:"F",weatherErrorMessage:"Weather info not obtained. Update Wind Speed and Time of Spill values manually",
windDirection:"Wind Direction (blowing to)",timeOfSpill:"Time of Spill",day:"Day",night:"Night",windSpeed:"Wind Speed",low:"Low",moderate:"Moderate",high:"High",transportContainer:"Transport Container",rail:"Rail tank car",semi:"Highway tank truck or trailer",mton:"Multiple ton cylinders",ston:"Multiple small cylinders or single ton cylinder",ag:"Agricultural nurse tank",msm:"Multiple small cylinders",bleveLabel:"Show BLEVE Isolation Zone",capacity:"Container Capacity (litres)",bleveMessage:"For the material you have selected an additional evacuation distance can be shown for BLEVE.\n\nTo enable this, set the Show BLEVE Isolation Zone toggle to on and select the appropiate container capacity.",
noPAZoneMessage:"There are no Protective Action distances for this material. Only the Initial Isolation and evacuation zones has been calculated",settingsTitle:"Settings",spillLocationLabel:"Spill Location",spillLocationButtonLabel:"Configure Spill Location Settings",IISettingsLabel:"Initial Isolation Zone",IIButtonLabel:"Configure Initial Isolation Settings",PASettingsLabel:"Protective Action Zone",PAButtonLabel:"Configure Protective Action Settings",downwindSettingsLabel:"Downwind Zone",downwindButtonLabel:"Configure Downwind Settings",
fireSettingsLabel:"Fire Isolation Zone",fireButtonLabel:"Configure Fire Isolation Settings",bleveSettingsLabel:"BLEVE Isolation Zone",bleveButtonLabel:"Configure BLEVE Settings",style:"Style",lineStyles:{esriSLSDash:"Dash",esriSLSDashDot:"Dash Dot",esriSLSDashDotDot:"Dash Dot Dot",esriSLSDot:"Dot",esriSLSLongDash:"Long Dash",esriSLSLongDashDot:"Long Dash Dot",esriSLSNull:"Null",esriSLSShortDash:"Short Dash",esriSLSShortDashDot:"Short Dash Dot",esriSLSShortDashDotDot:"Short Dash Dot Dot",esriSLSShortDot:"Short Dot",
esriSLSSolid:"Solid"},fillStyles:{esriSFSBackwardDiagonal:"Backward",esriSFSCross:"Cross",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Forward",esriSFSHorizontal:"Horizontal",esriSFSNull:"Null",esriSFSSolid:"Solid",esriSFSVertical:"Vertical"},resultsTitle:"Results",publishERGBtn:"Publish",ERGLayerName:"Published ERG Layer Name",invalidERGLayerName:"Layer name must only contain alpha-numeric characters and underscores",missingERGLayerName:"You must enter a name for the ERG",publishingFailedLayerExists:"Publishing Failed: You already have a feature service named {0}. Please choose another name.",
checkService:"Check Service: {0}",createService:"Create Service: {0}",unableToCreate:"Unable to create: {0}",addToDefinition:"Add to definition: {0}",successfullyPublished:"Successfully published web layer{0}Manage the web layer",userRole:"Unable to create service because user does not have permissions",transparency:"Transparency",outline:"Outline",fill:"Fill (Color only applies when style set to solid)",createERGBtn:"Create Zones",clearERGBtn:"Clear",labelFormat:"Label Format",helpIconTooltip:"The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (300 kilograms)",
cellWidth:"Cell Width (x)",cellHeight:"Cell Height (y)",invalidNumberMessage:"The value entered is not valid",invalidRangeMessage:"Value must be greater than 0",gridAngleInvalidRangeMessage:"Value must be between -89.9 and 89.9",formatIconTooltip:"Format Input",setCoordFormat:"Set Coordinate Format String",prefixNumbers:"Add '+/-' prefix to positive and negative numbers",cancelBtn:"Cancel",applyBtn:"Apply",comfirmInputNotation:"Confirm Input Notation",notationsMatch:"notations match your input please confirm which you would like to use:",
missingLayerNameMessage:"You must enter a valid layer name before you can publish",parseCoordinatesError:"Unable to parse coordinates. Please check your input.",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Decimal Degrees - Latitude/Longitude",DDLongLatNotation:"Decimal Degrees  - Longitude/Latitude",DDMLatLongNotation:"Degrees Decimal Minutes - Latitude/Longitude",DDMLongLatNotation:"Degrees Decimal Minutes - Longitude/Latitude",
DMSLatLongNotation:"Degrees Minutes Seconds - Latitude/Longitude",DMSLongLatNotation:"Degrees Minutes Seconds - Longitude/Latitude",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - Band Letter",UTMHemNotation:"UTM - Hemisphere (N/S)",_localized:{ar:1,bs:1,ca:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hi:1,hr:1,hu:1,id:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sl:1,sr:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1,"zh-hk":1,
"zh-tw":1}}});