// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/EmergencyResponseGuide/nls/strings":{_widgetLabel:"Vodi\u010d za hitni odgovor",ergMainPageTitle:"Temelji se na Vodi\u010du za hitni odgovor iz 2016.",coordInputLabelStart:"Lokacija izljeva (DD)",coordInputLabel:"Lokacija izljeva",addPointToolTip:"Dodaj lokaciju izljeva",drawPointToolTip:"Kliknite da biste dodali lokaciju izljeva",material:"Materijal",materialPlaceholder:"Po\u010dnite tipkati za tra\u017eenje materijala",table3Message:"Za materijal koji ste odabrali potrebne su dodatne informacije ako se radi o velikom izljevu.\n\nProvjerite jeste li odabrali ispravne vrijednosti za brzinu vjetra i spremnik za transport.",
table2Message:"Materijal koji ste odabrali mo\u017ee proizvesti veliku koli\u010dinu otrovnih plinova za udisanje pri izlijevanju u vodu.\n\nMo\u017eete razmisliti o upotrebi sljede\u0107ih materijala:\n\n",spillSize:"Veli\u010dina izljeva",small:"Mala",large:"Velika",fireLabel:"Prika\u017ei zonu izolacije po\u017eara",weatherLabel:"Trenuta\u010dno vrijeme na lokaciji izljeva",weatherIntialText:"\x3cbr /\x3eA\u017eurirat \u0107e se kad se utvrdi lokacija izljeva",temperature:"Temperatura",wind:"Vjetar",
c:"C",f:"F",weatherErrorMessage:"Podaci o vremenu nisu dobiveni. Ru\u010dno a\u017eurirajte vrijednosti brzine vjetra i vremena izlijeva",windDirection:"Smjer vjetra (pu\u0161e u smjeru)",timeOfSpill:"Vrijeme izljeva",day:"Dan",night:"No\u0107",windSpeed:"Brzina vjetra",low:"Nisko",moderate:"Umjereno",high:"Visoko",transportContainer:"Spremnik za transport",rail:"Vagon sa spremnikom",semi:"Kamion ili prikolica sa spremnikom za autocestu",mton:"Cilindri s kapacitetom od vi\u0161e tona",ston:"Vi\u0161e malih cilindara ili cilindar s kapacitetom od jedne tone",
ag:"Spremnik za poljoprivredne svrhe",msm:"Vi\u0161e malih cilindara",bleveLabel:"Prika\u017ei zonu izolacije BLEVE",capacity:"Kapacitet spremnika (litre)",bleveMessage:"Za materijal koji ste odabrali dodatna udaljenost evakuacije mo\u017ee se prikazati za BLEVE.\n\nDa biste to omogu\u0107ili, postavite postavku Prika\u017ei zonu izolacije BLEVE na uklju\u010deno i odaberite odgovaraju\u0107i kapacitet spremnika.",noPAZoneMessage:"Nema udaljenosti za za\u0161titne mjere za ovaj materijal. Izra\u010dunate su samo zone po\u010detne izolacije i evakuacije",
settingsTitle:"Postavke",spillLocationLabel:"Lokacija izljeva",spillLocationButtonLabel:"Konfiguriraj postavke lokacije izljeva",IISettingsLabel:"Zona po\u010detne izolacije",IIButtonLabel:"Konfiguriraj postavke po\u010detne izolacije",PASettingsLabel:"Zona za\u0161titnih mjera",PAButtonLabel:"Konfiguriraj postavke za\u0161titnih mjera",downwindSettingsLabel:"Zona niz vjetar",downwindButtonLabel:"Konfiguriraj postavke niz vjetar",fireSettingsLabel:"Zona izolacije po\u017eara",fireButtonLabel:"Konfiguriraj postavke izolacije po\u017eara",
bleveSettingsLabel:"Zona izolacije BLEVE",bleveButtonLabel:"Konfiguriraj postavke BLEVE",style:"Stil",lineStyles:{esriSLSDash:"Linija s crticom",esriSLSDashDot:"Linija s crticom i to\u010dkom",esriSLSDashDotDot:"Linija s crticom i dvije to\u010dke",esriSLSDot:"To\u010dka",esriSLSLongDash:"Duga crtica",esriSLSLongDashDot:"Duga crtica i to\u010dka",esriSLSNull:"Nema vrijednosti",esriSLSShortDash:"Kratka crtica",esriSLSShortDashDot:"Kratka crtica i to\u010dka",esriSLSShortDashDotDot:"Kratka crtica i dvije to\u010dke",
esriSLSShortDot:"Kratka to\u010dka",esriSLSSolid:"Puna linija"},fillStyles:{esriSFSBackwardDiagonal:"Unatrag",esriSFSCross:"Kri\u017e",esriSFSDiagonalCross:"Dijagonalno",esriSFSForwardDiagonal:"Naprijed",esriSFSHorizontal:"Vodoravni",esriSFSNull:"Nema vrijednosti",esriSFSSolid:"Puna linija",esriSFSVertical:"Uspravno"},resultsTitle:"Rezultati",publishERGBtn:"Objavi",ERGLayerName:"Objavljen naziv sloja ERG",invalidERGLayerName:"Naziv sloja mora sadr\u017eavati samo alfanumeri\u010dke znakove i podvlake",
missingERGLayerName:"Morate navesti naziv za ERG",publishingFailedLayerExists:"Objavljivanje nije uspjelo: ve\u0107 imate uslugu geoobjekata s nazivom {0}. Odaberite drugi naziv.",checkService:"Provjeri uslugu: {0}",createService:"Stvori uslugu: {0}",unableToCreate:"Nije mogu\u0107e stvoriti: {0}",addToDefinition:"Dodaj definiciji: {0}",successfullyPublished:"Uspje\u0161no objavljen web-sloj{0}Upravljaj web-slojem",userRole:"Nije mogu\u0107e stvoriti uslugu jer korisnik nema dopu\u0161tenja",transparency:"Prozirnost",
outline:"Obris",fill:"Ispuni (boja se primjenjuje samo kad je stil postavljen na jednobojno)",createERGBtn:"Stvori zone",clearERGBtn:"O\u010disti",labelFormat:"Format oznake",helpIconTooltip:"Prag izme\u0111u malih i velikih veli\u010dina izljeva iznosi:\nTeku\u0107ine - 55 galona (208 litara)\n\u010cvrste tvari - 60 funti (300 kilograma)",cellWidth:"\u0160irina \u0107elije (x)",cellHeight:"Visina \u0107elije (y)",invalidNumberMessage:"Unesena vrijednost nije valjana",invalidRangeMessage:"Vrijednost mora biti ve\u0107a od 0",
gridAngleInvalidRangeMessage:"Vrijednost mora biti izme\u0111u -89,9 i 89,9",formatIconTooltip:"Format unosa",setCoordFormat:"Postavi niz formata koordinata",prefixNumbers:"Dodajte prefiks \u201e+/-\u201d pozitivnim i negativnim brojevima",cancelBtn:"Odustani",applyBtn:"Primijeni",comfirmInputNotation:"Notacija potvrde unosa",notationsMatch:"bilje\u0161ke se podudaraju s va\u0161im unosom, potvrdite \u0161to biste htjeli upotrijebiti:",missingLayerNameMessage:"Morate unijeti va\u017ee\u0107i naziv sloja prije objavljivanja",
parseCoordinatesError:"Nije mogu\u0107e parsirati koordinate. Provjerite unos.",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Decimalni stupnjevi - geografska \u0161irina/du\u017eina",DDLongLatNotation:"Decimalni stupnjevi - geografska du\u017eina/\u0161irina",DDMLatLongNotation:"Stupnjevi decimalne minute - geografska \u0161irina/du\u017eina",DDMLongLatNotation:"Stupnjevi decimalne minute - geografska du\u017eina/\u0161irina",
DMSLatLongNotation:"Stupnjevi minute sekunde - geografska \u0161irina/du\u017eina",DMSLongLatNotation:"Stupnjevi minute sekunde - geografska du\u017eina/\u0161irina",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - slovo retka",UTMHemNotation:"UTM - hemisfera (N/S)",_localized:{}}});