// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/EmergencyResponseGuide/nls/strings":{_widgetLabel:"Gu\u00eda de respuesta ante emergencias",ergMainPageTitle:"Basada en la Gu\u00eda de respuesta ante emergencias 2016",coordInputLabelStart:"Ubicaci\u00f3n de vertido (DD)",coordInputLabel:"Ubicaci\u00f3n de vertido",addPointToolTip:"Agregar ubicaci\u00f3n de vertido",drawPointToolTip:"Haga clic para agregar la ubicaci\u00f3n de vertido",material:"Material",materialPlaceholder:"Comience a escribir para buscar un material",table3Message:"El material que ha seleccionado requiere informaci\u00f3n adicional si se enfrenta a un vertido considerable.\n\nAseg\u00farese de que dispone de los valores correctos seleccionados en cuanto a velocidad del viento y contenedor de transporte.",
table2Message:"El material que ha seleccionado puede producir una gran cantidad de gases t\u00f3xicos por inhalaci\u00f3n si se vierten al agua.\n\nQuiz\u00e1 deber\u00eda plantearse emplear los siguientes materiales:\n\n",spillSize:"Magnitud del vertido",small:"Peque\u00f1a",large:"Grande",fireLabel:"Mostrar zona de aislamiento de incendios",weatherLabel:"Meteorolog\u00eda actual en la ubicaci\u00f3n del vertido",weatherIntialText:"\x3cbr /\x3eActualizado una vez identificada una ubicaci\u00f3n de vertido",
temperature:"Temperatura",wind:"Viento",c:"C",f:"F",weatherErrorMessage:"Informaci\u00f3n de meteorolog\u00eda no obtenida. Actualice manualmente los valores de velocidad del viento y hora del vertido",windDirection:"Direcci\u00f3n del viento (hacia d\u00f3nde sopla)",timeOfSpill:"Hora del vertido",day:"D\u00eda",night:"Noche",windSpeed:"Velocidad del viento",low:"Bajo",moderate:"Moderado",high:"Alto",transportContainer:"Contenedor de transporte",rail:"Vag\u00f3n cisterna",semi:"Cami\u00f3n o remolque cisterna",
mton:"Varios cilindros de una tonelada",ston:"Varios cilindros peque\u00f1os o un solo cilindro de una tonelada",ag:"Remolque cisterna agr\u00edcola",msm:"Varios cilindros peque\u00f1os",bleveLabel:"Mostrar zona de aislamiento BLEVE",capacity:"Capacidad del contenedor (litros)",bleveMessage:"Para el material que ha seleccionado, es posible mostrar una distancia de evacuaci\u00f3n adicional en caso de BLEVE.\n\nPara permitirlo, active el selector Mostrar zona de aislamiento BLEVE y seleccione la capacidad correcta del contenedor.",
noPAZoneMessage:"No existe ninguna distancia de Acci\u00f3n protectora para este material. Solo se han calculado las zonas de aislamiento inicial y evacuaci\u00f3n",settingsTitle:"Ajustes",spillLocationLabel:"Ubicaci\u00f3n de vertido",spillLocationButtonLabel:"Configurar ajustes de ubicaci\u00f3n de vertido",IISettingsLabel:"Zona de aislamiento inicial",IIButtonLabel:"Configurar ajustes de aislamiento inicial",PASettingsLabel:"Zona de acci\u00f3n protectora",PAButtonLabel:"Configurar ajustes de acci\u00f3n protectora",
downwindSettingsLabel:"Zona de sotavento",downwindButtonLabel:"Configurar los ajustes de sotavento",fireSettingsLabel:"Zona de aislamiento de incendios",fireButtonLabel:"Configurar ajustes de aislamiento de incendios",bleveSettingsLabel:"Zona de aislamiento BLEVE",bleveButtonLabel:"Configurar ajustes de BLEVE",style:"Estilo",lineStyles:{esriSLSDash:"Guion",esriSLSDashDot:"Guion Punto",esriSLSDashDotDot:"Guion Punto Punto",esriSLSDot:"Punto",esriSLSLongDash:"Guion largo",esriSLSLongDashDot:"Guion largo, Punto",
esriSLSNull:"Nulo",esriSLSShortDash:"Guion corto",esriSLSShortDashDot:"Guion corto Punto",esriSLSShortDashDotDot:"Guion corto Punto Punto",esriSLSShortDot:"Corto Punto",esriSLSSolid:"S\u00f3lido"},fillStyles:{esriSFSBackwardDiagonal:"Atr\u00e1s",esriSFSCross:"Cruz",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Hacia delante",esriSFSHorizontal:"Horizontal",esriSFSNull:"Nulo",esriSFSSolid:"S\u00f3lido",esriSFSVertical:"Vertical"},resultsTitle:"Resultados",publishERGBtn:"Publicar",ERGLayerName:"Nombre de capa ERG publicada",
invalidERGLayerName:"El nombre de la capa solo debe contener caracteres alfanum\u00e9ricos y guiones bajos",missingERGLayerName:"Debe indicar un nombre para el ERG",publishingFailedLayerExists:"Fallo de publicaci\u00f3n: ya tiene un servicio de entidades denominado {0}. Elija otro nombre.",checkService:"Comprobar servicio: {0}",createService:"Crear servicio: {0}",unableToCreate:"Imposible crear: {0}",addToDefinition:"Agregar a definici\u00f3n: {0}",successfullyPublished:"Capa web publicada correctamente{0}Administar la capa web",
userRole:"Imposible crear el servicio porque el usuario no tiene permisos",transparency:"Transparencia",outline:"Lista",fill:"Relleno (el color solo se aplica si el estilo es s\u00f3lido)",createERGBtn:"Crear zonas",clearERGBtn:"Borrar",labelFormat:"Formato de etiqueta",helpIconTooltip:"The threshold between small and large spill sizes are:\nLiquids - 55 gallons (208 liters)\nSolids - 60 pounds (30 kilograms)",cellWidth:"Ancho de celda (x)",cellHeight:"Altura de celda (y)",invalidNumberMessage:"El valor introducido no es v\u00e1lido",
invalidRangeMessage:"El valor debe ser mayor que 0",gridAngleInvalidRangeMessage:"El valor debe estar comprendido entre -89,9 y 89,9",formatIconTooltip:"Formato de entrada",setCoordFormat:"Definir cadena de caracteres de formato de coordenadas",prefixNumbers:"Agregar prefijo '+/-' a los n\u00fameros positivos y negativos",cancelBtn:"Cancelar",applyBtn:"Solicitar participaci\u00f3n",comfirmInputNotation:"Confirmar notaci\u00f3n de entrada",notationsMatch:"notaciones que coinciden con su entrada. Confirme cu\u00e1l desea usar:",
missingLayerNameMessage:"Debe introducir un nombre de capa v\u00e1lido antes de publicar",parseCoordinatesError:"No se pueden analizar las coordenadas. Compruebe la entrada.",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Grados decimales - Latitud/longitud",DDLongLatNotation:"Grados decimales - Longitud/latitud",DDMLatLongNotation:"Grados minutos decimales - Latitud/longitud",
DDMLongLatNotation:"Grados minutos decimales - Longitud/latitud",DMSLatLongNotation:"Grados minutos segundos - Latitud/longitud",DMSLongLatNotation:"Grados minutos segundos - Longitud/latitud",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - Letra de banda",UTMHemNotation:"UTM - Hemisferio (N/S)",_localized:{}}});