// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/EmergencyResponseGuide/nls/strings":{_widgetLabel:"Beredskapstjenesteguide",ergMainPageTitle:"Basert p\u00e5 beredskapstjenesteh\u00e5ndboken 2016",coordInputLabelStart:"Utslippssted (DD)",coordInputLabel:"Utslippssted",addPointToolTip:"Legg til utslippssted",drawPointToolTip:"Klikk for \u00e5 legge til utslippssted",material:"Artikkel",materialPlaceholder:"Skriv inn for \u00e5 s\u00f8ke etter materiale",table3Message:"Materialet du har valgt krever tilleggsinformasjon hvis det er snakk om st\u00f8rre utslipp.\n\nKontroller at det er valgt riktige verdier for vindhastighet og transportbeholder.",
table2Message:"Materialet du har valgt kan kan produsere store mengder gasser som er giftige ved inn\u00e5nding om de kommer i kontakt med vann.\n\nDu b\u00f8r heller vurdere \u00e5 bruke f\u00f8lgende material(er):\n\n",spillSize:"Utslippsomfang",small:"Liten",large:"Stor",fireLabel:"Vis brannisoleringssone",weatherLabel:"Gjeldende v\u00e6rforhold p\u00e5 utslippsstedet",weatherIntialText:"\x3cbr /\x3eOppdater n\u00e5r et utslippssted er identifisert",temperature:"Temperatur",wind:"Vind",c:"C",f:"F",
weatherErrorMessage:"V\u00e6rinformasjon ikke innhentet. Oppdater verdiene for vindhastighet og utslippstidspunkt manuelt.",windDirection:"Vindretning (bl\u00e5ser mot)",timeOfSpill:"Utslippstidspunkt",day:"Dag",night:"Natt",windSpeed:"Vindhastighet",low:"Lav",moderate:"Moderat",high:"H\u00f8y",transportContainer:"Transportbeholder",rail:"Tankvogn",semi:"Tankbil",mton:"Sylindre p\u00e5 flere tonn",ston:"Flere sm\u00e5 sylindre eller sylinder p\u00e5 ett tonn",ag:"Landbrukstank",msm:"Flere sm\u00e5 sylindre",
bleveLabel:"Vis BLEVE-isoleringssone",capacity:"Beholderkapasitet (liter)",bleveMessage:"For materialet du har valgt kan det vises en ekstra evakueringsavstand for BLEVE.\n\nDu aktiverer dette ved \u00e5 aktivere Vis BLEVE-isoleringssone og velge aktuell beholderkapasitet.",noPAZoneMessage:"Det finnes ingen avstand for beskyttelsestiltak for dette materialet. Kun opprinnelig isolasjonssone og evakueringssone er beregnet",settingsTitle:"Innstillinger",spillLocationLabel:"Utslippssted",spillLocationButtonLabel:"Konfigurer innstillinger for utslippssted",
IISettingsLabel:"Opprinnelig isolasjonssone",IIButtonLabel:"Konfigurer innstillinger for opprinnelig isolasjonssone",PASettingsLabel:"Sone for beskyttelsestiltak",PAButtonLabel:"Konfigurer innstillinger for beskyttelsestiltak",downwindSettingsLabel:"Medvindssone",downwindButtonLabel:"Konfigurer innstillinger for medvind",fireSettingsLabel:"Brannisoleringssone",fireButtonLabel:"Konfigurer innstillinger for brannisolering",bleveSettingsLabel:"BLEVE-isoleringssone",bleveButtonLabel:"Konfigurer innstillinger for BLEVE",
style:"Stil",lineStyles:{esriSLSDash:"Strek",esriSLSDashDot:"Strek prikk",esriSLSDashDotDot:"Strek prikk prikk",esriSLSDot:"Prikk",esriSLSLongDash:"Lang strek",esriSLSLongDashDot:"Lang strek-prikk",esriSLSNull:"Null",esriSLSShortDash:"Kort strek",esriSLSShortDashDot:"Kort strek-prikk",esriSLSShortDashDotDot:"Kort strek-prikk-prikk",esriSLSShortDot:"Kort prikk",esriSLSSolid:"Heltrukken"},fillStyles:{esriSFSBackwardDiagonal:"Bakover",esriSFSCross:"Kryss",esriSFSDiagonalCross:"Diagonal",esriSFSForwardDiagonal:"Fremover",
esriSFSHorizontal:"Vannrett",esriSFSNull:"Null",esriSFSSolid:"Heltrukken",esriSFSVertical:"Loddrett"},resultsTitle:"Resultater",publishERGBtn:"Publiser",ERGLayerName:"Publisert ERG-lagnavn",invalidERGLayerName:"Lagnavn kan bare inneholde alfanumeriske tegn og understrekingstegn",missingERGLayerName:"Du m\u00e5 oppgi et navn for ERG",publishingFailedLayerExists:"Publiseringen mislyktes: Du har allerede en geoobjektstjeneste med navnet {0}. Velg et annet navn.",checkService:"Kontroller tjeneste: {0}",
createService:"Opprett tjeneste {0}",unableToCreate:"Kan ikke opprette: {0}",addToDefinition:"Legg til definisjon: {0}",successfullyPublished:"Vellykket publisering av weblag{0}Administrer weblaget",userRole:"Kan ikke opprette tjeneste fordi brukeren ikke har tillatelser",transparency:"Gjennomsiktighet",outline:"Omriss",fill:"Fyll (farge brukes bare n\u00e5r heldekkende er valgt som stil)",createERGBtn:"Opprett soner",clearERGBtn:"T\u00f8m",labelFormat:"Etikettformat",helpIconTooltip:"Terskelen mellom store og sm\u00e5 utslipp er:\nV\u00e6sker 208 liter\nFaste materialer \u2013 300 kg",
cellWidth:"Cellebredde (x)",cellHeight:"Celleh\u00f8yde (y)",invalidNumberMessage:"Den angitte verdien er ugyldig",invalidRangeMessage:"Verdien m\u00e5 v\u00e6re st\u00f8rre enn 0",gridAngleInvalidRangeMessage:"Verdien m\u00e5 v\u00e6re mellom -89,9 og 89,9",formatIconTooltip:"Formater inndata",setCoordFormat:"Angi koordinatformatstreng",prefixNumbers:'Legg til prefikset "+/-" for positive og negative tall',cancelBtn:"Avbryt",applyBtn:"Bruk",comfirmInputNotation:"Bekreft inndatanotasjon",notationsMatch:"notasjoner samsvarer med inndataene. Bekreft hvilke du vil bruke:",
missingLayerNameMessage:"Du m\u00e5 angi et gyldig lagnavn f\u00f8r du kan publisere",parseCoordinatesError:"Kan ikke analysere koordinater. Sjekk inndataene.",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"Desimalgrader - Breddegrad/lengdegrad",DDLongLatNotation:"Desimalgrader - Lengdegrad/breddegrad",DDMLatLongNotation:"Grader og desimalminutter - Breddegrad/lengdegrad",DDMLongLatNotation:"Grader og desimalminutter - Lengdegrad/breddegrad",
DMSLatLongNotation:"Grader Minutter Sekunder - Breddegrad/lengdegrad",DMSLongLatNotation:"Grader Minutter Sekunder - Lengdegrad/breddegrad",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - B\u00e5ndbokstav",UTMHemNotation:"UTM - Halvkule (N/S)",_localized:{}}});