// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/EmergencyResponseGuide/nls/strings":{_widgetLabel:"H\u00e4daolukorras reageerimise juhend",ergMainPageTitle:"P\u00f5hineb juhendil \u201eEmergency Response Guidebook 2016\u201c",coordInputLabelStart:"Saastumiskoht (DD)",coordInputLabel:"Saastumiskoht",addPointToolTip:"Lisa saastumiskoht",drawPointToolTip:"Kl\u00f5psake saastumiskoha lisamiseks",material:"Materjal",materialPlaceholder:"Aine otsimiseks alustage tippimist",table3Message:"Kui tegemist on ulatusliku saastumisega, tuleb teie valitud materjali korral sisestada lisateavet.\n\nVeenduge, et oleksite tuulekiiruse ja transpordikonteineri jaoks valinud \u00f5iged v\u00e4\u00e4rtused.",
table2Message:"Teie valitud materjal v\u00f5ib vette sattumise korral tekitada suures koguses toksilisi gaase, mille sissehingamine on ohtlik.\n\nV\u00f5iksite kaaluda j\u00e4rgmiste materjalide kasutamist:\n\n",spillSize:"Saastumise ulatus",small:"V\u00e4ike",large:"Suur",fireLabel:"Kuva tuleisolatsiooni tsoon",weatherLabel:"Praegune ilm saastumiskohas",weatherIntialText:"\x3cbr /\x3eUuendatakse p\u00e4rast saastumiskoha tuvastamist",temperature:"Temperatuur",wind:"Tuul",c:"C",f:"F",weatherErrorMessage:"Ilmateavet ei saa tuua. Uuendage tuulekiiruse ja saastumisaja v\u00e4\u00e4rtused k\u00e4sitsi.",
windDirection:"Tuule suund (sihtsuund)",timeOfSpill:"Saastumisaeg",day:"P\u00e4ev",night:"\u00d6\u00f6",windSpeed:"Tuule kiirus",low:"Madal",moderate:"M\u00f5\u00f5dukas",high:"K\u00f5rge",transportContainer:"Transpordikonteiner",rail:"Tsisternvagun",semi:"Tsisternveok v\u00f5i j\u00e4relhaagis",mton:"Mitu \u00fchetonnise mahutavusega ballooni",ston:"Mitu v\u00e4ikest ballooni v\u00f5i \u00fcks \u00fchetonnise mahutavusega balloon",ag:"P\u00f5llumajanduslik l\u00e4gatsistern",msm:"Mitu v\u00e4ikest ballooni",
bleveLabel:"Kuva BLEVE isolatsioonitsoon",capacity:"Konteineri mahutavus (liitrites)",bleveMessage:"Teie valitud materjali korral saab BLEVE jaoks n\u00e4idata t\u00e4iendavat evakueerimiskaugust.\n\nSelle s\u00e4tte lubamiseks l\u00fclitage s\u00e4te \u201eKuva BLEVE isolatsioonitsoon\u201c sisse ja valige asjakohane konteineri mahutavus.",noPAZoneMessage:"Selle materjali korral ei saa kaitsetoimingute kaugust m\u00e4\u00e4rata. Arvutatud on ainult algse isolatsiooni ja evakuatsiooni tsoonid.",settingsTitle:"Seaded",
spillLocationLabel:"Saastumiskoht",spillLocationButtonLabel:"Konfigureeri saastumiskoha s\u00e4tted",IISettingsLabel:"Algne isolatsioonitsoon",IIButtonLabel:"Konfigureeri algse isoleerimise s\u00e4tted",PASettingsLabel:"Kaitsetoimingute tsoon",PAButtonLabel:"Konfigureeri kaitsetoimingute s\u00e4tted",downwindSettingsLabel:"Allatuuletsoon",downwindButtonLabel:"Konfigureeri allatuules\u00e4tted",fireSettingsLabel:"Tuleisolatsiooni tsoon",fireButtonLabel:"Konfigureeri tuleisolatsiooni s\u00e4tted",bleveSettingsLabel:"BLEVE isolatsiooni tsoon",
bleveButtonLabel:"Konfigureeri BLEVE s\u00e4tted",style:"Laad",lineStyles:{esriSLSDash:"Katkendlik",esriSLSDashDot:"Katkendlik punktiga",esriSLSDashDotDot:"Katkendlik kahe punktiga",esriSLSDot:"Punktiir",esriSLSLongDash:"Pikk katkendlik kriips",esriSLSLongDashDot:"Pikk katkendlik kriips punktiga",esriSLSNull:"Null",esriSLSShortDash:"L\u00fchike katkendlik kriips",esriSLSShortDashDot:"L\u00fchike katkendlik kriips punktiga",esriSLSShortDashDotDot:"L\u00fchike katkendlik kriips kahe punktiga",esriSLSShortDot:"L\u00fchike punktiir",
esriSLSSolid:"Pidev"},fillStyles:{esriSFSBackwardDiagonal:"Tagasi",esriSFSCross:"Rist",esriSFSDiagonalCross:"Diagonaal",esriSFSForwardDiagonal:"Edasi",esriSFSHorizontal:"Horisontaalne",esriSFSNull:"Null",esriSFSSolid:"Pidev",esriSFSVertical:"Vertikaalne"},resultsTitle:"Tulemused",publishERGBtn:"Publitseeri",ERGLayerName:"Avaldatud ERG kihi nimi",invalidERGLayerName:"Kihi nimi tohib sisaldada ainult t\u00e4he- ja numbrim\u00e4rke ning allkriipse",missingERGLayerName:"Peate sisestama ERG nime",publishingFailedLayerExists:"Avaldamine nurjus: objektiteenus nimega {0} on juba olemas. Valige m\u00f5ni muu nimi.",
checkService:"Kontrolli teenust: {0}",createService:"Loo teenus: {0}",unableToCreate:"Ei saa luua: {0}",addToDefinition:"Lisa definitsiooni: {0}",successfullyPublished:"Veebikiht on avaldatud{0}Halda veebikihti",userRole:"Teenust ei saa luua, kuna kasutajal pole n\u00f5utavaid \u00f5igusi",transparency:"L\u00e4bipaistvus",outline:"\u00c4\u00e4rejoon",fill:"T\u00e4ida (v\u00e4rv rakendatakse ainult juhul, kui valitud on pidev laad)",createERGBtn:"Loo tsoonid",clearERGBtn:"T\u00fchjenda",labelFormat:"Sildi vorming",
helpIconTooltip:"V\u00e4ikese ja suure saastumise vaheline l\u00e4vi on j\u00e4rgmine:\nVedelikud \u2013 208 liitrit (55 gallonit)\nTahkained \u2013 300 kilogrammi (600 naela)",cellWidth:"Ruudu laius (x)",cellHeight:"Ruudu k\u00f5rgus (y)",invalidNumberMessage:"Sisestatud v\u00e4\u00e4rtus ei sobi",invalidRangeMessage:"V\u00e4\u00e4rtus peab olema suurem kui 0",gridAngleInvalidRangeMessage:"V\u00e4\u00e4rtus peab olema vahemikus -89,9 kuni 89,9",formatIconTooltip:"Vormingu sisestus",setCoordFormat:"M\u00e4\u00e4ra koordinaatide vormingu string",
prefixNumbers:"Lisa positiivsetele ja negatiivsetele arvudele eesliide \u201e+/-\u201d",cancelBtn:"Loobu",applyBtn:"Rakenda",comfirmInputNotation:"Kinnita sisestatud t\u00e4histus",notationsMatch:"t\u00e4histust vastab Teie sisestusele; palun kinnitage, millist soovite kasutada:",missingLayerNameMessage:"Avaldamiseks peate esmalt sisestama sobiva kihinime",parseCoordinatesError:"Ei saa koordinaate s\u00f5eluda. Kontrollige sisendit.",DD:"DD",DDM:"DDM",DMS:"DMS",DDRev:"DDRev",DDMRev:"DDMRev",DMSRev:"DMSRev",
USNG:"USNG",MGRS:"MGRS",UTM_H:"UTM (H)",UTM:"UTM",GARS:"GARS",GEOREF:"GEOREF",DDLatLongNotation:"K\u00fcmnendkraadid \u2013 laiuskraad/pikkuskraad",DDLongLatNotation:"K\u00fcmnendkraadid  \u2013 pikkuskraad/laiuskraad",DDMLatLongNotation:"Kraadid-k\u00fcmnendminutid \u2013 laiuskraad/pikkuskraad",DDMLongLatNotation:"Kraadid-k\u00fcmnendminutid \u2013 pikkuskraad/laiuskraad",DMSLatLongNotation:"Kraadid-k\u00fcmnendsekundid \u2013 laiuskraad/pikkuskraad",DMSLongLatNotation:"Kraadid-k\u00fcmnendsekundid \u2013 pikkuskraad/laiuskraad",
GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM \u2013 vahemiku t\u00e4ht",UTMHemNotation:"UTM \u2013 poolkera (N/S)",_localized:{}}});