// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dgrid/extensions/nls/pagination":{status:"${start} - ${end} van ${total} resultaten",gotoFirst:"Ga naar eerste pagina",gotoNext:"Ga naar volgende pagina",gotoPrev:"Ga naar vorige pagina",gotoLast:"Ga naar laatste pagina",gotoPage:"Ga naar pagina",jumpPage:"Spring naar pagina",rowsPerPage:"Number of rows per page",_localized:{}},"widgets/Analysis/setting/nls/strings":{selectAnalysisTools:"Selecteer analysetools om te gebruiken in de widget.",graphicalDisplay:"Grafische weergave",toolSetting:"Tooldetails instellen",
toolLabel:"De weergegeven naam van de tool",showHelpTip:"Helplinks weergeven in de widget",showCurrentMapExtent:"Optie weergeven om de huidige kaart te gebruiken",showCredits:"Optie \x3cb\x3eCredits weergeven\x3c/b\x3e tonen",saveAsFeatureService:"Sla het resultaat op in de account van de gebruiker",showReadyToUseLayers:"Direct te gebruiken lagen van ArcGIS Online levende atlas van de wereld weergeven",toolNotAvailable:"Deze tool is niet beschikbaar omdat de kaart geen vereiste objectla(a)g(en) bevat.",
aggregatePoints:"Punten aggregeren",aggregatePointsUsage:"Punten aggregeren in polygonen waar de punten zich bevinden.",calculateDensity:"Dichtheid berekenen",calculateDensityUsage:"Maakt een dichtheidskaart vanaf punt- of lijnobjecten door bekende hoeveelheden van een bepaald fenomeen (voorgesteld als attributen van de punten of lijnen) over de kaart te verspreiden.",connectOriginsToDestinations:"Vertrekpunten en bestemmingen met elkaar verbinden",connectOriginsToDestinationsUsage:"Meet de reistijd of afstand tussen paren van beginpunten.",
createBuffers:"Buffers maken",createBuffersUsage:"Bufferpolygonen maken van invoerobjecten.",createDriveTimeAreas:"Gebieden op basis van reisduur maken",createDriveTimeAreasUsage:"Maak polygonen voor reistijd (of rij-afstand) rond invoerpunten voor de gegeven reistijdwaarden.",createViewshed:"Viewshed maken",createViewshedUsage:"Maakt gebieden die zichtbaar zijn op basis van locaties die u opgeeft.",createWatersheds:"Stroomgebied maken",createWatershedsUsage:"Maakt stroomgebieden op basis van locaties die u opgeeft.",
deriveNewLocations:"Nieuwe locaties afleiden",deriveNewLocationsUsage:"Leid nieuwe objecten af van de invoerlagen die voldoen aan een query die u opgeeft",dissolveBoundaries:"Grenzen oplossen",dissolveBoundariesUsage:"Los polygonen op die een gemeenschappelijke grens overlappen of delen.",enrichLayer:"Laag verrijken",enrichLayerUsage:"Verrijk invoerobjecten met informatie over mensen, plaatsen en bedrijven in nabijgelegen gebieden.",extractData:"Gegevens exporteren",extractDataDesc:"Exporteer gegevens van een of meerdere lagen binnen een bepaalde extent",
findCentroids:"Zwaartepunten zoeken",findCentroidsUsage:"Zoekt het representatieve centrum (zwaartepunt) voor elke functie voor meervoudige invoer, lijn of oppervlakte.",findExistingLocations:"Bestaande locaties zoeken",findExistingLocationsUsage:"Selecteer objecten in de invoerlaag die voldoen aan een attribuut en/of ruimtelijke query u opgeeft",findHotSpots:"Hotspots zoeken",findHotSpotsUsage:"Zoek statistisch signficante clusters van invoerobjecten of hoge/lage waarden.",findNearest:"Dichtstbijzijnde zoeken",
findNearestUsage:"Zoek voor elk object op een invoerlaag het dichtstbijzijnde object op een andere laag",findPointClusters:"Puntclusters zoeken",findPointClustersUsage:"Deze tool detecteert gebieden waar punten geconcentreerd zijn en waar ze gescheiden worden door gebieden die leeg of schaars zijn.",findSimilarLocations:"Gelijksoortige locaties zoeken",findSimilarLocationsUsage:"Meet de gelijkenis van kandidaat-locaties aan de hand van \u00e9\u00e9n of meerdere referentiepunten.",geocodeLocations:"Geocodeer Locaties vanuit Tabel",
geocodeLocationsUsage:"Een handige manier om grote tabellen of bestanden met adressen in punten te geocoderen.",interpolatePoints:"Punten interpoleren",interpolatePointsUsage:"Voorspel waarden op nieuwe locaties op basis van metingen die worden gevonden in een verzameling van punten.",mergeLayers:"Lagen samenvoegen",mergeLayersUsage:"Voeg objecten toe van meerdere lagen aan een nieuwe laag",overlayLayers:"Lagen bovenop plaatsen",overlayLayersUsage:"Combineer meerdere lagen in \u00e9\u00e9n enkele laag met informatie uit de originele bewaarde kaartlagen.",
planRoutes:"Routes plannen",planRoutesUsage:"Bepaal hoe taken effici\u00ebnt kunnen worden verdeeld over mobiel personeel.",summarizeCenterAndDispersion:"Samenvatten centrum en spreiding",summarizeCenterAndDispersionUsage:"Gebruik puntobjecten om de centrale functie, het gemiddelde centrum, het middencentrum of de ellips (verdeling) te berekenen.",summarizeNearby:"Samenvatten in de buurt van",summarizeNearbyUsage:"Zoek voor elk object een invoerlaag op het dichtstbijzijnde object op een andere laag.",
summarizeWithin:"Samenvatten in",summarizeWithinUsage:"Vat voor elke polygoon op een invoerpolygoonlaag data samen met objecten uit een andere laag.",traceDownstream:"Stroomafwaarts traceren",traceDownstreamUsage:"Bepaal de stromingstrajecten stroomafwaarts van de locaties die u opgeeft.",allowToExport:"Resultaten exporteren",joinFeatures:"Objecten koppelen",joinFeaturesUsage:"De tool Objecten koppelen brengt attributen over van de ene laag of tabel naar de andere op basis van ruimtelijke en attribuutrelaties. Optioneel kunnen ook statistieken berekend worden voor de gekoppelde objecten.",
includeRouteLayer:"Routelagen toevoegen",findOutliers:"Afwijkingen vinden",findOutliersUsage:"De tool Afwijkingen vinden bepaalt of er sprake is van statistisch significante afwijkingen in het ruimtelijke patroon van uw data.",_localized:{}},"widgets/Analysis/nls/strings":{_widgetLabel:"Analyse",executeAnalysisTip:"Klik op een analysetool voor uitvoeren",noToolTip:"Er is geen analysetool geconfigureerd!",jobSubmitted:"verzonden.",jobCancelled:"Geannuleerd.",jobFailed:"Mislukt",jobSuccess:"Gelukt.",
executing:"Uitvoeren",cancelJob:"De analysetaak annuleren",paramName:"Parameternaam",learnMore:"Meer weten",outputtip:"Opmerking: Object- en tabeluitvoer worden toegevoegd aan de folder als operationele lagen.",outputSaveInPortal:"De data wordt opgeslagen in uw portaal .",privilegeError:'Uw gebruikersrol kan geen analyse uitvoeren. IOm de analyse te kunnen uitvoeren, moet de beheerder van uw organisatie u bepaalde \x3ca href\x3d"http://doc.arcgis.com/en/arcgis-online/reference/roles.htm" target\x3d"_blank"\x3emachtigingen\x3c/a\x3e verlenen.',
noServiceError:"Er zijn geen beschikbare ruimtelijke analyseservices. Controleer uw portalconfiguraties.",_localized:{}}});