// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/lang esri/tasks/QueryTask esri/tasks/query".split(" "),function(f,v,p,x,w,r,u,z,A,B){function y(c){var a=v.clone(c.attributes);(c=c.geometry)&&"point"===c.type&&("x"in a?a._x=c.x:a.x=c.x,"y"in a?a._y=c.y:a.y=c.y);return a}f.exportCSV=function(c,a,b,d,g){return f._createCSVStr(a,b,d,g).then(function(a){return f._download(c+".csv",a)})};f.exportCalculatedResultsCSV=function(c,a){var b="",d=0;p.forEach(a,
function(g){b+=g.name+" ("+g.type+")\r\n";f._createCSVStr([],[],g.appendColumns,g.appendDatas).then(function(e){b+=e;d++;if(d===a.length)return f._download(c+".csv",b);b+="\r\n\r\n"})})};f.exportCSVFromFeatureLayer=function(c,a,b){b=b||{};return f._getExportData(a,{datas:b.datas,fromClient:b.fromClient,withGeometry:b.withGeometry,outFields:b.outFields,filterExpression:b.filterExpression}).then(function(d){return f._formattedData(a,d,{formatNumber:b.formatNumber,formatDate:b.formatDate,formatCodedValue:b.formatCodedValue,
popupInfo:b.popupInfo,appendColumns:b.appendColumns,appendDatas:b.appendDatas}).then(function(a){return f.exportCSV(c,a.datas,a.columns,a.appendColumns,a.appendDatas)})})};f.exportCSVByAttributes=function(c,a,b,d){d=v.mixin({},d);d.datas=b;return f.exportCSVFromFeatureLayer(c,a,d)};f.exportCSVByGraphics=function(c,a,b,d){b=p.map(b,function(a){return a.attributes});return f.exportCSVByAttributes(c,a,b,d)};f._createCSVStr=function(c,a,b,d){var f=new r,e="",h=0,m=0,k="",l="";try{if(a&&0<a.length){p.forEach(a,
function(a){e=e+k+a;k=","});for(var e=e+"\r\n",h=c.length,m=a.length,t=0;t<h;t++){for(var k="",n=0;n<m;n++)(l=c[t][a[n]])||"number"===typeof l||(l=""),l&&/[",\r\n]/g.test(l)&&(l='"'+l.replace(/(")/g,'""')+'"'),e=e+k+l,k=",";e+="\r\n"}}"undefined"!==typeof b&&"undefined"!==typeof d&&0<b.length&&0<d.length&&(k="",p.forEach(b,function(a){e=e+k+a;k=","}),k="",e+="\r\n",p.forEach(d,function(a){Array.isArray(a)?(p.forEach(a,function(a){e=e+k+a;k=","}),k="",e+="\r\n"):(e=e+k+a,k=",")}));f.resolve(e)}catch(q){console.error(q),
f.resolve("")}return f};f._isIE11=function(){return 11===u.has("ie")};f._isEdge=function(){return u.has("edge")};f._getDownloadUrl=function(c){return window.Blob&&window.URL&&window.URL.createObjectURL?(c=new Blob(["\ufeff"+c],{type:"text/csv"}),URL.createObjectURL(c)):"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(c)};f._download=function(c,a){var b=new r;try{if(w("ie")&&10>w("ie")){var d=window.top.open("about:blank","_blank");d.document.write("sep\x3d,\r\n"+a);d.document.close();
d.document.execCommand("SaveAs",!0,c);d.close()}else if(10===w("ie")||f._isIE11()||f._isEdge()){var g=new Blob(["\ufeff"+a],{type:"text/csv"});navigator.msSaveBlob(g,c)}else{var e=x.create("a",{href:f._getDownloadUrl(a),target:"_blank",download:c},document.body);if(w("safari")){var h=document.createEvent("MouseEvents");h.initEvent("click",!0,!0);e.dispatchEvent(h)}else e.click();x.destroy(e)}b.resolve()}catch(m){b.reject(m)}return b};f._getExportData=function(c,a){var b=new r,d=null,g=a.datas,e=a.withGeometry,
d=a.outFields;d&&d.length||(d=c.fields);d=v.clone(d);if(e&&!(g&&0<g.length)){var h="",h=-1!==d.indexOf("x")?"_x":"x";d.push({name:h,alias:h,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});h=-1!==d.indexOf("y")?"_y":"y";d.push({name:h,alias:h,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"})}g&&0<g.length?b.resolve({data:g||[],outFields:d}):a.fromClient?(g=p.map(c.graphics,function(a){return e?y(a):v.clone(a)}),b.resolve({data:g||[],outFields:d})):f._getExportDataFromServer(c,
d,a).then(function(a){b.resolve({data:a||[],outFields:d})});return b};f._getExportDataFromServer=function(c,a,b){var d=new r;if("esri.layers.FeatureLayer"!==c.declaredClass)return d.resolve([]),d;var f=new A(c.url),e=new B;e.where=b.filterExpression||c.getDefinitionExpression&&c.getDefinitionExpression()||"1\x3d1";0<a.length?(c=p.map(a,function(a){return a.name}),e.outFields=c):e.outFields=["*"];e.returnGeometry=b.withGeometry;f.execute(e,function(a){a=p.map(a.features,function(a){return y(a)});d.resolve(a)},
function(a){console.error(a);d.resolve([])});return d};f._formattedData=function(c,a,b){var d=new r,g=[],e=a.data;a=a.outFields;for(var h=u.getFeatureLayerDefinition(c),m=0,k=e.length;m<k;m++){for(var l={},t=0;t<a.length;t++){var n=a[t];l[n.alias||n.name]=f._getExportValue(e[m][n.name],n,c.objectIdField,c.typeIdField,e[m][c.typeIdField],c.types,b,h,e[m],c)}g.push(l)}c=p.map(a,function(a){return a.alias||a.name});d.resolve({datas:g,columns:c,appendColumns:b.appendColumns,appendDatas:b.appendDatas});
return d};f._getExportValue=function(c,a,b,d,f,e,h,m,k,l){function g(a){if(n&&z.isDefined(n.fieldInfos))for(var b=0,c=n.fieldInfos.length;b<c;b++){var d=n.fieldInfos[b];if(d.fieldName===a)return d.format}return null}var n=h.popupInfo,q=!!a.domain&&h.formatCodedValue;h="esriFieldTypeDate"===a.type&&h.formatDate;var r=b&&a.name===b;d=d&&a.name===d;l=l&&l.renderer?l:m;return h?u.fieldFormatter.getFormattedDate(c,g(a.name)):(d||q)&&m&&k&&(m=u.getDisplayValueForCodedValueOrSubtype(l,a.name,k))&&m.hasOwnProperty("displayValue")?
m.displayValue:q||h||r||d?c:(q=null,b&&e&&0<e.length&&(b=(b=p.filter(e,function(a){return a.id===f}))&&b[0])&&b.domains&&b.domains[a.name]&&b.domains[a.name].codedValues&&(a=u.getDisplayValueForCodedValueOrSubtype(l,a.name,k))&&a.hasOwnProperty("displayValue")&&(q=a.displayValue),null!==q?q:c)}});