// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Defini\u00e7\u00f5es",titleSettings:"Defini\u00e7\u00f5es de texto",imageSettings:"Defini\u00e7\u00f5es de imagem",backgroundColor:"Cor de fundo",alignment:"Alinhamento",textSize:"Tamanho do texto",textColor:"Cor do texto",dataSource:"Fonte de Dados",chartSettings:"Defini\u00e7\u00f5es de gr\u00e1ficos",data:"Dados",dataLabels:"R\u00f3tulos de dados",displayMode:"Modo de exibi\u00e7\u00e3o",featureOption:"Exibir valores elemento a elemento",
categoryOption:"Exibir valores por categoria",countOption:"Exibir contagens de elementos por categoria",fieldOption:"Exibir valores de atributos como gr\u00e1ficos",categoryField:"Campo de categoria",labelField:"Campo de r\u00f3tulo",valueFields:"Campos de valor",operation:"Opera\u00e7\u00e3o",sumOption:"Soma",averageOption:"M\u00e9dia",minOption:"M\u00ednimo",maxOption:"M\u00e1ximo",countString:"Contagem",dataFormat:"Formato de dados",decimalPlaces:"Casas decimais",prefix:"Prefixo",suffix:"Sufixo",
dataType:"Tipo de Dados",featureCount:"Contagem de elementos",fieldStatistics:"Estat\u00edsticas de campos",display:"Exibir",chartColor:"Cor do gr\u00e1fico",horizontalAxis:"Eixo horizontal",verticalAxis:"Eixo vertical",legend:"Legenda",position:"Posi\u00e7\u00e3o",top:"Superior",bottom:"Inferior",useDataSourceSelection:"Utilizar sele\u00e7\u00e3o",dataSourceFilterByExtent:"Filtrar por extens\u00e3o",changeTemplate:"Alterar modelo",numberSettings:"Defini\u00e7\u00f5es de n\u00fameros",gaugeSettings:"Defini\u00e7\u00f5es de medidor",
indicators:"Indicadores",ifValue:"Valor If",and:"e",numberOperatorIsLessThan:"\u00e9 inferior a",numberOperatorIsGreaterThan:"\u00e9 superior a",numberOperatorIsBetween:"\u00e9 entre",numberOperatorIsEqual:"\u00e9 igual a",numberOperatorIsNotEqual:"n\u00e3o \u00e9 igual a",then:"Portanto",ratio:"R\u00e1cio",trueValue:"Valor real",changeValueColor:"Alterar cor do valor para",changeGaugeColor:"Alterar cor do medidor para",setIndicatorIcon:"Definir \u00edcone de indicador como",icons:"\u00cdcones",style:"Estilo",
placement:"Coloca\u00e7\u00e3o",left:"Esquerda",replace:"Substituir",right:"Direita",color:"Cor",categoryExists:"A categoria existe!",comboxHint:"Digite ou selecione uma",comboxDisableInputHint:"Selecionar um",comboxDisableSelectHint:"Digitar uma",comboxDisableInputEmptySelectHint:"N\u00e3o existem mais categorias",sortBy:"Ordenar por",labelAxis:"R\u00f3tulo",valueAxis:"Valor",minPeriod:"Per\u00edodo m\u00ednimo",automatic:"Autom\u00e1tico",periodsWithOutRecords:"Per\u00edodos sem registos",nullValue:"Valor nulo",
calculatedAsZero:"Calculado como zero",ignored:"Ignorado",maxCategories:"M\u00e1ximo de categorias",useLayerSymbology:"Utilizar simbologia da camada",hollowsize:"Tamanho vazio",splitField:"Dividir campo",parsingperiodTip:"Ocorreu uma falha ao computar. Demasiados intervalos temporais devido ao curto per\u00edodo de an\u00e1lise.",manyCategoryTip:"Ocorreu uma falha ao exibir o gr\u00e1fico. Demasiadas categorias.",setColor:"Definir cor",setTheColorOf:"Depois defina a cor de",setTheColorAs:"Depois defina a cor como",
ifStr:"Se",as:"como",is:"\u00e9",isNot:"n\u00e3o \u00e9",barCluster:"cluster de barras",individualBar:"barra individual",allOthers:"Todos os Outros",category:"Categoria",indicatorSum:"SOMA",indicatorAve:"M\u00c9DIA",indicatorMax:"M\u00c1XIMO",indicatorMin:"M\u00cdNIMO",setCorrectyIndicatorTip:"Por favor, defina os indicadores corretamente.",dataRange:"Intervalo de datas",targetValue:"Valor alvo",currentValue:"Valor atual",gaugeColor:"Cor do medidor",min:"M\u00ednimo",max:"M\u00e1ximo",displayValueIn:"Exibir valor em",
noData:"Sem dados",thousandAbbreviation:"q",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Aviso",noSettingWaring1:"Clique num elemento para definir as respetivas propriedades.",noSettingWaring2:"Arraste para redimensionar ou reordenar um elemento.",donNotShowAgain:"N\u00e3o exibir novamente",changeTemplateWarning:"Esta a\u00e7\u00e3o ir\u00e1 apagar todas as suas defini\u00e7\u00f5es e abrir\u00e1 um novo modelo vazio",requiredFieldWarning:"Este valor \u00e9 exigido:",dataSourceNotSet:"Por favor, defina a fonte de dados.",
addIndicatorTip:"Adicionar um indicador",chooseTemplatePopupTitle:"Seleccione um modelo",filterExtentTipWithaTag:"Pode desativar o filtro por \x3ca target\x3d'_blank' href\x3d'http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'\x3eFonte de dados extra\x3c/a\x3e no Separador Atributo.",filterExtentTip:"Pode desativar o filtro por Fonte de dados extra no Separador Atributo.",customColorByCategory:"Cor personalizada por categoria",randomColor:"Cor Aleat\u00f3ria",
valueString:"Valor",fieldString:"Campo",includeThresholdValue:"Incluir valor de limiar",percentage:"Percentagem",colorSchema:"Esquema de cores",addCategory:"Adicionar categoria",clickToEdit:"Clicar para editar",nullText:"Nulo",others:"Outros",dsErrorTipSuf:"n\u00e3o se encontra dispon\u00edvel",front:"Frente",back:"Voltar",title:"T\u00edtulo",titleColor:"Cor do t\u00edtulo",labelString:"R\u00f3tulo",labelSize:"Tamanho do r\u00f3tulo",labelColor:"Cor do r\u00f3tulo",addMarkLine:"Adicionar uma marca de linha",
addMarkArea:"Adicionar uma marca de \u00e1rea",labelPosition:"Posi\u00e7\u00e3o do r\u00f3tulo",toString:"at\u00e9",start:"Iniciar",middle:"Meio",end:"Final",inString:"Em",outString:"Fora",lineColor:"Cor da Linha",lineWidth:"Largura de linha",dashType:"Tipo de tra\u00e7o",areaColor:"Cor da \u00e1rea",line:"Linha",area:"\u00c1rea",stringsInTemplate:{name_number:"N\u00famero",name_gauge:"Medidor",name_vertical_gauge:"Medidor Vertical",name_horizontal_gauge:"Medidor Horizontal",name_pie:"Circular",name_donut:"Donut",
name_bar:"Barra",name_stacked_bar:"Barra Empilhada",name_percentage_stacked_bar:"Barra Empilhada de Percentagem",name_column:"Coluna",name_stacked_column:"Coluna empilhada",name_percentage_stacked_column:"Coluna Empilhada de Percentagem",name_line:"Linha",name_area:"\u00c1rea",name_stacked_area:"\u00c1rea Empilhada",name_percentage_stacked_area:"\u00c1rea Empilhada de Percentagem",titleOfTheInfographic:"T\u00cdTULO DA INFOGRAFIA",description:"Descri\u00e7\u00e3o: informa\u00e7\u00f5es adicionais sobre esta infografia."},
marks:"Marcas",displayValue:"Exibir valor",statistic:"Estat\u00edstica",valueType:"Tipo de valor",valueField:"Campo de valor",fixed:"Corrigido",sdsTip:"Selecione um dado estat\u00edstico configurado em origem de dados Extra",noSdsTip:"Sem dados estat\u00edsticos dispon\u00edveis",intScaleText:"Exibir escala apenas de n\u00fameros inteiros",resetLayout:"Repor layout",fbeTip:"Tenha em aten\u00e7\u00e3o que, se a sua aplica\u00e7\u00e3o for partilhada publicamente, a ativa\u00e7\u00e3o desta op\u00e7\u00e3o poder\u00e1 reduzir drasticamente o desempenho da aplica\u00e7\u00e3o. Recomendamos fortemente a utiliza\u00e7\u00e3o de outros widgets, tais como Filtro e Filtro de Grupo para ampliar os elementos.",
openFbeTip:"Ative a op\u00e7\u00e3o de qualquer forma",use1000Separator:"Usar separador de milhares",_localized:{}}});