// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/keys dojo/dom-construct dojo/query dijit/_WidgetBase dijit/_TemplatedMixin jimu/dijit/ViewStack jimu/utils".split(" "),function(q,g,r,h,k,m,l,n,t,u,v,p){return q([t,u],{baseClass:"jimu-header-more-popup",templateString:'\x3cdiv\x3e\x3cdiv class\x3d"close" tabindex\x3d"0" data-dojo-attach-point\x3d"closeNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"pages" data-dojo-attach-point\x3d"pagesNode"\x3e\x3c/div\x3e\x3cdiv class\x3d"points jimu-corner-bottom"\x3e\x3cdiv class\x3d"points-inner"data-dojo-attach-point\x3d"pointsNode"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',
margin:4,postCreate:function(){this.nodes=[];this.pages=[];this.createCloseBtn();this.own(k(this.domNode,"keydown",g.hitch(this,function(a){h.hasClass(a.target,"close-btn")||a.keyCode!==m.ESCAPE||this.closeNode.focus()})))},startup:function(){this.viewStack=new v({views:[],viewType:"dom"},this.pagesNode);this.viewStack.startup();this.resize();this.nodes.length&&this.nodes[0].focus()},resize:function(){var a=this._calculateGridParam(),c;null!==a?(h.setStyle(this.domNode,p.getPositionStyle(a.position)),
this.nodeWidth=a.cellSize-this.margin,this.oldGridParam&&this.oldGridParam.rows===a.rows&&this.oldGridParam.cols===a.cols||(this.clearPages(),this.createPages(a)),this.nodes.forEach(g.hitch(this,function(b,c){this.setItemNodePosition(b,c,a)})),this.oldGridParam=a,c=n("div.close",this.domNode)[0],h.setStyle(c,{width:.25*this.nodeWidth+"px",height:.25*this.nodeWidth+"px"})):(this.oldGridParam=null,h.setStyle(this.domNode,p.getPositionStyle({left:0,top:0,width:0,height:0,zIndex:111})),this.nodeWidth=
0)},setItemNodePosition:function(a,c,b){var d,e,f=48,g=16;d=0===c%b.cols?0:this.margin/2;e=c%(b.rows*b.cols)<b.cols?0:this.margin/2;c={};"number"===typeof this.nodeWidth&&(c.width=this.nodeWidth+"px",c.height=this.nodeWidth+"px");"number"===typeof d&&(window.isRTL?c.marginRight=d+"px":c.marginLeft=d+"px");"number"===typeof e&&(c.marginTop=e+"px");if(d=n("img",a)[0])b.iconScaled&&(f*=this.nodeWidth/120),h.setStyle(d,{width:f+"px",height:f+"px"});if(f=n("div.node-label",a)[0])b.showLabel?(b.iconScaled&&
(g*=this.nodeWidth/120),h.setStyle(f,{"font-size":g+"px",display:"block"})):h.setStyle(f,{"font-size":g+"px",display:"none"});h.setStyle(a,c)},clearPages:function(){r.forEach(this.pages,function(a){this.viewStack.removeView(a.pageNode)},this);l.empty(this.pointsNode);this.pages=[];this.nodes=[]},createPages:function(a){var c,b,d,e;c=Math.ceil(this.items.length/(a.rows*a.cols));for(b=0;b<c;b++){d=l.create("div",{"class":"page"});this.createPageItems(b,d,a);this.viewStack.addView(d);if(1<c){var f=b===
c-1;e=l.create("div",{"class":"point",tabindex:0},this.pointsNode);this.own(k(e,"click",g.hitch(this,this._onPageNodeClick,b)));this.own(k(e,"keydown",g.hitch(this,function(a,c,b){b.keyCode===m.ENTER?(this._onPageNodeClick(a),n(".page.view",this.viewStack.domNode)[a].children[0].focus()):c&&!b.shiftKey&&b.keyCode===m.TAB&&b.preventDefault()},b,f)))}this.pages.push({pageNode:d,pointNode:e})}0<this.viewStack.views.length&&this._selectPage(0)},_onPageNodeClick:function(a){this._selectPage(a)},_selectPage:function(a){1<
this.pages.length&&(n(".point",this.domNode).removeClass("point-selected"),h.addClass(this.pages[a].pointNode,"point-selected"));this.viewStack.switchView(this.pages[a].pageNode)},createPageItems:function(a,c,b){var d,e,f;d=this.items.length;e=b.rows*b.cols;b=(a+1)*e;f=b-d;b=Math.min(b,d);for(a*=e;a<b;a++)this.createItemNode(a,c);for(a=d;a<d+f;a++)this.createEmptyItemNode(c)},createItemNode:function(a,c){var b;a=this.items[a];b=l.create("div",{"class":"icon-node jimu-float-leading jimu-main-background",
title:a.label,settingId:a.id,"data-widget-name":a.name,tabindex:0},c);c=l.create("img",{src:a.icon},b);window.isRTL&&a.mirrorIconForRTL&&h.addClass(c,"jimu-flipx");l.create("div",{"class":"node-label",title:a.label,innerHTML:p.stripHTML(a.label)},b);b.config=a;this.own(k(b,"click",g.hitch(this,function(){this.onNodeClicked(b)})));this.own(k(b,"keydown",g.hitch(this,function(a){if(a.keyCode===m.ENTER)this.onNodeClicked(b)})));this.nodes.push(b)},createEmptyItemNode:function(a){a=l.create("div",{"class":"icon-node jimu-float-leading jimu-main-background",
tabindex:0},a);this.own(k(a,"focus",g.hitch(this,function(a){p.isInNavMode()&&(1===this.viewStack.domNode.children.length?a.target.parentNode.children[0].focus():n(".point-selected",this.pointsNode)[0].previousSibling.focus())})));this.nodes.push(a);return a},createCloseBtn:function(){l.create("div",{"class":"close-inner jimu-main-background"},this.closeNode);this.own(k(this.closeNode,"click",g.hitch(this,function(){this.hide()})));this.own(k(this.closeNode,"keydown",g.hitch(this,function(a){a.keyCode===
m.ENTER?this.hide():a.shiftKey&&a.keyCode===m.TAB&&a.preventDefault()})));return this.closeNode},hide:function(){h.setStyle(this.domNode,"display","none")},show:function(){h.setStyle(this.domNode,"display","block")},onNodeClicked:function(a){this.hide()},_calculateGridParam:function(){var a,c,b,d,e=!1,f=!0;a=h.getContentBox(jimuConfig.mapId);c=Math.min(a.w,a.h)-40;if(360<=c)d=120;else{d=Math.floor(c/3);if(10>d)return null;e=!0;80>d&&(f=!1)}c=Math.floor((a.h-40)/d);b=Math.floor((a.w-40)/d);c=4<c?4:
c;c=3>c?3:c;b=3>c?3:4<b?4:b;return{rows:c,cols:b,cellSize:d,iconScaled:e,showLabel:f,position:{top:(a.h-d*c)/2,bottom:(a.h-d*c)/2,left:(a.w-d*b)/2,right:(a.w-d*b)/2,width:d*b-this.margin*(b-1)/2,height:d*c-this.margin*(c-1)/2,zIndex:111}}}})});