// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Query/nls/strings":{_widgetLabel:"Interrogazione",executeQueryTip:"Fare clic su uno degli elementi attivit\u00e0 seguenti per eseguire la query.",invalidConfig:"Configurazione non valida. Utilizzare la pagina delle impostazioni interrogazione per ottenere la configurazione corretta.",queryParams:"Opzioni",parameters:"OPZIONI",queries:"INTERROGAZIONI",apply:"Applica",queryResults:"Risultati",clear:"Cancella",noResults:"Nessuna feature trovata.",queryError:"Interrogazione non riuscita.",
numberFound:"Numero di feature trovate",mapExtentTip:"Limita i risultati all'area della mappa corrente.",noValue:"Valore non disponibile",and:"e",stringOperatorIs:"\u00e8",stringOperatorIsNot:"non \u00e8",stringOperatorStartsWith:"inizia con",stringOperatorEndsWith:"termina con",stringOperatorContains:"contiene",stringOperatorDoesNotContain:"non contiene",stringOperatorIsBlank:"\u00e8 vuoto",stringOperatorIsNotBlank:"non \u00e8 vuoto",dateOperatorIsOn:"ricorre il giorno",dateOperatorIsNotOn:"non ricorre il giorno",
dateOperatorIsBefore:"ricorre prima del giorno",dateOperatorIsAfter:"ricorre dopo il giorno",dateOperatorDays:"giorni",dateOperatorWeeks:"settimane",dateOperatorMonths:"mesi",dateOperatorInTheLast:"negli ultimi/nelle ultime",dateOperatorNotInTheLast:"non negli ultimi/nelle ultime",dateOperatorIsBetween:"\u00e8 compreso tra",dateOperatorIsNotBetween:"non \u00e8 compreso tra",dateOperatorIsBlank:"\u00e8 vuoto",dateOperatorIsNotBlank:"non \u00e8 vuoto",numberOperatorIs:"\u00e8",numberOperatorIsNot:"non \u00e8",
numberOperatorIsAtLeast:"\u00e8 almeno",numberOperatorIsLessThan:"\u00e8 minore di",numberOperatorIsAtMost:"\u00e8 al massimo",numberOperatorIsGreaterThan:"\u00e8 maggiore di",numberOperatorIsBetween:"\u00e8 compreso tra",numberOperatorIsNotBetween:"non \u00e8 compreso tra",numberOperatorIsBlank:"\u00e8 vuoto",numberOperatorIsNotBlank:"non \u00e8 vuoto",operationalLayerTip:"Aggiungi risultato come layer operativo",queryResult:"Risultato interrogazione",specifyParamsTip:"Specificare i parametri per l'attivit\u00e0",
useSpatialFilter:"Usa filtro spaziale per limitare le feature",useCurrentMapExtent:"Solo le feature che intersecano l'area della mappa corrente",drawGraphicOnMap:"Solo le feature che intersecano l'area definita dall'utente",specifySpatialFilterMsg:"Specificare il filtro spaziale per questa attivit\u00e0.",clearResults:"Elimina risultati",operationalTip:'Se questa opzione \u00e8 selezionata, i risultati verranno mantenuti sulla mappa finch\u00e9 non si fa clic sul pulsante "${clearResults}".',noneQueryTip:"Nessuna attivit\u00e0 di interrogazione \u00e8 stata configurata per questo widget.",
noPermissionsMsg:"Non si dispone delle autorizzazioni per accedere al servizio.",attributesFromRelationship:"Attributi da tabella correlata",tasks:"Attivit\u00e0",applySpatialFilterToLimitResults:"Applica un filtro spaziale per limitare i risultati",useCurrentExtentTip:"Restituisci solo feature all'interno dell'estensione mappa corrente",useDrawGraphicTip:"Restituisci solo feature che si intersecano con la forma disegnata sulla mappa",useFeaturesTip:"Restituisci solo feature caratterizzate da una relazione spaziale con le feature in un altro layer",
noSpatialLimitTip:"Restituisci feature all'interno dell'estensione completa della mappa",applySearchDistance:"Applica a distanza di ricerca",spatialRelationship:"Relazione spaziale",relatedLayer:"Layer correlato",bufferDistance:"Distanza di buffer",miles:"Miglia",kilometers:"Chilometri",feet:"Piede",meters:"Metri",yards:"Iarde",nauticalMiles:"Miglia nautiche",back:"Indietro",execute:"Esegui",zoomTo:"Zoom a",openAttributeTable:"Visualizza nella tabella degli attributi",noResult:"Nessun risultato.",
noTask:"Nessuna attivit\u00e0.",removeThisResult:"Rimuovi questo risultato",attributeCriteira:"Criteri attributo",spatialFilter:"Filtro spaziale",value:"VALUE",noAttributeSpatialFilterTip:"Nessun filtro definito. Tutte le feature verranno restituite.",showAllRelatedRecords:"Mostra tutti i record correlati",changeSymbol:"Cambia simbolo",queryCriteira:"Criteri di interrogazione",customQuery:"Interrogazione personalizzata",layer:"Layer",createCustomQuery:"Crea interrogazione personalizzata.",rename:"Rinomina",
clearShapeTip:"Cancella questa forma dopo aver applicato l\u2019interrogazione.",displayedFeatures:"Feature visualizzate",loadMore:"Carica altro",expandAll:"Espandi tutto",collapseAll:"Comprimi tutto",_localized:{}}});