// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ParcelDrafter/nls/strings":{_widgetLabel:"Maa\u00fcksuse koostaja",newTraverseButtonLabel:"Alusta uut l\u00e4bimist",invalidConfigMsg:"Vigane konfiguratsioon",geometryServiceURLNotFoundMSG:"Ei saa hankida geomeetriateenuse URL-i",editTraverseButtonLabel:"Redigeeri l\u00e4bimist",mapTooltipForStartNewTraverse:"Alustamiseks valige kaardil koht v\u00f5i tippige allpool",mapTooltipForEditNewTraverse:"Valige maa\u00fcksus, mida redigeerida",mapTooltipForUpdateStartPoint:"Kl\u00f5psake alguspunkti v\u00e4rskendamiseks",
mapTooltipForScreenDigitization:"Kl\u00f5psake maa\u00fcksuse punkti lisamiseks",mapTooltipForUpdatingRotaionPoint:"Kl\u00f5psake p\u00f6\u00f6rdepunkti v\u00e4rskendamiseks",mapTooltipForRotate:"Haara p\u00f6\u00f6ramiseks",mapTooltipForScale:"Haara suuruse muutmiseks",backButtonTooltip:"Tagasi",newTraverseTitle:"Uus l\u00e4bimine",editTraverseTitle:"Redigeeri l\u00e4bimist",clearingDataConfirmationMessage:"Muudatused l\u00e4hevad kaotsi, kas soovite j\u00e4tkata?",unableToFetchParcelMessage:"Ei saa tuua maa\u00fcksust.",
unableToFetchParcelLinesMessage:"Ei saa tuua maa\u00fcksuse jooni.",planSettings:{planSettingsTitle:"Seaded",directionOrAngleTypeLabel:"Suuna v\u00f5i nurga t\u00fc\u00fcp",directionOrAngleUnitsLabel:"Suuna v\u00f5i nurga \u00fchikud",distanceAndLengthUnitsLabel:"Vahemaa ja pikkuse \u00fchikud",areaUnitsLabel:"Pindala\u00fchikud",circularCurveParameters:"\u00dcmara k\u00f5vera parameetrid",northAzimuth:"P\u00f5hja asimuut",southAzimuth:"L\u00f5una asimuut",quadrantBearing:"Kvadrandi kurss",radiusAndChordLength:"Raadiuse ja k\u00f5\u00f5lu pikkus",
radiusAndArcLength:"Raadiuse ja kaare pikkus",expandGridTooltipText:"Laienda ruudustik",collapseGridTooltipText:"Ahenda ruudustik",zoomToLocationTooltipText:"Suumi asukohta",onScreenDigitizationTooltipText:"Digiteeri",updateRotationPointTooltipText:"V\u00e4rskenda p\u00f6\u00f6rdepunkti"},traverseSettings:{bearingLabel:"Kurss",lengthLabel:"Pikkus",radiusLabel:"Raadius",noMiscloseCalculated:"Sulgumisviga pole arvutatud",traverseMiscloseBearing:"Sulgumisvea kurss",traverseAccuracy:"T\u00e4psus",accuracyHigh:"Tugev",
traverseDistance:"Sulgumisvea vahemaa",traverseMiscloseRatio:"Sulgumisvea suhe",traverseStatedArea:"Esitatud pindala",traverseCalculatedArea:"Arvutatud pindala",addButtonTitle:"Lisa",deleteButtonTitle:"Eemalda"},parcelTools:{rotationToolLabel:"Nurk",scaleToolLabel:"M\u00f5\u00f5tkava"},newTraverse:{invalidBearingMessage:"Vigane kurss.",invalidLengthMessage:"Vigane pikkus.",invalidRadiusMessage:"Vigane raadius.",negativeLengthMessage:"Kehtib ainult k\u00f5verate puhul",enterValidValuesMessage:"Sisestage kehtivad v\u00e4\u00e4rtused.",
enterValidParcelInfoMessage:"Sisestage salvestamiseks kehtiv maa\u00fcksuse info.",unableToDrawLineMessage:"Joont ei saa joonistada.",invalidEndPointMessage:"Vigane l\u00f5pp-punkt, joont ei saa joonistada."},planInfo:{requiredText:"(n\u00f5utud)",optionalText:"(valikuline)",parcelNamePlaceholderText:"Maa\u00fcksuse nimi",parcelDocumentTypeText:"Dokumendi t\u00fc\u00fcp",planNamePlaceholderText:"Plaani nimi",cancelButtonLabel:"Loobu",saveButtonLabel:"Salvesta",saveNonClosedParcelConfirmationMessage:"Sisestatud maa\u00fcksus pole l\u00f5petatud, kas soovite siiski j\u00e4tkata ja salvestada ainult maa\u00fcksuse jooned?",
unableToCreatePolygonParcel:"Maa\u00fcksuse pol\u00fcgooni ei saa luua.",unableToSavePolygonParcel:"Maa\u00fcksuse pol\u00fcgooni ei saa salvestada.",unableToSaveParcelLines:"Maa\u00fcksuse jooni ei saa salvestada.",unableToUpdateParcelLines:"Maa\u00fcksuse jooni ei saa v\u00e4rskendada.",parcelSavedSuccessMessage:"Maa\u00fcksus salvestati edukalt.",parcelDeletedSuccessMessage:"Maa\u00fcksus on kustutatud.",parcelDeleteErrorMessage:"Maa\u00fcksuse kustutamisel ilmnes t\u00f5rge.",enterValidParcelNameMessage:"Sisestage kehtiv maa\u00fcksuse nimi.",
enterValidPlanNameMessage:"Sisestage kehtiv plaani nimi.",enterValidDocumentTypeMessage:"Vigane dokumendit\u00fc\u00fcp.",enterValidStatedAreaNameMessage:"Sisestage kehtiv esitatud pindala."},xyInput:{explanation:"Teie kruntide kihi georuumilises viitamises"},_localized:{}}});