// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/ThreatAnalysis/nls/strings":{_widgetLabel:"Dreigingsanalyse",threatAnalysisMainPageTitle:"Gebaseerd op JCAT Counterterrorism Guide",jcatURL:"https://www.dni.gov/nctc/jcat/references.html",inputLocation:"Invoerlocatie",interactive:"Interactief",fromCoord:"Vast co\u00f6rdinaat",existingFeature:"Van bestaande objecten",threatAnalysisCoordInputLabel:"Dreigingslocatie",enterCoords:"Co\u00f6rdinaten invoeren",threatAddPointToolTip:"Dreigingslocatie toevoegen",threatDrawPointToolTip:"Klik om een dreigingslocatie toe te voegen",
threatType:"Dreigingstype",threatPlaceholder:"Begin te typen om een dreiging te zoeken",mandatoryLabel:"Verplichte evacuatie-afstand",safeLabel:"Veilige evacuatie-afstand",zoneTypeLabel:"Zonetype",feetLabel:"Voet",metersLabel:"Meter",unitsLabel:"Eenheden",threatGraphicLayer:"Dreigingsgrafiek",settingsTitle:"Instellingen",mandatoryButtonLabel:"Verplichte afstandsinstellingen configureren",safeButtonLabel:"Shelter In Place-instellingen configureren",style:"Stijl",lineStyles:{esriSLSDash:"Streep",esriSLSDashDot:"Streep punt",
esriSLSDashDotDot:"Streep punt punt",esriSLSDot:"Punt",esriSLSLongDash:"Lange streep",esriSLSLongDashDot:"Lange streep punt",esriSLSNull:"Null",esriSLSShortDash:"Korte streep",esriSLSShortDashDot:"Korte streep punt",esriSLSShortDashDotDot:"Korte streep punt punt",esriSLSShortDot:"Korte punt",esriSLSSolid:"Ononderbroken"},fillStyles:{esriSFSBackwardDiagonal:"Achterwaarts",esriSFSCross:"Kruis",esriSFSDiagonalCross:"Diagonaal",esriSFSForwardDiagonal:"Voorwaarts",esriSFSHorizontal:"Horizontaal",esriSFSNull:"Null",
esriSFSSolid:"Ononderbroken",esriSFSVertical:"Verticaal"},resultsTitle:"Resultaten",publishTABtn:"Publiceren",layerName:"Gepubliceerde laagnaam",invalidLayerName:"Laagnaam mag alleen alfanumerieke tekens en onderstrepingstekens bevatten",missingLayerName:"U moet een naam invoeren voor de laag",missingLayerNameMessage:"U moet een geldige laagnaam invoeren voordat u kunt publiceren",publishingFailedLayerExists:"Publiceren mislukt: u hebt al een featureservice met de naam {0}. Kies een andere naam.",
checkService:"Controleer service: {0}",createService:"Maak service: {0}",unableToCreate:"Niet mogelijk om te maken: {0}",addToDefinition:"Voeg toe aan definitie: {0}",successfullyPublished:"Succesvolle publicatie weblaag{0}Beheer de weblaag",userRole:"Kan service niet maken omdat de gebruiker niet gemachtigd is",transparencyLabel:"Transparantie",outline:"Omtreklijn",fill:"Vullen (kleur wordt alleen toegepast als stijl ingesteld is al solid)",createBtn:"Zones maken",clearBtn:"Annuleren",invalidNumberMessage:"De ingevoerde waarde is niet geldig",
invalidRangeMessage:"Waarde moet groter zijn dan 0",parseCoordinatesError:"Co\u00f6rdinaten kunnen niet geparseerd worden. Controleer uw invoer.",manualCoordinateInputInfo:"Co\u00f6rdinaten handmatig invoeren en op \x3cb\x3eEnter\x3c/b\x3e drukken om erop in te zoomen",pipeBombLabel:"Pijpbom",suicideBombLabel:"Zelfmoordaanslag",briefcaseLabel:"Aktetas",carLabel:"Auto",suvVanLabel:"SUV/busje",smallDeliveryTruckLabel:"Klein bestelbusje",containerWaterTruckLabel:"Container/vrachtwagen voor vervoer van water",
semiTrailerLabel:"Oplegger",selectDrawModeLabel:"Tekenmodus selecteren",selectFeatureLabel:"Object uit deze laag selecteren",_localized:{}}});