// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/PublicNotification/setting/nls/strings":{searchSourceSetting:{title:"Ustawienia wyszukiwania i buforowania",mainHint:"Mo\u017cna w\u0142\u0105czy\u0107 wyszukiwanie tekstowe adres\u00f3w i obiekt\u00f3w, digitalizacj\u0119 geometrii oraz buforowanie."},addressSourceSetting:{title:"Warstwy adres\u00f3w",mainHint:"Mo\u017cna poda\u0107, kt\u00f3re warstwy etykiet adres\u00f3w s\u0105 dost\u0119pne."},notificationSetting:{title:"Opcje powiadomie\u0144",mainHint:"Mo\u017cna poda\u0107, kt\u00f3re typy powiadomie\u0144 s\u0105 dost\u0119pne."},
groupingLabels:{addressSources:"Warstwa, kt\u00f3ra ma by\u0107 u\u017cywana do wyboru warstw adres\u00f3w",averyStickersDetails:"Naklejki Avery(r)",csvDetails:"Plik z warto\u015bciami rozdzielanymi przecinkami (CSV)",drawingTools:"Narz\u0119dzia rysowania do okre\u015blania obszaru",featureLayerDetails:"Warstwa obiektowa",geocoderDetails:"Geokoder",labelFormats:"Dost\u0119pne formaty etykiet",printingOptions:"Opcje drukowanych stron etykiet",searchSources:"\u0179r\u00f3d\u0142a wyszukiwania",stickerFormatDetails:"Parametry strony etykiet"},
hints:{alignmentAids:"Znaczniki dodawane do strony etykiet, kt\u00f3re s\u0105 pomocne przy dostosowywaniu strony do u\u017cywanej drukarki",csvNameList:"Lista rozdzielanych przecinkami nazw p\u00f3l, w kt\u00f3rych rozr\u00f3\u017cniana jest wielko\u015b\u0107 liter",horizontalGap:"Spacja mi\u0119dzy dwiema etykietami w wierszu",insetToLabel:"Spacja mi\u0119dzy kraw\u0119dzi\u0105 etykiety a pocz\u0105tkiem tekstu",labelFormatDescription:"Spos\u00f3b przedstawiania stylu etykiety na li\u015bcie opcji formatowania wid\u017cetu",
labelFormatDescriptionHint:"Etykieta narz\u0119dzia uzupe\u0142niaj\u0105ca opis na li\u015bcie opcji formatowania",labelHeight:"Wysoko\u015b\u0107 poszczeg\u00f3lnych etykiet na stronie",labelWidth:"Szeroko\u015b\u0107 poszczeg\u00f3lnych etykiet na stronie",localSearchRadius:"Okre\u015bla promie\u0144 obszaru wok\u00f3\u0142 centrum bie\u017c\u0105cej mapy u\u017cywanego do przyspieszenia oceny propozycji geokodowania, aby propozycje znajduj\u0105ce si\u0119 najbli\u017cej lokalizacji by\u0142y zwracane jako pierwsze",
rasterResolution:"100 pikseli na cal w przybli\u017ceniu pasuje do rozdzielczo\u015bci ekranu. Im wy\u017csza rozdzielczo\u015b\u0107, tym wi\u0119cej potrzeba pami\u0119ci przegl\u0105darki. R\u00f3\u017cne przegl\u0105darki maj\u0105 r\u00f3\u017cne mo\u017cliwo\u015bci odpowiedniej obs\u0142ugi du\u017cego zapotrzebowania na pami\u0119\u0107.",selectionListOfOptionsToDisplay:"Zaznaczone elementy s\u0105 wy\u015bwietlane jako opcje w wid\u017cecie, kolejno\u015b\u0107 mo\u017cna zmieni\u0107 wed\u0142ug potrzeb",
verticalGap:"Spacja mi\u0119dzy dwiema etykietami w kolumnie"},propertyLabels:{bufferDefaultDistance:"Domy\u015blna odleg\u0142o\u015b\u0107 buforowania",bufferUnits:"Jednostki buforowania do podania w wid\u017cecie",countryRegionCodes:"Kody kraju lub regionu",description:"Opis",descriptionHint:"Wskaz\u00f3wka dotycz\u0105ca opisu",displayField:"Pole wy\u015bwietlania",drawingToolsFreehandPolygon:"poligon odr\u0119czny",drawingToolsLine:"linia",drawingToolsPoint:"punkt",drawingToolsPolygon:"polygon",
drawingToolsPolyline:"polyline",enableLocalSearch:"W\u0142\u0105cz wyszukiwanie lokalne",exactMatch:"Dok\u0142adne dopasowanie",fontSizeAlignmentNote:"Rozmiar czcionki dla notatek na marginesach wydruku",gridDarkness:"Zaciemnienie siatki",gridlineLeftInset:"Ramka linii siatki z lewej strony",gridlineMajorTickMarksGap:"Znacznik g\u0142\u00f3wny zaznacza wszystko",gridlineMinorTickMarksGap:"Znacznik pomocniczy zaznacza wszystko",gridlineRightInset:"Ramka linii siatki z prawej strony",labelBorderDarkness:"Zaciemnienie ramki etykiety",
labelBottomEdge:"Dolna kraw\u0119d\u017a etykiet na stronie",labelFontSize:"Rozmiar czcionki",labelHeight:"Wysoko\u015b\u0107 etykiety",labelHorizontalGap:"Odst\u0119p w poziomie",labelInitialInset:"Ramka tekstu etykiety",labelLeftEdge:"Lewa kraw\u0119d\u017a etykiet na stronie",labelMaxLineCount:"Maksymalna liczba wierszy na etykiecie",labelPageHeight:"Wysoko\u015b\u0107 strony",labelPageWidth:"Szeroko\u015b\u0107 strony",labelRightEdge:"Prawa kraw\u0119d\u017a etykiet na stronie",labelsInAColumn:"Liczba etykiet w kolumnie",
labelsInARow:"Liczba etykiet w wierszu",labelTopEdge:"G\u00f3rna kraw\u0119d\u017a etykiet na stronie",labelVerticalGap:"Odst\u0119p w pionie",labelWidth:"Szeroko\u015b\u0107 etykiety",limitSearchToMapExtent:"Wyszukaj tylko w bie\u017c\u0105cym zasi\u0119gu mapy",maximumResults:"Maksymalna liczba wynik\u00f3w",maximumSuggestions:"Maksymalna liczba sugestii",minimumScale:"Skala minimalna",name:"Nazwa",percentBlack:"% czarnego",pixels:"piksele",pixelsPerInch:"piksele na cal",placeholderText:"Tekst zast\u0119pczy",
placeholderTextForAllSources:"Tekst zast\u0119pczy przeszukiwania wszystkich \u017ar\u00f3de\u0142",radius:"Promie\u0144",rasterResolution:"Rozdzielczo\u015b\u0107 rastra",searchFields:"Pola wyszukiwania",showAlignmentAids:"Poka\u017c na stronie elementy wspomagaj\u0105ce wyr\u00f3wnywanie",showGridTickMarks:"Poka\u017c znaczniki siatki",showLabelOutlines:"Poka\u017c obrysy etykiety",showPopupForFoundItem:"Wy\u015bwietl odr\u0119bne okno ze znalezionym elementem: obiektem lub miejscem",tool:"Narz\u0119dzia",
units:"Jednostki",url:"Adres URL",urlToGeometryService:"Adres URL do us\u0142ugi geometrii",useRelatedRecords:"U\u017cyj jego powi\u0105zanych rekord\u00f3w",useSecondarySearchLayer:"U\u017cyj warstwy dodatkowego wyboru",useSelectionDrawTools:"U\u017cyj narz\u0119dzi rysowania zaznaczenia",useVectorFonts:"U\u017cyj czcionek wektorowych (tylko czcionki \u0142aci\u0144skie)",zoomScale:"Skala powi\u0119kszenia"},buttons:{addAddressSource:"Dodaj warstw\u0119 zawieraj\u0105c\u0105 etykiety adresowe w jej oknie podr\u0119cznym",
addLabelFormat:"Dodaj format etykiety",addSearchSource:"Dodaj \u017ar\u00f3d\u0142o wyszukiwania",set:"Ustaw"},placeholders:{averyExample:"np. Etykieta Avery(r) ${averyPartNumber}",countryRegionCodes:"np. USA,CHN",descriptionCSV:"Warto\u015bci rozdzielane przecinkami",descriptionPDF:"Etykieta pliku PDF ${heightLabelIn} x ${widthLabelIn} cale(i); ${labelsPerPage} na stron\u0119"},tooltips:{getWebmapFeatureLayer:"Pobierz warstw\u0119 obiektow\u0105 z mapy internetowej",openCountryCodes:"Kliknij, aby pobra\u0107 wi\u0119cej informacji o kodach",
openFieldSelector:"Kliknij, aby otworzy\u0107 selektor p\u00f3l",setAndValidateURL:"Ustaw adres URL i sprawd\u017a jego poprawno\u015b\u0107"},problems:{noAddresseeLayers:"Okre\u015bl co najmniej jedn\u0105 warstw\u0119 adres\u00f3w",noBufferUnitsForDrawingTools:"Skonfiguruj co najmniej jedn\u0105 jednostk\u0119 buforowania dla narz\u0119dzi rysowania",noBufferUnitsForSearchSource:'Skonfiguruj co najmniej jedn\u0105 jednostk\u0119 buforowania dla \u017ar\u00f3d\u0142a wyszukiwania "${sourceName}"',
noGeometryServiceURL:"Skonfiguruj adres URL us\u0142ugi geometrii",noNotificationLabelFormats:"Okre\u015bl co najmniej jeden format etykiety powiadomienia",noSearchSourceFields:'Skonfiguruj jedno lub wi\u0119ksz\u0105 liczb\u0119 p\u00f3l wyszukiwania dla \u017ar\u00f3d\u0142a wyszukiwania "${sourceName}"',noSearchSourceURL:'Skonfiguruj adres URL dla \u017ar\u00f3d\u0142a wyszukiwania "${sourceName}"'},querySourceSetting:{sourceSetting:"Ustawienia \u017ar\u00f3d\u0142a wyszukiwania",instruction:"Dodaj i skonfiguruj us\u0142ugi geokodowania lub warstwy obiektowe jako \u017ar\u00f3d\u0142a wyszukiwania. Okre\u015blone \u017ar\u00f3d\u0142a decyduj\u0105 o tym, co jest przeszukiwane przy u\u017cyciu pola wyszukiwania.",
add:"Dodaj \u017ar\u00f3d\u0142o wyszukiwania",addGeocoder:"Dodaj geokoder",geocoder:"Geokoder",setLayerSource:"Skonfiguruj \u017ar\u00f3d\u0142o warstwy",setGeocoderURL:"Skonfiguruj adres URL geokodera",searchableLayer:"Warstwa",name:"Nazwa",countryCode:"Kody kraju lub regionu",countryCodeEg:"np. ",countryCodeHint:"Pozostawienie pustego pola uruchomi wyszukiwanie we wszystkich krajach i regionach",generalSetting:"Ustawienia og\u00f3lne",allPlaceholder:"Tekst zast\u0119pczy dla wyszukiwania wszystkich: ",
showInfoWindowOnSelect:"Wy\u015bwietl odr\u0119bne okno ze znalezionym elementem: obiektem lub miejscem",showInfoWindowOnSelect2:"Wy\u015bwietla okno podr\u0119czne po znalezieniu obiektu lub lokalizacji.",searchInCurrentMapExtent:"Wyszukaj tylko w bie\u017c\u0105cym zasi\u0119gu mapy",zoomScale:"Skala powi\u0119kszenia",locatorUrl:"Adres URL geokodera",locatorName:"Nazwa geokodera",locatorExample:"Przyk\u0142ad",locatorWarning:"Ta wersja us\u0142ugi geokodowania nie jest obs\u0142ugiwana. Ten wid\u017cet obs\u0142uguje us\u0142ugi geokodowania w wersji 10.1 i nowsze.",
locatorTips:"Sugestie s\u0105 niedost\u0119pne poniewa\u017c us\u0142uga geokodowania nie obs\u0142uguje funkcji sugestii.",layerSource:"\u0179r\u00f3d\u0142o warstwy",searchLayerTips:"Sugestie s\u0105 niedost\u0119pne poniewa\u017c us\u0142uga obiektowa nie obs\u0142uguje funkcji paginacji.",placeholder:"Tekst zast\u0119pczy",searchFields:"Pola wyszukiwania",displayField:"Pole wy\u015bwietlania",exactMatch:"Dok\u0142adne dopasowanie",maxSuggestions:"Maksymalna liczba sugestii",maxResults:"Maksymalna liczba wynik\u00f3w",
enableLocalSearch:"W\u0142\u0105cz wyszukiwanie lokalne",minScale:"Skala min.",minScaleHint:"Kiedy skala mapy b\u0119dzie wi\u0119ksza ni\u017c ta skala, zostanie zastosowane wyszukiwanie lokalne",radius:"Promie\u0144",radiusHint:"Okre\u015bla promie\u0144 obszaru wok\u00f3\u0142 bie\u017c\u0105cego centrum mapy u\u017cywanego do przyspieszenia oceny propozycji geokodowania, aby propozycje znajduj\u0105ce si\u0119 najbli\u017cej lokalizacji by\u0142y zwracane jako pierwsze",meters:"Metry",setSearchFields:"Skonfiguruj pola wyszukiwania",
set:"Zestaw",fieldSearchable:"mo\u017cliwe do wyszukiwania",fieldName:"Nazwa",fieldAlias:"Alias",ok:"OK",cancel:"Anuluj",invalidUrlTip:"Adres URL ${URL} jest nieprawid\u0142owy lub nieosi\u0105galny.",locateResults:"Wyniki lokalizacji",panTo:"Przesu\u0144 do",zoomToScale:"Powi\u0119ksz do skali",locatorError:"Lokalizator musi obs\u0142ugiwa\u0107 lokalizacj\u0119 pojedynczych linii."},_localized:{}}});