// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Tebal",copy:"Salin",cut:"Potong","delete":"Hapus",indent:"Inden",insertHorizontalRule:"Penggaris horisontal",insertOrderedList:"Daftar Bernomor",insertUnorderedList:"Daftar Poin",italic:"Miring",justifyCenter:"Rata Tengah",justifyFull:"Rata Kanan Kiri",justifyLeft:"Rata Kiri",justifyRight:"Rata Kanan",outdent:"Hapus spasi di depan",paste:"Tempel",redo:"Ulangi",removeFormat:"Hapus Format",selectAll:"Pilih Semua",strikethrough:"Coretan",subscript:"Subskrip",
superscript:"Superskrip",underline:"Garis Bawah",undo:"Batalkan",unlink:"Hapus Tautan",createLink:"Buat Tautan",toggleDir:"Ubah Arah",insertImage:"Masukkan Gambar",insertTable:"Masukkan/Edit Tabel",toggleTableBorder:"Ubah Tepi Tabel",deleteTable:"Hapus Tabel",tableProp:"Properti Tabel",htmlToggle:"Sumber HTML",foreColor:"Warna Latar Depan",hiliteColor:"Warna Latar Belakang",plainFormatBlock:"Gaya Paragraf",formatBlock:"Gaya Paragraf",fontSize:"Ukuran Font",fontName:"Nama Font",tabIndent:"Inden Tab",
fullScreen:"Beralih ke Layar Penuh",viewSource:"Lihat Sumber HTML",print:"Cetak",newPage:"Halaman Baru",systemShortcut:'Tindakan "${0}" hanya tersedia pada peramban Anda menggunakan jalan pintas keyboard. Gunakan ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Min Sen Sel Rab Kam Jum Sab".split(" "),"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"sekarang","quarters-standAlone-narrow":["1",
"2","3","4"],"field-weekday":"Hari dalam Seminggu","field-wed-relative+0":"Rabu ini","field-wed-relative+1":"Rabu berikutnya","dateFormatItem-GyMMMEd":"E, d MMM y G","dateFormatItem-MMMEd":"E, d MMM",eraNarrow:["AH"],"field-tue-relative+-1":"Selasa lalu","days-format-short":"Min Sen Sel Rab Kam Jum Sab".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"d MMMM y G","field-fri-relative+-1":"Jumat lalu","field-wed-relative+-1":"Rabu lalu","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sya\u2019ban;Ramadhan;Syawal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"dateFormatItem-yyyyQQQ":"QQQ y G","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"EEEE, dd MMMM y G","dateFormatItem-yyyyMEd":"E, d/M/y G","field-thu-relative+-1":"Kamis lalu","dateFormatItem-Md":"d/M","dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sya\u2019ban;Ramadhan;Syawal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),
"timeFormat-short":"HH.mm","quarters-format-wide":["Kuartal ke-1","Kuartal ke-2","Kuartal ke-3","Kuartal ke-4"],"timeFormat-long":"HH.mm.ss z","field-year":"Tahun","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Jam","months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Syaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"Sabtu ini","field-sat-relative+1":"Sabtu berikutnya","timeFormat-full":"HH.mm.ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})",
"field-day-relative+0":"hari ini","field-thu-relative+0":"Kamis ini","field-day-relative+1":"besok","field-thu-relative+1":"Kamis berikutnya","dateFormatItem-GyMMMd":"d MMM y G","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Syaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"quarters-format-abbr":["K1","K2","K3","K4"],"quarters-standAlone-wide":["Kuartal ke-1","Kuartal ke-2","Kuartal ke-3","Kuartal ke-4"],"dateFormatItem-Gy":"y G","dateFormatItem-yyyyMMMEd":"E, d MMM y G",
"dateFormatItem-M":"L","days-standAlone-wide":"Minggu Senin Selasa Rabu Kamis Jumat Sabtu".split(" "),"dateFormatItem-yyyyMMM":"MMM y G","dateFormatItem-yyyyMMMd":"d MMM y G","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH.mm.ss","field-sun-relative+0":"hari Minggu ini","dateFormatItem-Hm":"HH.mm","field-sun-relative+1":"hari Minggu berikutnya","quarters-standAlone-abbr":["K1","K2","K3","K4"],eraAbbr:["AH"],"field-minute":"Menit","field-dayperiod":"AM/PM","days-standAlone-abbr":"Min Sen Sel Rab Kam Jum Sab".split(" "),
"dateFormatItem-d":"d","dateFormatItem-ms":"mm.ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"kemarin","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"AM","dateFormatItem-h":"h a","dateFormatItem-MMMd":"d MMM","dateFormatItem-MEd":"E, d/M","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"Jumat ini","field-fri-relative+1":"Jumat berikutnya","field-day":"Hari","days-format-wide":"Minggu Senin Selasa Rabu Kamis Jumat Sabtu".split(" "),"field-zone":"Zona Waktu",
"months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"y G","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"tahun lalu","field-month-relative+-1":"bulan lalu","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h.mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM","days-format-abbr":"Min Sen Sel Rab Kam Jum Sab".split(" "),eraNames:["AH"],"days-format-narrow":"MSSRKJS".split(""),"dateFormatItem-yyyyMd":"d/M/y G",
"field-month":"Bulan","days-standAlone-narrow":"MSSRKJS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"Selasa ini","field-tue-relative+1":"Selasa berikutnya","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})","dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"Senin ini","field-mon-relative+1":"Senin berikutnya","dateFormat-short":"d/M/y GGGGG",
"dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Detik","field-sat-relative+-1":"Sabtu lalu","field-sun-relative+-1":"hari Minggu lalu","field-month-relative+0":"bulan ini","field-month-relative+1":"Bulan berikutnya","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"E, d","field-week":"Minggu","dateFormat-medium":"d MMM y G","field-week-relative+-1":"minggu lalu","field-year-relative+0":"tahun ini","dateFormatItem-yyyyM":"M/y G",
"field-year-relative+1":"tahun depan","dayPeriods-format-narrow-pm":"PM","dateFormatItem-yyyyQQQQ":"QQQQ y G","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH.mm.ss","dateFormatItem-hms":"h.mm.ss a","dateFormatItem-GyMMM":"MMM y G","field-mon-relative+-1":"Senin lalu","dateFormatItem-yyyy":"y G","field-week-relative+0":"minggu ini","field-week-relative+1":"minggu berikutnya","field-day-relative+2":"lusa","dateFormatItem-MMMMd":"d MMMM","field-day-relative+-2":"kemarin lusa","dateFormatItem-MMMMEd":"E, d MMMM",
_localized:{}},"widgets/BatchAttributeEditor/nls/strings":{_widgetLabel:"Editor Atribut Kelompok",widgetIntroSelectByArea:"Gunakan salah satu alat di bawah untuk membuat set fitur terpilih untuk diperbarui. Jika baris adalah \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, maka jumlah maksimal catatan telah terlampaui.",widgetIntroSelectByFeature:"Gunakan alat di bawah untuk memilih fitur dari layer \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Fitur ini akan digunakan untuk memilih dan memperbarui semua fitur yang berpotongan. Jika baris adalah \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, maka jumlah maksimal catatan telah terlampaui.",
widgetIntroSelectByFeatureQuery:"Gunakan alat di bawah untuk memilih fitur dari \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e . Atribut \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e fitur ini akan digunakan untuk meng-query layer di bawah dan memperbarui fitur yang dihasilkan. Jika baris adalah \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, maka jumlah maksimal catatan telah terlampaui.",widgetIntroSelectByQuery:"Masukkan nilai untuk membuat set pilihan. Jika baris adalah \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, maka jumlah maksimal catatan telah terlampaui.",
layerTable:{colLabel:"Nama Layer",numSelected:"#",colSyncStatus:""},noConfiguredLayers:"Tidak ada layer yang dapat diedit dikonfigurasikan",editorPopupTitle:"Editor Atribut Kelompok",editorPopupSaveBtn:"Simpan",editorPopupMultipleValues:"",clear:"Kosongkan",featuresUpdated:"${0} / ${1} fitur diperbarui",featuresSelected:"${0} fitur dipilih",featuresSkipped:"Dilewati",search:"Cari",queryInput:"Masukkan nilai pada query",noFilterTip:"Tanpa menetapkan ekspresi filter, tugas query ini akan mencantumkan semua fitur dalam sumber data yang sudah ditentukan.",
setFilterTip:"Tetapkan filter dengan benar.",filterPopup:"Layer Filter",cancel:"Batal",noValue:"Tidak Ada Nilai",emptyString:"String Kosong",existingValue:"Simpan Nilai yang Ada",newDate:"Tanggal Baru",valueChooser:"Pilih/Ketikkan sebuah Nilai",ok:"Ya",drawBox:{point:"Titik",line:"Garis",polyline:"Polyline",freehandPolyline:"Polyline Freehand",extent:"Jangkauan",polygon:"Poligon",freehandPolygon:"Poligon Bebas",clear:"Kosongkan",addPointToolTip:"Klik untuk memilih di area ini",addShapeToolTip:"Gambar sebuah bentuk untuk memilih fitur",
freehandToolTip:"Tekan dan tahan untuk menggambar bentuk untuk memilih fitur",startToolTip:"Gambar sebuah bentuk untuk memilih fitur"},errors:{layerNotFound:"Layer ${0} dengan ID ${1} tidak ditemukan dalam peta, peta mungkin telah berubah sejak konfigurasi widget",queryNullID:"Fitur dari ${0} menghasilkan ID yang tidak valid",noSelectedLayers:"Tidak ada layer yang mengandung catatan dipilih untuk diperbarui",inputValueError:"Nilai dalam form tidak valid",saveError:"Tidak dapat menyimpan ${0} fitur, rincian ditambahkan ke konsol",
requiredValue:"Nilai Harus Diisi"},_localized:{}}});