// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Geoprocessing/resultrenderers/FeatureSetRenderer.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"output-label" data-dojo-attach-point\x3d"labelNode"\x3e\r\n    \x3cspan data-dojo-attach-point\x3d"labelContent"\x3e${nls.drawnOnMap}\x3c/span\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"clear-node" data-dojo-attach-point\x3d"clearNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"popup-menu-button" data-dojo-attach-point\x3d"exportNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-style dojo/dom-attr dojo/on dojo/dom-geometry dijit/_TemplatedMixin esri/layers/GraphicsLayer esri/layers/FeatureLayer esri/graphicsUtils esri/renderers/SimpleRenderer esri/renderers/jsonUtils esri/InfoTemplate jimu/dijit/FeatureActionPopupMenu dojo/text!./FeatureSetRenderer.html ../BaseResultRenderer ../LayerOrderUtil ./defaultSymbol ../utils".split(" "),function(q,d,g,e,m,h,r,t,u,n,v,k,p,w,x,y,z,A,l,B){return q([z,t],{baseClass:"jimu-gp-resultrenderer-base jimu-gp-renderer-draw-feature",
templateString:y,postCreate:function(){this.inherited(arguments);this.popupMenu=x.getInstance();this.value.features&&0<this.value.features.length?(this._displayText(),this._drawResultFeature(this.param,this.value)):this.value.url?(this._displayText(!0),this._addResultURL(this.param,this.value.url)):(e.set(this.clearNode,"display","none"),e.set(this.exportNode,"display","none"),this.labelContent.innerHTML=this.nls.emptyResult)},destroy:function(){this.resultLayer&&this.map.removeLayer(this.resultLayer);
this.inherited(arguments)},_displayText:function(a){e.set(this.clearNode,"display","");m.set(this.clearNode,"title",this.nls.clear);this.own(h(this.clearNode,"click",d.hitch(this,function(){this.resultLayer&&(this.map.infoWindow.isShowing&&this.map.infoWindow.hide(),this.resultLayer.clear(),this.map.removeLayer(this.resultLayer));e.set(this.exportNode,"display","none");e.set(this.clearNode,"display","none");this.labelContent.innerHTML=this.nls.cleared})));a||(e.set(this.exportNode,"display",""),m.set(this.exportNode,
"title",this.nls.exportOutput),this.own(h(this.exportNode,"click",d.hitch(this,this._showActions))))},_showActions:function(a){this.popupMenu.prepareActions(this.value,this.config.showExportButton).then(d.hitch(this,function(){var b=r.position(a.target);this.popupMenu.show(b)}))},_addResultURL:function(a,b){this.resultLayer=new n(b,{id:this.widgetUID+a.name});this.resultLayer.title=a.label||a.name;a.renderer&&(b=p.fromJson(a.renderer),!1===a.renderer._showOthersSymbol&&(b.defaultSymbol=null),this.resultLayer.setRenderer(b));
this.resultLayer.setVisibility(!0!==a.layerInvisible);this._addResultLayer(a.name);this.own(h(this.resultLayer,"load",d.hitch(this,function(a){a.layer&&a.layer.fullExtent&&this.map.setExtent(a.layer.fullExtent.expand(1.2))})))},_drawResultFeature:function(a,b){var c,f=B.useDynamicSchema(a,this.config);if(!a.popup||f)a.popup={enablePopup:!0,title:"",fields:[]};a.popup.enablePopup&&(c=new w(a.popup.title||"${Non-Exist-Field}",this._generatePopupContent(b,f)));if(this.config.shareResults&&!f){if(!a.defaultValue||
!a.defaultValue.geometryType)throw Error("Output parameter default value does not provide enough information to draw feature layer.");a.defaultValue.name=a.name;this.resultLayer=new n({layerDefinition:a.defaultValue,featureSet:null},{id:this.widgetUID+a.name,infoTemplate:c})}else this.resultLayer=new u({id:this.widgetUID+a.name,infoTemplate:c});g.forEach(b.features,function(a){this.resultLayer.add(a)},this);this.resultLayer.title=a.label||a.name;c=a.renderer;f||!c?"esriGeometryPoint"===b.geometryType||
"esriGeometryMultipoint"===b.geometryType?c=new k(l.pointSymbol):"esriGeometryPolyline"===b.geometryType?c=new k(l.lineSymbol):"esriGeometryPolygon"===b.geometryType&&(c=new k(l.polygonSymbol)):(c=p.fromJson(c),!1===a.renderer._showOthersSymbol&&(c.defaultSymbol=null));this.resultLayer.setRenderer(c);this.resultLayer.setVisibility(!0!==a.layerInvisible);this._addResultLayer(a.name);try{if(b.features&&0<b.features.length&&b.features[0].geometry){var d=v.graphicsExtent(b.features);d&&(this.resultLayer.fullExtent=
d)}}catch(C){console.error(C)}},_addResultLayer:function(a){var b=new A(this.config,this.map);try{b.calculateLayerIndex(a,this.widgetUID).then(d.hitch(this,function(a){-1!==a?this.map.addLayer(this.resultLayer,a):this.map.addLayer(this.resultLayer)}))}catch(c){console.error(c.message),console.warn("Draw result feature set on the top of map"),this.map.addLayer(this.resultLayer)}},_generatePopupContent:function(a,b){var c="";a=!b&&this.param.popup.fields&&0<this.param.popup.fields.length?g.filter(this.param.popup.fields,
d.hitch(this,function(a){return!1!==a.visible})):a.fields;g.forEach(a,function(a){c+='\x3ctr valign\x3d"top"\x3e\x3ctd class\x3d"attr-name"\x3e'+a.alias+'\x3c/td\x3e\x3ctd class\x3d"attr-value"\x3e${'+a.name+"}\x3c/td\x3e\x3c/tr\x3e"});return'\x3cdiv class\x3d"geoprocessing-popup"\x3e\x3ctable class\x3d"geoprocessing-popup-table" cellpadding\x3d"0" cellspacing\x3d"0"\x3e\x3ctbody\x3e'+c+"\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e"}})});