// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negreta",copy:"Copia",cut:"Retalla","delete":"Suprimeix",indent:"Sagnat",insertHorizontalRule:"Regla horitzontal",insertOrderedList:"Llista numerada",insertUnorderedList:"Llista de vinyetes",italic:"Cursiva",justifyCenter:"Alineaci\u00f3 centrada",justifyFull:"Justifica",justifyLeft:"Alineaci\u00f3 a l'esquerra",justifyRight:"Alineaci\u00f3 a la dreta",outdent:"Sagnat a l'esquerra",paste:"Enganxa",redo:"Ref\u00e9s",removeFormat:"Elimina el format",selectAll:"Selecciona-ho tot",
strikethrough:"Ratllat",subscript:"Sub\u00edndex",superscript:"Super\u00edndex",underline:"Subratllat",undo:"Desf\u00e9s",unlink:"Elimina l'enlla\u00e7",createLink:"Crea un enlla\u00e7",toggleDir:"Inverteix la direcci\u00f3",insertImage:"Insereix imatge",insertTable:"Insereix/edita la taula",toggleTableBorder:"Inverteix els contorns de taula",deleteTable:"Suprimeix la taula",tableProp:"Propietat de taula",htmlToggle:"Font HTML",foreColor:"Color de primer pla",hiliteColor:"Color de fons",plainFormatBlock:"Estil de par\u00e0graf",
formatBlock:"Estil de par\u00e0graf",fontSize:"Mida del tipus de lletra",fontName:"Nom del tipus de lletra",tabIndent:"Sagnat",fullScreen:"Commuta pantalla completa",viewSource:"Visualitza font HTML",print:"Imprimeix",newPage:"P\u00e0gina nova",systemShortcut:"L'acci\u00f3 \"${0}\" \u00e9s l'\u00fanica disponible al navegador utilitzant una drecera del teclat. Utilitzeu ${1}.",ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"dojo/cldr/nls/islamic":{"dateFormatItem-Ehm":"E h:mm a","days-standAlone-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),
"months-format-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"field-second-relative+0":"now","quarters-standAlone-narrow":["1","2","3","4"],"field-weekday":"Day of the Week","field-wed-relative+0":"this Wednesday","field-wed-relative+1":"next Wednesday","dateFormatItem-GyMMMEd":"G y MMM d, E","dateFormatItem-MMMEd":"MMM d, E",eraNarrow:["AH"],"field-tue-relative+-1":"last Tuesday","days-format-short":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateTimeFormats-appendItem-Day-Of-Week":"{0} {1}","dateFormat-long":"G y MMMM d",
"field-fri-relative+-1":"last Friday","field-wed-relative+-1":"last Wednesday","months-format-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"dateFormatItem-yyyyQQQ":"G y QQQ","dateTimeFormat-medium":"{1} {0}","dayPeriods-format-wide-pm":"PM","dateFormat-full":"G y MMMM d, EEEE","dateFormatItem-yyyyMEd":"GGGGG y-MM-dd, E","field-thu-relative+-1":"last Thursday","dateFormatItem-Md":"MM-dd",
"dayPeriods-format-abbr-am":"AM","dateTimeFormats-appendItem-Second":"{0} ({2}: {1})","dayPeriods-format-wide-noon":"noon","field-era":"Era","months-standAlone-wide":"Muharram;Safar;Rabi\u02bb I;Rabi\u02bb II;Jumada I;Jumada II;Rajab;Sha\u02bbban;Ramadan;Shawwal;Dhu\u02bbl-Qi\u02bbdah;Dhu\u02bbl-Hijjah".split(";"),"timeFormat-short":"HH:mm","quarters-format-wide":["Q1","Q2","Q3","Q4"],"timeFormat-long":"HH:mm:ss z","field-year":"Year","dateTimeFormats-appendItem-Era":"{1} {0}","field-hour":"Hour",
"months-format-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),"field-sat-relative+0":"this Saturday","field-sat-relative+1":"next Saturday","timeFormat-full":"HH:mm:ss zzzz","dateTimeFormats-appendItem-Week":"{0} ({2}: {1})","field-day-relative+0":"today","field-thu-relative+0":"this Thursday","field-day-relative+1":"tomorrow","field-thu-relative+1":"next Thursday","dateFormatItem-GyMMMd":"G y MMM d","dateFormatItem-H":"HH","months-standAlone-abbr":"Muh.;Saf.;Rab. I;Rab. II;Jum. I;Jum. II;Raj.;Sha.;Ram.;Shaw.;Dhu\u02bbl-Q.;Dhu\u02bbl-H.".split(";"),
"quarters-format-abbr":["Q1","Q2","Q3","Q4"],"quarters-standAlone-wide":["Q1","Q2","Q3","Q4"],"dateFormatItem-Gy":"G y","dateFormatItem-yyyyMMMEd":"G y MMM d, E","dateFormatItem-M":"L","days-standAlone-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-yyyyMMM":"G y MMM","dateFormatItem-yyyyMMMd":"G y MMM d","dayPeriods-format-abbr-noon":"noon","timeFormat-medium":"HH:mm:ss","field-sun-relative+0":"this Sunday","dateFormatItem-Hm":"HH:mm","field-sun-relative+1":"next Sunday","quarters-standAlone-abbr":["Q1",
"Q2","Q3","Q4"],eraAbbr:["AH"],"field-minute":"Minute","field-dayperiod":"Dayperiod","days-standAlone-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"dateFormatItem-d":"d","dateFormatItem-ms":"mm:ss","quarters-format-narrow":["1","2","3","4"],"field-day-relative+-1":"yesterday","dateTimeFormat-long":"{1} {0}","dayPeriods-format-narrow-am":"a","dateFormatItem-h":"h a","dateFormatItem-MMMd":"MMM d","dateFormatItem-MEd":"MM-dd, E","dateTimeFormat-full":"{1} {0}","field-fri-relative+0":"this Friday",
"field-fri-relative+1":"next Friday","field-day":"Day","days-format-wide":"Sun Mon Tue Wed Thu Fri Sat".split(" "),"field-zone":"Zone","months-standAlone-narrow":"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),"dateFormatItem-y":"G y","dateTimeFormats-appendItem-Day":"{0} ({2}: {1})","field-year-relative+-1":"last year","field-month-relative+-1":"last month","dateTimeFormats-appendItem-Year":"{1} {0}","dateFormatItem-hm":"h:mm a","dateTimeFormats-appendItem-Hour":"{0} ({2}: {1})","dayPeriods-format-abbr-pm":"PM",
"days-format-abbr":"Sun Mon Tue Wed Thu Fri Sat".split(" "),eraNames:["AH"],"days-format-narrow":"SMTWTFS".split(""),"dateFormatItem-yyyyMd":"GGGGG y-MM-dd","field-month":"Month","days-standAlone-narrow":"SMTWTFS".split(""),"dateFormatItem-MMM":"LLL","field-tue-relative+0":"this Tuesday","field-tue-relative+1":"next Tuesday","dateTimeFormats-appendItem-Quarter":"{0} ({2}: {1})","dayPeriods-format-wide-am":"AM","dateTimeFormats-appendItem-Month":"{0} ({2}: {1})","dateTimeFormats-appendItem-Minute":"{0} ({2}: {1})",
"dateFormatItem-EHm":"E HH:mm","field-mon-relative+0":"this Monday","field-mon-relative+1":"next Monday","dateFormat-short":"GGGGG y-MM-dd","dateFormatItem-EHms":"E HH:mm:ss","dateFormatItem-Ehms":"E h:mm:ss a","dayPeriods-format-narrow-noon":"n","field-second":"Second","field-sat-relative+-1":"last Saturday","field-sun-relative+-1":"last Sunday","field-month-relative+0":"this month","field-month-relative+1":"next month","dateTimeFormats-appendItem-Timezone":"{0} {1}","dateFormatItem-Ed":"d, E","field-week":"Week",
"dateFormat-medium":"G y MMM d","field-week-relative+-1":"last week","field-year-relative+0":"this year","dateFormatItem-yyyyM":"GGGGG y-MM","field-year-relative+1":"next year","dayPeriods-format-narrow-pm":"p","dateFormatItem-yyyyQQQQ":"G y QQQQ","dateTimeFormat-short":"{1} {0}","dateFormatItem-Hms":"HH:mm:ss","dateFormatItem-hms":"h:mm:ss a","dateFormatItem-GyMMM":"G y MMM","field-mon-relative+-1":"last Monday","dateFormatItem-yyyy":"G y","field-week-relative+0":"this week","field-week-relative+1":"next week",
_localized:{}},"widgets/BatchAttributeEditor/nls/strings":{_widgetLabel:"Editor d'atributs per lots",widgetIntroSelectByArea:"Utilitzeu una de les eines seg\u00fcents per crear un conjunt d'entitats seleccionat per a l'actualitzaci\u00f3. Si la fila \u00e9s \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, s'ha superat el nombre m\u00e0xim de registres.",widgetIntroSelectByFeature:"Utilitzeu l'eina seg\u00fcent per seleccionar una entitat de la capa \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. Aquesta entitat s'utilitzar\u00e0 per seleccionar i actualitzar totes les entitats que s'intersequin. Si la fila \u00e9s \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, s'ha superat el nombre m\u00e0xim de registres.",
widgetIntroSelectByFeatureQuery:"Utilitzeu l'eina seg\u00fcent per seleccionar una entitat de \x3cfont class\x3d'layerInIntro'\x3e${0}\x3c/font\x3e. L'atribut \x3cfont class\x3d'layerInIntro'\x3e${1}\x3c/font\x3e d'aquesta entitat s'utilitzar\u00e0 per consultar les capes seg\u00fcents i actualitzar les entitats resultants. Si la fila \u00e9s \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, s'ha superat el nombre m\u00e0xim de registres.",widgetIntroSelectByQuery:"Introdu\u00efu un valor per crear un conjunt de selecci\u00f3. Si la fila \u00e9s \x3cfont class\x3d'maxRecordInIntro'\x3ehighlighted\x3c/font\x3e, s'ha superat el nombre m\u00e0xim de registres.",
layerTable:{colLabel:"Nom de la capa",numSelected:"#",colSyncStatus:""},noConfiguredLayers:"No s'ha configurat cap capa editable",editorPopupTitle:"Editor d'atributs per lots",editorPopupSaveBtn:"Desa",editorPopupMultipleValues:"",clear:"Esborra",featuresUpdated:"Entitats actualitzades: ${0}/${1}",featuresSelected:"Entitats seleccionades: ${0}",featuresSkipped:"Om\u00e8s",search:"Cerca",queryInput:"Introdu\u00efu el valor que vulgueu consultar",noFilterTip:"Sense cap expressi\u00f3 de filtre definida, aquesta tasca de consulta enumerar\u00e0 totes les entitats de l'origen de dades especificat.",
setFilterTip:"Definiu el filtre correctament.",filterPopup:"Filtra la capa",cancel:"Cancel\u00b7la",noValue:"Sense valor",emptyString:"Cadena buida",existingValue:"Mant\u00e9n el valor existent",newDate:"Data nova",valueChooser:"Seleccioneu o escriviu un valor",ok:"D'acord",drawBox:{point:"Punt",line:"L\u00ednia",polyline:"Polil\u00ednia",freehandPolyline:"Polil\u00ednia a m\u00e0 al\u00e7ada",extent:"Extensi\u00f3",polygon:"Pol\u00edgon",freehandPolygon:"Pol\u00edgon a m\u00e0 al\u00e7ada",clear:"Esborra",
addPointToolTip:"Feu clic per seleccionar en aquesta \u00e0rea",addShapeToolTip:"Dibuixa una forma per seleccionar entitats",freehandToolTip:"Manteniu premut per dibuixar una forma i seleccionar entitats",startToolTip:"Dibuixa una forma per seleccionar entitats"},errors:{layerNotFound:"La capa ${0} amb l'ID ${1} no s'ha trobat al mapa. \u00c9s possible que el mapa hagi canviat des que s'han configurat els widgets.",queryNullID:"L'entitat de ${0} ha retornat un ID no v\u00e0lid",noSelectedLayers:"No s'ha seleccionat cap capa amb registres per actualitzar",
inputValueError:"Valor no v\u00e0lid al formulari",saveError:"No es poden desar ${0} entitats i s'han afegit els detalls a la consola",requiredValue:"Valor necessari"},_localized:{}}});