// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Lihavointi",copy:"Kopioi",cut:"Leikkaa","delete":"Poista",indent:"Sisenn\u00e4",insertHorizontalRule:"Vaakasuuntainen viiva",insertOrderedList:"Numeroitu luettelo",insertUnorderedList:"Numeroimaton luettelo",italic:"Kursivointi",justifyCenter:"Tasaus keskelle",justifyFull:"Tasaus",justifyLeft:"Tasaus vasemmalle",justifyRight:"Tasaus oikealle",outdent:"Ulonna",paste:"Liit\u00e4",redo:"Tee uudelleen",removeFormat:"Poista muotoilu",selectAll:"Valitse kaikki",
strikethrough:"Yliviivaus",subscript:"Alennettu",superscript:"Korotettu",underline:"Alleviivaus",undo:"Kumoa",unlink:"Poista linkki",createLink:"Luo linkki",toggleDir:"Vaihda suuntaa",insertImage:"Lis\u00e4\u00e4 kuva",insertTable:"Lis\u00e4\u00e4 taulukko/muokkaa taulukkoa",toggleTableBorder:"Ota taulukon kehys k\u00e4ytt\u00f6\u00f6n/poista kehys k\u00e4yt\u00f6st\u00e4",deleteTable:"Poista taulukko",tableProp:"Taulukon ominaisuudet",htmlToggle:"HTML-l\u00e4hde",foreColor:"Edustav\u00e4ri",hiliteColor:"Taustav\u00e4ri",
plainFormatBlock:"Kappaletyyli",formatBlock:"Kappaletyyli",fontSize:"Fonttikoko",fontName:"Fontin nimi",tabIndent:"Sarkainsisennys",fullScreen:"Vaihda koko n\u00e4ytt\u00f6",viewSource:"N\u00e4yt\u00e4 HTML-l\u00e4hde",print:"Tulosta",newPage:"Uusi sivu",systemShortcut:'Toiminto "${0}" on k\u00e4ytett\u00e4viss\u00e4 selaimessa vain n\u00e4pp\u00e4imist\u00f6n pikatoiminnolla. K\u00e4yt\u00e4 seuraavaa: ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Koko",
fontName:"Fontti",formatBlock:"Muotoile",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Ei mit\u00e4\u00e4n",p:"Kappale",h1:"Otsikko",h2:"Alatason otsikko",h3:"Alimman tason otsikko",pre:"Esimuotoiltu",1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Esikatselu",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Etsi:",findTooltip:"Anna etsitt\u00e4v\u00e4 teksti",
replaceLabel:"Korvaa seuraavalla:",replaceTooltip:"Anna korvaava teksti",findReplace:"Etsi ja korvaa",matchCase:"Sama kirjainkoko",matchCaseTooltip:"Sama kirjainkoko",backwards:"Taaksep\u00e4in",backwardsTooltip:"Etsi teksti\u00e4 taaksep\u00e4in",replaceAllButton:"Korvaa kaikki",replaceAllButtonTooltip:"Korvaa kaikki teksti",findButton:"Etsi",findButtonTooltip:"Etsi teksti",replaceButton:"Korvaa",replaceButtonTooltip:"Korvaa teksti",replaceDialogText:"Korvattu ${0} esiintym\u00e4\u00e4.",eofDialogText:"Viimeinen esiintym\u00e4 ${0}",
eofDialogTextFind:"l\u00f6ytynyt",eofDialogTextReplace:"korvattu",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Liit\u00e4 Word-ohjelmasta",instructions:"Liit\u00e4 sis\u00e4lt\u00f6 Word-tiedostosta alla olevaan tekstikentt\u00e4\u00e4n. Kun lis\u00e4tt\u00e4v\u00e4 sis\u00e4lt\u00f6 on mielest\u00e4si valmis, napsauta Liit\u00e4-painiketta. Voit peruuttaa lis\u00e4yksen napsauttamalla Peruuta-painiketta.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Lis\u00e4\u00e4 ankkuri",
title:"Ankkurin ominaisuudet",anchor:"Nimi:",text:"Kuvaus:",set:"Aseta",cancel:"Peruuta",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/NetworkTrace/setting/nls/strings":{taskUrl:"Teht\u00e4v\u00e4n URL-osoite",setTask:"M\u00e4\u00e4rit\u00e4",setTaskPopupTitle:"M\u00e4\u00e4rit\u00e4 teht\u00e4v\u00e4",validate:"M\u00e4\u00e4rit\u00e4",inValidGPService:"Anna kelvollinen geoprosessointipalvelu.",GPFeatureRecordSetLayerERR:"Anna geoprosessointipalvelu, jossa on vain GPFeatureRecordSetLayer-tyypin l\u00e4ht\u00f6aineistoa.",
invalidInputParameters:"Sy\u00f6teparametreja on alle 1 tai yli 3. Anna kelvollinen geoprosessointipalvelu.",projectSetting:{title:"Projektiasetukset",note:"Huomautus: projektiasetukset ovat valinnaiset, koska m\u00e4\u00e4ritetty k\u00e4ytt\u00e4j\u00e4 voi tallentaa projektin haluamiinsa web-kartan karttatasoihin verkon k\u00e4ytt\u00f6katkoalueiden ja l\u00e4ht\u00f6aineiston parametrien kanssa. K\u00e4ytt\u00e4j\u00e4 voi tallentaa muut tulosparametrit Sy\u00f6te/Tulos-v\u00e4lilehden Tulos-ryhm\u00e4st\u00e4.",
projectPolygonLayer:"Projektin aluekarttataso",outputParameterName:"Tulosparametrin nimi",projectPointLayer:"Projektin pistekarttataso",selectLabel:"Valitse",polygonLayerHelp:"\x3cp\x3eSeuraavia ehtoja vastaavat aluekarttatasot n\u00e4ytet\u00e4\u00e4n:\x3cbr/\x3e\x3cli\x3eKarttatasossa on oltava muokkaustoiminnot eli Luo, Poista ja P\u00e4ivit\u00e4\x3c/li\x3e\x3cli\x3eKarttatasossa on oltava kaksi kentt\u00e4\u00e4, joissa on tarkat nimi- ja tietotyypit:\x3c/li\x3e\x3cul\x3e\x3cli\x3enimi (String-tyypin kentt\u00e4)\x3c/li\x3e\x3cli\x3eglobalid (GlobalID-tyypin kentt\u00e4)\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e",
outputParameterHelp:"\x3cp\x3eTeht\u00e4v\u00e4n URL-osoitteen tulosaineiston aluekarttatasot n\u00e4ytet\u00e4\u00e4n\x3cp/\x3e",pointLayerHelp:"\x3cp\x3eSeuraavia ehtoja vastaavat pistekarttatasot n\u00e4ytet\u00e4\u00e4n:\x3cbr/\x3e\x3cli\x3eKarttatasossa on oltava muokkaustoiminnot eli Luo, Poista ja P\u00e4ivit\u00e4\x3c/li\x3e\x3cli\x3eKarttatasossa on oltava kaksi kentt\u00e4\u00e4, joissa on tarkat nimi- ja tietotyypit:\x3c/li\x3e\x3cul\x3e\x3cli\x3einputtype  (String-tyypin kentt\u00e4)\x3c/li\x3e\x3cli\x3eprojectid (GUID-tyypin kentt\u00e4)\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e"},
inputOutputTab:{title:"Sy\u00f6te/Tulos",inputSettingsLabel:"Sy\u00f6teasetukset",outputSettingsLabel:"Tulosasetukset",inputLabel:"Tunnusteksti",inputTooltip:"Ty\u00f6kalun ohje",symbol:"Symboli",typeText:"Tyyppi",outputParametersText:"Tulosparametrit",saveToLayerText:"Tallenna karttatasoon (valinnainen)",skipText:"Ohitettavissa",visibilityText:"N\u00e4kyv\u00e4",exportToCsvText:"Vie CSV-tiedostoon",exportToCsvDisplayText:"CSV",settitngstext:"Asetukset",addFieldTitle:"Lis\u00e4\u00e4 kentt\u00e4",
enterDisplayText:"Kirjoita n\u00e4ytt\u00f6teksti",setScale:"M\u00e4\u00e4rit\u00e4 mittakaava",outputDisplay:"N\u00e4ytt\u00f6teksti",saveToLayerHelp:"\x3cp\x3eSeuraavia ehtoja vastaava karttataso n\u00e4ytet\u00e4\u00e4n:\x3cbr/\x3e\x3cli\x3eKarttatasossa on oltava muokkaustoiminnot eli Luo, Poista ja P\u00e4ivit\u00e4\x3c/li\x3e\x3cli\x3eKarttatasossa on oltava kaksi kentt\u00e4\u00e4, joissa on nimi- ja tietotyypit:\x3c/li\x3e\x3cul\x3e\x3cli\x3eparametername (String-tyypin kentt\u00e4)\x3c/li\x3e\x3cli\x3eprojectid (GUID-tyypin kentt\u00e4)\x3c/li\x3e\x3c/ul\x3e\x3cp/\x3e"},
summaryTab:{title:"Yhteenveto",summaryFieldsetText:"Yhteenvetoasetukset",inputOutput:"Sy\u00f6tteet/Tulokset",field:"Kent\u00e4t",operator:"Operaattorit",inputOperatorCountOption:"Lukum\u00e4\u00e4r\u00e4",outputOperatorCountOption:"Lukum\u00e4\u00e4r\u00e4",outputOperatorSkipCountOption:"OhitettavaM\u00e4\u00e4r\u00e4",fieldOperatorSumOption:"Summa",fieldOperatorMinOption:"V\u00e4himm\u00e4isarvo",fieldOperatorMaxOption:"Enimm\u00e4isarvo",fieldOperatorMeanOption:"Keskiarvo",expressionAddButtonText:"Lis\u00e4\u00e4",
expressionVerifyButtonText:"Tarkasta",summaryEditorText:"Yhteenvetoteksti"},generalSettings:{title:"Yleiset asetukset",displayTextForButtonLegend:"Suorita-painikkeen n\u00e4ytt\u00f6teksti",displayTextforButtonDefaultValue:"Suorita",displayTextForButton:"N\u00e4ytt\u00f6teksti",autoZoomAfterTrace:"Tarkennusasetukset",zoomText:"Automaattinen tarkennus j\u00e4ljityksen j\u00e4lkeen"},validationErrorMessage:{webMapError:"Web-kartassa ei ole karttatasoja. Valitse kelvollinen web-kartta.",inputTypeFlagGreaterThanError:"Lipputyypin sy\u00f6tteit\u00e4 ei voi olla yht\u00e4 enemp\u00e4\u00e4.",
inputTypeFlagLessThanError:"V\u00e4hint\u00e4\u00e4n yksi lipputyypin sy\u00f6te on pakollinen.",inputTypeBarrierErr:"Estetyypin sy\u00f6tteit\u00e4 ei voi olla yht\u00e4 enemp\u00e4\u00e4.",inputTypeSkipErr:"Ohitustyypin sy\u00f6tteit\u00e4 ei voi olla yht\u00e4 enemp\u00e4\u00e4.",displayTextForButtonError:"Suorita-painikkeen n\u00e4ytt\u00f6teksti ei voi olla tyhj\u00e4.",UnableToLoadGeoprocessError:"Geoprosessointipalvelua ei voi ladata.",invalidSummaryExpression:"Virheellinen lauseke.",validSummaryExpression:"Onnistui!",
invalidProjectSettings:"Virheelliset projektiasetukset.\x3cbr/\x3e Valitse kelvollinen arvo asetuksessa ${projectSetting}."},hintText:{labelTextHint:"Vihje: m\u00e4\u00e4rit\u00e4 tulosparametrin tulosruudussa n\u00e4ytett\u00e4v\u00e4 tunnusteksti.",displayTextHint:"Vihje: t\u00e4m\u00e4 n\u00e4ytet\u00e4\u00e4n t\u00e4m\u00e4n tulosparametrin Tiedot-ruudussa.",inputTextHint:"Vihje: muodosta lausekkeesi yll\u00e4 valitsemalla sy\u00f6te, tulos ja kenttien nimet.",expressionHint:"Vihje: muodosta lauseke valitsemalla kohteet ja napsauttamalla Lis\u00e4\u00e4."},
_localized:{}}});