// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/DistanceAndDirection/nls/strings":{_widgetLabel:"Udaljenost i smjer",tabLineTitle:"Linija",tabCircleTitle:"Krug",tabEllipseTitle:"Elipsa",tabRingsTitle:"Prsteni",multipleNotationsMessage:" bilje\u0161ke koje se podudaraju s va\u0161im unosom. Potvrdite \u0161to biste htjeli upotrijebiti:",invalidCoordinateMessage:"Nevaljana koordinata",confirmInputNotationMessage:"Notacija potvrde unosa",prefixSuffixMessage:"Otkriveno je da unesene koordinate imaju prefiks i sufiks za vrijednosti geografske \u0161irine i du\u017eine, vra\u0107ene koordinate temelje se na prefiksu.",
rememberDecisionMessage:"Zapamti moju odluku i nemoj me pitati ponovo.\x3cbr/\x3e",majorAxisTooltipMessage:"Kliknite duljinu glavne osi",minorAxisTooltipMessage:"Pomaknite mi\u0161 natrag u po\u010detni polo\u017eaj da biste postavili manje osi i zavr\u0161ili crtanje elipse",clickToFinishLineMessage:"Kliknite da biste dovr\u0161ili crtanje linije",doubleClickEllipseMesage:"Dvaput kliknite da biste dovr\u0161ili crtanje prstena raspona",invalidCoordinateTypeMessage:"Nije mogu\u0107e utvrditi vrstu unesene koordinate. Provjerite unos",
noCenterPointSetMessage:"Nije postavljena sredi\u0161nja to\u010dka. Provjerite unos",ellipseMajorAxis:"Glavna os",ellipseMinorAxis:"Manja os",degreesRangeMessage:"Vrijednost mora biti izme\u0111u 0 i 360",millsRangeMessage:"Vrijednost mora biti izme\u0111u 0 i 6400",lengthLabel:"Duljina",angleLabel:"Kut",startPointLabel:"Po\u010detna to\u010dka",endPointLabel:"Zavr\u0161na to\u010dka",centerPointLabel:"Sredi\u0161nja to\u010dka",distanceTableErrorMessage:"Tablica udaljenosti je prazna. Provjerite jeste li unijeli neke udaljenosti.",
setCoordFormatStringMessage:"Postavi niz formata koordinata",prefixMessage:"Dodajte prefiks \u201e+/-\u201d pozitivnim i negativnim brojevima",ddLabel:"DD",ddmLabel:"DDM",dmsLabel:"DMS",garsLabel:"GARS",georefLabel:"GEOREF",mgrsLabel:"MGRS",usngLabel:"USNG",utmLabel:"UTM",utmhLabel:"UTM (H)",DDLatLongNotation:"Decimalni stupnjevi - geografska \u0161irina/du\u017eina",DDLongLatNotation:"Decimalni stupnjevi - geografska du\u017eina/\u0161irina",DDMLatLongNotation:"Stupnjevi decimalne minute - geografska \u0161irina/du\u017eina",
DDMLongLatNotation:"Stupnjevi decimalne minute - geografska du\u017eina/\u0161irina",DMSLatLongNotation:"Stupnjevi minute sekunde - geografska \u0161irina/du\u017eina",DMSLongLatNotation:"Stupnjevi minute sekunde - geografska du\u017eina/\u0161irina",GARSNotation:"GARS",GEOREFNotation:"GEOREF",MGRSNotation:"MGRS",USNGNotation:"USNG",UTMBandNotation:"UTM - slovo retka",UTMHemNotation:"UTM - hemisfera (N/S)",circleTitle:"Stvori krug iz",radiusLabel:"Polumjer",diameterLabel:"Promjer",startPointPlaceHolderLabel:"Unesi koordinate",
formatInputLabel:"Format unosa",drawCircleLabel:"Nacrtaj krug",drawLineLabel:"Nacrtaj liniju",createCircleInteractivelyLabel:"Interaktivno stvori krug",rangeErrorMessage:"Neva\u017ee\u0107i polumjer ili promjer",numericInvalidMessage:"Unesite broj\u010danu vrijednost",timeLabel:"Vrijeme",invalidTimeMessage:"Neva\u017ee\u0107a vremenska vrijednost",hoursLabel:"Sati",minutesLabel:"Minute",secondsLabel:"Sekunde",rateLabel:"Brzina",invalidDistanceMessage:"Neva\u017ee\u0107a vrijednost udaljenosti",feetSecondsLabel:"Stopa / sekunda",
feetHourLabel:"Stopa / sat",kmSecondLabel:"Kilometri / sekunda",kmHourLabel:"Kilometar / sat",metersSecondLabel:"Metri / sekunda",metersHourLabel:"Metri / sat",milesSecondLabel:"Milje / sekunda",milesHourLabel:"Milje / sat",nauticalMilesSecondLabel:"Nauti\u010dke milje / sekunda",nauticalMilesHourLabel:"Nauti\u010dke milje / sat",clearGraphicsLabel:"Izbri\u0161i grafike",ellipseTypeLabel:"Vrsta elipse",ellipseSemiLabel:"Polovi\u010dna",ellipseFullLabel:"Cijela",drawEllipseLabel:"Nacrtaj elipsu",createEllipseInteractively:"Interaktivno stvori elipsu",
axisLabel:"Os",unitLabel:"Jedinica",majorRadiusLabel:"Glavna (polumjer)",majorDiameterLabel:"Velik (promjer)",axisErrorMessage:"Vrijednost mora biti ve\u0107a od 0",minorRadiusLabel:"Manja (polumjer)",minorDiameterLabel:"Malen (promjer)",orientationLabel:"Orijentacija",orientationErrorMessage:"Vrijednost mora biti izme\u0111u 0 i 360",warningMessage:"Upozorenje: grafike generirane pomo\u0107u elipse alata nisu geodetske",fromLabel:"Od",distanceBearingLabel:"Udaljenost i usmjerenje",pointsLabel:"To\u010dke",
createLineInteractively:"Interaktivno stvori liniju",lineLengthErrorMessage:"Neva\u017ee\u0107a duljina linije",degreesLabel:"Stupnjevi",milsLabel:"Mil",lineTypeLabel:"Vrsta",interactiveLabel:"Interaktivno",fixedLabel:"Popravljeno",originLabel:"Podrijetlo",cumulativeLabel:"Kumulativno",numberOfRingsLabel:"Broj prstena",ringsErrorMessage:"Neva\u017ee\u0107i broj prstena",distanceBetweenRingsLabel:"Udaljenost izme\u0111u prstena",ringsDecimalErrorMessage:"Unesite broj\u010danu vrijednost na 2 decimalna mjesta",
distanceUnitsLabel:"Jedinice udaljenosti",distancesLabel:"Udaljenosti",numberOfRadialsLabel:"Broj radijala",upLabel:"Gore",downLabel:"Dolje",deleteLabel:"Izbri\u0161i",radialsErrorMessage:"Neva\u017ee\u0107i broj radijala. Maksimalno dopu\u0161teno je 360",radialsInvalidMessage:"Neva\u017ee\u0107e vrijednosti za radijale",addPointLabel:"Dodaj to\u010dku",valueLabel:"Vrijednost",valueText:"Unesite vrijednost",actionLabel:"Radnja",distanceCalculatorLabel:"Kalkulator udaljenosti",abbrevMetersLabel:"m",
abbrevFeetLabel:"ft",abbrevKmLabel:"km",abbrevMilesLabel:"mi",abbrevYardsLabel:"yd",abbrevNauticalMilesLabel:"nm",abbrevDegreesLabel:"\u00c2\u00b0",abbrevMilsLabel:"mil",abbrevHoursLabel:"v",abbrevMinutesLabel:"m",abbrevSecondsLabel:"s",abbrevFeetSecondsLabel:"ft/s",abbrevFeetHourLabel:"ft/h",abbrevKmSecondLabel:"km/s",abbrevKmHourLabel:"km/h",abbrevMetersSecondLabel:"m/s",abbrevMetersHourLabel:"m/h",abbrevMilesSecondLabel:"mi/s",abbrevMilesHourLabel:"mi/h",abbrevNauticalMilesSecondLabel:"nm/s",abbrevNauticalMilesHourLabel:"nm/h",
_localized:{}}});