// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Innstillinger",titleSettings:"Tekstinnstillinger",imageSettings:"Bildeinnstillinger",backgroundColor:"Bakgrunnsfarge",alignment:"Justering",textSize:"Tekstst\u00f8rrelse",textColor:"Tekstfarge",dataSource:"Datakilde",chartSettings:"Diagraminnstillinger",data:"Data",dataLabels:"Dataetikketter",displayMode:"Visningsmodus",featureOption:"Vis verdier geoobjekt for geoobjekt",categoryOption:"Vis verdier etter kategori",countOption:"Vis antall geoobjekter etter kategori",
fieldOption:"Vis attributtverdier som diagrammer",categoryField:"Kategorifelt",labelField:"P\u00e5skriftfelt",valueFields:"Verdifelter",operation:"Operasjon",sumOption:"Summer",averageOption:"Gjennomsnitt",minOption:"Minimum",maxOption:"Maksimum",countString:"Antall",dataFormat:"Datoformat",decimalPlaces:"Desimaler",prefix:"Prefiks",suffix:"Suffiks",dataType:"Datatype",featureCount:"Geoobjektantall",fieldStatistics:"Feltstatistikk",display:"Vis",chartColor:"Diagramfarge",horizontalAxis:"Horisontal akse",
verticalAxis:"Vertikal akse",legend:"Tegnforklaring",position:"Posisjon",top:"Topp",bottom:"Bunn",useDataSourceSelection:"Bruk utvalg",dataSourceFilterByExtent:"Filtrer etter utstrekning",changeTemplate:"Endre mal",numberSettings:"Tallinnstillinger",gaugeSettings:"M\u00e5lerinnstillinger",indicators:"Indikatorer",ifValue:"Verdien Hvis",and:"og",numberOperatorIsLessThan:"er mindre enn",numberOperatorIsGreaterThan:"er st\u00f8rre enn",numberOperatorIsBetween:"er mellom",numberOperatorIsEqual:"er lik",
numberOperatorIsNotEqual:"er ikke lik",then:"S\u00e5",ratio:"Forhold",trueValue:"Verdien Sann",changeValueColor:"endre verdifarge til",changeGaugeColor:"endre m\u00e5lerfarge til",setIndicatorIcon:"angi indikatorikon som",icons:"Ikoner",style:"Stil",placement:"Plassering",left:"Venstre",replace:"Erstatt",right:"H\u00f8yre",color:"Farge",categoryExists:"Kategorien finnes",comboxHint:"Skriv inn eller velg en",comboxDisableInputHint:"Velg \u00e9n",comboxDisableSelectHint:"Skriv inn en",comboxDisableInputEmptySelectHint:"Ingen flere kategorier",
sortBy:"Sorter etter",labelAxis:"Etikett",valueAxis:"Verdi",minPeriod:"Minimumsperiode",automatic:"Automatisk",periodsWithOutRecords:"Perioder uten poster",nullValue:"Null verdi",calculatedAsZero:"Beregnet som null",ignored:"Ignorert",maxCategories:"Maksimalt antall kategorier",useLayerSymbology:"Bruk lagens symboler",hollowsize:"Hulhetsst\u00f8rrelse",splitField:"Del felt",parsingperiodTip:"Kan ikke beregne. For mange tidsintervaller p\u00e5 grunn av den korte analyseperioden.",manyCategoryTip:"Kan ikke vise diagram. For mange kategorier.",
setColor:"Angi farge",setTheColorOf:"Angi deretter fargen for",setTheColorAs:"Angi deretter fargen som",ifStr:"Hvis",as:"som",is:"er",isNot:"er ikke",barCluster:"stolpediagramklynge",individualBar:"enkelt stolpediagram",allOthers:"Alle andre",category:"Kategori",indicatorSum:"SUM",indicatorAve:"MIDDEL",indicatorMax:"MAKS.",indicatorMin:"MIN.",setCorrectyIndicatorTip:"Angi indikatorene p\u00e5 riktig m\u00e5te.",dataRange:"Dataomr\u00e5de",targetValue:"M\u00e5lverdi",currentValue:"Gjeldende verdi",
gaugeColor:"M\u00e5lerfarge",min:"Minimum",max:"Maksimum",displayValueIn:"Vis verdi i",noData:"Ingen data",thousandAbbreviation:"k",millionAbbreviation:"M",billionAbbreviation:"G",warning:"Advarsel",noSettingWaring1:"Klikk p\u00e5 et element for \u00e5 angi egenskaper for elementet.",noSettingWaring2:"Dra for \u00e5 endre st\u00f8rrelsen eller rekkef\u00f8lgen for et element.",donNotShowAgain:"Ikke vis igjen",changeTemplateWarning:"Dette fjerner alle innstillinger og \u00e5pner en ny tom mal.",requiredFieldWarning:"Denne verdien er obligatorisk:",
dataSourceNotSet:"Angi datakilde.",addIndicatorTip:"Legg til en indikator",chooseTemplatePopupTitle:"Velg en mal",filterExtentTipWithaTag:"Du kan deaktivere filteret med \x3ca target\x3d'_blank' href\x3d'http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'\x3eEkstra datakilde\x3c/a\x3e i Attributt-fanen.",filterExtentTip:"Du kan deaktivere filteret med Ekstra datakilde i Attributt-fanen.",customColorByCategory:"Egendefinert farge etter kategori",
randomColor:"Tilfeldig farge",valueString:"Verdi",fieldString:"Felt",includeThresholdValue:"Inkluder terskelverdi",percentage:"Prosentandel",colorSchema:"Fargevalg",addCategory:"Legg til kategori",clickToEdit:"Klikk for \u00e5 redigere",nullText:"Null",others:"Andre",dsErrorTipSuf:"er ikke tilgjengelig.",front:"Front",back:"Bak",title:"Tittel",titleColor:"Tittelfarge",labelString:"Etikett",labelSize:"Etikettst\u00f8rrelse",labelColor:"Etikettfarge",addMarkLine:"Legg til et linjemerke",addMarkArea:"Legg til et omr\u00e5demerke",
labelPosition:"Etikettposisjon",toString:"til",start:"Start",middle:"Midten",end:"Slutt",inString:"Inn",outString:"Ut",lineColor:"Linjefarge",lineWidth:"Linjebredde",dashType:"Strektype",areaColor:"Omr\u00e5defarge",line:"Linje",area:"Areal",stringsInTemplate:{name_number:"Tall",name_gauge:"M\u00e5ler",name_vertical_gauge:"Vertikal m\u00e5ler",name_horizontal_gauge:"Horisontal m\u00e5ler",name_pie:"Sektor",name_donut:"Hjuldiagram",name_bar:"Linjal",name_stacked_bar:"Stablet liggende stolpediagram",
name_percentage_stacked_bar:"Stablet liggende stolpediagram med prosentfordeling",name_column:"S\u00f8yle",name_stacked_column:"Stablet liggende s\u00f8ylediagram",name_percentage_stacked_column:"Stablet liggende s\u00f8ylediagram med prosentfordeling",name_line:"Linje",name_area:"Areal",name_stacked_area:"Stablet arealdiagram",name_percentage_stacked_area:"Stablet arealdiagram med prosentfordeling",titleOfTheInfographic:"TITTEL P\u00c5 INFOGRAFIKK",description:"Beskrivelse: tilleggsinformasjon om denne infografikken."},
marks:"Merker",displayValue:"Vis verdi",statistic:"Statistikk",valueType:"Verditype",valueField:"Verdifelt",fixed:"Fast",sdsTip:"Velg en statistisk data konfigurert i Ekstra datakilde",noSdsTip:"Ingen tilgjengelige statistiske data.",intScaleText:"Vis kun heltallsskala",resetLayout:"Tilbakestill layout",fbeTip:"V\u00e6r oppmerksom p\u00e5 at dersom appen deles offentlig og bredt, vil appens ytelse bli kraftig redusert hvis du aktiverer dette alternativet. Vi anbefaler at du bruker andre widgeter, for eksempel Filter og Gruppefilter, til \u00e5 zoome inn p\u00e5 geoobjektet i stedet.",
openFbeTip:"Aktiver alternativet likevel",use1000Separator:"Bruk tusenskilletegn",_localized:{}}});