// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/Infographic/setting/nls/strings":{settings:"Param\u00e8tres",titleSettings:"Param\u00e8tres de texte",imageSettings:"Param\u00e8tres d'image",backgroundColor:"Couleur d'arri\u00e8re-plan",alignment:"Alignement",textSize:"Taille de texte",textColor:"Couleur du texte",dataSource:"Source de donn\u00e9es",chartSettings:"Param\u00e8tres de diagramme",data:"Donn\u00e9es",dataLabels:"Etiquettes de donn\u00e9es",displayMode:"Mode Affichage",featureOption:"Afficher les valeurs entit\u00e9 par entit\u00e9",
categoryOption:"Afficher les valeurs par cat\u00e9gorie",countOption:"Afficher le nombre d\u2019entit\u00e9s par cat\u00e9gorie",fieldOption:"Afficher les valeurs attributaires sous forme de diagrammes",categoryField:"Champ de cat\u00e9gorie",labelField:"Champ d\u2019\u00e9tiquette",valueFields:"Champs de valeur",operation:"Op\u00e9ration",sumOption:"Somme",averageOption:"Moyenne",minOption:"Minimal",maxOption:"Maximal",countString:"Total",dataFormat:"Format des donn\u00e9es",decimalPlaces:"D\u00e9cimales",
prefix:"Pr\u00e9fixe",suffix:"Suffixe",dataType:"Type de donn\u00e9es",featureCount:"Nombre d'entit\u00e9s",fieldStatistics:"Statistiques du champ",display:"Affichage",chartColor:"Couleur du diagramme",horizontalAxis:"Axe horizontal",verticalAxis:"Axe vertical",legend:"L\u00e9gende",position:"Position",top:"Haut",bottom:"Bas",useDataSourceSelection:"Utiliser la s\u00e9lection",dataSourceFilterByExtent:"Filtrer selon l'\u00e9tendue",changeTemplate:"Changer de mod\u00e8le",numberSettings:"Param\u00e8tres de num\u00e9rotation",
gaugeSettings:"Param\u00e8tres de jauge",indicators:"Indicateurs",ifValue:"Si la valeur",and:"et",numberOperatorIsLessThan:"est inf\u00e9rieur \u00e0",numberOperatorIsGreaterThan:"est sup\u00e9rieur \u00e0",numberOperatorIsBetween:"est entre",numberOperatorIsEqual:"est \u00e9gal \u00e0",numberOperatorIsNotEqual:"est diff\u00e9rent de",then:"Avant",ratio:"Ratio",trueValue:"Valeur true",changeValueColor:"remplacer la couleur de valeur par",changeGaugeColor:"remplacer la couleur de jauge par",setIndicatorIcon:"d\u00e9finir l'ic\u00f4ne de l'indicateur comme",
icons:"Ic\u00f4nes",style:"Style",placement:"Placement",left:"Gauche",replace:"Remplacer",right:"Droite",color:"Couleur",categoryExists:"La cat\u00e9gorie existe\u00a0!",comboxHint:"Saisir ou s\u00e9lectionner une valeur",comboxDisableInputHint:"Choix unique",comboxDisableSelectHint:"Saisissez une valeur",comboxDisableInputEmptySelectHint:"Aucune autre cat\u00e9gorie",sortBy:"Trier par",labelAxis:"Etiquette",valueAxis:"Valeur",minPeriod:"P\u00e9riode minimale",automatic:"Automatique",periodsWithOutRecords:"P\u00e9riodes sans enregistrements",
nullValue:"Valeur nulle",calculatedAsZero:"Calcul\u00e9(e) comme z\u00e9ro",ignored:"Ignor\u00e9",maxCategories:"Cat\u00e9gories maximum",useLayerSymbology:"Utiliser la symbologie de la couche",hollowsize:"Taille de vide",splitField:"Champ de fractionnement",parsingperiodTip:"\u00c9chec du calcul. Trop d\u2019intervalles de temps en raison de la p\u00e9riode d\u2019analyse br\u00e8ve.",manyCategoryTip:"\u00c9chec de l\u2019affichage du diagramme. Trop de cat\u00e9gories.",setColor:"D\u00e9finir la couleur",
setTheColorOf:"Puis d\u00e9finir la couleur de",setTheColorAs:"Puis d\u00e9finir la couleur comme",ifStr:"Si",as:"as",is:"is",isNot:"n'est pas",barCluster:"agr\u00e9gat de barre",individualBar:"barre individuelle",allOthers:"Tous les autres",category:"Cat\u00e9gorie",indicatorSum:"SOMME",indicatorAve:"MOY",indicatorMax:"MAX",indicatorMin:"MIN",setCorrectyIndicatorTip:"D\u00e9finissez les indicateurs correctement.",dataRange:"Plage de donn\u00e9es",targetValue:"Valeur cible",currentValue:"Valeur actuelle",
gaugeColor:"Couleur de jauge",min:"Minimal",max:"Maximal",displayValueIn:"Afficher la valeur dans",noData:"Aucune donn\u00e9e",thousandAbbreviation:"k",millionAbbreviation:"V",billionAbbreviation:"V",warning:"Avertissement",noSettingWaring1:"Cliquez sur un \u00e9l\u00e9ment pour en d\u00e9finir les propri\u00e9t\u00e9s.",noSettingWaring2:"Faites glisser pour redimensionner ou r\u00e9organiser un \u00e9l\u00e9ment.",donNotShowAgain:"Ne plus afficher",changeTemplateWarning:"Cette action va effacer l'ensemble de vos param\u00e8tres et ouvrir un nouveau mod\u00e8le vide.",
requiredFieldWarning:"Cette valeur est obligatoire\u00a0:",dataSourceNotSet:"D\u00e9finissez une source de donn\u00e9es.",addIndicatorTip:"Ajouter un indicateur",chooseTemplatePopupTitle:"Choisir un mod\u00e8le",filterExtentTipWithaTag:"Vous pouvez d\u00e9sactiver le filtre par \x3ca target\x3d'_blank' href\x3d'http://doc.arcgis.com/en/web-appbuilder/create-apps/attributes-tab.htm#ESRI_SECTION1_90B658C55CAE428FA43A110272096C81'\x3esource de donn\u00e9es suppl\u00e9mentaire\x3c/a\x3e sous l\u2019onglet Attribut.",
filterExtentTip:"Vous pouvez d\u00e9sactiver le filtre par source de donn\u00e9es suppl\u00e9mentaire sous l\u2019onglet Attribut.",customColorByCategory:"Couleur personnalis\u00e9e par cat\u00e9gorie",randomColor:"Couleur al\u00e9atoire",valueString:"Valeur",fieldString:"Terrain",includeThresholdValue:"Inclure la valeur de seuil",percentage:"Pourcentage",colorSchema:"Combinaison de couleurs",addCategory:"Ajouter une cat\u00e9gorie",clickToEdit:"Cliquer pour mettre \u00e0 jour",nullText:"Null",others:"Autres",
dsErrorTipSuf:"n\u2019est pas disponible.",front:"Avant",back:"Pr\u00e9c\u00e9dent",title:"Titre",titleColor:"Couleur du titre",labelString:"Etiquette",labelSize:"Taille de l\u2019\u00e9tiquette",labelColor:"Couleur de l\u2019\u00e9tiquette",addMarkLine:"Ajouter un rep\u00e8re lin\u00e9aire",addMarkArea:"Ajouter un rep\u00e8re surfacique",labelPosition:"Position de l\u2019\u00e9tiquette",toString:"\u00e0",start:"D\u00e9but",middle:"Milieu",end:"Fin",inString:"Dedans",outString:"Dehors",lineColor:"Couleur de ligne",
lineWidth:"Largeur de ligne",dashType:"Type de tiret",areaColor:"Couleur de la surface",line:"Ligne",area:"Surface",stringsInTemplate:{name_number:"Nombre",name_gauge:"Jauge",name_vertical_gauge:"Jauge verticale",name_horizontal_gauge:"Jauge horizontale",name_pie:"Secteur",name_donut:"Anneau",name_bar:"Barre",name_stacked_bar:"Barre empil\u00e9e",name_percentage_stacked_bar:"Barre empil\u00e9e de pourcentage",name_column:"Colonne",name_stacked_column:"Colonne empil\u00e9e",name_percentage_stacked_column:"Colonne empil\u00e9e de pourcentage",
name_line:"Ligne",name_area:"Surface",name_stacked_area:"Zone empil\u00e9e",name_percentage_stacked_area:"Zone empil\u00e9e de pourcentage",titleOfTheInfographic:"TITLE OF THE INFOGRAPHIC",description:"Description\u00a0: informations suppl\u00e9mentaires sur cette infographie."},marks:"Rep\u00e8res",displayValue:"Valeur d\u2019affichage",statistic:"Statistique",valueType:"Type de valeur",valueField:"Champ de valeurs",fixed:"Constant",sdsTip:"Choisir des donn\u00e9es statistiques configur\u00e9es dans Source de donn\u00e9es suppl\u00e9mentaire",
noSdsTip:"Aucune donn\u00e9e statistique n\u2019est disponible.",intScaleText:"Afficher une \u00e9chelle d\u2019entier uniquement",resetLayout:"R\u00e9initialiser la mise en page",fbeTip:"N\u2019oubliez pas que si votre application est partag\u00e9e publiquement et utilis\u00e9e intens\u00e9ment, cette option ralentira consid\u00e9rablement ses performances. Nous vous conseillons fortement d\u2019utiliser d\u2019autres widgets, tels que Filtrer et Filtrer les groupes pour zoomer sur les entit\u00e9s.",
openFbeTip:"Activer l\u2019option quand m\u00eame",use1000Separator:"Utiliser le s\u00e9parateur de milliers",_localized:{}}});