// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Grassetto",copy:"Copia",cut:"Taglia","delete":"Elimina",indent:"Rientro",insertHorizontalRule:"Righello orizzontale",insertOrderedList:"Elenco numerato",insertUnorderedList:"Elenco puntato",italic:"Corsivo",justifyCenter:"Allinea al centro",justifyFull:"Giustifica",justifyLeft:"Allinea a sinistra",justifyRight:"Allinea a destra",outdent:"Annulla rientro",paste:"Incolla",redo:"Ripristina",removeFormat:"Rimuovi formato",selectAll:"Seleziona tutto",strikethrough:"Barrato",
subscript:"Pedice",superscript:"Apice",underline:"Sottolinea",undo:"Annulla",unlink:"Rimuovi collegamento",createLink:"Crea collegamento",toggleDir:"Attiva/Disattiva direzione",insertImage:"Inserisci immagine",insertTable:"Inserisci/Modifica tabella",toggleTableBorder:"Attiva/Disattiva bordo tabella",deleteTable:"Elimina tabella",tableProp:"Propriet\u00e0 tabella",htmlToggle:"Origine HTML",foreColor:"Colore primo piano",hiliteColor:"Colore sfondo",plainFormatBlock:"Stile paragrafo",formatBlock:"Stile paragrafo",
fontSize:"Dimensione carattere",fontName:"Nome carattere",tabIndent:"Rientro tabulazione",fullScreen:"Attiva/Disattiva schermo intero",viewSource:"Visualizza origine HTML",print:"Stampa",newPage:"Nuova pagina",systemShortcut:'La azione "${0}" \u00e8 disponibile solo nel browser tramite un tasto di scelta rapida. Utilizzare ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{fontSize:"Dimensione",fontName:"Carattere",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",
monospace:"spaziatura fissa",cursive:"corsivo",fantasy:"fantasy",noFormat:"Nessuna",p:"Paragrafo",h1:"Intestazione",h2:"Sottointestazione",h3:"Sottointestazione secondaria",pre:"Preformattato",1:"piccolissimo",2:"molto piccolo",3:"piccolo",4:"medio",5:"grande",6:"molto grande",7:"grandissimo",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Anteprima",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Trova:",findTooltip:"Immettere il testo da ricercare",replaceLabel:"Sostituisci con:",
replaceTooltip:"Immettere il testo con cui sostituire",findReplace:"Trova e sostituisci",matchCase:"Corrispondenza maiuscolo/minuscolo",matchCaseTooltip:"Corrispondenza maiuscolo/minuscolo",backwards:"Indietro",backwardsTooltip:"Ricercare il testo all'indietro",replaceAllButton:"Sostituisci tutti",replaceAllButtonTooltip:"Sostituisci tutto il testo",findButton:"Trova",findButtonTooltip:"Trova il testo",replaceButton:"Sostituisci",replaceButtonTooltip:"Sostituisci il testo",replaceDialogText:"Sostituite ${0} ricorrenze.",
eofDialogText:"Ultime ${0} ricorrenze",eofDialogTextFind:"trovato",eofDialogTextReplace:"sostituito",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Incolla da Word",instructions:"Incollare i contenuti da Word nella seguente casella di testo. Quando si \u00e8 deciso quali contenuti inserire, fare clic sul pulsante incolla. Per interrompere l'inserimento del testo premere il pulsante annulla.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserisci ancoraggio",
title:"Propriet\u00e0 ancoraggio",anchor:"Nome:",text:"Descrizione:",set:"Imposta",cancel:"Annulla",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/Splash/setting/nls/strings":{instruction:"La schermata di avvio appare prima che l'applicazione sia accessibile.",defaultContent:"Aggiungere qui testo, collegamenti e piccole immagini.",requireConfirm:"Per continuare, \u00e8 necessario confermare",noRequireConfirm:"Non richiedere conferma per continuare.",
optionText:"Opzione per utente per disabilitare la schermata di avvio all'avvio dell'applicazione.",confirmLabel:"Testi di conferma: ",confirmLabelColor:"Colore testi di conferma",defaultConfirmText:"Accetto le seguenti condizioni d'uso",confirmOption:"Visualizza sempre questa schermata iniziale a ogni avvio dell'app",backgroundColor:"Colore di sfondo",content:"Contenuto",contentDescription:"Definire il contenuto visualizzato nella schermata di avvio.",appearance:"Aspetto",appearanceDescription:"Impostare l'aspetto della schermata di avvio.",
size:"Dimensione",width:"Larghezza",height:"Altezza",custom:"Personalizzata",background:"Sfondo",colorFill:"Colore di riempimento",imageFill:"Immagine di riempimento",chooseFile:"Seleziona file",noFileChosen:"Nessun file selezionato",sizeFill:"Riempi",sizeFit:"Misura",sizeStretch:"Adatta allo sfondo",sizeCenter:"Al centro",sizeTile:"Affianca",buttonColor:"Colore pulsante",buttonText:"Testo pulsante",buttonTextColor:"Colore testo pulsante",contentAlign:"Allineamento contenuto",alignTop:"In alto",alignMiddle:"Mezzo",
maskColor:"Colore maschera",options:"Opzioni",optionsDescription:"Impostare il comportamento della schermata di avvio.",_localized:{}}});